from pathlib import Path
import gzip,hashlib,io,json,subprocess,tarfile,xml.etree.ElementTree as E
root=Path('/dev/shm/e02-orch03-20261008/c09');scratch=Path('/dev/shm/e02-orch03-20261008/c09-scratch');prefix=Path('policy-engine/docs/research/e02-cloud-test-plan/implementation-handoffs/E/parallel-20261008-c09');pack=root/prefix;packet=pack/'interval-consumer-basis';packet.mkdir(exist_ok=True)
base='6d470eb884c31a8b19ee06058881cf0deaa492f5';runtime='adb66080e3ac64d73b3faa85d693a47c6c284427';candidate='b3df9b6d84c67b48e91ea9227cadb89f5010b2a2';tree='9d6577fe7dfc4e238f106e2f0bd22815e1d57e4e';reviewroot=Path('/dev/shm/e02-orch03-20261008/oracle-empirical/interval-consumer')
assert subprocess.check_output(['git','rev-parse','HEAD'],cwd=root,text=True).strip()==candidate
reviews=[('main',reviewroot/'review-adb/independent-review.json','774390f75f2b7707c1b8a55756cc622cff59ebbf099a90fc979830b5330fa27c'),('fixture',reviewroot/'review-b3/independent-fixture-forward-review.json','6c603af13e63ca4d1e34edc22b0ee8798683d487ccd54c9b810914d3acaea4aa'),('retry',reviewroot/'review-b3/independent-retry-verification.json','827ed6c6a9278262261999e63cfeda0ddb3da2ac58ed804474185c9c9a278c96')]
for name,path,digest in reviews:
 data=path.read_bytes();assert hashlib.sha256(data).hexdigest()==digest;(packet/('independent-'+name+'-review.json')).write_bytes(data)
archives=[]
for label,path in [('author-interval',scratch/'phase2-interval-consumers'),('author-final',scratch/'phase2-final'),('author-law',scratch/'phase2-mean-law'),('publication',scratch/'phase2-publication'),('review-baseline',reviewroot/'baseline-ee0'),('review-661',reviewroot/'review-661'),('review-adb',reviewroot/'review-adb'),('review-b3',reviewroot/'review-b3')]:
 members=[];excluded=[];tar_bytes=io.BytesIO()
 with tarfile.open(fileobj=tar_bytes,mode='w',format=tarfile.PAX_FORMAT) as archive:
  for file in sorted(path.rglob('*')):
   if not file.is_file():continue
   relative=file.relative_to(path);parts=relative.parts
   if 'input' in parts or '__pycache__' in parts or 'G-review' in parts or file.name in {'source.tar','companions.tar','resume.stdout.json'} or any(p.endswith('-cache') or p=='import-cache' for p in parts):
    excluded.append({'path':relative.as_posix(),'reason':'reproducible Git source/cache or exact doctor JSON already in root807 custody'});continue
   data=file.read_bytes();info=tarfile.TarInfo(relative.as_posix());info.size=len(data);info.mtime=0;info.mode=0o644;archive.addfile(info,io.BytesIO(data));members.append({'path':relative.as_posix(),'bytes':len(data),'sha256':hashlib.sha256(data).hexdigest()})
 raw=tar_bytes.getvalue();encoded=gzip.compress(raw,mtime=0);filename=label+'.tar.gz';(packet/filename).write_bytes(encoded)
 record={'archive':str(prefix/'interval-consumer-basis'/filename),'encoding':'gzip+tar','stored_bytes':len(encoded),'stored_sha256':hashlib.sha256(encoded).hexdigest(),'decoded_tar_bytes':len(raw),'decoded_tar_sha256':hashlib.sha256(raw).hexdigest(),'member_count':len(members),'member_payload_bytes':sum(i['bytes'] for i in members),'members':members,'exclusions':excluded};archives.append(record)
 # Validate the actual lossless stored payload against every member before publication.
 with tarfile.open(fileobj=io.BytesIO(gzip.decompress(encoded)),mode='r:') as check:
  assert len(check.getmembers())==len(members)
  for m in members:assert hashlib.sha256(check.extractfile(m['path']).read()).hexdigest()==m['sha256']
(packet/'archive-members.json.gz').write_bytes(gzip.compress((json.dumps({'archives':archives},indent=2)+'\n').encode(),mtime=0))
(packet/'implementation.diff').write_bytes(subprocess.check_output(['git','diff','--binary',base,candidate],cwd=root))
(packet/'law-label.diff').write_bytes(subprocess.check_output(['git','diff','--binary','aa2d87945c2fc385418188086165927a2fa66cb7','66134569f999951e8eefef737424f12aeba24616'],cwd=root))
footprint=[]
for path in subprocess.check_output(['git','diff','--name-only',base,candidate],cwd=root,text=True).splitlines():
 def blob(ref):
  r=subprocess.run(['git','rev-parse','--verify',ref+':'+path],cwd=root,capture_output=True,text=True);return None if r.returncode else r.stdout.strip()
 footprint.append({'path':path,'base_blob':blob(base),'candidate_blob':blob(candidate)})
assert len(footprint)==24
wave=json.loads((scratch/'phase2-final/affected.execution.json').read_text());retry=json.loads((scratch/'phase2-final/fixture-retry.execution.json').read_text());assert wave['denominator']=={'tests':56,'failures':2,'errors':0,'skipped':0};assert retry['denominator']=={'tests':2,'failures':0,'errors':0,'skipped':0}
origins=json.loads((scratch/'phase2-final/loaded-module-origins.json').read_text());retry_origins=json.loads((scratch/'phase2-final/fixture-retry.origins.json').read_text());assert origins['byte_mismatches']==retry_origins['byte_mismatches']==0
originals=json.loads((pack/'interval-admission.json').read_text())['original_bindings']
originalB21=json.loads((pack/'mean-error.json').read_text())['original_criterion']
common={
 'schema':'policyos.e02.orch03.source_handoff.v1','role':'C09','canonical_writer':'/root/c09','original_unit_owner':'E predictive/calibration producer; B21 original owner A/SIM-03 preserved','topic':'codex/e02-E-c09-20261008',
 'slice_base_sha':base,'slice_base_tree':'99f904d38e56fc5709a78a3a20c980b6e6fba9d4','G_interval_dependency':'71ec2e0758cd7cd93423d3a91afe1a07cef61401','G_law_dependency':'d23ea5e9dd252214fc9e0c5c941a8a3789cead0a',
 'candidate_sha':candidate,'candidate_tree':tree,'runtime_source_sha':runtime,'runtime_source_tree':'f2c1f993052c25586420d07c766b868f632fbf39',
 'implementation_commits':['aa2d87945c2fc385418188086165927a2fa66cb7','66134569f999951e8eefef737424f12aeba24616','adb66080e3ac64d73b3faa85d693a47c6c284427','b3df9b6d84c67b48e91ea9227cadb89f5010b2a2'],
 'source_acceptance_G':'not_issued; historical ee0/1b8 HOLD preserved until G selects this forward source','formal_finding_closure':'not_issued','closed_ids':[],
 'admission':{'carrier':'8077016f144712b00a05f0b3b6701c51852f1d21','path':'policy-engine/docs/research/e02-cloud-test-plan/implementation-handoffs/ORCH03/parallel-20261008-c09-propagation-resume.json.gz','branch':'codex/e02-E-c09-20261008','worktree':'/dev/shm/e02-orch03-20261008/c09','status':'admitted','decoded_sha256':'9eab02529709f5a7371785f639acd0e505118b38227905eecaaa8abb9c5fc1c6','full_JSON_custody':'exactroot807 receipt; not duplicate broad workspace JSON here'},
 'full_footprint':footprint,'full_diff':'interval-consumer-basis/implementation.diff','full_output_custody':'interval-consumer-basis/artifact-manifest.json + archive-members.json.gz; complete stdout/stderr/JUnit/commands/origins/CAS/control bytes, all attempts retained; Git source archives/cache excluded as reproducible, exact source objects retained',
 'reviews':[{'name':name,'path':'interval-consumer-basis/independent-'+name+'-review.json','sha256':digest,'decision':'GO'} for name,path,digest in reviews],
 'checks':[
  {'name':'final_affected_wave','source_sha':runtime,'check_state':'FAIL','counts':{'PASS':54,'FAIL':2,'ERROR':0,'SKIP':0},'denominator':56,'wall_seconds':wave['wall_seconds'],'max_rss_kib':wave['max_rss_kib'],'origin_denominator':origins['loaded_denominator'],'origin_mismatches':0,'outputs':'author-final.tar.gz affected.* +loaded-module-origins.json','reason':'both old calibration_validation fixtures use absent shaped candidate refs; existing real CAS resolver correctly refuses before job. No inherited/P41 attribution.'},
  {'name':'fixture_forward_retry','source_sha':candidate,'check_state':'PASS','counts':{'PASS':2,'FAIL':0,'ERROR':0,'SKIP':0},'denominator':2,'wall_seconds':retry['wall_seconds'],'max_rss_kib':retry['max_rss_kib'],'origin_denominator':retry_origins['loaded_denominator'],'origin_mismatches':0,'outputs':'author-final.tar.gz fixture-retry.*','qualification':'only two corrected test body selectors. src/schema/architecture trees byte-identical through b3; all54 unchanged case inputs carried. No whole56-case b3 run asserted.'},
  {'name':'independent_661_defining_controls','source_sha':'66134569f999951e8eefef737424f12aeba24616','check_state':'PASS','ordinary_observations':18,'retained_marker_EXPECTED_FAIL':4,'fresh_child_refs':14,'parent_loaded_origins':988,'child_loaded_origins':971,'origin_mismatches':0,'outputs':'review-661.tar.gz','qualification':'real C5b native Matrix/Stress/Leaderboard and actual ETS; fixture governance/context is not authentic authority. Private harness attempts1/2ERROR retained; third uses previously actual persisted deciding outputs, not repeated numerical jobs.'},
  {'name':'independent_adb_summary_delta','source_sha':runtime,'check_state':'PASS','ordinary_controls':3,'retained_marker_EXPECTED_FAIL':1,'fresh_child_refs':4,'parent_child_loaded_origins':862,'origin_mismatches':0,'outputs':'review-adb.tar.gz','qualification':'limited/complete/point-only and fake summary; preserved other annotations'},
  {'name':'scoped_quality_and_compatibility','check_state':'PASS','outputs':'author-final.tar.gz static.* +compatibility-inspection.*','scope':'14 changed Python files Ruff/format +exact2 fragments+same-object governance alias+additive constructor; no global lint/scanner/public-surface verdict'},
  {'name':'changed_import_directions','check_state':'PASS','direction_violations':0,'reported_cycle_count':1,'cycles_enforced':False,'outputs':'author-interval.tar.gz imports.*','qualification':'direction report exit0; broad cycle warning remains non-enforced/unattributed, not global strictarchitecturePASS'}],
 'attempts_and_historical_red':[
  'independent baselineee0 actual full C5b/forecast/temporal FAIL and prior setupERROR fully retained; no authority positive inferred',
  'author development first19-case run15PASS/3FAIL/1ERROR: new test fixture setup mistakes (missing cas_store fixture/media_type), all fulloutputs retained; second23case PASS before later orphan/reconciled-issue additions, not final frozen proof',
  'author and independent661 temporal-summary product diagnostic FAIL retained; typed degraded/trust protection stayed effective. ForwardADB supersedes only that property.',
  'independent661 private Forecast-reader module and point_forecasts name errors are harness ERROR/incomplete, not product/backendFAIL; complete attempt/CAS bytes retained',
  'historical1b8 weighted-bootstrap law label is false despite unavailable/null nongating SEM; old37 PASS covers its original assertions, not newlabeltruth. Existing law-label-supersession source qualifier retained in prior reviewer custody; no old37 rerun.',
  'ADB wide-wave2 unexpected pytestFAIL preserved; root-approved b3 actualcandidate fixtures corrected only these cases,2PASS separate',
  'global scannerERROR/incomplete, Ruff/public-surface reds and P41not_established unchanged; no inherited/globalgreen claim'],
 'limits_and_next_owners':[
  {'owner':'C10 predictive consumer/C09 producer','check_state':'UNRUN','limit':'authentic ordered source/row currentness: OutcomeComparison lacks row/time ID; coherent substituted equal-count rows not detected from report shape','minimum_packet':'interval-consumer-basis/minimum-row-roster-packet.json','next_result':'existing ForecastOwner actual observedDataSnapshot+explicit split/horizon+actual source/prediction/bundle/report refs resolved and ordered paired roster compared; no invented row IDs'},
  {'owner':'C10/Runtime/S10 +accountable scientific source owner','check_state':'UNRUN','limit':'no authentic verifier/current revision/appointment/fresh challenge/scientific-law admission; fixture role/context and governance approve remain fixtures','next_result':'exact permitted source/CAS/manifest/bytes and genuine current verifier/context/issuer/revision/fresh challenge packet when criterion requires authority'},
  {'owner':'E/BKT accountable purpose owner','check_state':'not_established','limit':'historical heuristic trust policy remains separate; no universal neutral/equivalence proof or B172/B173 scientific inference closure'},
  {'owner':'A/B21 and E MC source/law owner','check_state':'bounded_nongating_only','limit':'Normal-input conditional SEM assumes unverified deterministic response/finite variance; no scientific meanCI or universalIID law; unknown/adaptive/incomplete/weighted/QMC pooled profile unavailable'},
  {'owner':'G','check_state':'UNRUN','limit':'installed/current integration/production composition and source/finding acceptance; no new wheel/sdist or C13 broad replay'}],
 'delta_only_carry':{'prior_CI_source':'ee0b2c85289d8c5537ba4e01713d9be71e2f557e','prior_CI_receipt':'514f90058104f7dd8ada1c83b8bf5f62bfc33b88','prior_MC_source':'1b8c9e1c84d9f2e86d4b0900bf5aa54515487747','prior_MC_receipt':'0c3c1ed6a40823f56fef6e8e565d8990df7b3942','qualification':'old79/37 bounded property receipts historical only; newaffectedconsumers and label controls run. All MC4 label blobs unchanged661→ADB→b3; b3 only2 candidate testfixtures. Independent complete source/AST closure in main/fixture/retry reviews. No cumulative Ecarrier import.'},
 'cleanup':{'performed':False,'preserve':'source/docs/unique inputs/deciding outputs/active environments','candidates_for_later_review':[str(scratch/'phase2-interval-consumers/development-bases'),str(scratch/'phase2-interval-consumers/development2-bases'),str(scratch/'phase2-final/affected-bases'),str(scratch/'phase2-final/fixture-retry-bases')],'action':'no deletion or Trash action; exact candidates only; inactive-user check still required before future cleanup'}
}
interval=dict(common,slice='shared-interval-basis-consumer-consistency',original_bindings=originals,original_binding_scope='B172/B173 underlying maintained diagnostic cards preserved; this P40 consumer-property followup adds no finding ID or full original closure',property='One canonical numerical interval basis reconciles actual finite ordered bounds/hits/requested typed counts and retained limitations across temporal/report/score/forecast/promotion. Conditional evaluated-pair coverage cannot be promoted by missing/fake positive metadata. Actual CAS kind/schema/bytes and full matrix/kind/scenario roster checked before promotion. Reserved temporal summary stays recomputed.',producer_artifact_bridge_consumer_surface=['HistoricalValidationPlan actual inputs→PredictionEvaluator','real BacktestOrchestrator/Matrix→persisted BacktestReport','actual temporal compiler/solver/evaluator→public report builder→CAS/fresh child','CalibrationValidationRunner existing CAS→actual report-profile/bytes/kind/scenario readback→CalibrationLeaderboard promotion','actual forecast bridge produce/persist/fresh reader (fixture-content positive; genuine Runtime admission UNRUN)'],oracle_negative={'oracle':'actual complete15/15 vs partial15/5 roster, paired observed hits, complete/point-only/legacy controls and real configured ETS holdout changes; preserve partial conditional coverage1.0 and point errors','negative':'fake/missing evaluated marker, retained issue/orphan rate, empty/foreign axis, forged matrix score, missing/corrupt/wrongkind/schema CAS, fake temporal summary','retained_marker':'four independent runtime removals on661 +one summary removalADB EXPECTED_FAIL while enums/strings/diagnostics/raw rows retained'},compatibility='CalibrationLeaderboard optional store additive; existing store reused. Deep governance alias same object. No new schema/export/rootstable helper; explicit supported entrypoint inventory scope inspected, unresolved totals remain unresolved.')
(pack/'interval-consumer-basis.json').write_text(json.dumps(interval,indent=2,ensure_ascii=False)+'\n')
law=dict(common,slice='MC-actual-input-recipe-label',original_criterion=originalB21,property='Observed sampling_law names actual implemented input recipe, separate from supported estimator profile. Fixed-random typedNormal product label only on that actual profile; weighted/inferred/adaptive/QMC uses generic recipe label plus actual family/carrier. No numeric eligibility/formula/count/gate change.',law_implementation_sha='66134569f999951e8eefef737424f12aeba24616',law_implementation_tree='a1d408e8c9ead9573a9ad846b6672d9c6dc7506e',law_full_diff='interval-consumer-basis/law-label.diff',law_footprint=[i for i in footprint if '/foundry/uncertainty/' in i['path'] or i['path'].endswith('2026-10-08-c09-mc-mean-error.toml')],producer_artifact_bridge_consumer_surface=['typed actual uncertainty carrier→MonteCarloPropagator actual sampler','mean_estimator_error actual input_recipe_profiles and supported_estimator_profile','persist_uncertainty_envelope→fresh independent child'],oracle_negative={'positive':'actual fixed typedNormal100finite draws retains Normal product law and conditional SEM; arithmetic unchanged','negative':'weighted Bootstrap .9/.1 PosteriorSamplesCarrier with counterfeitNormal/iid metadata100requested/attempted/finite must remain generic/unavailable/null/nongating; legacy/adaptive/QMC profiles disclosed','retained_marker':'restore only old Normal label while unsupported reason/null/false fields and raw carrier remain; native label assertion EXPECTED_FAIL'},original_scope='C09 supplier followup only; original A/B21 complete requested replication contract remains separate, no full B21 closure')
(pack/'mean-law-label.json').write_text(json.dumps(law,indent=2,ensure_ascii=False)+'\n')
manifest=[]
for p in sorted(packet.rglob('*')):
 if p.is_file() and p.name!='artifact-manifest.json':manifest.append({'path':str(p.relative_to(root)),'bytes':p.stat().st_size,'sha256':hashlib.sha256(p.read_bytes()).hexdigest()})
(packet/'artifact-manifest.json').write_text(json.dumps({'schema':'policyos.e02.complete_lossless_transport.v1','artifacts':manifest,'archives_summary':[{k:v for k,v in a.items() if k not in {'members','exclusions'}} for a in archives],'complete_archive_members':'archive-members.json.gz','exclusions':'only reproducible Git source/cache androot807 full doctor custody; no unique/deciding bytes removed'},indent=2)+'\n')
report=pack/'REPORT.md'
with report.open('a') as f:f.write('\n\nForward C09 consumer/law delivery: runtime `'+runtime+'` / tree `f2c1f993052c25586420d07c766b868f632fbf39`, test-only companion `'+candidate+'` / tree `'+tree+'`. The shared interval invariant now reaches actual temporal/CAS, Matrix/Stress/Leaderboard promotion, and forecast consumers; caller annotations cannot replace recomputed temporal summary. MC observed recipe labels describe actual carriers separately from estimator support. Independent source reviews are GO. Actual affected ADB wave remains **54 PASS /2 FAIL /0 ERROR/SKIP** (56 cases); two old missing-CAS candidate fixtures were corrected in b3 and only those selectors retried: **2 PASS**. No complete56-case b3 run or G acceptance is asserted. Eighteen ordinary independent661 controls plus threeADB controls passed; five retained-property removal controls failed as expected; separate fresh children reopened14+4 refs. See [interval handoff](interval-consumer-basis.json), [law-label handoff](mean-law-label.json), and [lossless transport manifest](interval-consumer-basis/artifact-manifest.json). Authentic ordered source-row roster and genuine Runtime/S10 admission remain UNRUN under the committed minimum packet. Historical intake/mean receipts and all prior red/error attempts remain separate. No broad old79/37 wave, installed/G composition, source/finding acceptance or main publication is claimed.\n')
print(json.dumps({'source':candidate,'runtime':runtime,'footprint_paths':len(footprint),'archive_count':len(archives),'archive_members':sum(a['member_count'] for a in archives),'decoded_member_bytes':sum(a['member_payload_bytes'] for a in archives),'stored_archive_bytes':sum(a['stored_bytes'] for a in archives),'transport_files':len(manifest),'outputs':str(packet)},indent=2))
