"""Unrun owner-boundary probes; no production writes or scientific authority.

The output probe supplies genuinely recomputed current payload bytes at the
reader seam while epoch artifacts are not yet committed. All gate logic runs.
"""

# Disposable instrumentation deliberately prints complete evidence and asserts it.
# ruff: noqa: ANN001, ANN002, ANN003, ANN202, S101, T201

from __future__ import annotations

import argparse
import copy
import hashlib
import inspect
import json
import tempfile
from pathlib import Path
from unittest.mock import patch

ROOT = Path(__file__).resolve().parents[3]


def _identities(issues):
    return {json.dumps(issue, sort_keys=True, separators=(",", ":")) for issue in issues}


def _report(stage, report):
    # These two fields duplicate the live producer's derived packet bodies.
    # Keep the complete finding list and bind omitted recomputable projections.
    result = {key: value for key, value in report.items() if key not in {"accuracy", "ingest"}}
    result["recomputable_projection_sha256"] = {
        key: hashlib.sha256(json.dumps(report[key], sort_keys=True).encode()).hexdigest()
        for key in ("accuracy", "ingest")
        if key in report
    }
    print(json.dumps({"stage": stage, "report": result}, sort_keys=True), flush=True)


def marked_list_outputs() -> None:
    from tools.quality.validation import check_layer3_gy_openalex_artifacts as gate

    live = gate.build_live_payloads(ROOT)
    declared = set(gate.declared_outputs())
    assert set(live) == declared == set(gate.OUTPUTS)
    assert len(live) == len(gate.OUTPUTS), "duplicate_declared_output"
    original_reader = Path.read_text
    original_bytes = Path.read_bytes
    original_exists = Path.exists
    original_is_file = Path.is_file
    contents = {
        ROOT / relative: json.dumps(payload, indent=2, sort_keys=True) + "\n"
        for relative, payload in live.items()
    }

    def read_text(path, *args, **kwargs):
        if path in contents:
            return contents[path]
        return original_reader(path, *args, **kwargs)

    def read_bytes(path):
        if path in contents:
            return contents[path].encode("utf-8")
        return original_bytes(path)

    def exists(path, *args, **kwargs):
        return path in contents or original_exists(path, *args, **kwargs)

    def is_file(path, *args, **kwargs):
        return path in contents or original_is_file(path, *args, **kwargs)

    def fixed_live(repo_root):
        assert repo_root.resolve() == ROOT
        return copy.deepcopy(live)

    print(
        json.dumps(
            {
                "probe": "whole_owner_current_output_object_contract",
                "declared_output_identities": sorted(declared),
                "station_control": (
                    "Current generated bytes supplied only at Path read/exists seam; "
                    "one actual complete live recomputation reused; no gate or lifecycle bypass. "
                    "Any not-yet-reissued registry/input issues remain in the complete baseline."
                ),
            },
            sort_keys=True,
        ),
        flush=True,
    )
    failures = []
    with (
        patch.object(Path, "read_text", read_text),
        patch.object(Path, "read_bytes", read_bytes),
        patch.object(Path, "exists", exists),
        patch.object(Path, "is_file", is_file),
        patch.object(gate, "build_live_payloads", fixed_live),
    ):
        baseline = gate.validate(ROOT)
        _report("baseline_current_payloads", baseline)
        baseline_ids = _identities(baseline["issues"])
        for relative in sorted(declared):
            path = ROOT / relative
            original = contents[path]
            payload = live[relative]
            assert isinstance(payload, dict)
            assert isinstance(payload["schema_version"], str)
            # Delete every substantive field, keep all original lifecycle markers
            # within a top-level array the nested provenance walker understands.
            markers = {
                key: payload[key]
                for key in ("schema_version", "gy_lifecycle_marker", "produced_by")
                if key in payload
            }
            contents[path] = json.dumps([markers], sort_keys=True)
            try:
                measured = gate.validate(ROOT)
                _report(f"marked_list:{relative}", measured)
                measured_ids = _identities(measured["issues"])
                lost = baseline_ids - measured_ids
                added = measured_ids - baseline_ids
                print(
                    json.dumps(
                        {
                            "path": relative,
                            "lost_baseline_identities": [json.loads(row) for row in sorted(lost)],
                            "added_identities": [json.loads(row) for row in sorted(added)],
                        },
                        sort_keys=True,
                    ),
                    flush=True,
                )
                if lost or not added:
                    failures.append(
                        {"path": relative, "lost": sorted(lost), "added": sorted(added)}
                    )
            finally:
                contents[path] = original
    assert not failures, "current_object_contract_not_enforced:" + json.dumps(
        failures, sort_keys=True
    )


def _check_accuracy(gate, payload, root):
    issues = []
    kwargs = {"expected": payload, "issues": issues}
    # Before repair call the existing signature and obtain its actual wrong-root
    # content finding. After repair consult the explicit root, not an API error.
    if "repo_root" in inspect.signature(gate.validate_accuracy_report_payload).parameters:
        kwargs["repo_root"] = root
    gate.validate_accuracy_report_payload(payload, **kwargs)
    return issues


def alternate_population_root() -> None:
    from tools.quality.validation import check_layer3_gy_openalex_artifacts as gate

    baseline = gate._build_current_accuracy_payload(ROOT)
    baseline_issues = _check_accuracy(gate, baseline, ROOT)
    print(
        json.dumps({"stage": "original_root", "issues": baseline_issues}, sort_keys=True),
        flush=True,
    )
    assert baseline_issues == []
    parent = ROOT / "_build/gy-gaps/k"
    with tempfile.TemporaryDirectory(prefix="actual-population-root-", dir=parent) as directory:
        alternate = Path(directory)
        config = json.loads((ROOT / gate.CONFIG_PATH).read_text())
        paths = config["provenance"]["recorded_response_fixtures"]
        assert len(paths) == len(set(paths))
        relocated_paths = []
        source_bindings = []
        for relative in paths:
            relocated = "relocated_recorded_population/" + relative
            raw = (ROOT / relative).read_bytes()
            destination = alternate / relocated
            destination.parent.mkdir(parents=True, exist_ok=True)
            destination.write_bytes(raw)
            relocated_paths.append(relocated)
            source_bindings.append(
                {
                    "original_path": relative,
                    "relocated_path": relocated,
                    "same_raw_sha256": hashlib.sha256(raw).hexdigest(),
                }
            )
        config["provenance"]["recorded_response_fixtures"] = relocated_paths
        config_path = alternate / gate.CONFIG_PATH
        config_path.parent.mkdir(parents=True, exist_ok=True)
        config_path.write_text(json.dumps(config, sort_keys=True))
        expected = gate._build_current_accuracy_payload(alternate)
        before_rows = baseline["accuracy"]["observations"]
        after_rows = expected["accuracy"]["observations"]
        original_work_query = sorted((row["openalex_id"], row["query"]) for row in before_rows)
        alternate_work_query = sorted((row["openalex_id"], row["query"]) for row in after_rows)
        assert original_work_query == alternate_work_query
        assert len(before_rows) == len(after_rows)
        assert {row["case_id"] for row in before_rows}.isdisjoint(
            {row["case_id"] for row in after_rows}
        ), "relocated_source_custody_did_not_affect_identity"
        assert baseline != expected
        issues = _check_accuracy(gate, expected, alternate)
        print(
            json.dumps(
                {
                    "stage": "different_supplied_root_same_complete_recorded_source_population",
                    "source_bindings": source_bindings,
                    "work_query_identities": original_work_query,
                    "complete_observation_denominator": len(before_rows),
                    "source_content_changed": False,
                    "positive_accuracy_claim": None,
                    "issues": issues,
                    "explicit_repo_root_argument_available": (
                        "repo_root"
                        in inspect.signature(gate.validate_accuracy_report_payload).parameters
                    ),
                },
                sort_keys=True,
            ),
            flush=True,
        )
        assert issues == [], "valid_alternate_root_compared_against_module_home:" + json.dumps(
            issues
        )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("mode", choices=("marked-list", "supplied-root"))
    args = parser.parse_args()
    if args.mode == "marked-list":
        marked_list_outputs()
    else:
        alternate_population_root()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
