"""Read-only source-bound B56 dependency packet; no production or authority writes."""
from pathlib import Path
import hashlib,json,subprocess
ROOT=Path('/workspace/e02-F-closeout-20261006')
OUT=Path('/tmp/e02-F-continuation-20261006/tmle-bridge-investigation')
REF='4a038c2ebf0c4fd79dcc084c983ed7b76756a488'
def git(*args):return subprocess.check_output(['git',*args],cwd=ROOT)
def h(data):return hashlib.sha256(data).hexdigest()
def ref(path):
 data=Path(path).read_bytes();return dict(path=str(path),bytes=len(data),sha256=h(data))
def bind(path):
 data=git('show',f'{REF}:{path}');assert (ROOT/path).read_bytes()==data
 return dict(git_ref=REF,path=path,git_blob=git('rev-parse',f'{REF}:{path}').decode().strip(),bytes=len(data),sha256=h(data))
paths=['policy-engine/src/polisyos/scientist/orchestration/engine/runner/local_runner.py','policy-engine/src/polisyos/scientist/orchestration/engine/runner/config.py','policy-engine/src/polisyos/scientist/orchestration/engine/runner/local_pool.py','policy-engine/src/polisyos/scientist/orchestration/engine/runner/task_router.py','policy-engine/src/polisyos/scientist/orchestration/engine/runner/_activity_worker.py','policy-engine/src/polisyos/scientist/orchestration/engine/runner/serialization.py','policy-engine/src/polisyos/scientist/orchestration/engine/async_executor.py','policy-engine/src/polisyos/scientist/orchestration/engine/budget_middleware.py','policy-engine/src/polisyos/scientist/orchestration/workflows/builder.py','policy-engine/src/polisyos/scientist/orchestration/workflows/causal_full.py','policy-engine/src/polisyos/scientist/api.py','policy-engine/src/polisyos/runtime/http/services/control/run_lifecycle.py','policy-engine/src/polisyos/runtime/http/services/control_worker.py','policy-engine/src/polisyos/runtime/quality/evaluation_safety.py','policy-engine/src/polisyos/foundry/methods/components/io.py','policy-engine/src/polisyos/foundry/methods/backends/numpy_runner.py','policy-engine/src/polisyos/foundry/methods/catalog/causal/_common.py','policy-engine/src/polisyos/foundry/methods/catalog/causal/g_computation.py','policy-engine/src/polisyos/foundry/methods/selection/advisor.py','policy-engine/tests/unit/foundry/methods/catalog/causal/test_tmle_fit_contract.py','policy-engine/docs/plans/active/agent-packages/PolicyOS_E02_Combined_Agent_Package/bundles/FIT-01.md']
source_bindings=[bind(p) for p in paths]
argv=['git','grep','-n','-E',r'LocalWorkerPool\(|TaskRouter\(',REF,'--','policy-engine/src/polisyos']
p=subprocess.run(argv,cwd=ROOT,stdout=subprocess.PIPE,stderr=subprocess.PIPE)
(OUT/'pool-construction-census.stdout.txt').write_bytes(p.stdout);(OUT/'pool-construction-census.stderr.txt').write_bytes(p.stderr)
assert p.returncode==1 and not p.stdout and not p.stderr
files=git('ls-tree','-r','--name-only',REF,'--','policy-engine/src/polisyos').decode().splitlines()
product_python=[x for x in files if x.endswith('.py')]
census=dict(command=argv,cwd=str(ROOT),source_sha=REF,exit_code=1,search_completed=True,outcome='PASS',interpretation='Zero literal direct LocalWorkerPool( or TaskRouter( construction sites across all tracked product paths at exactsource; not a proof excluding dynamic imports/indirect constructors or external composition',tracked_product_paths=len(files),tracked_product_python_files=len(product_python),python_path_denominator_sha256=h(('\n'.join(product_python)+'\n').encode()),output=str(OUT/'pool-construction-census.stdout.txt'),output_ref=ref(OUT/'pool-construction-census.stdout.txt'),stderr_ref=ref(OUT/'pool-construction-census.stderr.txt'))
(OUT/'pool-construction-census.json').write_text(json.dumps(census,indent=2)+'\n')
actual=[]
for name in ('job-v2','jobdefault-v3','input-v2','pool-v2'):
 run=json.loads((OUT/(name+'.json')).read_text());assert run['outcome']=='PASS' and run['exit_code']==0
 objects=[]
 for line in (OUT/(name+'.stdout.txt')).read_text().splitlines():
  if line.startswith('{'):
   try:objects.append(json.loads(line))
   except ValueError:pass
 stderr=(OUT/(name+'.stderr.txt')).read_text()
 actual.append(dict(name=name,execution=ref(OUT/(name+'.json')),output=str(OUT/(name+'.stdout.txt')),output_ref=ref(OUT/(name+'.stdout.txt')),stderr_ref=ref(OUT/(name+'.stderr.txt')),observed_probes=objects,user_warnings=stderr.count('UserWarning:'),prometheus_bootstrap_warnings=stderr.count('Prometheus metrics exporter disabled'),claim='PASS means the stated current behavior/refusal was reproduced, not production budget/causal authority admission'))
historical=[]
for name in ('job','input','pool','jobdefault-v2'):
 run=json.loads((OUT/(name+'.json')).read_text())
 historical.append(dict(execution=ref(OUT/(name+'.json')),outcome=run['outcome'],exit_code=run['exit_code'],output_ref=run['output_ref'],stderr_ref=run['stderr_ref'],classification={'job':'Whole original assertion ERROR; partial actual MethodJob configured-parameter refusal genuine','input':'Scratch expected blocker omitted @1.0.0 suffix; genuine current refusal retained','pool':'Scratch expected blocker omitted @1.0.0 suffix; genuine existing-pool refusal retained','jobdefault-v2':'Scratch compared JSON-normalized persisted tuples/lists with raw Python structures; native job succeeded; subsequent distinct semantic-normalized freshreader receipt supplies PASS'}[name]))
packet=dict(schema='policyos.e02.readonly-dependency-packet.v1',source_sha=REF,source_tree=git('rev-parse',REF+'^{tree}').decode().strip(),finding_ids=['B56'],disposition='limited: codeable typed common producer/consumer bridge authorized only after exact lease; genuine admitted workload/shared aggregate resource positive UNRUN',preserved_B54='Existing fitcacheidentity/readermutability/binaryboundedlogit/regular_iidEIF implementations unchanged; this packet does not replace prior deciding native receipts',source_bindings=source_bindings,actual_executions=actual,historical_errors_retained=historical,constructor_denominator=ref(OUT/'pool-construction-census.json'),observations=[
 dict(axis='producer_method_identity',property='Canonical cross-sectional binary-treatment TMLE has FQN causal.treatment_effects.tmle@1.0.0; CausalMethod currently has no TMLE value; LTMLE is genuinely longitudinal state A_seq/L_seq with E[Y^a], not equivalent'),
 dict(axis='input_route',property='HTEObservationalData is an existing shape-valid cross-sectional DTO, but lacks contract_id. TMLE accepts only raw Mapping X/treatment/outcome; common legacy loader classifies exactTMLE as defaultPanel and fails. Selected ObservationMethodInputEnvelope rejects absent native method contract capability; no new ID is inferred'),
 dict(axis='public_parameters',property='TMLE signature.parameters empty causes actual configured MethodJob rejection before fit. Direct pure_step-only tests do not cover this real ABI. Canonical defaults must use ATENuisanceContract.from_params({}), whose outcome_scaling auto differs from dataclass constructor raw+standardized'),
 dict(axis='numerical_output',property='Default real MethodJob invokes native models, serial all 15 default fold tasks, outputs result only with actual candidate point/CI. Complete fresh CAS semantic-normalized result equality established. Producer/reader metadata is reproducibility evidence only, not permission or identification'),
 dict(axis='resource_composition',property='LocalWorkerPool exposes real admission/queue but current common Node worker context drops EvalSafety context/verifier; actual registered common node returns execution_context_missing twice, no fits. LocalWorkflowRunner instantiates per-workflow AsyncWorkflowExecutor. Actual scientist_causal_full builder uses syncWorkflowExecutor; Runtime embedded ControlWorker leases one job at a time per worker and Runtime RunLifecycle supplies legitimate admission to local run_experiment. No shared all-deployment concurrency budget is inferred from these per-instance limits'),
 dict(axis='budget_owner',property='BudgetMiddleware is thread-safe monetary reservation/spend/ledger accounting, not CPU/fold admission. Runtime NL max_parallel_models is run-specific. No new global scheduler or shared executor substitution is proposed'),
 dict(axis='prior_pool_fixture',property='Existing test_native_studies_wait_in_actual_worker_pool_without_nested_fold_fanout genuinely tests pool/native folds/CAS for synthetic registered StudyNode; it does not execute the canonical common causal Node, Runtime admission or deployed all-study workload')],proposed_producer_lease=[
 'policy-engine/src/polisyos/foundry/methods/catalog/causal/treatment_effects.py (TMLE branch only, native ParameterSpec declarations, HTE|legacy adaptation, additive declared literal result/report/envelope slots, public pure projection)',
 'policy-engine/src/polisyos/ir/analytics/causal.py (only scientific CausalMethod.TMLE="tmle", existing status/report validation unchanged)',
 'policy-engine/tests/unit/foundry/methods/catalog/causal/test_tmle_common_report.py (unique actual MethodJob/freshreader/type/consumer/negative profiles)',
 'policy-engine/docs/reference/foundry/tmle-common-report.md (unique candidate/lifecycle limits)',
 'policy-engine/release-fragments/unreleased/2026-10-06-tmle-common-report.toml (structured additive public enum/method compatibility)',
 'unique own handoff/complete deciding logs'],root_shared_consumer_lease='Existing run_causal_evaluation.py typed HTE route for exact canonical TMLE + persisted report/projection/result reconciliation; existing blocked admission and candidate caps retained. Root owns schema/public census refresh. Native typed legacy CAS route can be implemented without guessed new contract ID; selected input-envelope path requires actual owner registration packet',schema_delta='Only $defs.CausalMethod enum adds scientifically truthful tmle; CausalEffectReport field/schema_version1.0/status validation unchanged; existing report JSON consumers regression tested; previous reader that lacks enum requires coherent consumer upgrade, not alleged backward parsing acceptance',projection='Exact finite regular_iid/no-trim/converged EIF result creates SUCCESS point/CI candidate report. Unsupported inference/trim/positivity gives existing point-free ASSUMPTION_FAILED report; nonconverged gives point-free NUMERICAL_FAILURE, confidence_interval=None. Actual descriptive payload persists as legacy result. Existing failure uncertainty range is explicitly heuristic and non-gating, never relabelled confidence interval.',minimum_owner_packet=[
 dict(owner='Runtime/PDC current EvaluationSafety composition',required='An existing appointed EvalSafetyVerifierPort, accepted current EvaluationExecutionContext/revision/owner/mode, exact real CAS observational/selectedcontract/bundle/intake identities and independently reconciled provenance; fresh actual common consumer challenge must verify. Supply canonical owner fixture/constructor from actual Runtime, not fake verifier/marker/state flag'),
 dict(owner='IR/Foundry DataForge existing input-contract owner',required='Exact admitted cross-sectional view with outcome,treatment,covariates/sample order/feature names/target population/estimand/contrast; if selected ObservationMethodInputEnvelope is acceptance prerequisite, supply genuine native registered contract_id + target owner and method relation. HTE shape validity alone is not input source/admission'),
 dict(owner='C/Runtime runner &deployment resource owner',required='Actual production entrypoint path Runtime durable job→configured worker instances→Scientist common node→MethodJob and resource policy/configuration owner/revision; identify whether cap is per study/workflow/worker/process/deployment, current worker count/shared queue identity, actual existing admission/wait trace. Provide canonical accepted local context carrier or remote worker verifier reconstruction bridge before real-pool positive'),
 dict(owner='G actual study workload owner',required='Pinned candidate SHA + admitted finite run/study IDs, exact retained data refs/local access, complete model/fit configs, seeds and seed manifest, folds/repeats/test index digests, competing jobs, required aggregate budget scope/resource metrics. G measures complete allfold results, numerical/provenance equality across allowed budgets, real active/wait/maxRSS/wall with no omitted studies or repeats'),
 dict(owner='Runtime/IR identification issuer',required='Identification authorization distinct from EvalSafety. Until genuine current source/graph/estimand/target-bound issuer/verifier bridge is supplied, reports/envelopes remain candidate/non-gating even numerical SUCCESS/CI.')],falsifier='On exact coherent candidate, run current Runtime-issued context/input-bound common node alongside competing admitted jobs under the actual owner budget; observe admission/wait counts and all native fold executions and persisted fresh-reader full report/result lineage. Any wrong input/seed/estimand, unsupported profile/fake admission/context or copied proof must refuse/non-gate. If fresh canonical common admission/workload cannot be supplied, production B56 remains UNRUN/limited.',production_writes=False,tests_only_scratch=True)
(OUT/'feasibility-packet.json').write_text(json.dumps(packet,indent=2)+'\n')
selected=['probe.py','replay.py','probe-v2.py','replay-v2.py','probe-v3.py','replay-v3.py','assemble_packet.py','feasibility-packet.json','pool-construction-census.json','pool-construction-census.stdout.txt','pool-construction-census.stderr.txt']
for name in ['job','input','pool','job-v2','input-v2','pool-v2','jobdefault-v2','jobdefault-v3']:
 selected.extend([name+'.json',name+'.stdout.txt',name+'.stderr.txt'])
selection=dict(schema='policyos.e02.transfer-selection.v1',source_sha=REF,files=[ref(OUT/p) for p in selected],total_bytes=sum(ref(OUT/p)['bytes'] for p in selected),sanitation='None; original complete moderate stdout/stderr/log bodies include warnings and harness ERRORs. No credentials/raw admitted production inputs in these synthetic probes; no copied trackedsource bodies.',exclusions='Synthetic temp CAS stores/caches are nondeciding; exact artifacts and source Git refs bound. No duplicated historical source or generated views.')
(OUT/'transfer-selection.json').write_text(json.dumps(selection,indent=2)+'\n')
print(json.dumps(dict(packet=ref(OUT/'feasibility-packet.json'),selection=ref(OUT/'transfer-selection.json'),unique_files=len(selected),total_bytes=selection['total_bytes'],production_positive='UNRUN')))
