import { describe, expect, it } from "vitest";
import { epochNonreceipt } from "@/shared/ui/temporal/TimeSemanticsLabel";

import type { BureaucraticDocumentAST } from "../ast/bureaucratic-document-ast";
import { exportBureaucraticHtml } from "./export-html";
import { checkBureaucraticExportParity } from "./parity-check";

describe("bureaucratic export parity", () => {
  it("renders every AST block with machine-readable watermark and lineage", () => {
    const document = fixtureDocument();
    const html = exportBureaucraticHtml(document);
    const parity = checkBureaucraticExportParity(document, html);

    expect(parity).toMatchObject({
      missingBlockIds: [],
      passed: true,
      watermarkPresent: true,
    });
    expect(html).toContain('name="polisyos:watermark"');
    expect(html).toContain('name="polisyos:template-version"');
    expect(html).toContain('data-block-id="quantity_policy_cost"');
    expect(html).toContain('data-lineage-id="lin_policy_cost"');
    expect(html).toContain('data-raw-source-refs="artifact:source"');
    expect(html).toContain(
      "Generated by PolicyOS / Draft / Not an official state document",
    );
  });
});

function fixtureDocument(): BureaucraticDocumentAST {
  return {
    annexes: [
      {
        authorship: {
          author: "PolicyOS",
          author_role: "system",
          reviewed_by_human: false,
        },
        epistemic_origin: "imported",
        id: "annex_provenance",
        items: ["artifact:source"],
        kind: "annex",
        level: 1,
        raw_source_refs: ["artifact:source"],
        title: "Provenance",
      },
    ],
    blocks: [
      {
        authorship: {
          author: "PolicyOS",
          author_role: "system",
          reviewed_by_human: false,
        },
        epistemic_origin: "imported",
        id: "header",
        kind: "header",
        level: 1,
        title: "Header",
      },
      {
        authorship: {
          author: "PolicyOS",
          author_role: "system",
          reviewed_by_human: false,
        },
        children: [
          {
            authorship: {
              author: "PolicyOS",
              author_role: "system",
              reviewed_by_human: false,
            },
            epistemic_origin: "operator_filled",
            id: "child_clause",
            kind: "clause",
            level: 2,
            text: "Nested clause",
          },
        ],
        epistemic_origin: "model_generated",
        id: "quantity_policy_cost",
        kind: "quantity",
        level: 1,
        provenance: [{ kind: "result", label: "policy_cost" }],
        quantity: {
          lineage: {
            freshness: "current",
            id: "lin_policy_cost",
            status: "verified",
          },
          metric_id: "policy_cost",
          point: 100,
          quantity_class: "decision",
          unit: { code: "USD", display: "USD", system: "ucum" },
        },
        raw_source_refs: ["artifact:source"],
        title: "Policy Cost",
      },
    ],
    epistemic_summary: {
      evidence_filled: 0,
      imported: 0.5,
      model_generated: 0.25,
      operator_filled: 0.25,
    },
    genre: "postanova_kmu",
    id: "doc_1",
    jurisdiction: "ua",
    language: "uk",
    packet_hash: "abcdef123456",
    packet_id: "sha256:abc",
    render_timestamp: "2026-02-11T12:00:00Z",
    temporal_semantics: epochNonreceipt(),
    status: "draft",
    template: {
      genre: "postanova_kmu",
      id: "ua.kmu.postanova.v1",
      jurisdiction: "ua",
      legal_review_status: "pending_external_review",
      locale: "uk-UA",
      version: "1.0.0",
    },
    title: "Test document",
    trust_view: false,
    watermark: "Generated by PolicyOS / Draft / Not an official state document",
  };
}
