"""Public IR CAS boundary for artifact metadata, ref normalization, and JSON persistence helpers."""
from .contracts import (
    ArtifactID,
    ArtifactStore,
    CanonInfo,
    InputRef,
    PutOptions,
    SchemaInfo,
    StorePutOptions,
    normalize_artifact_ref,
    normalize_input_refs,
    to_store_put_options,
)
from .io import get_json_artifact, normalize_input_sequence, put_json_artifact
from .lineage import (
    ArtifactLineageEdge,
    ArtifactLineageGraph,
    ArtifactLineageNode,
    ArtifactLineageNodeKind,
    ArtifactLineageRelationKind,
    ArtifactTaskBinding,
    build_artifact_lineage_graph,
)
from .transport import (
    OBSERVATION_STREAM_TRANSPORT,
    ArtifactDeltaEntry,
    ArtifactDeltaEnvelope,
    BinaryWireFormat,
    DeltaSemantics,
    IncrementalRelinkManifest,
    ObservationBinaryBatchArtifact,
    ObservationStreamCheckpoint,
    ObservationStreamEntry,
    ObservationStreamUpdate,
    StreamUpdateOperation,
    TransportDescriptor,
    TransportMode,
)

__all__ = [
    "ArtifactID",
    "ArtifactStore",
    "ArtifactDeltaEntry",
    "ArtifactDeltaEnvelope",
    "ArtifactLineageEdge",
    "ArtifactLineageGraph",
    "ArtifactLineageNode",
    "ArtifactLineageNodeKind",
    "ArtifactLineageRelationKind",
    "BinaryWireFormat",
    "CanonInfo",
    "DeltaSemantics",
    "IncrementalRelinkManifest",
    "InputRef",
    "OBSERVATION_STREAM_TRANSPORT",
    "ObservationBinaryBatchArtifact",
    "ObservationStreamCheckpoint",
    "ObservationStreamEntry",
    "ObservationStreamUpdate",
    "PutOptions",
    "SchemaInfo",
    "StreamUpdateOperation",
    "StorePutOptions",
    "ArtifactTaskBinding",
    "TransportDescriptor",
    "TransportMode",
    "build_artifact_lineage_graph",
    "get_json_artifact",
    "normalize_artifact_ref",
    "normalize_input_refs",
    "normalize_input_sequence",
    "put_json_artifact",
    "to_store_put_options",
]
