import pathlib,json,hashlib,subprocess,re
D=pathlib.Path(__file__).parent;R=pathlib.Path('/workspace/e02-F-economics-20261006');F='8236d9c368336a5ea20c1586f29aea7321db6536';base=D/'transfer-selection.json'
def bind(p):
 b=p.read_bytes();return dict(path=str(p),bytes=len(b),sha256=hashlib.sha256(b).hexdigest())
for name in ['recovery-review.initial.stderr','recovery-review.second.stderr','recovery-review.third.stderr','recovery-review.stderr','recovery-review.stdout']:
 p=pathlib.Path('/tmp/e02-F-continuation-20261007/economics')/name;(D/('reviewer-'+name)).write_bytes(p.read_bytes())
p='policy-engine/docs/research/e02-cloud-test-plan/implementation-handoffs/F/economic-science-profiles-20261006-economic-native-final-candidate.txt';q=subprocess.run(['git','show',F+':'+p],cwd=R,capture_output=True);assert q.returncode==0;(D/'existing244-full-native-stdout.txt').write_bytes(q.stdout);(D/'existing244-full-native-fetch.stderr').write_bytes(q.stderr);assert re.search(rb'=+ 244 passed(?:,| in)' ,q.stdout)
receipt=json.loads((D/'existing244-native-receipt.stdout').read_bytes());claim=receipt['output'];native=dict(actual_full_Git_output=bind(D/'existing244-full-native-stdout.txt'),declared_original_raw_output=claim,stored_exact_declared_rawsha=hashlib.sha256(q.stdout).hexdigest()==claim['sha256'],role='Existing244source532 completeoriginalnativeoutput, re-readonly; no newnativeexecution or broad244transfer to8236/519/G855.',command=['git','show',F+':'+p],git_ref=F,output_path=p)
extra=dict(schema='policyos.e02.F.economics.review-supplement.v1',retry_source='519e4822f608cbe4e7ac1ee7b01f6c29cb84bc82',G_source='855cb26a7a2c9fea60356663cf81e7d01e20c738',prior_native=native,own_harness_errors='First expectedtwo193testsat8236 erroneously; secondscientific193treeassertion versus actualdocc008receipt; thirdmetadata-insertion NameError. Exactstderrretained, corrected sourceclaims; no productfailure or scientifictestexecution.',latest_script_stderr='ExplicitmissingG/sourcehistorypaths preserved, notproducterrors; actualpresent/missingpaths recordedinmetadata.',no_new_math_oracle_or_scanner_replay=True)
(D/'review-supplement.json').write_text(json.dumps(extra,indent=2)+'\n');old=json.loads(base.read_bytes());selected=old['selection']+[bind(p) for p in sorted(D.iterdir()) if p.is_file() and (p.name.startswith('reviewer-') or p.name in ['review-supplement.json','additional_output_bindings.py','existing244-full-native-stdout.txt','existing244-full-native-fetch.stderr'])];allnames=[x['path'] for x in selected];assert len(allnames)==len(set(allnames))
for row in selected:assert bind(pathlib.Path(row['path']))==row
out=dict(schema=old['schema'],files=len(selected),bytes=sum(x['bytes'] for x in selected),selection=selected,append_only_prior44review=old['append_only_prior44review'],intermediate63_selection=bind(base),no_huge_oldJSON_read_copy=True,all_output_bytes_lossless=True);(D/'transfer-selection-final.json').write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(dict(selection=bind(D/'transfer-selection-final.json'),review=bind(D/'source-review.json'),retry=bind(D/'retry-review-delta.json'),supplement=bind(D/'review-supplement.json'),files=len(selected),bytes=out['bytes'])))
