"""
Method Scaffold CLI — generate a new Foundry method skeleton.

Generates a fully-conforming method class file with:
- ``@foundry_method`` decorator
- Correctly typed ``signature``, ``metadata``, and ``pure_step``
- A companion ``_registry_boot.py`` stub if the target namespace is new
- An empty test file skeleton

Usage (standalone)
------------------
::

    python -m polisyos.foundry.methods.cli.scaffold \\
        --namespace causal.did \\
        --name my_new_did \\
        --version 1.0.0 \\
        --backend numpy \\
        --output-dir policy-engine/src/polisyos/foundry/methods/catalog/causal

Usage (programmatic)
--------------------
::

    from polisyos.foundry.methods.cli.scaffold import MethodScaffold

    scaffold = MethodScaffold(
        namespace="causal.did",
        name="my_new_did",
        version="1.0.0",
        backend="numpy",
    )
    scaffold.write(output_dir=Path("..."))
    print(scaffold.class_name)
"""
from __future__ import annotations

import re
import textwrap
from dataclasses import dataclass, field
from pathlib import Path
from typing import Sequence

__all__ = [
    "MethodScaffold",
    "ScaffoldConfig",
    "scaffold_method",
]


# ---------------------------------------------------------------------------
# ScaffoldConfig
# ---------------------------------------------------------------------------


@dataclass
class ScaffoldConfig:
    """Configuration for method scaffolding."""

    namespace: str
    name: str
    version: str = "1.0.0"
    backend: str = "numpy"
    input_slots: list[str] = field(default_factory=lambda: ["features", "target"])
    output_slots: list[str] = field(default_factory=lambda: ["result"])
    tags: list[str] = field(default_factory=list)
    description: str = ""
    fidelity: str = "medium"
    complexity: str = "O_N2"
    author: str = ""


# ---------------------------------------------------------------------------
# MethodScaffold
# ---------------------------------------------------------------------------


class MethodScaffold:
    """
    Generates a valid Foundry method skeleton from configuration.

    Parameters
    ----------
    namespace, name, version, backend:
        Core FQN components.
    input_slots, output_slots:
        Slot names to scaffold.
    tags:
        Metadata tags.
    description:
        Short docstring for the generated method.
    """

    def __init__(
        self,
        namespace: str,
        name: str,
        version: str = "1.0.0",
        backend: str = "numpy",
        input_slots: Sequence[str] | None = None,
        output_slots: Sequence[str] | None = None,
        tags: Sequence[str] | None = None,
        description: str = "",
        fidelity: str = "medium",
        complexity: str = "O_N2",
        author: str = "",
    ) -> None:
        self.namespace = namespace
        self.name = name
        self.version = version
        self.backend = backend.lower()
        self.input_slots = list(input_slots or ["features", "target"])
        self.output_slots = list(output_slots or ["result"])
        self.tags = list(tags or [namespace.split(".")[0]])
        self.description = description or f"Scaffold for {namespace}.{name}@{version}"
        self.fidelity = fidelity.upper()
        self.complexity = complexity
        self.author = author

    @property
    def class_name(self) -> str:
        """PascalCase class name derived from name."""
        parts = re.split(r"[._\-\s]+", self.name)
        return "".join(p.capitalize() for p in parts) + "Estimator"

    @property
    def fqn(self) -> str:
        return f"{self.namespace}.{self.name}@{self.version}"

    def render_method_file(self) -> str:
        """Return the rendered Python source for the method file."""
        supports_jit = self.backend == "jax"
        backend_enum = {
            "jax": "ComputeBackend.JAX",
            "numpy": "ComputeBackend.NUMPY",
            "solver": "ComputeBackend.SOLVER",
            "bayesian": "ComputeBackend.BAYESIAN",
        }.get(self.backend, "ComputeBackend.NUMPY")

        input_slots_code = "\n".join(
            f'            SlotSpec("{s}", SlotType.VECTOR, Unit("{s}", "value")),'
            for s in self.input_slots
        )
        output_slots_code = "\n".join(
            f'            SlotSpec("{s}", SlotType.SCALAR, Unit("{s}", "json")),'
            for s in self.output_slots
        )
        tags_repr = "{" + ", ".join(f'"{t}"' for t in self.tags) + "}"

        header = f'"""\n{self.description}\n\nAuto-generated by MethodScaffold.'
        if self.author:
            header += f"\nAuthor: {self.author}"
        header += '\n"""\nfrom __future__ import annotations\n\nfrom typing import Any, ClassVar, Mapping\n\nimport numpy as np\n'

        code = textwrap.dedent(f"""
            {header}

            from polisyos.foundry.methods.base import (
                ComplexityClass,
                ComputeBackend,
                FidelityLevel,
                MethodMetadata,
                MethodSignature,
                ParameterSpec,
                SlotSpec,
                SlotType,
                Unit,
                foundry_method,
            )


            @foundry_method(
                namespace={self.namespace!r},
                version={self.version!r},
                tags={tags_repr},
            )
            class {self.class_name}:
                \"\"\"
                {self.description}

                Replace this docstring with the method's full documentation.
                Describe the statistical model, assumptions, and limitations.
                \"\"\"

                signature: ClassVar[MethodSignature] = MethodSignature(
                    name={self.name!r},
                    namespace="placeholder",
                    version="0.0.0",
                    input_slots=frozenset({{
            {input_slots_code}
                    }}),
                    output_slots=frozenset({{
            {output_slots_code}
                    }}),
                    parameters=(
                        ParameterSpec(name="seed", default=0),
                    ),
                    fidelity=FidelityLevel.{self.fidelity},
                    complexity=ComplexityClass.{self.complexity},
                    backend={backend_enum},
                    supports_jit={supports_jit},
                    supports_vmap={supports_jit},
                    supports_grad={supports_jit},
                )

                metadata: ClassVar[MethodMetadata] = MethodMetadata(
                    description={self.description!r},
                    tags=frozenset({tags_repr}),
                )

                @staticmethod
                def pure_step(state: Any, params: Mapping[str, Any]) -> dict[str, Any]:
                    \"\"\"
                    Core computation.  Must be a pure function — no I/O, no globals.

                    Parameters
                    ----------
                    state : dict or domain object
                        Input data.  Access with ``state.get("key")`` or
                        ``state["key"]``.
                    params : dict
                        Runtime parameters declared in ``signature.parameters``.

                    Returns
                    -------
                    dict[str, Any]
                        Must contain keys matching ``signature.output_slots``.
                    \"\"\"
                    # TODO: implement this method
                    raise NotImplementedError(
                        f"{self.class_name}.pure_step is not yet implemented."
                    )
        """).lstrip("\n")
        return code

    def render_test_file(self) -> str:
        """Return a skeleton test file for the generated method."""
        return textwrap.dedent(f"""\
            \"\"\"Tests for {self.class_name}.\"\"\"
            from __future__ import annotations

            import numpy as np
            import pytest


            def test_{self.name}_registers() -> None:
                \"\"\"Method must register without errors.\"\"\"
                from polisyos.foundry.methods.registry import registry_scope
                with registry_scope() as reg:
                    from polisyos.foundry.methods.catalog.{self.namespace.replace(".", ".")} import {self.class_name}
                    reg.register({self.class_name})
                    assert reg.get({self.fqn!r}) is {self.class_name}


            def test_{self.name}_pure_step_raises_not_implemented() -> None:
                \"\"\"Scaffold stub must raise NotImplementedError until implemented.\"\"\"
                from polisyos.foundry.methods.catalog.{self.namespace.replace(".", ".")} import {self.class_name}
                with pytest.raises(NotImplementedError):
                    {self.class_name}.pure_step({{}}, {{}})
        """)

    def write(
        self,
        output_dir: Path,
        *,
        overwrite: bool = False,
        dry_run: bool = False,
    ) -> dict[str, Path]:
        """
        Write method and test files to *output_dir*.

        Returns a dict with keys ``"method"`` and ``"test"`` pointing to
        the written paths.
        """
        output_dir = Path(output_dir)
        method_path = output_dir / f"{self.name}.py"
        test_dir = output_dir.parents[4] / "tests" / "foundry" / "methods" / "catalog"
        for part in self.namespace.split("."):
            test_dir = test_dir / part
        test_path = test_dir / f"test_{self.name}.py"

        if dry_run:
            print(f"[dry-run] would write: {method_path}")
            print(f"[dry-run] would write: {test_path}")
            return {"method": method_path, "test": test_path}

        output_dir.mkdir(parents=True, exist_ok=True)
        if method_path.exists() and not overwrite:
            raise FileExistsError(
                f"{method_path} already exists. Use overwrite=True to replace."
            )
        method_path.write_text(self.render_method_file(), encoding="utf-8")

        test_dir.mkdir(parents=True, exist_ok=True)
        if not test_path.exists():
            test_path.write_text(self.render_test_file(), encoding="utf-8")

        return {"method": method_path, "test": test_path}


# ---------------------------------------------------------------------------
# Convenience function
# ---------------------------------------------------------------------------


def scaffold_method(
    namespace: str,
    name: str,
    output_dir: Path | str,
    *,
    version: str = "1.0.0",
    backend: str = "numpy",
    tags: Sequence[str] | None = None,
    description: str = "",
    dry_run: bool = False,
) -> dict[str, Path]:
    """
    Create a new Foundry method scaffold in *output_dir*.

    Returns a dict with ``"method"`` and ``"test"`` path keys.
    """
    s = MethodScaffold(
        namespace=namespace,
        name=name,
        version=version,
        backend=backend,
        tags=tags,
        description=description,
    )
    return s.write(Path(output_dir), dry_run=dry_run)


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------


def main() -> None:
    import argparse

    parser = argparse.ArgumentParser(
        prog="foundry-scaffold",
        description="Generate a Foundry method skeleton.",
    )
    parser.add_argument("--namespace", required=True, help="Method namespace, e.g. causal.did")
    parser.add_argument("--name", required=True, help="Method name (snake_case)")
    parser.add_argument("--version", default="1.0.0")
    parser.add_argument("--backend", default="numpy", choices=["numpy", "jax", "solver", "bayesian"])
    parser.add_argument("--output-dir", required=True, type=Path)
    parser.add_argument("--tag", action="append", dest="tags", default=[])
    parser.add_argument("--description", default="")
    parser.add_argument("--author", default="")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--overwrite", action="store_true")
    args = parser.parse_args()

    scaffold = MethodScaffold(
        namespace=args.namespace,
        name=args.name,
        version=args.version,
        backend=args.backend,
        tags=args.tags or None,
        description=args.description,
        author=args.author,
    )
    paths = scaffold.write(args.output_dir, overwrite=args.overwrite, dry_run=args.dry_run)
    for kind, path in paths.items():
        print(f"[{kind}] {path}")


if __name__ == "__main__":
    main()
