"""Full actual91 census, exact Graph membership and bounded historical warnings."""
import collections,hashlib,json,re,subprocess
from pathlib import Path
import xml.etree.ElementTree as ET
base=Path(__file__).resolve().parent;config=json.loads((base/'installed-config.json').read_text());old=Path(config['old_b5_scratch']);out={}
def status(c):return 'FAIL' if c.find('failure') is not None else 'ERROR' if c.find('error') is not None else 'SKIP' if c.find('skipped') is not None else 'PASS'
def key(c):return (c.attrib['classname'].split('tests.',1)[-1],c.attrib['name'])
for kind in ('wheel','sdist'):
 cases=list(ET.parse(base/(kind+'-junit.xml')).iter('testcase'));assert len(cases)==91
 graph=[c for c in cases if c.attrib['classname'].startswith('tests.')];assert len(graph)==79
 oldcases={key(c):c for c in ET.parse(old/(kind+'-junit.xml')).iter('testcase')};assert all(key(c) in oldcases for c in graph)
 transition=[{'module':c.attrib['classname'],'name':c.attrib['name'],'b5_outcome':status(oldcases[key(c)]),'current_outcome':status(c)} for c in graph]
 raw=(base/(kind+'-native-v2.stdout.txt')).read_text();err=(base/(kind+'-native-v2.stderr.txt')).read_text();proof=json.loads((base/(kind+'-installed-proof.json')).read_text());assert proof['isolated']==1 and not proof['origin_violations']
 anomalies=re.findall(r'\[(?:INFO|WARNING|ERROR)\] [^\\\n]*?: (?:nan_detected|inf_detected|unexpected_key|missing_key|empty_array|shape_mismatch|distribution_shift)',raw+'\n'+err)
 out[kind]={'actual_cases':len(cases),'outcomes':dict(collections.Counter(status(c) for c in cases)),'by_module':{name:dict(collections.Counter(status(c) for c in cases if c.attrib['classname']==name)) for name in sorted({c.attrib['classname'] for c in cases})},'actual_graph79_membership_identical_to_b5_subset':True,'graph_b5_counts':dict(collections.Counter(r['b5_outcome'] for r in transition)),'graph_current_counts':dict(collections.Counter(r['current_outcome'] for r in transition)),'complete_graph_membership_transition':transition,'origin_count':len(proof['product_origins']),'origin_violations':proof['origin_violations'],'literal_warning_counts':{'PytestUnknownMarkWarning':raw.count('PytestUnknownMarkWarning:'),'actual_AnomalyFlag_format_matches':len(anomalies),'LightGBM_literal':raw.count('LightGBM')+err.count('LightGBM'),'Prometheus_bootstrap_failure_literal':raw.count('Prometheus metrics exporter disabled')+err.count('Prometheus metrics exporter disabled'),'load_simulation_result_degraded_path_literal':raw.count('Degraded path component=governance.confidence_pass')+err.count('Degraded path component=governance.confidence_pass')},'stderr_bytes':len(err.encode())}
 assert out[kind]['outcomes']=={'PASS':91} and out[kind]['graph_b5_counts']=={'PASS':47,'FAIL':32}
neg=json.loads((base/'negative-controls.json').read_text());assert len(neg['profiles'])==6 and all(r['exit_code']==1 for r in neg['profiles'])
historical_path='policy-engine/docs/research/e02-cloud-test-plan/implementation-handoffs/F/installed-final-consumer-20261006.json';head='a2d55a1942e1f56f35cf2b9772ae56b0b46de95d';rawhistorical=subprocess.check_output(['git','-C',config['git_root'],'show',head+':'+historical_path])
summary={'source_sha':config['source_sha'],'source_tree':config['source_tree'],'outcome':'PASS','profiles':out,'expected_negative_controls_actual_FAIL':6,'expected_negative_property_detection':'PASS','historical_warning_denominator':{'receipt':historical_path,'git_sha':head,'bytes':len(rawhistorical),'sha256':hashlib.sha256(rawhistorical).hexdigest(),'denominator':'Original historical15=14 runtime+1 instrumentation; repaired8236 old selectedprofile0runtime with90optionalLightGBM separate. Current91 scope omits that old expensivewave; not freshly remeasured. Current warningmembership is exact unitmark only per rawnative stdout.','scope':'Prior profile/source bound evidence only; this resource-only delta does not revalidate all historical runtime consumers.'},'scientific_limits':'Native Graph/default data-resource consumers and synthetic inputs only; genuine operational/statistical/value authority and admitted B56 aggregate competingstudy budget remain UNRUN. No TMLE refit/backend inference here.','baseline_attribution':'Complete actualcurrent79Graph IDs match b5subset; observed47PASS32FAIL then79PASS. No whole global/invocation inherited-red/P41 claim.','source_only_tests':'22 source-resource cases intentionally omitted because checkout-derived NAMES is empty in neutral installations. Four exact bytes+native six-owner defaults/custom/missing/unknown/publicPath ABI are actual12 installedcases, noempty-paramSKIP.'}
(base/'native-census.json').write_text(json.dumps(summary,indent=2)+'\n');print(json.dumps({'source_sha':config['source_sha'],'profiles':{k:{f:r[f] for f in ('actual_cases','outcomes','graph_b5_counts','graph_current_counts','literal_warning_counts','origin_count')} for k,r in out.items()},'outcome':'PASS','expected_negative_FAIL':6}))
