from __future__ import annotations

import fnmatch
import json
import subprocess
import tomllib
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[2]
WORKSPACE_ROOT = REPO_ROOT.parent


def test_phase4_generated_artifact_registry_covers_non_python_surfaces() -> None:
    families = _families_by_id()

    required = {
        "runtime-openapi-snapshot",
        "runtime-api-client",
        "runtime-dashboard-api-types",
        "release-sbom",
        "frontend-workspace-lockfiles",
        "frontend-local-generated-outputs",
        "committed-data-fixtures-and-catalogs",
        "local-medallion-data-lake",
        "local-runtime-state",
        "ops-observability-baselines",
        "ops-security-release-baselines",
        "ops-runtime-and-migration-baselines",
    }
    assert required <= set(families)

    for family_id in required:
        family = families[family_id]
        assert family["owner"], family_id
        assert family["approval_owner"], family_id
        assert family["source_of_truth"], family_id
        assert family["outputs"], family_id
        assert family["regenerate_commands"], family_id
        assert family["freshness_rule"], family_id
        assert family["commit_policy"] in {"committed", "mixed", "local_ignored"}
        assert family["drift_gate"] in {"automated", "manual_review", "ignored_by_policy"}
        assert _contract_path_exists(family["workflow"]), family_id

    for family in families.values():
        if family["commit_policy"] != "committed":
            continue
        missing = [output for output in family["outputs"] if not _contract_path_exists(output)]
        assert missing == []

    assert (
        (REPO_ROOT / "frontend/runtime-api-client/runtimeApiClient.ts")
        .read_text(encoding="utf-8")
        .startswith("// GENERATED FILE. DO NOT EDIT.")
    )
    assert (
        (REPO_ROOT / "frontend/runtime-api-client/runtimeApiClient.js")
        .read_text(encoding="utf-8")
        .startswith("// GENERATED FILE. DO NOT EDIT.")
    )
    assert "auto-generated by openapi-typescript" in (
        REPO_ROOT / "frontend/runtime-dashboard/src/api/types.ts"
    ).read_text(encoding="utf-8")


def test_phase4_frontend_workspace_contract_has_owners_commands_and_ignores() -> None:
    contract = _read_toml("architecture/frontend_workspaces.toml")
    workspaces = {workspace["id"]: workspace for workspace in contract["workspace"]}

    assert set(workspaces) == {
        "cli",
        "runtime-api-client",
        "runtime-dashboard",
        "runtime-reference-shell",
    }

    for workspace in workspaces.values():
        root = REPO_ROOT / workspace["path"]
        package_json = _contract_path(workspace["package_json"])
        lockfile = _contract_path(workspace["lockfile"])
        scripts = json.loads(package_json.read_text(encoding="utf-8"))["scripts"]

        assert root.exists()
        assert workspace["owner"]
        assert package_json.exists()
        assert lockfile.exists()
        assert workspace["public_entrypoints"]

        for command in (
            workspace["build_commands"] + workspace["test_commands"] + workspace["drift_commands"]
        ):
            script = _npm_script_name(command)
            if script is not None:
                assert script in scripts, (workspace["id"], command)

        for output in workspace["generated_outputs"]:
            assert (root / output).exists(), (workspace["id"], output)

        for output in workspace["ignored_outputs"]:
            sample = _ignored_output_sample(root, output)
            assert _git_ignores(sample), sample


def test_phase4_data_policy_keeps_local_lake_ignored_and_product_data_allowlisted() -> None:
    policy = _read_toml("architecture/data_policy.toml")

    assert policy["data_policy"]["local_data_lake"] == "data/policy-engine-local"
    assert policy["data_policy"]["product_commit_policy"] == "allowlist_only"
    assert policy["data_policy"]["cleanup_commands"]
    assert _git_ignores(REPO_ROOT / "data" / "bronze" / "phase4.tmp")

    for zone in policy["medallion_zone"]:
        assert zone["state"] == "ignored_local"
        assert zone["cleanup_command"]
        assert _git_ignores(_contract_path(zone["path"]) / "phase4.tmp")

    committed_patterns: list[str] = ["data/README.md"]
    for item in policy["product_data_class"]:
        if item["commit_policy"].startswith("committed"):
            committed_patterns.extend(item["allowed_patterns"])
        else:
            for local_path in item["paths"]:
                assert _git_ignores(REPO_ROOT / local_path / "phase4.tmp")

    tracked_data = subprocess.run(
        ["git", "ls-files", "policy-engine/data"],
        cwd=WORKSPACE_ROOT,
        check=True,
        capture_output=True,
        text=True,
    ).stdout.splitlines()
    max_bytes = int(policy["data_policy"]["max_committed_example_bytes"])

    for tracked in tracked_data:
        relative = Path(tracked).relative_to("policy-engine").as_posix()
        assert any(fnmatch.fnmatch(relative, pattern) for pattern in committed_patterns), relative
        path = WORKSPACE_ROOT / tracked
        assert path.stat().st_size <= max_bytes, relative


def test_phase4_local_runtime_state_is_ignored_retention_classed_and_cleanable() -> None:
    contract = _read_toml("architecture/local_runtime_state.toml")
    state = contract["local_runtime_state"]

    assert state["cleanup_commands"]
    assert _git_ignores(REPO_ROOT / ".polisyos" / "runs" / "phase4.lock")

    state_classes = {item["id"]: item for item in contract["state_class"]}
    assert {"runs", "reports", "artifact_cache", "provider_verification"} <= set(state_classes)

    for item in state_classes.values():
        assert item["owner"]
        assert item["retention_class"]
        assert int(item["default_retention_days"]) > 0
        assert item["cleanup_command"]
        for path in item["paths"]:
            assert _git_ignores(_contract_path(path) / "phase4.tmp")


def test_phase4_ops_baselines_cover_security_observability_release_runtime_migrations() -> None:
    contract = _read_toml("architecture/ops_baselines.toml")
    baselines = {item["id"]: item for item in contract["baseline"]}

    assert {
        "secrets",
        "osv",
        "sbom",
        "otel",
        "slo",
        "release_fragments",
        "commit_policy",
        "runtime",
        "migrations",
    } <= set(baselines)

    for baseline in baselines.values():
        assert baseline["owner"]
        assert baseline["mode"] == "fail_closed"
        assert baseline["baseline_command"]
        for path in baseline["paths"]:
            assert _baseline_path_exists(path), (baseline["id"], path)

    assert "pnpm-lock.yaml" in (REPO_ROOT / "ops/security/osv-scanner.toml").read_text(
        encoding="utf-8"
    )
    assert "pnpm-lock.yaml" in (REPO_ROOT / "ops/security/sbom.toml").read_text(encoding="utf-8")
    assert "service.name" in (REPO_ROOT / "ops/observability/otel/baseline.yaml").read_text(
        encoding="utf-8"
    )
    assert tomllib.loads(
        (REPO_ROOT / "ops/release/release-fragment-policy.toml").read_text(encoding="utf-8")
    )["release_fragments"]["required_fields"]
    assert tomllib.loads(
        (REPO_ROOT / "ops/runtime/runtime-contracts.toml").read_text(encoding="utf-8")
    )["runtime_contracts"]["telemetry_baselines"]
    migration_contracts = tomllib.loads(
        (REPO_ROOT / "ops/migrations/migration-contracts.toml").read_text(encoding="utf-8")
    )["migration_contracts"]
    assert migration_contracts["forward_sequence"] == [
        "001_tenant_columns.sql",
        "002_tenant_backfill.sql",
        "003_rls_enable.sql",
        "004_roles_grants.sql",
    ]
    assert migration_contracts["rollback_sequence"] == ["003_rls_disable_rollback.sql"]


def test_phase4_plan_and_reference_docs_link_the_contracts() -> None:
    evidence = (
        REPO_ROOT / "docs/plans/accepted/REPOSITORY_SOTA_PHASE_4_GENERATED_FRONTEND_DATA_OPS.md"
    )
    plan = (REPO_ROOT / "docs/plans/accepted/REPOSITORY_SOTA_PLAN.md").read_text(encoding="utf-8")

    assert evidence.exists()
    assert "REPOSITORY_SOTA_PHASE_4_GENERATED_FRONTEND_DATA_OPS.md" in plan

    for path in (
        "docs/reference/frontend/workspace-contract.md",
        "docs/reference/data-lake-policy.md",
        "docs/reference/local-runtime-state.md",
        "docs/reference/operations/ops-baselines.md",
    ):
        text = (REPO_ROOT / path).read_text(encoding="utf-8")
        assert "Source of truth:" in text


def _read_toml(path: str) -> dict[str, Any]:
    return tomllib.loads((REPO_ROOT / path).read_text(encoding="utf-8"))


def _families_by_id() -> dict[str, dict[str, Any]]:
    data = _read_toml("architecture/generated_artifacts.toml")
    return {family["id"]: family for family in data["family"]}


def _contract_path(path: str) -> Path:
    candidate = Path(path)
    if candidate.is_absolute():
        return candidate
    return (REPO_ROOT / candidate).resolve()


def _contract_path_exists(path: str) -> bool:
    return _contract_path(path).exists()


def _baseline_path_exists(path: str) -> bool:
    resolved = _contract_path(path)
    if any(char in path for char in "*?["):
        return bool(list(resolved.parent.glob(resolved.name)))
    return resolved.exists()


def _npm_script_name(command: str) -> str | None:
    if command == "npm test":
        return "test"
    if command.startswith("npm run "):
        return command.removeprefix("npm run ").split()[0]
    return None


def _ignored_output_sample(root: Path, output: str) -> Path:
    if output.endswith("/"):
        return root / output / "phase4.tmp"
    return root / output


def _git_ignores(path: Path) -> bool:
    result = subprocess.run(
        ["git", "check-ignore", "-q", path.resolve().relative_to(WORKSPACE_ROOT).as_posix()],
        cwd=WORKSPACE_ROOT,
        check=False,
    )
    return result.returncode == 0
