from pathlib import Path
import subprocess,json,hashlib,gzip,re,csv,io
R=Path('/workspace/e02-F-graph-20261006');D=Path('/tmp/e02-F-continuation-20261007/graph/root519-G855-review');A='79895c6758307a56b1613a8d1c19daa3f0d92c25';S='519e4822f608cbe4e7ac1ee7b01f6c29cb84bc82';G='855cb26a7a2c9fea60356663cf81e7d01e20c738';O='ffae9fa4b45c23c3d2dca5c1bbf78d18418a7634';B='363e7ae0cb2929a92d9667334fdc0ac3087daf5e';P='policy-engine/'
def git(*args):return subprocess.check_output(['git',*args],cwd=R)
def data(s,p):return git('show',s+':'+p)
def binding(s,p):
 b=data(s,p);return {'git_ref':s,'path':p,'bytes':len(b),'sha256':hashlib.sha256(b).hexdigest(),'git_blob':git('rev-parse',s+':'+p).decode().strip()}
def tree(s):
 rows={}
 for line in git('ls-tree','-r','-z',s).split(b'\0'):
  if line:
   m,p=line.split(b'\t');rows[p.decode()]=m.decode().split()[2]
 return rows
before={'head':git('rev-parse','HEAD').decode().strip(),'tree':git('rev-parse','HEAD^{tree}').decode().strip(),'branch':git('symbolic-ref','--short','HEAD').decode().strip(),'status':git('status','--porcelain=v1').decode()}
T={s:tree(s) for s in [A,S,G,O,B]};report={'schema':'policyos.e02.independent.readonly_composition_review.v1','reviewer':'F graph_scm; source author of graph/resource slices, reviewing assembly/input identity only, not replacing original independent semantic reviews','check':'UNRUN','verdict':'pending','source519':S,'source519_tree':git('rev-parse',S+'^{tree}').decode().strip(),'candidate':A,'candidate_tree':git('rev-parse',A+'^{tree}').decode().strip(),'candidate_parents':git('show','-s','--format=%P',A).decode().split(),'G_checkpoint':G,'G_tree':git('rev-parse',G+'^{tree}').decode().strip(),'own_published_carrier':O,'own_before':before}
source_prefixes=[P+x for x in ['src/','tools/','workers/','architecture/','schemas/','data/']]+['.github/'];singletons={P+x for x in ['hatch.toml','pyproject.toml','uv.lock','.python-version']}
def mechanism(p):return (p in singletons or any(p.startswith(x) for x in source_prefixes)) and not p.endswith('.md')
allpaths=sorted(set(T[S])|set(T[A]));runtime=[p for p in allpaths if mechanism(p)];tests=[p for p in allpaths if p.startswith(P+'tests/')];unions=sorted(set(runtime)|set(tests))
report['runtime_test_build_schema_union']={'selection':source_prefixes+sorted(singletons)+[P+'tests/**'],'documentation_md_excluded_from_runtime_only':True,'path_denominator':len(unions),'runtime_build_schema_path_denominator':len(runtime),'test_path_denominator':len(tests),'changed_paths':[p for p in unions if T[S].get(p)!=T[A].get(p)],'bindings':[{'path':p,'source519_blob':T[S].get(p),'candidate_blob':T[A].get(p),'unchanged':T[S].get(p)==T[A].get(p)} for p in unions]}
changes=report['runtime_test_build_schema_union']['changed_paths'];req=P+'tests/unit/remediation/test_req_01_installed.py';report['runtime_identity_check']='PASS' if not any(p for p in changes if p!=req) else 'FAIL';report['new_nonF_test']={'path':req,'G':binding(G,req),'candidate':binding(A,req),'byte_identical_G':data(G,req)==data(A,req),'owner':'A/REQ-01','scope':'new installed compiler test; not executed in this review; no modification of graph selectors or shared conftest'}
gchanged=[p for p in sorted(set(T[B])|set(T[G])) if T[B].get(p)!=T[G].get(p)];exceptions={P+'docs/research/e02-cloud-test-plan/closure-decisions/F.md',P+'docs/research/e02-cloud-test-plan/closure-decisions/method-decisions.md'}
report['G_retention']={'full_changed_path_denominator':len(gchanged),'intentional_F_conflict_paths':sorted(exceptions),'current_G_nonconflict_bindings':[{'path':p,'G_blob':T[G].get(p),'candidate_blob':T[A].get(p),'identical':T[G].get(p)==T[A].get(p)} for p in gchanged if p not in exceptions]}
report['G_retention']['check']='PASS' if all(x['identical'] for x in report['G_retention']['current_G_nonconflict_bindings']) else 'FAIL'
report['ledger_resolution']={}
for n in ['F.md','method-decisions.md']:
 path=P+'docs/research/e02-cloud-test-plan/closure-decisions/'+n;b=data(A,path);proposal=(D/('proposed-'+n)).read_bytes();row={'actual':binding(A,path),'matches_exact_reviewed_proposal':b==proposal,'markers_present':any(x in b for x in [b'<<<<<<< ',b'=======\n',b'>>>>>>> '])}
 if n=='method-decisions.md':
  anchor=b'<a id="methods-f"></a>';ca=b'<a id="methods-c"></a>';g=data(G,path);s=data(S,path);row['all_G_C_D_E_bytes_preserved']=b[b.index(ca):b.index(anchor)]==g[g.index(ca):g.index(anchor)];row['all_ROOT_F_method_bytes_preserved']=b[b.index(anchor):]==s[s.index(anchor):];row['G_B109_B111_B100_notice_preserved']=g.split(b'\n\n',1)[0] in b;row['F_anchors']=re.findall(r'<a id="f-m(\d+)"></a>',b.decode())
 else:
  rows=[line for line in b.decode().splitlines() if re.match(r'^\| (?:B\d+|LA-\d+) \|',line)];ids=[line.split('|')[1].strip() for line in rows];owners=list(csv.DictReader(io.StringIO(data('198076863e143dea9f89f02734b13d50dae3eed5',P+'docs/research/e02-cloud-test-plan/execution-organization/finding-owners.tsv').decode()),delimiter='\t'));expected={x['finding_id'] for x in owners if x['unit']=='F'};row['finding_rows']=len(ids);row['distinct_IDs']=len(set(ids));row['exact_current_ID_denominator']=set(ids)==expected;row['recommendation_counts']={'closed':sum('; closed |' in x for x in rows),'limited':sum('; limited |' in x for x in rows)};row['limited_IDs']=[x.split('|')[1].strip() for x in rows if '; limited |' in x];row['semantic_scope']='F recommendations on original cards; G formal acceptance not granted; B214 bounded partial capability and B56 admitted competing-study inputs remain limited'
 report['ledger_resolution'][n]=row
report['components']=[]
for name in ['graph-intake-current-content-20261007','catalog-default-resources-20261007']:
 rp=P+'docs/research/e02-cloud-test-plan/implementation-handoffs/F/'+name+'.json';receipt=json.loads(data(O,rp));mf=receipt['evidence_transfer']['full_output_manifest'];material=json.loads(data(O,mf['path']))['files'];models=receipt['changed_paths'][:]
 if name.startswith('catalog'):models.extend(P+'data/dataset_catalog/'+x for x in ['seed_variable_alignments.yaml','proxy_metric_alignments.yaml','wvs_indicator_registry.yaml','metrics_map.yaml'])
 record={'name':name,'primary':binding(A,rp),'primary_byte_identical_published':data(A,rp)==data(O,rp),'manifest':binding(A,mf['path']),'manifest_byte_identical_published':data(A,mf['path'])==data(O,mf['path']),'source':receipt['candidate_sha'],'source_tree':receipt['candidate_tree_sha'],'source_inputs':[],'material':[]}
 for p in models:record['source_inputs'].append({'path':p,'original_source':binding(receipt['candidate_sha'],p),'candidate':binding(A,p),'byte_identical':data(receipt['candidate_sha'],p)==data(A,p)})
 for item in material:
  p=item['path'];b=data(A,p);x={'path':p,'stored_bytes':len(b),'stored_sha256':hashlib.sha256(b).hexdigest(),'stored_matches_manifest':len(b)==item['bytes'] and hashlib.sha256(b).hexdigest()==item['sha256'],'matches_published_bytes':b==data(O,p)}
  if p.endswith('.gz'):
   raw=gzip.decompress(b);x.update({'decoded_bytes':len(raw),'decoded_sha256':hashlib.sha256(raw).hexdigest(),'decoded_matches_manifest':len(raw)==item['decoded_bytes'] and hashlib.sha256(raw).hexdigest()==item['decoded_sha256']})
  record['material'].append(x)
 record['check']='PASS' if record['primary_byte_identical_published'] and record['manifest_byte_identical_published'] and all(x['byte_identical'] for x in record['source_inputs']) and all(x['stored_matches_manifest'] and x['matches_published_bytes'] and x.get('decoded_matches_manifest',True) for x in record['material']) else 'FAIL';report['components'].append(record)
report['ancestry']=[{'ancestor':x,'descendant':A,'established':subprocess.run(['git','merge-base','--is-ancestor',x,A],cwd=R).returncode==0} for x in [S,G,O,'647f5d35362c2a5d7ad32283b804a5b03ea56e83','81f482e04bd8a2c85f894d425847c6e8657b6ea6']]
report['semantic_properties_retained_by_source_identity']={'graph_current_content':'original actual CAS selected ref/manifest/schema/current content re-resolution and full recomputation before shortcuts unchanged','composition_basis':'full current composition certificate/source/alignment/mapping projection unchanged; semantic fields compared while query operational cache recomputed','direction_and_endpoint':'known reverse canonicalization and bidirected handling unchanged; unresolved circle/tail-tail/compact lag static refusal unchanged','curated_default_resources':'finite four original YAML/durable Path/source anchor/installed package projection and explicit override/fallback laws unchanged','scope':'finite static resolved ADMG and unpacked installed/source resource profiles; no universal PAG/CPDAG completion, temporal inference, ID completeness, production inference or authority'}
quality=Path('/tmp/e02-F-continuation-20261007/root-recovery');refs=[]
for n in ['merge-latest-G.json','merge-latest-G.stdout','merge-latest-G.stderr','merge-latest-G-full.patch','merge-latest-G-diff-check.stdout','merge-latest-G-diff-check.stderr','merge-authored-docs-diff-check.stdout','merge-authored-docs-diff-check.stderr']:
 p=quality/n;b=p.read_bytes();refs.append({'path':str(p),'bytes':len(b),'sha256':hashlib.sha256(b).hexdigest()})
rawpath=P+'docs/research/e02-cloud-test-plan/integration/checks/2026-10-07-tenth-wave/C-canon/results/attempt2/stdout.txt';report['root_quality_evidence']={'full_merge_diff_check':'FAIL','reason':'two raw artifact stdout trailing whitespace lines; retained verbatim','raw_stdout_G':binding(G,rawpath),'raw_stdout_candidate':binding(A,rawpath),'raw_stdout_byte_identical_G':data(G,rawpath)==data(A,rawpath),'authored_doc_diff_check':'PASS','P41':'not_established; no exact pre-slice/full disjoint proof','complete_companions':refs}
report['not_run']=['79 graph/native defining selectors','41 resources/native packaging selectors','independent finite graph/SCM/numerical oracles','91/199 historical installed positive waves','full architecture/docs/production invocation scanners','G formal finding acceptance']
report['narrow_check_queue']=[{'owner':'ROOT/G publisher','trigger':'now after ordinary merge','check':'frozen source/tree/parents + all current source/input/material hash custody and final35 criterion/ref consistency; retain old519 and published slice outcomes without changing tested SHA','scientific_rerun_required':False},{'owner':'API canonical inventory/census','trigger':'tracked tree denominator changed by G docs/evidence and one REQ test','check':'refresh source/config/FQN/loader census metadata if required; compare maintained renderer complete source-read/is_file closure against changed paths before deciding generated freshness; no inferred static completeness','scientific_rerun_required':False},{'owner':'A/REQ-01 or G','trigger':'new G-installed compiler test admitted into chosen suite','check':req+' (installed build test) only if that A consumer needs new execution; preserve own G source-specific receipts','scientific_rerun_required':False},{'owner':'ROOT quality owner','trigger':'one composed final diagnostic requested by parent','check':'actual full invocation/architecture/quality command on frozen input with complete output; do not turn prior ERROR/FAIL into PASS or claim P41','scientific_rerun_required':False},{'owner':'graph_scm/independent API reviewer','trigger':'ONLY if later source/schema/resource/Hatch/shared-fixture delta affects corresponding owner','check':'affected exact registered method/node→CAS→fresh-reader or required four-resource packaging selector plus retained-marker removal; no blanket79/41 repetition for evidence/doc publication','scientific_rerun_required':False}]
after={'head':git('rev-parse','HEAD').decode().strip(),'tree':git('rev-parse','HEAD^{tree}').decode().strip(),'branch':git('symbolic-ref','--short','HEAD').decode().strip(),'status':git('status','--porcelain=v1').decode()};report['own_after']=after;report['own_pair_unchanged']=before==after
ok=report['runtime_identity_check']=='PASS' and report['new_nonF_test']['byte_identical_G'] and report['G_retention']['check']=='PASS' and all(x['matches_exact_reviewed_proposal'] and not x['markers_present'] for x in report['ledger_resolution'].values()) and all(x['check']=='PASS' for x in report['components']) and report['own_pair_unchanged']
report['check']='PASS' if ok else 'FAIL';report['verdict']='GO_BOUNDED assembly/input-custody and original-scope ledger resolution' if ok else 'BLOCK actual assembly/input difference';report['scientific_authority']='not granted; source identity retains original bounded receipts only'
(D/'actual798-review.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n');print(json.dumps({'check':report['check'],'verdict':report['verdict'],'runtime_test_build_schema_union':{k:v for k,v in report['runtime_test_build_schema_union'].items() if k!='bindings'},'runtime_identity_check':report['runtime_identity_check'],'G_nonconflict_retention':report['G_retention']['check'],'G_nonconflict_paths':len(report['G_retention']['current_G_nonconflict_bindings']),'components':[{'name':x['name'],'source_inputs':len(x['source_inputs']),'material':len(x['material']),'gzip':sum('decoded_bytes' in z for z in x['material']),'check':x['check']} for x in report['components']],'ledger_resolution':report['ledger_resolution'],'own_pair_unchanged':report['own_pair_unchanged']},ensure_ascii=False,indent=2))
