from pathlib import Path
import json,hashlib,gzip
D=Path('/tmp/e02-F-continuation-20261007/graph/root519-G855-review');d=json.loads((D/'actual798-review.json').read_text());q=Path('/tmp/e02-F-continuation-20261007/root-recovery')
text='''Read-only assembly review: GO_BOUNDED exact79895c6758307a56b1613a8d1c19daa3f0d92c25/tree5bfbc2720c92fccb63ab2f288971b182cd09073b.

The full runtime/test/build/schema union is7450 Git paths:4122 runtime/build/schema and3328 tests. The sole changed union path from recovered519 is the new A/REQ-01 installed test, byte-identical to G855. The broader src-prefix change is a search README only. Graph647's seven inputs and resource81's fourteen owner companions plus four original YAML remain byte-identical. Both published primary/manifests and all396 companion files, including124 decoded gzip payloads, match the committed798 tree. This is input identity/custody review, not a new scientific execution.

Virtual519/G855 merge returned two ledger-document conflicts. Actual798 resolves both exactly as reviewed: F.md retains original-card current recommendations33closed/2limited(B214/B56); method-decisions keeps all sixteen current F anchors, the entire73820-byte current G C-D-E block, and the current B109/B111/B100 criterion notice. All372 nonconflict changed G paths are retained exactly. LA035 requires equivalent historical score relocation, not a new optimizer/normative packet; LA004 remains distinct-model comparison, not Gini. B214 still has the sound partial/conditional extension residual; B218 representation/export/static refusal remains separate. G formal acceptance is not granted.

Historical519 lacked all173 resource companions plus primary/manifest: that custody FAIL and initial strict-reader ERROR remain preserved. Current798 contains those exact publishedffae bytes after ordinary evidence merge. The full merge diff-check remains FAIL on two unchanged raw C-canon stdout whitespace lines; authored-doc diff-check PASS is separate. P41 remains not_established.

No79/41, finite graph/SCM/DGP,91/199 installed oracles were rerun for publication. Future checks are metadata/source-custody and source-derived inventory/census freshness first. Only an actual later owner-source/schema/resource/Hatch/shared-fixture change triggers its affected consumer/removal selectors. This review does not replace original independent scientific reviews, does not establish universal PAG/CPDAG/temporal/ID support, and makes no authority/production conclusion. Own admitted branch/path/head/index/worktree stayed unchanged.
'''
(D/'REVIEW.txt').write_text(text)
files=[]
# All complete observer reports, errors, scripts, actual source-card byte bindings and deciding moderate outputs.
names=['merge-tree.json','merge-tree.stdout.txt','merge-tree.stderr.txt','compare_inputs.py','source-input-comparison.stdout.txt','source-input-comparison.stderr.txt','compare_inputs_v2.py','source-input-comparison-v2.json','source-input-comparison-v2.stdout.txt','source-input-comparison-v2.stderr.txt','finalize_comparison.py','source-input-comparison-final.json','source-input-comparison-final.stdout.txt','source-input-comparison-final.stderr.txt','prepare_resolution.py','ledger-resolution-proposal.json','ledger-resolution-proposal.stdout.txt','ledger-resolution-proposal.stderr.txt','F.md.root-to-proposal.patch','method-decisions.md.root-to-proposal.patch','original-card-bindings.json','B214-original-card.md','B218-original-card.md','LA-004-original-card.md','LA-035-original-card.md','G-delta.txt','root-vs-own.txt','actual798-vs519-name-status.txt','review_actual_merge.py','actual798-review.json','actual798-review.stdout.txt','actual798-review.stderr.txt','REVIEW.txt','write_selection.py']
paths=[D/x for x in names]+[q/x for x in ['merge-latest-G.json','merge-latest-G.stdout','merge-latest-G.stderr','merge-latest-G-full.patch','merge-latest-G-diff-check.stdout','merge-latest-G-diff-check.stderr','merge-authored-docs-diff-check.stdout','merge-authored-docs-diff-check.stderr']]
for p in paths:
 b=p.read_bytes();row={'path':str(p),'bytes':len(b),'sha256':hashlib.sha256(b).hexdigest(),'encoding':'identity'}
 if len(b)>65536:
  target=D/(p.name+'.lossless.gz');encoded=gzip.compress(b,mtime=0);target.write_bytes(encoded);row={'path':str(target),'bytes':len(encoded),'sha256':hashlib.sha256(encoded).hexdigest(),'encoding':'gzip','decoded_bytes':len(b),'decoded_sha256':hashlib.sha256(b).hexdigest(),'original_raw_path':str(p),'transport_reason':'complete moderate/large deciding metadata or source-diff output; original unchanged; single lossless compressed copy for Git transfer'}
 files.append(row)
selection={'schema':'policyos.e02.complete_transfer_selection.v1','reviewer':'graph_scm','source_sha':d['candidate'],'source_tree':d['candidate_tree'],'scope':'independent assembly/source-input/custody review; not author-as-independent scientific review','check':'PASS','selection_is_complete':True,'item_count':len(files),'stored_bytes':sum(x['bytes'] for x in files),'decoded_bytes':sum(x.get('decoded_bytes',x['bytes']) for x in files),'files':files,'already_Git_source_inputs_not_duplicated':['519e4822 andG855 and798 complete Git source trees; actual two ledger docs and publishedffae primaries/material bound by review JSON','both proposed docs equal actual798; hashes retained in ledger proposal; no extra uncompressed source-body transport'],'preserved_nonPASS':['initial strict comparison readerERROR at missing519 resource companion','historical519 root-local resource custodyFAIL','v2 documentation-inclusive comparison metadata qualification','actual full merge raw stdout whitespaceFAIL/P41not_established'],'numerical_runs':'none'}
(D/'transfer-selection.json').write_text(json.dumps(selection,ensure_ascii=False,indent=2)+'\n')
print(json.dumps({'check':'PASS','review':{'path':str(D/'actual798-review.json'),'bytes':(D/'actual798-review.json').stat().st_size,'sha256':hashlib.sha256((D/'actual798-review.json').read_bytes()).hexdigest()},'items':len(files),'stored_bytes':selection['stored_bytes'],'decoded_bytes':selection['decoded_bytes'],'selection':str(D/'transfer-selection.json')},indent=2))
