from __future__ import annotations

from polisyos.core.contracts.lex import ChangeProposalRef, LegalEvaluationRequest, LegalReportRef

from .api import (
    assemble_norm_pack,
    build_legal_structure,
    build_version_index,
    evaluate_legality,
    ingest_legal_doc_bytes,
    propose_changes,
    resolve_active_version,
)
from .errors import (
    LexError,
    LexIndexError,
    LexIngestError,
    LexNotReadyError,
    LexStructureError,
    LexValidationError,
    LexVersioningError,
)
from .types import (
    ActiveVersionResult,
    ActiveVersionStrategy,
    LegalDocSource,
    LexIngestOptions,
    LexIngestResult,
    LexStructureOptions,
    LexStructureResult,
    LexVersionIndexOptions,
    LexVersionIndexResult,
    NormPackBudgets,
    NormPackBuildRequest,
    NormPackBuildResult,
    WorldEventRefLike,
)
from .simulator import (
    AffectedKPI,
    ComplianceDelta,
    ComplianceTransition,
    MutationIntent,
    NormChange,
    NormChangeType,
    NormDiff,
    NormImpactAnalyzer,
    NormImpactReport,
    NormPackMutator,
    diff_norm_packs,
)

__all__ = [
    "ActiveVersionResult",
    "ActiveVersionStrategy",
    "ChangeProposalRef",
    "LegalDocSource",
    "LegalEvaluationRequest",
    "LegalReportRef",
    "LexError",
    "LexIndexError",
    "LexIngestError",
    "LexIngestOptions",
    "LexIngestResult",
    "LexNotReadyError",
    "LexStructureError",
    "LexStructureOptions",
    "LexStructureResult",
    "LexValidationError",
    "LexVersionIndexOptions",
    "LexVersionIndexResult",
    "LexVersioningError",
    "NormPackBuildRequest",
    "NormPackBuildResult",
    "NormPackBudgets",
    "MutationIntent",
    "NormPackMutator",
    "NormChangeType",
    "NormChange",
    "NormDiff",
    "NormImpactAnalyzer",
    "NormImpactReport",
    "ComplianceTransition",
    "ComplianceDelta",
    "AffectedKPI",
    "diff_norm_packs",
    "WorldEventRefLike",
    "assemble_norm_pack",
    "build_legal_structure",
    "build_version_index",
    "evaluate_legality",
    "ingest_legal_doc_bytes",
    "propose_changes",
    "resolve_active_version",
]
