"""Expose the stable IR contract surface through a lazy package facade.

The root package is the compatibility boundary for schema-first contracts,
status enums, artifact refs, and bundle manifests shared between policy
authoring, Scientist runners, and Foundry methods. Names listed in ``__all__``
are resolved lazily so importing :mod:`polisyos.ir` does not eagerly pull
runtime-heavy submodules or trigger execution-side dependencies.

Treat ``__all__`` as the stable public API; helpers that are not re-exported
here remain internal to their submodules.
"""
from __future__ import annotations

import importlib
from typing import Any

__all__ = [
    "AccessTier",
    "ConnectorCapability",
    "ConnectorMetadataSpec",
    "DataFilter",
    "DataViewRequest",
    "DataViewType",
    "QualityTier",
    "TrustLevel",
    "NormPack",
    "NormRule",
    "NormRef",
    "RuleType",
    "load_policy",
    "CalibrationConfig",
    "CalibrationTarget",
    "ProblemFrame",
    "ProblemDomain",
    "KPISpec",
    "SuccessCriterion",
    "ProblemConstraintSpec",
    "ConstraintType",
    "StakeholderSpec",
    "PolicySpec",
    "PolicyInterventionSpec",
    "MechanismBinding",
    "ParameterSpec",
    "PolicyPortfolio",
    "PolicyInteraction",
    "InteractionMatrix",
    "InteractionType",
    "ModelSpec",
    "FidelityLevel",
    "GovernancePassAlias",
    "GovernancePassAliasRegistry",
    "GovernancePassAliasStatus",
    "GovernancePassMappingRegistry",
    "GovernancePassMappingBundle",
    "AssumptionSpec",
    "AssumptionType",
    "AgentConfig",
    "AgentTypeConfig",
    "EnvironmentConfig",
    "EnvironmentParam",
    "GateContext",
    "GateDecision",
    "GateEvent",
    "GateEventType",
    "GatePriority",
    "GateRequest",
    "GateVerdict",
    "DistributionFamily",
    "IntervalSemantics",
    "PropagationMethod",
    "UncertaintyEnvelope",
    "UncertaintySource",
    "CausalMethod",
    "EstimationStatus",
    "RefutationTestType",
    "RefutationResult",
    "CausalEffectReport",
    "QueryType",
    "InterventionType",
    "InterventionSpec",
    "CausalInterventionSpec",
    "CausalQuery",
    "CausalQueryResult",
    "CausalQueryResultRef",
    "CausalExecutionBundleRef",
    "EnsembleMember",
    "CausalModelEnsemble",
    "CausalModelEnsembleRef",
    "TransportabilityResult",
    "TransportabilityResultRef",
    "CausalDiscoveryReport",
    "DiagnosticTest",
    "MechanismFamily",
    "MechanismSource",
    "NodeMechanism",
    "StructuralCausalModelSpec",
    "PlaceboResult",
    "CohortDimension",
    "ImpactDirection",
    "MetricUnit",
    "CohortImpact",
    "DimensionBreakdown",
    "WinnersLosersEntry",
    "WinnersLosersTable",
    "DistributionalReport",
    "SubgroupEffect",
    "FeatureImportance",
    "HTEResult",
    "TargetingRule",
    "PolicyRecommendation",
    "BiasDirection",
    "OutcomeComparison",
    "SystematicBias",
    "BacktestScenario",
    "BacktestReport",
    "BacktestPlanBundle",
    "BoundsEstimationBundle",
    "CalibrationTargetBundleManifest",
    "CalibrationSplitLabel",
    "CalibrationSplitPlan",
    "CalibrationSplitWindow",
    "CausalPanelBundleManifest",
    "DTRTreatmentSequenceBundleManifest",
    "EntityScope",
    "IdentificationMode",
    "LessonRegistrySeedBundle",
    "LeontiefIOBundle",
    "MicrosimSurveyContractBundle",
    "MultiplexGraphLayerId",
    "NetworkCausalContractBundle",
    "NetworkContractBundle",
    "ObservationFamily",
    "ObservationFamilyPolicy",
    "ObservationFamilyPolicyRegistry",
    "IdentificationModeRouter",
    "IdentificationRoute",
    "MeasurementRegistry",
    "MeasurementTrustTier",
    "NegativeControlSpec",
    "ObservationPanel",
    "ObservationRecord",
    "ObservationToContractManifest",
    "BoundsEstimationInput",
    "FirmEvents",
    "FirmPanels",
    "GraphArtifacts",
    "LeontiefIOInput",
    "ObservationContractCompilerSuite",
    "PanelEconometricBundleManifest",
    "ProxyMap",
    "ProxyIdentificationBundle",
    "TransportabilityCheckBundle",
    "CounterfactualCheckBundle",
    "InterferenceLossSpecBundle",
    "CausalReadinessBundle",
    "BoundsEstimationTask",
    "BoundsEstimationEntry",
    "TemporalDTRTask",
    "TemporalDTRExecutionEntry",
    "CausalExecutionBundle",
    "load_causal_execution_bundle",
    "persist_causal_execution_bundle",
    "RegionSectorPanels",
    "SourceConfidenceTier",
    "SpecificationCurveInput",
    "SparseDenseBridge",
    "SpecificationCurveBundle",
    "StrategicResponseChannel",
    "StrategicResponseSpecsBundle",
    "SurvivalDataBundleManifest",
    "RegimeCalendar",
    "SchemaChangepoint",
    "SchemaRegimeRegistry",
    "SchemaRegimeSpec",
    "ShockCalendar",
    "TemporalInterventionSequence",
    "TemporalInterventionStep",
]

_LAZY_IMPORTS: dict[str, tuple[str, str]] = {
    "CalibrationConfig": ("polisyos.ir.analytics.calibration", "CalibrationConfig"),
    "CalibrationTarget": ("polisyos.ir.analytics.calibration", "CalibrationTarget"),
    "ConnectorCapability": ("polisyos.ir.connectors", "ConnectorCapability"),
    "ConnectorMetadataSpec": ("polisyos.ir.connectors", "ConnectorMetadataSpec"),
    "QualityTier": ("polisyos.ir.connectors", "QualityTier"),
    "TrustLevel": ("polisyos.ir.connectors", "TrustLevel"),
    "AccessTier": ("polisyos.ir.analytics.data_views", "AccessTier"),
    "DataFilter": ("polisyos.ir.analytics.data_views", "DataFilter"),
    "DataViewRequest": ("polisyos.ir.analytics.data_views", "DataViewRequest"),
    "DataViewType": ("polisyos.ir.analytics.data_views", "DataViewType"),
    "load_policy": ("polisyos.ir.loaders", "load_policy"),
    "NormPack": ("polisyos.ir.norm_pack", "NormPack"),
    "NormRule": ("polisyos.ir.norm_pack", "NormRule"),
    "NormRef": ("polisyos.ir.norm_pack", "NormRef"),
    "RuleType": ("polisyos.ir.norm_pack", "RuleType"),
    "AgentConfig": ("polisyos.ir.model_spec", "AgentConfig"),
    "AgentTypeConfig": ("polisyos.ir.model_spec", "AgentTypeConfig"),
    "AssumptionSpec": ("polisyos.ir.model_spec", "AssumptionSpec"),
    "AssumptionType": ("polisyos.ir.model_spec", "AssumptionType"),
    "EnvironmentConfig": ("polisyos.ir.model_spec", "EnvironmentConfig"),
    "EnvironmentParam": ("polisyos.ir.model_spec", "EnvironmentParam"),
    "FidelityLevel": ("polisyos.ir.model_spec", "FidelityLevel"),
    "GovernancePassAlias": ("polisyos.ir.observation.governance", "GovernancePassAlias"),
    "GovernancePassAliasRegistry": (
        "polisyos.ir.observation.governance",
        "GovernancePassAliasRegistry",
    ),
    "GovernancePassAliasStatus": (
        "polisyos.ir.observation.governance",
        "GovernancePassAliasStatus",
    ),
    "GovernancePassMappingRegistry": (
        "polisyos.ir.observation.governance",
        "GovernancePassMappingRegistry",
    ),
    "ModelSpec": ("polisyos.ir.model_spec", "ModelSpec"),
    "GateContext": ("polisyos.ir.governance.gate", "GateContext"),
    "GateDecision": ("polisyos.ir.governance.gate", "GateDecision"),
    "GateEvent": ("polisyos.ir.governance.gate", "GateEvent"),
    "GateEventType": ("polisyos.ir.governance.gate", "GateEventType"),
    "GatePriority": ("polisyos.ir.governance.gate", "GatePriority"),
    "GateRequest": ("polisyos.ir.governance.gate", "GateRequest"),
    "GateVerdict": ("polisyos.ir.governance.gate", "GateVerdict"),
    "DistributionFamily": ("polisyos.ir.analytics.uncertainty", "DistributionFamily"),
    "IntervalSemantics": ("polisyos.ir.analytics.uncertainty", "IntervalSemantics"),
    "PropagationMethod": ("polisyos.ir.analytics.uncertainty", "PropagationMethod"),
    "MechanismBinding": ("polisyos.ir.governance.policy_spec", "MechanismBinding"),
    "ParameterSpec": ("polisyos.ir.governance.policy_spec", "ParameterSpec"),
    "PolicyInterventionSpec": ("polisyos.ir.governance.policy_spec", "InterventionSpec"),
    "PolicySpec": ("polisyos.ir.governance.policy_spec", "PolicySpec"),
    "TemporalInterventionSequence": (
        "polisyos.ir.governance.policy_spec",
        "TemporalInterventionSequence",
    ),
    "TemporalInterventionStep": (
        "polisyos.ir.governance.policy_spec",
        "TemporalInterventionStep",
    ),
    "PolicyPortfolio": ("polisyos.ir.portfolio", "PolicyPortfolio"),
    "PolicyInteraction": ("polisyos.ir.portfolio", "PolicyInteraction"),
    "InteractionMatrix": ("polisyos.ir.portfolio", "InteractionMatrix"),
    "InteractionType": ("polisyos.ir.portfolio", "InteractionType"),
    "ConstraintType": ("polisyos.ir.governance.problem_frame", "ConstraintType"),
    "KPISpec": ("polisyos.ir.governance.problem_frame", "KPISpec"),
    "ProblemConstraintSpec": ("polisyos.ir.governance.problem_frame", "ConstraintSpec"),
    "ProblemDomain": ("polisyos.ir.governance.problem_frame", "ProblemDomain"),
    "ProblemFrame": ("polisyos.ir.governance.problem_frame", "ProblemFrame"),
    "StakeholderSpec": ("polisyos.ir.governance.problem_frame", "StakeholderSpec"),
    "SuccessCriterion": ("polisyos.ir.governance.problem_frame", "SuccessCriterion"),
    "UncertaintyEnvelope": ("polisyos.ir.analytics.uncertainty", "UncertaintyEnvelope"),
    "UncertaintySource": ("polisyos.ir.analytics.uncertainty", "UncertaintySource"),
    "CausalMethod": ("polisyos.ir.analytics.causal", "CausalMethod"),
    "EstimationStatus": ("polisyos.ir.analytics.causal", "EstimationStatus"),
    "RefutationTestType": ("polisyos.ir.analytics.causal", "RefutationTestType"),
    "RefutationResult": ("polisyos.ir.analytics.causal", "RefutationResult"),
    "CausalEffectReport": ("polisyos.ir.analytics.causal", "CausalEffectReport"),
    "QueryType": ("polisyos.ir.analytics.causal_queries", "QueryType"),
    "InterventionType": ("polisyos.ir.analytics.causal_queries", "InterventionType"),
    "InterventionSpec": ("polisyos.ir.analytics.causal_queries", "InterventionSpec"),
    "CausalInterventionSpec": (
        "polisyos.ir.analytics.causal_queries",
        "CausalInterventionSpec",
    ),
    "CausalQuery": ("polisyos.ir.analytics.causal_queries", "CausalQuery"),
    "CausalQueryResult": ("polisyos.ir.analytics.causal_queries", "CausalQueryResult"),
    "CausalQueryResultRef": ("polisyos.ir.refs", "CausalQueryResultRef"),
    "CausalExecutionBundleRef": ("polisyos.ir.refs", "CausalExecutionBundleRef"),
    "EnsembleMember": ("polisyos.ir.analytics.causal_ensemble", "EnsembleMember"),
    "CausalModelEnsemble": (
        "polisyos.ir.analytics.causal_ensemble",
        "CausalModelEnsemble",
    ),
    "CausalModelEnsembleRef": ("polisyos.ir.refs", "CausalModelEnsembleRef"),
    "TransportabilityResult": (
        "polisyos.ir.analytics.transportability",
        "TransportabilityResult",
    ),
    "TransportabilityResultRef": (
        "polisyos.ir.refs",
        "TransportabilityResultRef",
    ),
    "CausalDiscoveryReport": (
        "polisyos.ir.analytics.causal_discovery",
        "CausalDiscoveryReport",
    ),
    "MechanismFamily": (
        "polisyos.ir.analytics.structural_causal_model",
        "MechanismFamily",
    ),
    "MechanismSource": (
        "polisyos.ir.analytics.structural_causal_model",
        "MechanismSource",
    ),
    "NodeMechanism": (
        "polisyos.ir.analytics.structural_causal_model",
        "NodeMechanism",
    ),
    "StructuralCausalModelSpec": (
        "polisyos.ir.analytics.structural_causal_model",
        "StructuralCausalModelSpec",
    ),
    "DiagnosticTest": ("polisyos.ir.analytics.causal", "DiagnosticTest"),
    "PlaceboResult": ("polisyos.ir.analytics.causal", "PlaceboResult"),
    "CohortDimension": ("polisyos.ir.analytics.distributional", "CohortDimension"),
    "ImpactDirection": ("polisyos.ir.analytics.distributional", "ImpactDirection"),
    "MetricUnit": ("polisyos.ir.analytics.distributional", "MetricUnit"),
    "CohortImpact": ("polisyos.ir.analytics.distributional", "CohortImpact"),
    "DimensionBreakdown": ("polisyos.ir.analytics.distributional", "DimensionBreakdown"),
    "WinnersLosersEntry": ("polisyos.ir.analytics.distributional", "WinnersLosersEntry"),
    "WinnersLosersTable": ("polisyos.ir.analytics.distributional", "WinnersLosersTable"),
    "DistributionalReport": ("polisyos.ir.analytics.distributional", "DistributionalReport"),
    "SubgroupEffect": ("polisyos.ir.analytics.hte", "SubgroupEffect"),
    "FeatureImportance": ("polisyos.ir.analytics.hte", "FeatureImportance"),
    "HTEResult": ("polisyos.ir.analytics.hte", "HTEResult"),
    "TargetingRule": ("polisyos.ir.analytics.hte", "TargetingRule"),
    "PolicyRecommendation": ("polisyos.ir.analytics.hte", "PolicyRecommendation"),
    "BiasDirection": ("polisyos.ir.analytics.backtest", "BiasDirection"),
    "OutcomeComparison": ("polisyos.ir.analytics.backtest", "OutcomeComparison"),
    "SystematicBias": ("polisyos.ir.analytics.backtest", "SystematicBias"),
    "BacktestScenario": ("polisyos.ir.analytics.backtest", "BacktestScenario"),
    "BacktestReport": ("polisyos.ir.analytics.backtest", "BacktestReport"),
    "BacktestPlanBundle": ("polisyos.ir.observation.bundles", "BacktestPlanBundle"),
    "BoundsEstimationBundle": ("polisyos.ir.observation.bundles", "BoundsEstimationBundle"),
    "CalibrationTargetBundleManifest": (
        "polisyos.ir.observation.bundles",
        "CalibrationTargetBundleManifest",
    ),
    "CausalPanelBundleManifest": (
        "polisyos.ir.observation.bundles",
        "CausalPanelBundleManifest",
    ),
    "DTRTreatmentSequenceBundleManifest": (
        "polisyos.ir.observation.bundles",
        "DTRTreatmentSequenceBundleManifest",
    ),
    "EntityScope": ("polisyos.ir.observation.contracts", "EntityScope"),
    "GovernancePassMappingBundle": (
        "polisyos.ir.observation.bundles",
        "GovernancePassMappingBundle",
    ),
    "IdentificationMode": ("polisyos.ir.observation.contracts", "IdentificationMode"),
    "LessonRegistrySeedBundle": (
        "polisyos.ir.observation.bundles",
        "LessonRegistrySeedBundle",
    ),
    "LeontiefIOBundle": ("polisyos.ir.observation.bundles", "LeontiefIOBundle"),
    "MicrosimSurveyContractBundle": (
        "polisyos.ir.observation.bundles",
        "MicrosimSurveyContractBundle",
    ),
    "MultiplexGraphLayerId": (
        "polisyos.ir.observation.contracts",
        "MultiplexGraphLayerId",
    ),
    "NetworkCausalContractBundle": (
        "polisyos.ir.observation.bundles",
        "NetworkCausalContractBundle",
    ),
    "NetworkContractBundle": (
        "polisyos.ir.observation.bundles",
        "NetworkContractBundle",
    ),
    "ObservationFamily": ("polisyos.ir.observation.contracts", "ObservationFamily"),
    "ObservationFamilyPolicy": (
        "polisyos.ir.observation.governance",
        "ObservationFamilyPolicy",
    ),
    "ObservationFamilyPolicyRegistry": (
        "polisyos.ir.observation.governance",
        "ObservationFamilyPolicyRegistry",
    ),
    "CalibrationSplitLabel": ("polisyos.ir.observation.compiler", "CalibrationSplitLabel"),
    "CalibrationSplitPlan": ("polisyos.ir.observation.compiler", "CalibrationSplitPlan"),
    "CalibrationSplitWindow": ("polisyos.ir.observation.compiler", "CalibrationSplitWindow"),
    "IdentificationModeRouter": ("polisyos.ir.observation.measurement", "IdentificationModeRouter"),
    "IdentificationRoute": ("polisyos.ir.observation.measurement", "IdentificationRoute"),
    "MeasurementRegistry": ("polisyos.ir.observation.measurement", "MeasurementRegistry"),
    "MeasurementTrustTier": ("polisyos.ir.observation.measurement", "MeasurementTrustTier"),
    "NegativeControlSpec": ("polisyos.ir.observation.compiler", "NegativeControlSpec"),
    "ObservationPanel": ("polisyos.ir.observation.contracts", "ObservationPanel"),
    "ObservationRecord": ("polisyos.ir.observation.contracts", "ObservationRecord"),
    "ObservationToContractManifest": (
        "polisyos.ir.observation.bundles",
        "ObservationToContractManifest",
    ),
    "BoundsEstimationInput": (
        "polisyos.ir.observation.contract_compilers",
        "BoundsEstimationInput",
    ),
    "FirmEvents": ("polisyos.ir.observation.contract_compilers", "FirmEvents"),
    "FirmPanels": ("polisyos.ir.observation.contract_compilers", "FirmPanels"),
    "GraphArtifacts": ("polisyos.ir.observation.contract_compilers", "GraphArtifacts"),
    "LeontiefIOInput": ("polisyos.ir.observation.contract_compilers", "LeontiefIOInput"),
    "ObservationContractCompilerSuite": (
        "polisyos.ir.observation.contract_compilers",
        "ObservationContractCompilerSuite",
    ),
    "PanelEconometricBundleManifest": (
        "polisyos.ir.observation.bundles",
        "PanelEconometricBundleManifest",
    ),
    "ProxyMap": ("polisyos.ir.observation.contract_compilers", "ProxyMap"),
    "ProxyIdentificationBundle": (
        "polisyos.ir.observation.bundles",
        "ProxyIdentificationBundle",
    ),
    "TransportabilityCheckBundle": (
        "polisyos.ir.observation.bundles",
        "TransportabilityCheckBundle",
    ),
    "CounterfactualCheckBundle": (
        "polisyos.ir.observation.bundles",
        "CounterfactualCheckBundle",
    ),
    "InterferenceLossSpecBundle": (
        "polisyos.ir.observation.bundles",
        "InterferenceLossSpecBundle",
    ),
    "CausalReadinessBundle": (
        "polisyos.ir.observation.causal_readiness",
        "CausalReadinessBundle",
    ),
    "BoundsEstimationTask": (
        "polisyos.ir.observation.causal_execution",
        "BoundsEstimationTask",
    ),
    "BoundsEstimationEntry": (
        "polisyos.ir.observation.causal_execution",
        "BoundsEstimationEntry",
    ),
    "TemporalDTRTask": (
        "polisyos.ir.observation.causal_execution",
        "TemporalDTRTask",
    ),
    "TemporalDTRExecutionEntry": (
        "polisyos.ir.observation.causal_execution",
        "TemporalDTRExecutionEntry",
    ),
    "CausalExecutionBundle": (
        "polisyos.ir.observation.causal_execution",
        "CausalExecutionBundle",
    ),
    "load_causal_execution_bundle": (
        "polisyos.ir.observation.causal_execution",
        "load_causal_execution_bundle",
    ),
    "persist_causal_execution_bundle": (
        "polisyos.ir.observation.causal_execution",
        "persist_causal_execution_bundle",
    ),
    "RegionSectorPanels": (
        "polisyos.ir.observation.contract_compilers",
        "RegionSectorPanels",
    ),
    "SourceConfidenceTier": (
        "polisyos.ir.observation.contracts",
        "SourceConfidenceTier",
    ),
    "SpecificationCurveInput": (
        "polisyos.ir.observation.contract_compilers",
        "SpecificationCurveInput",
    ),
    "SparseDenseBridge": (
        "polisyos.ir.observation.contract_compilers",
        "SparseDenseBridge",
    ),
    "SpecificationCurveBundle": (
        "polisyos.ir.observation.bundles",
        "SpecificationCurveBundle",
    ),
    "StrategicResponseChannel": (
        "polisyos.ir.observation.contracts",
        "StrategicResponseChannel",
    ),
    "RegimeCalendar": ("polisyos.ir.observation.measurement", "RegimeCalendar"),
    "SchemaChangepoint": ("polisyos.ir.observation.measurement", "SchemaChangepoint"),
    "SchemaRegimeRegistry": ("polisyos.ir.observation.measurement", "SchemaRegimeRegistry"),
    "SchemaRegimeSpec": ("polisyos.ir.observation.measurement", "SchemaRegimeSpec"),
    "ShockCalendar": ("polisyos.ir.observation.measurement", "ShockCalendar"),
    "StrategicResponseSpecsBundle": (
        "polisyos.ir.observation.bundles",
        "StrategicResponseSpecsBundle",
    ),
    "SurvivalDataBundleManifest": (
        "polisyos.ir.observation.bundles",
        "SurvivalDataBundleManifest",
    ),
}


def __getattr__(name: str) -> Any:
    """Resolve a public IR export on first access.

    Args:
        name: Facade attribute requested by user code.

    Returns:
        The lazily imported class, enum, or function bound to ``name``.

    Raises:
        AttributeError: If ``name`` is not part of the stable facade surface.
    """
    if name in _LAZY_IMPORTS:
        module_name, attr = _LAZY_IMPORTS[name]
        module = importlib.import_module(module_name)
        value = getattr(module, attr)
        globals()[name] = value
        return value
    raise AttributeError(f"module 'polisyos.ir' has no attribute '{name}'")


def __dir__() -> list[str]:
    """Return eager globals plus lazily exported contract names."""
    return sorted(list(globals().keys()) + list(_LAZY_IMPORTS.keys()))
