"""Expose the stable IR contract surface through a lazy package facade.

The root package is the compatibility boundary for schema-first contracts,
status enums, artifact refs, and bundle manifests shared between policy
authoring, Scientist runners, and Foundry methods. Names listed in ``__all__``
are resolved lazily so importing :mod:`polisyos.ir` does not eagerly pull
runtime-heavy submodules or trigger execution-side dependencies.

Treat ``__all__`` as the stable public API; helpers that are not re-exported
here remain internal to their submodules.
"""

from __future__ import annotations

import importlib
from typing import Any

from polisyos.ir.api import install_ir_legacy_module_aliases as _install_ir_legacy_module_aliases

_install_ir_legacy_module_aliases()
del _install_ir_legacy_module_aliases

__all__ = [
    "ABMBifurcationReport",
    "ABMIdentifiabilityCertificate",
    "ABMResult",
    "ABMResultRef",
    "AccessTier",
    "AdministrativeMissingnessClass",
    "AdministrativeMissingnessDirection",
    "AdministrativeMissingnessMetadata",
    "AdministrativeMissingnessScenarioFamily",
    "AdministrativeMissingnessUnitScope",
    "AgentConfig",
    "AgentTypeConfig",
    "AssumptionSpec",
    "AssumptionType",
    "BacktestPlanBundle",
    "BacktestReport",
    "BacktestScenario",
    "BiasDirection",
    "BlockSupportReport",
    "BoundsEstimationBundle",
    "BoundsEstimationEntry",
    "BoundsEstimationInput",
    "BoundsEstimationTask",
    "CalibrationConfig",
    "CalibrationSplitLabel",
    "CalibrationSplitPlan",
    "CalibrationSplitWindow",
    "CalibrationTarget",
    "CalibrationTargetBundleManifest",
    "CausalBlockBridge",
    "CausalBlockBridgeRef",
    "CausalDiscoveryReport",
    "CausalEffectReport",
    "CausalExecutionBundle",
    "CausalExecutionBundleRef",
    "CausalInterventionSpec",
    "CausalMethod",
    "CausalModelEnsemble",
    "CausalModelEnsembleRef",
    "CausalPanelBundleManifest",
    "CausalQuery",
    "CausalQueryResult",
    "CausalQueryResultRef",
    "CausalReadinessBundle",
    "CohortDimension",
    "CohortImpact",
    "ConnectorCapability",
    "ConnectorMetadataSpec",
    "ConstraintType",
    "CounterfactualCheckBundle",
    "DTRTreatmentSequenceBundleManifest",
    "DataFilter",
    "DataViewRequest",
    "DataViewType",
    "DependenceStructure",
    "DependenceStructureRef",
    "DependentSensitivityAnalysisBundle",
    "DependentSensitivityAnalysisBundleRef",
    "DependentSensitivityResult",
    "DependentSensitivityResultRef",
    "DetectorResult",
    "DiagnosticTest",
    "DimensionBreakdown",
    "DistributionFamily",
    "DistributionalReport",
    "DriftReadinessRef",
    "DynamicMicrosimValidationReport",
    "DynamicMicrosimValidationReportRef",
    "EnsembleMember",
    "EntityScope",
    "EnvironmentConfig",
    "EnvironmentParam",
    "EquilibriumMultiplicityWelfareAnnotation",
    "EstimationStatus",
    "ExplanationBundleRef",
    "ExposureMappingType",
    "FanChartSpec",
    "FeatureImportance",
    "FidelityLevel",
    "FirmEvents",
    "FirmPanels",
    "ForecastCalibrationMethod",
    "ForecastCoverageDiagnostic",
    "ForecastIntervalSemantics",
    "ForecastShiftTypeAssessment",
    "ForecastingUncertaintyBundle",
    "ForecastingUncertaintyBundleRef",
    "ForecastingUncertaintyBundleV2",
    "GEUncertaintyBundle",
    "GEUncertaintyBundleRef",
    "GEUncertaintyRepresentation",
    "GateContext",
    "GateDecision",
    "GateEvent",
    "GateEventType",
    "GatePriority",
    "GateRequest",
    "GateVerdict",
    "GovernancePassAlias",
    "GovernancePassAliasRegistry",
    "GovernancePassAliasStatus",
    "GovernancePassMappingBundle",
    "GovernancePassMappingRegistry",
    "GraphArtifacts",
    "HTEResult",
    "HorizonInterval",
    "HorizonPolicySpec",
    "IRExportInfo",
    "IRFieldInfo",
    "IRPublicStatus",
    "IRSchemaCatalog",
    "IRTypeInfo",
    "IRTypeKind",
    "IdentificationMode",
    "IdentificationModeRouter",
    "IdentificationRoute",
    "ImpactDirection",
    "InteractionComplex",
    "InteractionComplexRef",
    "InteractionMatrix",
    "InteractionType",
    "InterferenceCertificate",
    "InterferenceCertificateRef",
    "InterferenceEffectDecomposition",
    "InterferenceLossSpecBundle",
    "InterferenceMethod",
    "IntervalSemantics",
    "InterventionSpec",
    "InterventionType",
    "JudgeVerdictRef",
    "KPISpec",
    "LeontiefIOBundle",
    "LeontiefIOInput",
    "LessonRegistrySeedBundle",
    "MAUPInvarianceCertificate",
    "MAUPInvarianceCertificateRef",
    "MAUPPartitionCheck",
    "MeasurementRegistry",
    "MeasurementTrustTier",
    "MechanismBinding",
    "MechanismFamily",
    "MechanismSource",
    "MetricUnit",
    "MicrosimCalibrationReport",
    "MicrosimCalibrationReportRef",
    "MicrosimSurveyContractBundle",
    "MissingnessAssessmentProvenance",
    "MissingnessAssessmentReport",
    "MissingnessAssessmentStatus",
    "MissingnessEstimandRisk",
    "MissingnessEvidenceItem",
    "MobilityReport",
    "MobilityReportRef",
    "ModelSpec",
    "MultiplexGraphLayerId",
    "NegativeControlSpec",
    "NetworkCausalContractBundle",
    "NetworkContractBundle",
    "NetworkInterferenceReport",
    "NodeMechanism",
    "NormPack",
    "NormRef",
    "NormRule",
    "ObservationContractCompilerSuite",
    "ObservationFamily",
    "ObservationFamilyPolicy",
    "ObservationFamilyPolicyRegistry",
    "ObservationPanel",
    "ObservationRecord",
    "ObservationToContractManifest",
    "OperatingCharacteristicKey",
    "OperatingCharacteristicLibrary",
    "OperatingCharacteristicRecord",
    "OutcomeComparison",
    "PanelEconometricBundleManifest",
    "ParameterSpec",
    "Phase4DynamicsGate",
    "Phase4GateStatus",
    "Phase4TemporalPolicyGateVerdict",
    "PlaceboResult",
    "PolicyInteraction",
    "PolicyInterventionSpec",
    "PolicyPortfolio",
    "PolicyRecommendation",
    "PolicySpec",
    "ProblemConstraintSpec",
    "ProblemDomain",
    "ProblemFrame",
    "PropagationMethod",
    "ProxyIdentificationBundle",
    "ProxyMap",
    "QualityTier",
    "QueryType",
    "ReadinessImpact",
    "ReconciliationCertificate",
    "ReconciliationMethod",
    "ReconciliationStatus",
    "RefutationResult",
    "RefutationTestType",
    "RegimeBenchmarkStatus",
    "RegimeCalendar",
    "RegimeForecastCalibrationStatus",
    "RegimeIdentifiabilityStatus",
    "RegimeModelFamily",
    "RegimeShiftForecastBundle",
    "RegimeShiftForecastBundleRef",
    "RegionSectorPanels",
    "RuleType",
    "SchemaChangepoint",
    "SchemaRegimeRegistry",
    "SchemaRegimeSpec",
    "SensitivityAnalysisBundle",
    "SensitivityAnalysisBundleRef",
    "SensitivityAnalysisIndex",
    "ShiftComponent",
    "ShiftDiagnosticReport",
    "ShiftDiagnosticReportRef",
    "ShockCalendar",
    "SourceConfidenceTier",
    "SpaceTimeCausalCertificate",
    "SpaceTimeCausalCertificateRef",
    "SparseDenseBridge",
    "SpatialResult",
    "SpecificationCurveBundle",
    "SpecificationCurveInput",
    "StakeholderSpec",
    "StrategicResponseChannel",
    "StrategicResponseSpecsBundle",
    "StructuralCausalModelSpec",
    "SubgroupEffect",
    "SuccessCriterion",
    "SurveyAssumptionComponent",
    "SurveyAssumptionLayer",
    "SurveyAssumptionStatus",
    "SurveyQualityCertificate",
    "SurveyQualityCertificateRef",
    "SurveyRequestedRegime",
    "SurveyValidatedRegime",
    "SurveyVarianceMode",
    "SurvivalDataBundleManifest",
    "SystematicBias",
    "TargetingRule",
    "TemporalDTRExecutionEntry",
    "TemporalDTRTask",
    "TemporalGraphCausalCertificate",
    "TemporalGraphCausalCertificateRef",
    "TemporalInterventionSequence",
    "TemporalInterventionStep",
    "TransportabilityCheckBundle",
    "TransportabilityResult",
    "TransportabilityResultRef",
    "TrustLevel",
    "UncertaintyEnvelope",
    "UncertaintySource",
    "WelfareBundle",
    "WelfareBundleRef",
    "WelfareIntervalSemantics",
    "WelfareMethod",
    "WelfareSampleBundle",
    "WelfareSampleBundleRef",
    "WelfareStatus",
    "WinnersLosersEntry",
    "WinnersLosersTable",
    "enumerate_ir_exports",
    "get_ir_schema_catalog",
    "get_ir_type",
    "inspect_ir_schema",
    "list_ir_types",
    "load_causal_execution_bundle",
    "load_dependent_sensitivity_result",
    "load_policy",
    "persist_causal_execution_bundle",
    "persist_dependent_sensitivity_result",
]

_LAZY_IMPORTS: dict[str, tuple[str, str]] = {
    "ABMBifurcationReport": (
        "polisyos.ir.analytics.phase4_dynamics",
        "ABMBifurcationReport",
    ),
    "ABMIdentifiabilityCertificate": (
        "polisyos.ir.analytics.phase4_dynamics",
        "ABMIdentifiabilityCertificate",
    ),
    "ABMResult": ("polisyos.ir.analytics.phase4_dynamics", "ABMResult"),
    "ABMResultRef": ("polisyos.ir.registry.refs", "ABMResultRef"),
    "CalibrationConfig": ("polisyos.ir.analytics.calibration", "CalibrationConfig"),
    "CalibrationTarget": ("polisyos.ir.analytics.calibration", "CalibrationTarget"),
    "ConnectorCapability": ("polisyos.ir.connectors", "ConnectorCapability"),
    "ConnectorMetadataSpec": ("polisyos.ir.connectors", "ConnectorMetadataSpec"),
    "QualityTier": ("polisyos.ir.connectors", "QualityTier"),
    "TrustLevel": ("polisyos.ir.connectors", "TrustLevel"),
    "AccessTier": ("polisyos.ir.analytics.data_views", "AccessTier"),
    "DataFilter": ("polisyos.ir.analytics.data_views", "DataFilter"),
    "DataViewRequest": ("polisyos.ir.analytics.data_views", "DataViewRequest"),
    "DataViewType": ("polisyos.ir.analytics.data_views", "DataViewType"),
    "DetectorResult": ("polisyos.ir.analytics.shift_diagnostics", "DetectorResult"),
    "DependentSensitivityAnalysisBundle": (
        "polisyos.ir.analytics.dependent_sensitivity",
        "DependentSensitivityAnalysisBundle",
    ),
    "DependentSensitivityAnalysisBundleRef": (
        "polisyos.ir.analytics.dependent_sensitivity",
        "DependentSensitivityAnalysisBundleRef",
    ),
    "DependentSensitivityResult": (
        "polisyos.ir.analytics.dependent_sensitivity",
        "DependentSensitivityResult",
    ),
    "DependentSensitivityResultRef": (
        "polisyos.ir.analytics.dependent_sensitivity",
        "DependentSensitivityResultRef",
    ),
    "SensitivityAnalysisBundle": (
        "polisyos.ir.analytics.sensitivity",
        "SensitivityAnalysisBundle",
    ),
    "SensitivityAnalysisIndex": (
        "polisyos.ir.analytics.sensitivity",
        "SensitivityAnalysisIndex",
    ),
    "SensitivityAnalysisBundleRef": ("polisyos.ir.registry.refs", "SensitivityAnalysisBundleRef"),
    "ExplanationBundleRef": ("polisyos.ir.registry.refs", "ExplanationBundleRef"),
    "JudgeVerdictRef": ("polisyos.ir.registry.refs", "JudgeVerdictRef"),
    "DriftReadinessRef": ("polisyos.ir.registry.refs", "DriftReadinessRef"),
    "OperatingCharacteristicKey": (
        "polisyos.ir.analytics.shift_diagnostics",
        "OperatingCharacteristicKey",
    ),
    "OperatingCharacteristicLibrary": (
        "polisyos.ir.analytics.shift_diagnostics",
        "OperatingCharacteristicLibrary",
    ),
    "OperatingCharacteristicRecord": (
        "polisyos.ir.analytics.shift_diagnostics",
        "OperatingCharacteristicRecord",
    ),
    "ReadinessImpact": ("polisyos.ir.analytics.shift_diagnostics", "ReadinessImpact"),
    "ShiftComponent": ("polisyos.ir.analytics.shift_diagnostics", "ShiftComponent"),
    "ShiftDiagnosticReport": (
        "polisyos.ir.analytics.shift_diagnostics",
        "ShiftDiagnosticReport",
    ),
    "ShiftDiagnosticReportRef": ("polisyos.ir.registry.refs", "ShiftDiagnosticReportRef"),
    "load_policy": ("polisyos.ir.loading.loaders", "load_policy"),
    "IRExportInfo": ("polisyos.ir.schemas", "IRExportInfo"),
    "IRFieldInfo": ("polisyos.ir.schemas", "IRFieldInfo"),
    "IRPublicStatus": ("polisyos.ir.schemas", "IRPublicStatus"),
    "IRSchemaCatalog": ("polisyos.ir.schemas", "IRSchemaCatalog"),
    "IRTypeInfo": ("polisyos.ir.schemas", "IRTypeInfo"),
    "IRTypeKind": ("polisyos.ir.schemas", "IRTypeKind"),
    "enumerate_ir_exports": ("polisyos.ir.schemas", "enumerate_ir_exports"),
    "get_ir_schema_catalog": ("polisyos.ir.schemas", "get_ir_schema_catalog"),
    "get_ir_type": ("polisyos.ir.schemas", "get_ir_type"),
    "inspect_ir_schema": ("polisyos.ir.schemas", "inspect_ir_schema"),
    "list_ir_types": ("polisyos.ir.schemas", "list_ir_types"),
    "load_dependent_sensitivity_result": (
        "polisyos.ir.analytics.dependent_sensitivity",
        "load_dependent_sensitivity_result",
    ),
    "persist_dependent_sensitivity_result": (
        "polisyos.ir.analytics.dependent_sensitivity",
        "persist_dependent_sensitivity_result",
    ),
    "NormPack": ("polisyos.ir.loading.norm_pack", "NormPack"),
    "NormRule": ("polisyos.ir.loading.norm_pack", "NormRule"),
    "NormRef": ("polisyos.ir.loading.norm_pack", "NormRef"),
    "RuleType": ("polisyos.ir.loading.norm_pack", "RuleType"),
    "AgentConfig": ("polisyos.ir.model_layer.model_spec", "AgentConfig"),
    "AgentTypeConfig": ("polisyos.ir.model_layer.model_spec", "AgentTypeConfig"),
    "AssumptionSpec": ("polisyos.ir.model_layer.model_spec", "AssumptionSpec"),
    "AssumptionType": ("polisyos.ir.model_layer.model_spec", "AssumptionType"),
    "EnvironmentConfig": ("polisyos.ir.model_layer.model_spec", "EnvironmentConfig"),
    "EnvironmentParam": ("polisyos.ir.model_layer.model_spec", "EnvironmentParam"),
    "FidelityLevel": ("polisyos.ir.model_layer.model_spec", "FidelityLevel"),
    "GovernancePassAlias": ("polisyos.ir.observation.governance", "GovernancePassAlias"),
    "GovernancePassAliasRegistry": (
        "polisyos.ir.observation.governance",
        "GovernancePassAliasRegistry",
    ),
    "GovernancePassAliasStatus": (
        "polisyos.ir.observation.governance",
        "GovernancePassAliasStatus",
    ),
    "GovernancePassMappingRegistry": (
        "polisyos.ir.observation.governance",
        "GovernancePassMappingRegistry",
    ),
    "ModelSpec": ("polisyos.ir.model_layer.model_spec", "ModelSpec"),
    "GateContext": ("polisyos.ir.governance.gate", "GateContext"),
    "GateDecision": ("polisyos.ir.governance.gate", "GateDecision"),
    "GateEvent": ("polisyos.ir.governance.gate", "GateEvent"),
    "GateEventType": ("polisyos.ir.governance.gate", "GateEventType"),
    "GatePriority": ("polisyos.ir.governance.gate", "GatePriority"),
    "GateRequest": ("polisyos.ir.governance.gate", "GateRequest"),
    "GateVerdict": ("polisyos.ir.governance.gate", "GateVerdict"),
    "DistributionFamily": ("polisyos.ir.analytics.uncertainty", "DistributionFamily"),
    "IntervalSemantics": ("polisyos.ir.analytics.uncertainty", "IntervalSemantics"),
    "PropagationMethod": ("polisyos.ir.analytics.uncertainty", "PropagationMethod"),
    "MechanismBinding": ("polisyos.ir.governance.policy_spec", "MechanismBinding"),
    "ParameterSpec": ("polisyos.ir.governance.policy_spec", "ParameterSpec"),
    "PolicyInterventionSpec": ("polisyos.ir.governance.policy_spec", "InterventionSpec"),
    "PolicySpec": ("polisyos.ir.governance.policy_spec", "PolicySpec"),
    "TemporalInterventionSequence": (
        "polisyos.ir.governance.policy_spec",
        "TemporalInterventionSequence",
    ),
    "TemporalInterventionStep": (
        "polisyos.ir.governance.policy_spec",
        "TemporalInterventionStep",
    ),
    "PolicyPortfolio": ("polisyos.ir.loading.portfolio", "PolicyPortfolio"),
    "PolicyInteraction": ("polisyos.ir.loading.portfolio", "PolicyInteraction"),
    "InteractionMatrix": ("polisyos.ir.loading.portfolio", "InteractionMatrix"),
    "InteractionType": ("polisyos.ir.loading.portfolio", "InteractionType"),
    "ConstraintType": ("polisyos.ir.governance.problem_frame", "ConstraintType"),
    "KPISpec": ("polisyos.ir.governance.problem_frame", "KPISpec"),
    "ProblemConstraintSpec": ("polisyos.ir.governance.problem_frame", "ConstraintSpec"),
    "ProblemDomain": ("polisyos.ir.governance.problem_frame", "ProblemDomain"),
    "ProblemFrame": ("polisyos.ir.governance.problem_frame", "ProblemFrame"),
    "StakeholderSpec": ("polisyos.ir.governance.problem_frame", "StakeholderSpec"),
    "SuccessCriterion": ("polisyos.ir.governance.problem_frame", "SuccessCriterion"),
    "UncertaintyEnvelope": ("polisyos.ir.analytics.uncertainty", "UncertaintyEnvelope"),
    "UncertaintySource": ("polisyos.ir.analytics.uncertainty", "UncertaintySource"),
    "EquilibriumMultiplicityWelfareAnnotation": (
        "polisyos.ir.analytics.phase4_dynamics",
        "EquilibriumMultiplicityWelfareAnnotation",
    ),
    "WelfareBundle": ("polisyos.ir.analytics.welfare", "WelfareBundle"),
    "WelfareBundleRef": ("polisyos.ir.registry.refs", "WelfareBundleRef"),
    "WelfareIntervalSemantics": (
        "polisyos.ir.analytics.welfare",
        "WelfareIntervalSemantics",
    ),
    "WelfareMethod": ("polisyos.ir.analytics.welfare", "WelfareMethod"),
    "WelfareSampleBundle": (
        "polisyos.ir.analytics.welfare",
        "WelfareSampleBundle",
    ),
    "WelfareSampleBundleRef": ("polisyos.ir.registry.refs", "WelfareSampleBundleRef"),
    "WelfareStatus": ("polisyos.ir.analytics.welfare", "WelfareStatus"),
    "CausalMethod": ("polisyos.ir.analytics.causal", "CausalMethod"),
    "EstimationStatus": ("polisyos.ir.analytics.causal", "EstimationStatus"),
    "RefutationTestType": ("polisyos.ir.analytics.causal", "RefutationTestType"),
    "RefutationResult": ("polisyos.ir.analytics.causal", "RefutationResult"),
    "CausalEffectReport": ("polisyos.ir.analytics.causal", "CausalEffectReport"),
    "QueryType": ("polisyos.ir.analytics.causal_queries", "QueryType"),
    "InterventionType": ("polisyos.ir.analytics.causal_queries", "InterventionType"),
    "InterventionSpec": ("polisyos.ir.analytics.causal_queries", "InterventionSpec"),
    "CausalInterventionSpec": (
        "polisyos.ir.analytics.causal_queries",
        "CausalInterventionSpec",
    ),
    "CausalQuery": ("polisyos.ir.analytics.causal_queries", "CausalQuery"),
    "CausalQueryResult": ("polisyos.ir.analytics.causal_queries", "CausalQueryResult"),
    "CausalQueryResultRef": ("polisyos.ir.registry.refs", "CausalQueryResultRef"),
    "CausalExecutionBundleRef": ("polisyos.ir.registry.refs", "CausalExecutionBundleRef"),
    "BlockSupportReport": (
        "polisyos.ir.analytics.network_generative",
        "BlockSupportReport",
    ),
    "CausalBlockBridge": (
        "polisyos.ir.analytics.network_generative",
        "CausalBlockBridge",
    ),
    "CausalBlockBridgeRef": ("polisyos.ir.registry.refs", "CausalBlockBridgeRef"),
    "ExposureMappingType": ("polisyos.ir.analytics.interference", "ExposureMappingType"),
    "InteractionComplex": ("polisyos.ir.analytics.interference", "InteractionComplex"),
    "InteractionComplexRef": ("polisyos.ir.registry.refs", "InteractionComplexRef"),
    "InterferenceCertificate": (
        "polisyos.ir.analytics.interference",
        "InterferenceCertificate",
    ),
    "InterferenceCertificateRef": ("polisyos.ir.registry.refs", "InterferenceCertificateRef"),
    "InterferenceEffectDecomposition": (
        "polisyos.ir.analytics.interference",
        "InterferenceEffectDecomposition",
    ),
    "InterferenceMethod": ("polisyos.ir.analytics.interference", "InterferenceMethod"),
    "MAUPInvarianceCertificate": (
        "polisyos.ir.analytics.interference",
        "MAUPInvarianceCertificate",
    ),
    "MAUPInvarianceCertificateRef": ("polisyos.ir.registry.refs", "MAUPInvarianceCertificateRef"),
    "MAUPPartitionCheck": ("polisyos.ir.analytics.interference", "MAUPPartitionCheck"),
    "NetworkInterferenceReport": (
        "polisyos.ir.analytics.interference",
        "NetworkInterferenceReport",
    ),
    "SpatialResult": ("polisyos.ir.analytics.interference", "SpatialResult"),
    "EnsembleMember": ("polisyos.ir.analytics.causal_ensemble", "EnsembleMember"),
    "CausalModelEnsemble": (
        "polisyos.ir.analytics.causal_ensemble",
        "CausalModelEnsemble",
    ),
    "CausalModelEnsembleRef": ("polisyos.ir.registry.refs", "CausalModelEnsembleRef"),
    "TransportabilityResult": (
        "polisyos.ir.analytics.transportability",
        "TransportabilityResult",
    ),
    "TransportabilityResultRef": (
        "polisyos.ir.registry.refs",
        "TransportabilityResultRef",
    ),
    "ForecastCalibrationMethod": (
        "polisyos.ir.analytics.forecasting_uncertainty",
        "ForecastCalibrationMethod",
    ),
    "ForecastCoverageDiagnostic": (
        "polisyos.ir.analytics.forecasting_uncertainty",
        "ForecastCoverageDiagnostic",
    ),
    "ForecastIntervalSemantics": (
        "polisyos.ir.analytics.forecasting_uncertainty",
        "ForecastIntervalSemantics",
    ),
    "ForecastingUncertaintyBundle": (
        "polisyos.ir.analytics.forecasting_uncertainty",
        "ForecastingUncertaintyBundle",
    ),
    "ForecastingUncertaintyBundleV2": (
        "polisyos.ir.analytics.forecasting_uncertainty",
        "ForecastingUncertaintyBundleV2",
    ),
    "ForecastingUncertaintyBundleRef": (
        "polisyos.ir.registry.refs",
        "ForecastingUncertaintyBundleRef",
    ),
    "ForecastShiftTypeAssessment": (
        "polisyos.ir.analytics.regime_shift_forecast",
        "ForecastShiftTypeAssessment",
    ),
    "GEUncertaintyBundle": (
        "polisyos.ir.analytics.welfare",
        "GEUncertaintyBundle",
    ),
    "GEUncertaintyBundleRef": ("polisyos.ir.registry.refs", "GEUncertaintyBundleRef"),
    "GEUncertaintyRepresentation": (
        "polisyos.ir.analytics.welfare",
        "GEUncertaintyRepresentation",
    ),
    "FanChartSpec": (
        "polisyos.ir.analytics.forecasting_uncertainty",
        "FanChartSpec",
    ),
    "ReconciliationCertificate": (
        "polisyos.ir.analytics.forecasting_uncertainty",
        "ReconciliationCertificate",
    ),
    "ReconciliationMethod": (
        "polisyos.ir.analytics.forecasting_uncertainty",
        "ReconciliationMethod",
    ),
    "ReconciliationStatus": (
        "polisyos.ir.analytics.forecasting_uncertainty",
        "ReconciliationStatus",
    ),
    "HorizonInterval": (
        "polisyos.ir.analytics.forecasting_uncertainty",
        "HorizonInterval",
    ),
    "HorizonPolicySpec": (
        "polisyos.ir.analytics.forecasting_uncertainty",
        "HorizonPolicySpec",
    ),
    "RegimeBenchmarkStatus": (
        "polisyos.ir.analytics.regime_shift_forecast",
        "RegimeBenchmarkStatus",
    ),
    "RegimeForecastCalibrationStatus": (
        "polisyos.ir.analytics.regime_shift_forecast",
        "RegimeForecastCalibrationStatus",
    ),
    "RegimeIdentifiabilityStatus": (
        "polisyos.ir.analytics.regime_shift_forecast",
        "RegimeIdentifiabilityStatus",
    ),
    "RegimeModelFamily": (
        "polisyos.ir.analytics.regime_shift_forecast",
        "RegimeModelFamily",
    ),
    "RegimeShiftForecastBundle": (
        "polisyos.ir.analytics.regime_shift_forecast",
        "RegimeShiftForecastBundle",
    ),
    "RegimeShiftForecastBundleRef": (
        "polisyos.ir.registry.refs",
        "RegimeShiftForecastBundleRef",
    ),
    "Phase4DynamicsGate": (
        "polisyos.ir.analytics.phase4_dynamics",
        "Phase4DynamicsGate",
    ),
    "Phase4GateStatus": (
        "polisyos.ir.analytics.phase4_dynamics",
        "Phase4GateStatus",
    ),
    "Phase4TemporalPolicyGateVerdict": (
        "polisyos.ir.analytics.phase4_dynamics",
        "Phase4TemporalPolicyGateVerdict",
    ),
    "TemporalGraphCausalCertificate": (
        "polisyos.ir.analytics.phase4_dynamics",
        "TemporalGraphCausalCertificate",
    ),
    "TemporalGraphCausalCertificateRef": (
        "polisyos.ir.registry.refs",
        "TemporalGraphCausalCertificateRef",
    ),
    "SpaceTimeCausalCertificate": (
        "polisyos.ir.analytics.phase4_dynamics",
        "SpaceTimeCausalCertificate",
    ),
    "SpaceTimeCausalCertificateRef": (
        "polisyos.ir.registry.refs",
        "SpaceTimeCausalCertificateRef",
    ),
    "CausalDiscoveryReport": (
        "polisyos.ir.analytics.causal_discovery",
        "CausalDiscoveryReport",
    ),
    "MechanismFamily": (
        "polisyos.ir.analytics.structural_causal_model",
        "MechanismFamily",
    ),
    "MechanismSource": (
        "polisyos.ir.analytics.structural_causal_model",
        "MechanismSource",
    ),
    "NodeMechanism": (
        "polisyos.ir.analytics.structural_causal_model",
        "NodeMechanism",
    ),
    "StructuralCausalModelSpec": (
        "polisyos.ir.analytics.structural_causal_model",
        "StructuralCausalModelSpec",
    ),
    "DiagnosticTest": ("polisyos.ir.analytics.causal", "DiagnosticTest"),
    "PlaceboResult": ("polisyos.ir.analytics.causal", "PlaceboResult"),
    "CohortDimension": ("polisyos.ir.analytics.distributional", "CohortDimension"),
    "ImpactDirection": ("polisyos.ir.analytics.distributional", "ImpactDirection"),
    "MetricUnit": ("polisyos.ir.analytics.distributional", "MetricUnit"),
    "CohortImpact": ("polisyos.ir.analytics.distributional", "CohortImpact"),
    "DimensionBreakdown": ("polisyos.ir.analytics.distributional", "DimensionBreakdown"),
    "WinnersLosersEntry": ("polisyos.ir.analytics.distributional", "WinnersLosersEntry"),
    "WinnersLosersTable": ("polisyos.ir.analytics.distributional", "WinnersLosersTable"),
    "DistributionalReport": ("polisyos.ir.analytics.distributional", "DistributionalReport"),
    "SubgroupEffect": ("polisyos.ir.analytics.hte", "SubgroupEffect"),
    "FeatureImportance": ("polisyos.ir.analytics.hte", "FeatureImportance"),
    "HTEResult": ("polisyos.ir.analytics.hte", "HTEResult"),
    "TargetingRule": ("polisyos.ir.analytics.hte", "TargetingRule"),
    "PolicyRecommendation": ("polisyos.ir.analytics.hte", "PolicyRecommendation"),
    "BiasDirection": ("polisyos.ir.analytics.backtest", "BiasDirection"),
    "OutcomeComparison": ("polisyos.ir.analytics.backtest", "OutcomeComparison"),
    "SystematicBias": ("polisyos.ir.analytics.backtest", "SystematicBias"),
    "BacktestScenario": ("polisyos.ir.analytics.backtest", "BacktestScenario"),
    "BacktestReport": ("polisyos.ir.analytics.backtest", "BacktestReport"),
    "AdministrativeMissingnessClass": (
        "polisyos.ir.analytics.administrative_missingness",
        "AdministrativeMissingnessClass",
    ),
    "AdministrativeMissingnessDirection": (
        "polisyos.ir.analytics.administrative_missingness",
        "AdministrativeMissingnessDirection",
    ),
    "AdministrativeMissingnessMetadata": (
        "polisyos.ir.analytics.administrative_missingness",
        "AdministrativeMissingnessMetadata",
    ),
    "AdministrativeMissingnessScenarioFamily": (
        "polisyos.ir.analytics.administrative_missingness",
        "AdministrativeMissingnessScenarioFamily",
    ),
    "AdministrativeMissingnessUnitScope": (
        "polisyos.ir.analytics.administrative_missingness",
        "AdministrativeMissingnessUnitScope",
    ),
    "MissingnessAssessmentProvenance": (
        "polisyos.ir.analytics.administrative_missingness",
        "MissingnessAssessmentProvenance",
    ),
    "MissingnessAssessmentReport": (
        "polisyos.ir.analytics.administrative_missingness",
        "MissingnessAssessmentReport",
    ),
    "MissingnessAssessmentStatus": (
        "polisyos.ir.analytics.administrative_missingness",
        "MissingnessAssessmentStatus",
    ),
    "MissingnessEstimandRisk": (
        "polisyos.ir.analytics.administrative_missingness",
        "MissingnessEstimandRisk",
    ),
    "MissingnessEvidenceItem": (
        "polisyos.ir.analytics.administrative_missingness",
        "MissingnessEvidenceItem",
    ),
    "SurveyRakingIteration": (
        "polisyos.ir.analytics.survey_raking",
        "SurveyRakingIteration",
    ),
    "SurveyRakingCategoryDiagnostic": (
        "polisyos.ir.analytics.survey_raking",
        "SurveyRakingCategoryDiagnostic",
    ),
    "SurveyRakingDiagnosticReport": (
        "polisyos.ir.analytics.survey_raking",
        "SurveyRakingDiagnosticReport",
    ),
    "SurveyAssumptionComponent": (
        "polisyos.ir.analytics.survey_quality",
        "SurveyAssumptionComponent",
    ),
    "SurveyAssumptionLayer": (
        "polisyos.ir.analytics.survey_quality",
        "SurveyAssumptionLayer",
    ),
    "SurveyAssumptionStatus": (
        "polisyos.ir.analytics.survey_quality",
        "SurveyAssumptionStatus",
    ),
    "SurveyRequestedRegime": (
        "polisyos.ir.analytics.survey_quality",
        "SurveyRequestedRegime",
    ),
    "SurveyValidatedRegime": (
        "polisyos.ir.analytics.survey_quality",
        "SurveyValidatedRegime",
    ),
    "SurveyVarianceMode": (
        "polisyos.ir.analytics.survey_quality",
        "SurveyVarianceMode",
    ),
    "SurveyQualityCertificate": (
        "polisyos.ir.analytics.survey_quality",
        "SurveyQualityCertificate",
    ),
    "SurveyQualityCertificateRef": (
        "polisyos.ir.registry.refs",
        "SurveyQualityCertificateRef",
    ),
    "MicrosimCalibrationReport": (
        "polisyos.ir.analytics.microsim_calibration",
        "MicrosimCalibrationReport",
    ),
    "MicrosimCalibrationReportRef": (
        "polisyos.ir.registry.refs",
        "MicrosimCalibrationReportRef",
    ),
    "DynamicMicrosimValidationReport": (
        "polisyos.ir.analytics.phase4_dynamics",
        "DynamicMicrosimValidationReport",
    ),
    "DynamicMicrosimValidationReportRef": (
        "polisyos.ir.registry.refs",
        "DynamicMicrosimValidationReportRef",
    ),
    "DependenceStructure": (
        "polisyos.ir.analytics.dependence_structure",
        "DependenceStructure",
    ),
    "DependenceStructureRef": (
        "polisyos.ir.registry.refs",
        "DependenceStructureRef",
    ),
    "MobilityReport": (
        "polisyos.ir.analytics.mobility",
        "MobilityReport",
    ),
    "MobilityReportRef": (
        "polisyos.ir.registry.refs",
        "MobilityReportRef",
    ),
    "BacktestPlanBundle": ("polisyos.ir.observation.bundles", "BacktestPlanBundle"),
    "BoundsEstimationBundle": ("polisyos.ir.observation.bundles", "BoundsEstimationBundle"),
    "CalibrationTargetBundleManifest": (
        "polisyos.ir.observation.bundles",
        "CalibrationTargetBundleManifest",
    ),
    "CausalPanelBundleManifest": (
        "polisyos.ir.observation.bundles",
        "CausalPanelBundleManifest",
    ),
    "DTRTreatmentSequenceBundleManifest": (
        "polisyos.ir.observation.bundles",
        "DTRTreatmentSequenceBundleManifest",
    ),
    "EntityScope": ("polisyos.ir.observation.contracts", "EntityScope"),
    "GovernancePassMappingBundle": (
        "polisyos.ir.observation.bundles",
        "GovernancePassMappingBundle",
    ),
    "IdentificationMode": ("polisyos.ir.observation.contracts", "IdentificationMode"),
    "LessonRegistrySeedBundle": (
        "polisyos.ir.observation.bundles",
        "LessonRegistrySeedBundle",
    ),
    "LeontiefIOBundle": ("polisyos.ir.observation.bundles", "LeontiefIOBundle"),
    "MicrosimSurveyContractBundle": (
        "polisyos.ir.observation.bundles",
        "MicrosimSurveyContractBundle",
    ),
    "MultiplexGraphLayerId": (
        "polisyos.ir.observation.contracts",
        "MultiplexGraphLayerId",
    ),
    "NetworkCausalContractBundle": (
        "polisyos.ir.observation.bundles",
        "NetworkCausalContractBundle",
    ),
    "NetworkContractBundle": (
        "polisyos.ir.observation.bundles",
        "NetworkContractBundle",
    ),
    "ObservationFamily": ("polisyos.ir.observation.contracts", "ObservationFamily"),
    "ObservationFamilyPolicy": (
        "polisyos.ir.observation.governance",
        "ObservationFamilyPolicy",
    ),
    "ObservationFamilyPolicyRegistry": (
        "polisyos.ir.observation.governance",
        "ObservationFamilyPolicyRegistry",
    ),
    "CalibrationSplitLabel": ("polisyos.ir.observation.compiler", "CalibrationSplitLabel"),
    "CalibrationSplitPlan": ("polisyos.ir.observation.compiler", "CalibrationSplitPlan"),
    "CalibrationSplitWindow": ("polisyos.ir.observation.compiler", "CalibrationSplitWindow"),
    "IdentificationModeRouter": ("polisyos.ir.observation.measurement", "IdentificationModeRouter"),
    "IdentificationRoute": ("polisyos.ir.observation.measurement", "IdentificationRoute"),
    "MeasurementRegistry": ("polisyos.ir.observation.measurement", "MeasurementRegistry"),
    "MeasurementTrustTier": ("polisyos.ir.observation.measurement", "MeasurementTrustTier"),
    "NegativeControlSpec": ("polisyos.ir.observation.compiler", "NegativeControlSpec"),
    "ObservationPanel": ("polisyos.ir.observation.contracts", "ObservationPanel"),
    "ObservationRecord": ("polisyos.ir.observation.contracts", "ObservationRecord"),
    "ObservationToContractManifest": (
        "polisyos.ir.observation.bundles",
        "ObservationToContractManifest",
    ),
    "BoundsEstimationInput": (
        "polisyos.ir.observation.contract_compilers",
        "BoundsEstimationInput",
    ),
    "FirmEvents": ("polisyos.ir.observation.contract_compilers", "FirmEvents"),
    "FirmPanels": ("polisyos.ir.observation.contract_compilers", "FirmPanels"),
    "GraphArtifacts": ("polisyos.ir.observation.contract_compilers", "GraphArtifacts"),
    "LeontiefIOInput": ("polisyos.ir.observation.contract_compilers", "LeontiefIOInput"),
    "ObservationContractCompilerSuite": (
        "polisyos.ir.observation.contract_compilers",
        "ObservationContractCompilerSuite",
    ),
    "PanelEconometricBundleManifest": (
        "polisyos.ir.observation.bundles",
        "PanelEconometricBundleManifest",
    ),
    "ProxyMap": ("polisyos.ir.observation.contract_compilers", "ProxyMap"),
    "ProxyIdentificationBundle": (
        "polisyos.ir.observation.bundles",
        "ProxyIdentificationBundle",
    ),
    "TransportabilityCheckBundle": (
        "polisyos.ir.observation.bundles",
        "TransportabilityCheckBundle",
    ),
    "CounterfactualCheckBundle": (
        "polisyos.ir.observation.bundles",
        "CounterfactualCheckBundle",
    ),
    "InterferenceLossSpecBundle": (
        "polisyos.ir.observation.bundles",
        "InterferenceLossSpecBundle",
    ),
    "CausalReadinessBundle": (
        "polisyos.ir.observation.causal_readiness",
        "CausalReadinessBundle",
    ),
    "BoundsEstimationTask": (
        "polisyos.ir.observation.causal_execution",
        "BoundsEstimationTask",
    ),
    "BoundsEstimationEntry": (
        "polisyos.ir.observation.causal_execution",
        "BoundsEstimationEntry",
    ),
    "TemporalDTRTask": (
        "polisyos.ir.observation.causal_execution",
        "TemporalDTRTask",
    ),
    "TemporalDTRExecutionEntry": (
        "polisyos.ir.observation.causal_execution",
        "TemporalDTRExecutionEntry",
    ),
    "CausalExecutionBundle": (
        "polisyos.ir.observation.causal_execution",
        "CausalExecutionBundle",
    ),
    "load_causal_execution_bundle": (
        "polisyos.ir.observation.causal_execution",
        "load_causal_execution_bundle",
    ),
    "persist_causal_execution_bundle": (
        "polisyos.ir.observation.causal_execution",
        "persist_causal_execution_bundle",
    ),
    "RegionSectorPanels": (
        "polisyos.ir.observation.contract_compilers",
        "RegionSectorPanels",
    ),
    "SourceConfidenceTier": (
        "polisyos.ir.observation.contracts",
        "SourceConfidenceTier",
    ),
    "SpecificationCurveInput": (
        "polisyos.ir.observation.contract_compilers",
        "SpecificationCurveInput",
    ),
    "SparseDenseBridge": (
        "polisyos.ir.observation.contract_compilers",
        "SparseDenseBridge",
    ),
    "SpecificationCurveBundle": (
        "polisyos.ir.observation.bundles",
        "SpecificationCurveBundle",
    ),
    "StrategicResponseChannel": (
        "polisyos.ir.observation.contracts",
        "StrategicResponseChannel",
    ),
    "RegimeCalendar": ("polisyos.ir.observation.measurement", "RegimeCalendar"),
    "SchemaChangepoint": ("polisyos.ir.observation.measurement", "SchemaChangepoint"),
    "SchemaRegimeRegistry": ("polisyos.ir.observation.measurement", "SchemaRegimeRegistry"),
    "SchemaRegimeSpec": ("polisyos.ir.observation.measurement", "SchemaRegimeSpec"),
    "ShockCalendar": ("polisyos.ir.observation.measurement", "ShockCalendar"),
    "StrategicResponseSpecsBundle": (
        "polisyos.ir.observation.bundles",
        "StrategicResponseSpecsBundle",
    ),
    "SurvivalDataBundleManifest": (
        "polisyos.ir.observation.bundles",
        "SurvivalDataBundleManifest",
    ),
}


def __getattr__(name: str) -> Any:
    """Resolve a public IR export on first access.

    Args:
        name: Facade attribute requested by user code.

    Returns:
        The lazily imported class, enum, or function bound to ``name``.

    Raises:
        AttributeError: If ``name`` is not part of the stable facade surface.
    """
    if name in _LAZY_IMPORTS:
        module_name, attr = _LAZY_IMPORTS[name]
        module = importlib.import_module(module_name)
        value = getattr(module, attr)
        globals()[name] = value
        return value
    raise AttributeError(f"module 'polisyos.ir' has no attribute '{name}'")


def __dir__() -> list[str]:
    """Return eager globals plus lazily exported contract names."""
    return sorted(list(globals().keys()) + list(_LAZY_IMPORTS.keys()))
