from pathlib import Path
base=Path('policy-engine/docs/research/e02-cloud-test-plan/closure-decisions')
def replace(p,old,new):
 s=p.read_text();assert old in s or new in s,(p,old[:80]);p.write_text(s.replace(old,new))
f=base/'F.md'
replace(f,'continuation-transfer-20261006/REPORT.md','continuation-transfer-20261007/REPORT.md')
replace(f,'Сверка использует полный independent `original35-reconciliation.json` (235804 bytes, SHA-256 `95f728b758fde25591b0124bc0a2cd8b6c0acd86a61deb6d13bc07e99c4ba2a7`) и его selection/Markdown.', 'Сверка 2026-10-07 использует полный independent `original35-independent-review-final.json` (986045 bytes, SHA-256 `62a3de177f603b7daceb61d3024c21d6a5e2eb5013d92a303b38643228c4e0a5`), полный TSV и original blocks. Прежний independent235804 packet сохранён как исторический basis.')
replace(f,'Рекомендации F различают technical original criterion и current continuation: **30 closed / 4 limited / 1 held** против **25 closed / 9 limited / 1 held**; измеренные checks **33 PASS / 2 UNRUN**.', 'Рекомендация по исходным bounded criteria после independent original-card reconciliation: **33 closed / 2 limited** (B214 и B56), отдельные checks **34 PASS / 1 UNRUN** (B56). Это решения F по каждой исходной норме, а не закрытие G. ROOT072 recommendations **25/9/1**, technical **30/4/1**, checks **33/2** сохранены исторически; прежние authority/optimizer расширения не подменяют исходный criterion.')
rows={
'B207':('limited | DID; original finite scientific criterion closed, admitted production sampling/authority отдельно. |','closed | DID; fixed selected target/share IF established на known DGP; production assumptions/authority отдельно. |'),
'B208':('limited | DID; 160-DGP witness, endpoints/nextafter controls; не simultaneous/small-G guarantee. |','closed | DID; 160-DGP witness, endpoints/nextafter controls; не simultaneous/small-G guarantee. |'),
'B209':('limited | DID; support failure не меняет target; реальное anticipation assumption не установлено. |','closed | DID; support failure не меняет target; реальное anticipation assumption не установлено. |'),
'B212':('Point-only backend без изготовленного CI; limited','Point-only backend без изготовленного CI; closed'),
'B213':('Actual estimand/contrast/target binding; limited','Actual estimand/contrast/target binding; closed'),
'B214':('STATIC518 + intake632; default normalizes known reverse; Scientist node canonical DAG profile, не all PAG/CPDAG types.','STATIC518 + intake647; current CAS content/composition basis перепроверяется, reverse normalized, unresolved/temporal inputs refuse. Sound partial/conditional extension capability остаётся limited.'),
'B218':('Lag/self-lag representation/export и static refusal; limited | SCM6d + STATIC518/intake632;','Lag/self-lag representation/export и static refusal; closed | SCM6d + STATIC518/intake647;'),
'LA-017':('Norm diff/issues/pass config/report/topic consumer migration; limited | Lex00a6 finite plan/duplicate/CAS/CLI property; full supported migration packet distinct from real-law authority.','Norm diff/issues/pass config/report/topic consumer migration; closed | Lex00a6 actual four norm-diff states/issues/pass/report/CAS/CLI and supported relocation; current-law authority отдельно UNRUN.'),
'LA-035':('Named normalized-income/budget historical baseline; held | ECO412 check15 owner packet; formula/aliases/native/JIT/grad/guards pass. Named optimizer and units/population/time/sign intent absent.','Equivalent normalized-income/budget historical baseline relocation; closed | ECO532/412 + new193; actual GlobalState formula/aliases/native guards/JIT/gradient/callers match original. New optimizer/normative objective не prerequisite unchanged relocation.')}
s=f.read_text()
for id,pair in rows.items():
 old,new=pair; lines=s.splitlines();matches=[i for i,x in enumerate(lines) if x.startswith('| '+id+' |')];assert len(matches)==1,id;i=matches[0];assert old in lines[i],(id,old);lines[i]=lines[i].replace(old,new);s='\n'.join(lines)+'\n'
f.write_text(s)
replace(f,'LA-004 closed finite inequivalence; LA-035 held intent, not a common Gini hold.','LA-004 finite inequivalence и LA-035 equivalent historical relocation recommended closed; signed active Gini отдельно typed-refuses на actual C/PPO route.')
replace(f,'Topic similarity not causal effect; finite migration residual not identical to absent legal authority.','Supported equivalent relocation closed; topic similarity не causal effect, current-law authority отдельно UNRUN.')
replace(f,'distinct models/current metric/optimizer intent.','distinct models/current metric/historical objective identity. Shared intake second escape расширен на полный composition basis и fresh query cache, а не только status/graph equality.')
m=base/'method-decisions.md'
replace(m,'Latest broker/study и native report-consumer continuation packets pending; не выдавать новую функцию или unreviewed receipt за accepted closure.', 'Actual native TMLE persisted report → fresh ConfidencePass/value consumer выполнен на source0c/8d: 53 cases плюс independent mixed-reference controls. SUCCESS/CI сохраняются, causal blocker остаётся при missing/corrupt sibling simulation CAS. Genuine admitted shared-study workload/budget всё ещё UNRUN; consumer proof его не заменяет.')
replace(m,'Original finite iid/large-independent-unit scientific discriminator established; current continuation remains limited for admitted production assumptions/authority.', 'Original finite iid/large-independent-unit scientific discriminator recommended closed. Admitted production assumptions/authority остаются отдельным downstream contract, не новым исходным criterion.')
replace(m,'latest assembled confidence/native TMLE report continuation pending, not a new423 backend run.', 'source8236 wheel/rebuilt-sdist consumers реально исполнены; new0c/8d TMLE persisted ConfidencePass witness выполнен отдельно, не новый423 backend run.')
replace(m,'Source423 finite original scientific criterion measured; current whole consumer/real identification/Runtime evaluator/appointment/fresh challenge remains limited/UNRUN separately.', 'Source423 finite original criteria B212/B213 recommended closed. Whole Runtime-admitted Node и real identification/evaluator/appointment/fresh challenge остаются отдельными UNRUN contracts.')
replace(m,'Latest supported filename/loader/docs/installed API packet pending separately, no invented all-external-user prerequisite.', 'API90c supported filename/loader/docs/installed packet на source8236 исполнен. API605 reconciles nine later carrier commits: causal_graph.py AST equivalent, canonical internal contract retained; new2case consumer and2removal controls выполнены. Unknown computed/external callers не actual clients и не invented closure prerequisite.')
replace(m,'B214/B218 current limited; no invented dynamic estimator prerequisite to the original storage property, no identification from serialization.', 'B218 original lag/self-lag representation/export/static-refusal criterion recommended closed. B214 remains limited for explicit sound partial/conditional extension capability. Intake647 validates current selected CAS/composition bodies and preserves known endpoints; unresolved marks/compact lag typed-refuse before static persistence. Serialization не identification.')
replace(m,'Original whole LA-003 remains **limited** because actual decimal .10 fiscal budget precision gives1000.0000149011612 vs1000 in broader97; tolerance/law not altered to hide it.', 'Historical decimal .10 escape1000.0000149011612 vs1000 corrected FISCAL132 by incoming-state dtype at actual ParamDecimal/compiler/CAS consumer. Original bounded relocation recommended closed; 24defaultfloat32 profiles byte-identical, separate40lower/int/x64 profiles disclose dtype/reduction differences. ABM diagnostic FAIL и P41 not_established сохраняются, law/tolerance не изменены для сокрытия результата.')
replace(m,'### F-M14 — LA-004 distinct models; LA-035 historical baseline and intent','### F-M14 — LA-004 distinct models; LA-035 equivalent historical baseline')
replace(m,'**LA-035 remains held.** Original `-mean(income)/max(mean(abs(income)),1)+10·budget_penalty`, min_balance−1000, all population entries, aliases/nativeGlobalState/JIT/grad/numeric guards preserved. Nonnegative mean≥1 remains exactly−1 at every scale; not silently income maximization. Named optimizer/source-config/FQN caller and semantic units/population/time/sign intent are not established. Minimum owner packet in ECO check15 `author/economic-owner-packet.json`; no new welfare convention or interpretation is invented.', '**LA-035 original equivalent relocation, recommended closed.** Original `-mean(income)/max(mean(abs(income)),1)+10·budget_penalty`, min_balance−1000, all population entries, aliases/nativeGlobalState/JIT/grad/numeric guards preserved. Positive income≥1 remains exactly−1 at every scale; это normalized historical baseline, не raw-income maximization. ECO193 actual state/guard/JIT/gradient/literal caller tests: author83PASS, independent28+55PASS, 64Fraction evaluations/2analytic gradients and actual sign/guard removals FAIL. Existing formula unchanged; new optimizer or normative welfare packet не требуется исходной карточкой. New ranking/objective intent, если будет запрошен, требует отдельного owner decision/version. ROOT072 hold сохранён исторически.')
replace(m,'Known pairwise scale/zero-resource/JIT/registeredconsumer/removal proofs do not close LA-035 intent or LA-003 fiscal precision.', 'New193 actual EconomicsTrainingAdapter→actor/temporal consumption→registered labor/tax/transfers/savings→active signed wealth проверен: eager bridge и requested JIT PPO metrics refuse classical Gini before aggregate/API; nonnegative active population positive. Plain trajectory without requested Gini may retain signed wealth. Это отдельная property, не новый ID, welfare convention или замена historical LA-035.')
replace(m,'Actual ExprAST, config/report identity and duplicate first occurrence property measured; full supported caller/config/corpus migration reconciliation remains limited, not completed by dedupe alone.', 'Actual ExprAST, config/report identity, all four native norm-diff states, issue keys/pass configuration, persisted reports/refs and supported CLI/CAS relocation measured; original bounded migration recommended closed. Dedupe alone не является основанием этого решения; current-law authoritative conclusion остаётся отдельным local-only packet.')
replace(m,'**Current pending.** New API generic supported-export/annotation guard and source/loader/docs/install owner packets require their own frozen review/receipt. Do not adopt an uncommitted source or an independent BLOCK as current PASS; 182 computed candidates are inputs to classify, not proof that every expression or hypothetical external client is supported.', '**Current measured.** API90c/source8236 actual wheel and rebuilt-sdist consumers each199PASS, full3459files/site and seven resources bound, no missing/extra sources. API605 reconciliation of3dde vs8236 selects identical producer/reader AST with two formatting-only hunks, test-only property2PASS and2removalFAIL per retained installed profile. New assembled source has its own affected installed wave. 225dynamic candidates/38UNKNOWN static exports remain classification limits, not actual client counts or universal external zero.')
r=base/'runtime-profiles.md'
replace(r,'Pending new API/TMLE/assembled admission не выдаются за accepted runtime.', 'Source8236 installed evidence и new API605/FIT0c/ECO193/graph647 deltas имеют отдельные receipts. Assembled source проверяется отдельно; ни один installation/check не выдаётся за accepted Runtime/scientific authority.')
replace(r,'latest composed worker confidence/native TMLE wave pending.', 'source8236 installed consumer wave реально выполнена; new native0c/8d report→fresh ConfidencePass proof выполнен отдельно. Assembled affected wave имеет собственный exact source.')
replace(r,'Latest B56 common study/broker resource and native report-consumer continuation remains pending.', 'B56 admitted common study/resource workload остаётся UNRUN; new native0c/8d persisted TMLE report→ConfidencePass/value consumer proof выполнен и сохраняет causal blocker при missing/corrupt sibling CAS. Value consumer refuses missing upstream output-contract declaration; genuine statistical admission positive не заявляется.')
replace(r,'LA-003 decimal fiscal precision limited and LA-035 named optimizer/intent held.', 'FISCAL132 closes bounded LA-003 actual decimal/CAS precision with declared x64 boundary; LA-035 original unchanged normalized baseline relocation recommended closed on ECO193 state/guard/JIT/gradient/caller proof. No new optimizer/normative review prerequisite. Requested Gini on actual signed C/PPO wealth typed-refuses; signed trajectory without Gini remains supported.')
print('Updated only current F.md, F-M sections, F runtime text; historical carriers unchanged.')
