"""Catalog domain scaffolding for Data Forge."""

from __future__ import annotations

from .assets import (
    CATALOG_ASSET_GROUP,
    CATALOG_INDEX_KEY,
    CATALOG_NORMALIZED_DATASETS_KEY,
    CATALOG_OBSERVATIONS_KEY,
    CATALOG_RAW_SOURCES_KEY,
    CATALOG_READINESS_KEY,
    CATALOG_SOURCE_MODULES_KEY,
    CATALOG_SOURCE_PREFLIGHT_KEY,
)
from .quality import (
    CatalogBenchmarkReport,
    CatalogQCReport,
    CatalogReadinessPackage,
    load_catalog_benchmark_report,
    load_catalog_qc_report,
    load_catalog_readiness_package,
)
from .registry import (
    CatalogSourceRegistryEntry,
    CatalogSourceRegistrySpec,
    catalog_source_modules_from_registry,
    default_catalog_source_registry_path,
    load_catalog_source_registry,
)
from .schemas import (
    CATALOG_BASE_SCHEMA_CONTRACTS,
    CATALOG_BASE_SCHEMA_IDS,
    CATALOG_SCHEMA_CONTRACTS,
    CATALOG_SOURCE_SCHEMA_CONTRACTS,
    build_catalog_schema_registry,
)
from .shadow import (
    CatalogReadinessSummary,
    CatalogShadowArtifact,
    CatalogShadowBundle,
    CatalogShadowDiff,
    CatalogSourceSummary,
    CatalogStageManifest,
    compare_catalog_shadow_bundles,
    load_catalog_shadow_bundle,
)
from .source_modules import (
    CORE_CATALOG_SOURCE_MODULES,
    CatalogExecutionTier,
    CatalogHistoryPolicy,
    CatalogRunLane,
    CatalogRunProfile,
    CatalogSourceAssetKeys,
    CatalogSourceModulePlan,
    CatalogSourceModuleSpec,
    CatalogSourceStage,
    CatalogSourceStageContract,
    build_catalog_source_asset_group,
    plan_catalog_source_modules,
    plan_catalog_source_stage_contracts,
    select_catalog_source_modules,
)

__all__ = [
    "CATALOG_ASSET_GROUP",
    "CATALOG_BASE_SCHEMA_CONTRACTS",
    "CATALOG_BASE_SCHEMA_IDS",
    "CATALOG_INDEX_KEY",
    "CATALOG_NORMALIZED_DATASETS_KEY",
    "CATALOG_OBSERVATIONS_KEY",
    "CATALOG_RAW_SOURCES_KEY",
    "CATALOG_READINESS_KEY",
    "CATALOG_SCHEMA_CONTRACTS",
    "CATALOG_SOURCE_MODULES_KEY",
    "CATALOG_SOURCE_PREFLIGHT_KEY",
    "CATALOG_SOURCE_SCHEMA_CONTRACTS",
    "CORE_CATALOG_SOURCE_MODULES",
    "CatalogBenchmarkReport",
    "CatalogExecutionTier",
    "CatalogHistoryPolicy",
    "CatalogQCReport",
    "CatalogReadinessPackage",
    "CatalogReadinessSummary",
    "CatalogRunLane",
    "CatalogRunProfile",
    "CatalogShadowArtifact",
    "CatalogShadowBundle",
    "CatalogShadowDiff",
    "CatalogSourceAssetKeys",
    "CatalogSourceModulePlan",
    "CatalogSourceModuleSpec",
    "CatalogSourceRegistryEntry",
    "CatalogSourceRegistrySpec",
    "CatalogSourceStage",
    "CatalogSourceStageContract",
    "CatalogSourceSummary",
    "CatalogStageManifest",
    "build_catalog_schema_registry",
    "build_catalog_source_asset_group",
    "catalog_source_modules_from_registry",
    "compare_catalog_shadow_bundles",
    "default_catalog_source_registry_path",
    "load_catalog_benchmark_report",
    "load_catalog_qc_report",
    "load_catalog_readiness_package",
    "load_catalog_shadow_bundle",
    "load_catalog_source_registry",
    "plan_catalog_source_modules",
    "plan_catalog_source_stage_contracts",
    "select_catalog_source_modules",
]
