from __future__ import annotations

from collections.abc import Iterable
from dataclasses import dataclass
from enum import Enum


class Priority(str, Enum):
    P0 = "p0"
    P1 = "p1"
    P2 = "p2"


class CompatMode(str, Enum):
    STRICT = "strict"
    TOLERANT = "tolerant"


class Lifecycle(str, Enum):
    ACTIVE = "active"
    DEPRECATED = "deprecated"


@dataclass(frozen=True)
class ABIModelEntry:
    abi_key: str
    fqn: str
    module: str
    schema_file: str
    priority: Priority
    compat_mode: CompatMode = CompatMode.STRICT
    version_field: str | None = "schema_version"
    lifecycle: Lifecycle = Lifecycle.ACTIVE
    aliases: tuple[str, ...] = ()
    allow_missing: bool = False


IR_ABI_MODELS: tuple[ABIModelEntry, ...] = (
    ABIModelEntry(
        abi_key="trinity_bundle",
        fqn="polisyos.ir.trinity.TrinityBundle",
        module="ir",
        schema_file="trinity_bundle.schema.json",
        priority=Priority.P0,
    ),
    ABIModelEntry(
        abi_key="problem_frame",
        fqn="polisyos.ir.governance.problem_frame.ProblemFrame",
        module="ir",
        schema_file="problem_frame.schema.json",
        priority=Priority.P0,
    ),
    ABIModelEntry(
        abi_key="policy_spec",
        fqn="polisyos.ir.governance.policy_spec.PolicySpec",
        module="ir",
        schema_file="policy_spec.schema.json",
        priority=Priority.P0,
    ),
    ABIModelEntry(
        abi_key="policy_portfolio",
        fqn="polisyos.ir.loading.portfolio.PolicyPortfolio",
        module="ir",
        schema_file="policy_portfolio.schema.json",
        priority=Priority.P0,
    ),
    ABIModelEntry(
        abi_key="model_spec",
        fqn="polisyos.ir.model_layer.model_spec.ModelSpec",
        module="ir",
        schema_file="model_spec.schema.json",
        priority=Priority.P0,
    ),
    ABIModelEntry(
        abi_key="norm_pack",
        fqn="polisyos.ir.loading.norm_pack.NormPack",
        module="ir",
        schema_file="norm_pack.schema.json",
        priority=Priority.P0,
    ),
    ABIModelEntry(
        abi_key="norm_rule",
        fqn="polisyos.ir.loading.norm_pack.NormRule",
        module="ir",
        schema_file="norm_rule.schema.json",
        priority=Priority.P0,
    ),
    ABIModelEntry(
        abi_key="norm_ref",
        fqn="polisyos.ir.loading.norm_pack.NormRef",
        module="ir",
        schema_file="norm_ref.schema.json",
        priority=Priority.P0,
    ),
    ABIModelEntry(
        abi_key="claim",
        fqn="polisyos.ir.world.claim.Claim",
        module="ir",
        schema_file="claim.schema.json",
        priority=Priority.P0,
    ),
    ABIModelEntry(
        abi_key="conflict_set",
        fqn="polisyos.ir.world.conflict.ConflictSet",
        module="ir",
        schema_file="conflict_set.schema.json",
        priority=Priority.P0,
    ),
    ABIModelEntry(
        abi_key="conflict_set_resolution",
        fqn="polisyos.ir.world.conflict.ConflictSetResolution",
        module="ir",
        schema_file="conflict_set_resolution.schema.json",
        priority=Priority.P0,
    ),
    ABIModelEntry(
        abi_key="conflict_resolution",
        fqn="polisyos.ir.world.conflict.ConflictResolution",
        module="ir",
        schema_file="conflict_resolution.schema.json",
        priority=Priority.P0,
    ),
    ABIModelEntry(
        abi_key="world_event",
        fqn="polisyos.ir.world.event.WorldEvent",
        module="ir",
        schema_file="world_event.schema.json",
        priority=Priority.P0,
    ),
    ABIModelEntry(
        abi_key="prov_activity",
        fqn="polisyos.ir.world.event.ProvActivity",
        module="ir",
        schema_file="prov_activity.schema.json",
        priority=Priority.P0,
    ),
    ABIModelEntry(
        abi_key="doc_fragment",
        fqn="polisyos.ir.world.doc.DocFragment",
        module="ir",
        schema_file="doc_fragment.schema.json",
        priority=Priority.P1,
    ),
    ABIModelEntry(
        abi_key="doc_meta",
        fqn="polisyos.ir.world.doc.DocMeta",
        module="ir",
        schema_file="doc_meta.schema.json",
        priority=Priority.P1,
    ),
    ABIModelEntry(
        abi_key="trust_assessment",
        fqn="polisyos.ir.world.trust.TrustAssessment",
        module="ir",
        schema_file="trust_assessment.schema.json",
        priority=Priority.P1,
    ),
    ABIModelEntry(
        abi_key="quality_report",
        fqn="polisyos.ir.world.quality.QualityReport",
        module="ir",
        schema_file="quality_report.schema.json",
        priority=Priority.P1,
    ),
    ABIModelEntry(
        abi_key="uncertainty_envelope",
        fqn="polisyos.ir.analytics.uncertainty.UncertaintyEnvelope",
        module="ir",
        schema_file="uncertainty_envelope.schema.json",
        priority=Priority.P1,
    ),
    ABIModelEntry(
        abi_key="causal_effect_report",
        fqn="polisyos.ir.analytics.causal.CausalEffectReport",
        module="ir",
        schema_file="causal_effect_report.schema.json",
        priority=Priority.P1,
    ),
    ABIModelEntry(
        abi_key="abm_alignment_report",
        fqn="polisyos.ir.analytics.abm_bridge.ABMAlignmentReport",
        module="ir",
        schema_file="abm_alignment_report.schema.json",
        priority=Priority.P1,
    ),
    ABIModelEntry(
        abi_key="abm_result",
        fqn="polisyos.ir.analytics.phase4_dynamics.ABMResult",
        module="ir",
        schema_file="abm_result.schema.json",
        priority=Priority.P1,
    ),
    ABIModelEntry(
        abi_key="transportability_result",
        fqn="polisyos.ir.analytics.transportability.TransportabilityResult",
        module="ir",
        schema_file="transportability_result.schema.json",
        priority=Priority.P1,
    ),
    ABIModelEntry(
        abi_key="refutation_result",
        fqn="polisyos.ir.analytics.causal.RefutationResult",
        module="ir",
        schema_file="refutation_result.schema.json",
        priority=Priority.P1,
    ),
    ABIModelEntry(
        abi_key="causal_graph_model",
        fqn="polisyos.ir.analytics.causal_graph.CausalGraphModel",
        module="ir",
        schema_file="causal_graph_model.schema.json",
        priority=Priority.P1,
    ),
    ABIModelEntry(
        abi_key="structural_causal_model_spec",
        fqn="polisyos.ir.analytics.structural_causal_model.StructuralCausalModelSpec",
        module="ir",
        schema_file="structural_causal_model_spec.schema.json",
        priority=Priority.P1,
    ),
    ABIModelEntry(
        abi_key="causal_query_result",
        fqn="polisyos.ir.analytics.causal_queries.CausalQueryResult",
        module="ir",
        schema_file="causal_query_result.schema.json",
        priority=Priority.P1,
    ),
    ABIModelEntry(
        abi_key="causal_discovery_report",
        fqn="polisyos.ir.analytics.causal_discovery.CausalDiscoveryReport",
        module="ir",
        schema_file="causal_discovery_report.schema.json",
        priority=Priority.P1,
    ),
    ABIModelEntry(
        abi_key="causal_model_ensemble",
        fqn="polisyos.ir.analytics.causal_ensemble.CausalModelEnsemble",
        module="ir",
        schema_file="causal_model_ensemble.schema.json",
        priority=Priority.P1,
    ),
    ABIModelEntry(
        abi_key="causal_sensitivity_result",
        fqn="polisyos.ir.analytics.sensitivity.SensitivityResult",
        module="ir",
        schema_file="sensitivity_result.schema.json",
        priority=Priority.P1,
    ),
    ABIModelEntry(
        abi_key="distributional_report",
        fqn="polisyos.ir.analytics.distributional.DistributionalReport",
        module="ir",
        schema_file="distributional_report.schema.json",
        priority=Priority.P1,
    ),
    ABIModelEntry(
        abi_key="metric_validation_report",
        fqn="polisyos.ir.analytics.metric_validation_report.MetricValidationReport",
        module="ir",
        schema_file="metric_validation_report.schema.json",
        priority=Priority.P1,
    ),
    ABIModelEntry(
        abi_key="forecasting_uncertainty_bundle",
        fqn="polisyos.ir.analytics.forecasting_uncertainty.ForecastingUncertaintyBundle",
        module="ir",
        schema_file="forecasting_uncertainty_bundle.schema.json",
        priority=Priority.P1,
    ),
    ABIModelEntry(
        abi_key="regime_shift_forecast_bundle",
        fqn="polisyos.ir.analytics.regime_shift_forecast.RegimeShiftForecastBundle",
        module="ir",
        schema_file="regime_shift_forecast_bundle.schema.json",
        priority=Priority.P1,
    ),
    ABIModelEntry(
        abi_key="phase4_temporal_policy_gate_verdict",
        fqn="polisyos.ir.analytics.phase4_dynamics.Phase4TemporalPolicyGateVerdict",
        module="ir",
        schema_file="phase4_temporal_policy_gate_verdict.schema.json",
        priority=Priority.P1,
    ),
    ABIModelEntry(
        abi_key="dynamic_microsim_validation_report",
        fqn="polisyos.ir.analytics.phase4_dynamics.DynamicMicrosimValidationReport",
        module="ir",
        schema_file="dynamic_microsim_validation_report.schema.json",
        priority=Priority.P1,
    ),
    ABIModelEntry(
        abi_key="temporal_graph_causal_certificate",
        fqn="polisyos.ir.analytics.phase4_dynamics.TemporalGraphCausalCertificate",
        module="ir",
        schema_file="temporal_graph_causal_certificate.schema.json",
        priority=Priority.P1,
    ),
    ABIModelEntry(
        abi_key="space_time_causal_certificate",
        fqn="polisyos.ir.analytics.phase4_dynamics.SpaceTimeCausalCertificate",
        module="ir",
        schema_file="space_time_causal_certificate.schema.json",
        priority=Priority.P1,
    ),
    ABIModelEntry(
        abi_key="hte_result",
        fqn="polisyos.ir.analytics.hte.HTEResult",
        module="ir",
        schema_file="hte_result.schema.json",
        priority=Priority.P1,
    ),
    ABIModelEntry(
        abi_key="policy_recommendation",
        fqn="polisyos.ir.analytics.hte.PolicyRecommendation",
        module="ir",
        schema_file="policy_recommendation.schema.json",
        priority=Priority.P1,
    ),
    ABIModelEntry(
        abi_key="backtest_report",
        fqn="polisyos.ir.analytics.backtest.BacktestReport",
        module="ir",
        schema_file="backtest_report.schema.json",
        priority=Priority.P1,
    ),
    ABIModelEntry(
        abi_key="fact",
        fqn="polisyos.ir.loading.fact_log.Fact",
        module="ir",
        schema_file="fact.schema.json",
        priority=Priority.P0,
    ),
    ABIModelEntry(
        abi_key="fact_segment_manifest",
        fqn="polisyos.ir.loading.fact_log.FactSegmentManifest",
        module="ir",
        schema_file="fact_segment_manifest.schema.json",
        priority=Priority.P0,
    ),
    ABIModelEntry(
        abi_key="calibration_config",
        fqn="polisyos.ir.analytics.calibration.CalibrationConfig",
        module="ir",
        schema_file="calibration_config.schema.json",
        priority=Priority.P2,
    ),
    ABIModelEntry(
        abi_key="data_view_request",
        fqn="polisyos.ir.analytics.data_views.DataViewRequest",
        module="ir",
        schema_file="data_view_request.schema.json",
        priority=Priority.P2,
        version_field=None,
    ),
    ABIModelEntry(
        abi_key="article_extraction_result",
        fqn="polisyos.ir.analytics.literature.ArticleExtractionResult",
        module="ir",
        schema_file="article_extraction_result.schema.json",
        priority=Priority.P2,
    ),
    ABIModelEntry(
        abi_key="literature_causal_prior",
        fqn="polisyos.ir.analytics.literature.LiteratureCausalPrior",
        module="ir",
        schema_file="literature_causal_prior.schema.json",
        priority=Priority.P2,
    ),
    ABIModelEntry(
        abi_key="context_adaptive_parameter_bundle",
        fqn="polisyos.ir.analytics.parameters.ContextAdaptiveParameterBundle",
        module="ir",
        schema_file="context_adaptive_parameter_bundle.schema.json",
        priority=Priority.P2,
    ),
    ABIModelEntry(
        abi_key="causal_query",
        fqn="polisyos.ir.analytics.causal_queries.CausalQuery",
        module="ir",
        schema_file="causal_query.schema.json",
        priority=Priority.P2,
    ),
    ABIModelEntry(
        abi_key="gate_context",
        fqn="polisyos.ir.governance.gate.GateContext",
        module="ir",
        schema_file="gate_context.schema.json",
        priority=Priority.P1,
    ),
    ABIModelEntry(
        abi_key="gate_request",
        fqn="polisyos.ir.governance.gate.GateRequest",
        module="ir",
        schema_file="gate_request.schema.json",
        priority=Priority.P1,
    ),
    ABIModelEntry(
        abi_key="gate_decision",
        fqn="polisyos.ir.governance.gate.GateDecision",
        module="ir",
        schema_file="gate_decision.schema.json",
        priority=Priority.P1,
    ),
    ABIModelEntry(
        abi_key="gate_event",
        fqn="polisyos.ir.governance.gate.GateEvent",
        module="ir",
        schema_file="gate_event.schema.json",
        priority=Priority.P1,
    ),
    ABIModelEntry(
        abi_key="partial_identification_result",
        fqn="polisyos.ir.analytics.partial_identification.PartialIdentificationResult",
        module="ir",
        schema_file="partial_identification_result.schema.json",
        priority=Priority.P2,
    ),
    ABIModelEntry(
        abi_key="intervention_cost_manifold",
        fqn="polisyos.ir.analytics.recourse_manifold.InterventionCostManifold",
        module="ir",
        schema_file="intervention_cost_manifold.schema.json",
        priority=Priority.P2,
    ),
    ABIModelEntry(
        abi_key="optimal_recourse_intervention_query",
        fqn="polisyos.ir.analytics.recourse_manifold.OptimalRecourseInterventionQuery",
        module="ir",
        schema_file="optimal_recourse_intervention_query.schema.json",
        priority=Priority.P2,
    ),
    ABIModelEntry(
        abi_key="recourse_proof_bundle",
        fqn="polisyos.ir.analytics.recourse_manifold.RecourseProofBundle",
        module="ir",
        schema_file="recourse_proof_bundle.schema.json",
        priority=Priority.P2,
    ),
    ABIModelEntry(
        abi_key="recourse_feasibility_certificate",
        fqn="polisyos.ir.analytics.recourse_manifold.RecourseFeasibilityCertificate",
        module="ir",
        schema_file="recourse_feasibility_certificate.schema.json",
        priority=Priority.P2,
    ),
    ABIModelEntry(
        abi_key="optimal_recourse_intervention_bundle",
        fqn="polisyos.ir.analytics.recourse_manifold.OptimalRecourseInterventionBundle",
        module="ir",
        schema_file="optimal_recourse_intervention_bundle.schema.json",
        priority=Priority.P2,
    ),
    ABIModelEntry(
        abi_key="certification_result",
        fqn="polisyos.ir.analytics.alignment_certification.CertificationResult",
        module="ir",
        schema_file="certification_result.schema.json",
        priority=Priority.P2,
        version_field=None,
    ),
    ABIModelEntry(
        abi_key="outer_search_result",
        fqn="polisyos.ir.analytics.alignment_certification.OuterSearchResult",
        module="ir",
        schema_file="outer_search_result.schema.json",
        priority=Priority.P2,
        version_field=None,
    ),
    ABIModelEntry(
        abi_key="observation_record",
        fqn="polisyos.ir.observation.contracts.ObservationRecord",
        module="ir",
        schema_file="observation_record.schema.json",
        priority=Priority.P1,
    ),
    ABIModelEntry(
        abi_key="observation_panel",
        fqn="polisyos.ir.observation.contracts.ObservationPanel",
        module="ir",
        schema_file="observation_panel.schema.json",
        priority=Priority.P1,
    ),
    ABIModelEntry(
        abi_key="observation_family",
        fqn="polisyos.ir.observation.contracts.ObservationFamily",
        module="ir",
        schema_file="observation_family.schema.json",
        priority=Priority.P2,
        version_field=None,
    ),
    ABIModelEntry(
        abi_key="entity_scope",
        fqn="polisyos.ir.observation.contracts.EntityScope",
        module="ir",
        schema_file="entity_scope.schema.json",
        priority=Priority.P2,
        version_field=None,
    ),
    ABIModelEntry(
        abi_key="identification_mode",
        fqn="polisyos.ir.observation.contracts.IdentificationMode",
        module="ir",
        schema_file="identification_mode.schema.json",
        priority=Priority.P1,
        version_field=None,
    ),
    ABIModelEntry(
        abi_key="source_confidence_tier",
        fqn="polisyos.ir.observation.contracts.SourceConfidenceTier",
        module="ir",
        schema_file="source_confidence_tier.schema.json",
        priority=Priority.P2,
        version_field=None,
    ),
    ABIModelEntry(
        abi_key="multiplex_graph_layer_id",
        fqn="polisyos.ir.observation.contracts.MultiplexGraphLayerId",
        module="ir",
        schema_file="multiplex_graph_layer_id.schema.json",
        priority=Priority.P2,
        version_field=None,
    ),
    ABIModelEntry(
        abi_key="strategic_response_channel",
        fqn="polisyos.ir.observation.contracts.StrategicResponseChannel",
        module="ir",
        schema_file="strategic_response_channel.schema.json",
        priority=Priority.P2,
        version_field=None,
    ),
    ABIModelEntry(
        abi_key="governance_pass_alias_status",
        fqn="polisyos.ir.observation.governance.GovernancePassAliasStatus",
        module="ir",
        schema_file="governance_pass_alias_status.schema.json",
        priority=Priority.P2,
        version_field=None,
    ),
    ABIModelEntry(
        abi_key="governance_pass_alias",
        fqn="polisyos.ir.observation.governance.GovernancePassAlias",
        module="ir",
        schema_file="governance_pass_alias.schema.json",
        priority=Priority.P2,
    ),
    ABIModelEntry(
        abi_key="governance_pass_alias_registry",
        fqn="polisyos.ir.observation.governance.GovernancePassAliasRegistry",
        module="ir",
        schema_file="governance_pass_alias_registry.schema.json",
        priority=Priority.P1,
    ),
    ABIModelEntry(
        abi_key="observation_family_policy",
        fqn="polisyos.ir.observation.governance.ObservationFamilyPolicy",
        module="ir",
        schema_file="observation_family_policy.schema.json",
        priority=Priority.P1,
    ),
    ABIModelEntry(
        abi_key="observation_family_policy_registry",
        fqn="polisyos.ir.observation.governance.ObservationFamilyPolicyRegistry",
        module="ir",
        schema_file="observation_family_policy_registry.schema.json",
        priority=Priority.P1,
    ),
    ABIModelEntry(
        abi_key="temporal_intervention_step",
        fqn="polisyos.ir.governance.policy_spec.TemporalInterventionStep",
        module="ir",
        schema_file="temporal_intervention_step.schema.json",
        priority=Priority.P2,
    ),
    ABIModelEntry(
        abi_key="temporal_intervention_sequence",
        fqn="polisyos.ir.governance.policy_spec.TemporalInterventionSequence",
        module="ir",
        schema_file="temporal_intervention_sequence.schema.json",
        priority=Priority.P1,
    ),
    ABIModelEntry(
        abi_key="calibration_target_bundle_manifest",
        fqn="polisyos.ir.observation.bundles.CalibrationTargetBundleManifest",
        module="ir",
        schema_file="calibration_target_bundle_manifest.schema.json",
        priority=Priority.P1,
    ),
    ABIModelEntry(
        abi_key="microsim_survey_contract_bundle",
        fqn="polisyos.ir.observation.bundles.MicrosimSurveyContractBundle",
        module="ir",
        schema_file="microsim_survey_contract_bundle.schema.json",
        priority=Priority.P2,
    ),
    ABIModelEntry(
        abi_key="network_contract_bundle",
        fqn="polisyos.ir.observation.bundles.NetworkContractBundle",
        module="ir",
        schema_file="network_contract_bundle.schema.json",
        priority=Priority.P2,
    ),
    ABIModelEntry(
        abi_key="network_causal_contract_bundle",
        fqn="polisyos.ir.observation.bundles.NetworkCausalContractBundle",
        module="ir",
        schema_file="network_causal_contract_bundle.schema.json",
        priority=Priority.P2,
    ),
    ABIModelEntry(
        abi_key="causal_panel_bundle_manifest",
        fqn="polisyos.ir.observation.bundles.CausalPanelBundleManifest",
        module="ir",
        schema_file="causal_panel_bundle_manifest.schema.json",
        priority=Priority.P2,
    ),
    ABIModelEntry(
        abi_key="backtest_plan_bundle",
        fqn="polisyos.ir.observation.bundles.BacktestPlanBundle",
        module="ir",
        schema_file="backtest_plan_bundle.schema.json",
        priority=Priority.P2,
    ),
    ABIModelEntry(
        abi_key="observation_to_contract_manifest",
        fqn="polisyos.ir.observation.bundles.ObservationToContractManifest",
        module="ir",
        schema_file="observation_to_contract_manifest.schema.json",
        priority=Priority.P1,
    ),
    ABIModelEntry(
        abi_key="bounds_estimation_bundle",
        fqn="polisyos.ir.observation.bundles.BoundsEstimationBundle",
        module="ir",
        schema_file="bounds_estimation_bundle.schema.json",
        priority=Priority.P2,
    ),
    ABIModelEntry(
        abi_key="proxy_identification_bundle",
        fqn="polisyos.ir.observation.bundles.ProxyIdentificationBundle",
        module="ir",
        schema_file="proxy_identification_bundle.schema.json",
        priority=Priority.P2,
    ),
    ABIModelEntry(
        abi_key="dtr_treatment_sequence_bundle_manifest",
        fqn="polisyos.ir.observation.bundles.DTRTreatmentSequenceBundleManifest",
        module="ir",
        schema_file="dtr_treatment_sequence_bundle_manifest.schema.json",
        priority=Priority.P2,
    ),
    ABIModelEntry(
        abi_key="panel_econometric_bundle_manifest",
        fqn="polisyos.ir.observation.bundles.PanelEconometricBundleManifest",
        module="ir",
        schema_file="panel_econometric_bundle_manifest.schema.json",
        priority=Priority.P2,
    ),
    ABIModelEntry(
        abi_key="survival_data_bundle_manifest",
        fqn="polisyos.ir.observation.bundles.SurvivalDataBundleManifest",
        module="ir",
        schema_file="survival_data_bundle_manifest.schema.json",
        priority=Priority.P2,
    ),
    ABIModelEntry(
        abi_key="specification_curve_bundle",
        fqn="polisyos.ir.observation.bundles.SpecificationCurveBundle",
        module="ir",
        schema_file="specification_curve_bundle.schema.json",
        priority=Priority.P2,
    ),
    ABIModelEntry(
        abi_key="leontief_io_bundle",
        fqn="polisyos.ir.observation.bundles.LeontiefIOBundle",
        module="ir",
        schema_file="leontief_io_bundle.schema.json",
        priority=Priority.P2,
    ),
    ABIModelEntry(
        abi_key="strategic_response_specs_bundle",
        fqn="polisyos.ir.observation.bundles.StrategicResponseSpecsBundle",
        module="ir",
        schema_file="strategic_response_specs_bundle.schema.json",
        priority=Priority.P2,
    ),
    ABIModelEntry(
        abi_key="governance_pass_mapping_bundle",
        fqn="polisyos.ir.observation.bundles.GovernancePassMappingBundle",
        module="ir",
        schema_file="governance_pass_mapping_bundle.schema.json",
        priority=Priority.P2,
    ),
    ABIModelEntry(
        abi_key="lesson_registry_seed_bundle",
        fqn="polisyos.ir.observation.bundles.LessonRegistrySeedBundle",
        module="ir",
        schema_file="lesson_registry_seed_bundle.schema.json",
        priority=Priority.P2,
    ),
    ABIModelEntry(
        abi_key="measurement_aware_target",
        fqn="polisyos.foundry.calibration.measurement.MeasurementAwareTarget",
        module="ir",
        schema_file="measurement_aware_target.schema.json",
        priority=Priority.P2,
    ),
    ABIModelEntry(
        abi_key="measurement_aware_loss_config",
        fqn="polisyos.foundry.calibration.measurement.MeasurementAwareLossConfig",
        module="ir",
        schema_file="measurement_aware_loss_config.schema.json",
        priority=Priority.P2,
    ),
    ABIModelEntry(
        abi_key="feedback_solver_config",
        fqn="polisyos.core.contracts.foundry.FeedbackSolverConfig",
        module="ir",
        schema_file="feedback_solver_config.schema.json",
        priority=Priority.P2,
    ),
    ABIModelEntry(
        abi_key="feedback_jacobian_diagnostics",
        fqn="polisyos.core.contracts.foundry.FeedbackJacobianDiagnostics",
        module="ir",
        schema_file="feedback_jacobian_diagnostics.schema.json",
        priority=Priority.P2,
    ),
    ABIModelEntry(
        abi_key="feedback_solve_result",
        fqn="polisyos.core.contracts.foundry.FeedbackSolveResult",
        module="ir",
        schema_file="feedback_solve_result.schema.json",
        priority=Priority.P2,
    ),
    ABIModelEntry(
        abi_key="equilibrium_multiplicity_report",
        fqn="polisyos.core.contracts.foundry.EquilibriumMultiplicityReport",
        module="ir",
        schema_file="equilibrium_multiplicity_report.schema.json",
        priority=Priority.P2,
    ),
)


FABRIC_ABI_MODELS: tuple[ABIModelEntry, ...] = (
    ABIModelEntry(
        abi_key="edge_kind",
        fqn="polisyos.ir.world.abi.EdgeKind",
        module="fabric",
        schema_file="edge_kind.schema.json",
        priority=Priority.P0,
        version_field=None,
    ),
    ABIModelEntry(
        abi_key="node_kind",
        fqn="polisyos.ir.world.abi.NodeKind",
        module="fabric",
        schema_file="node_kind.schema.json",
        priority=Priority.P0,
        version_field=None,
    ),
)


ABI_MODELS: tuple[ABIModelEntry, ...] = IR_ABI_MODELS + FABRIC_ABI_MODELS


def iter_abi_entries(*, include_deprecated: bool = False) -> tuple[ABIModelEntry, ...]:
    if include_deprecated:
        return ABI_MODELS
    return tuple(entry for entry in ABI_MODELS if entry.lifecycle == Lifecycle.ACTIVE)


def select_abi_entries(
    filters: Iterable[str] | None,
    *,
    include_deprecated: bool = False,
) -> tuple[ABIModelEntry, ...]:
    entries = iter_abi_entries(include_deprecated=include_deprecated)
    if not filters:
        return entries

    normalized = tuple(token.strip().lower() for token in filters if token.strip())
    if not normalized:
        return entries

    selected: list[ABIModelEntry] = []
    for entry in entries:
        tags = {
            entry.abi_key.lower(),
            entry.module.lower(),
            entry.priority.value,
            entry.fqn.lower(),
        }
        tags.update(alias.lower() for alias in entry.aliases)
        if any(token in tags for token in normalized):
            selected.append(entry)
            continue
        if any(entry.abi_key.lower().startswith(token) for token in normalized):
            selected.append(entry)

    return tuple(selected)
