from _typeshed import Incomplete
from collections.abc import Iterator, Mapping, Sequence
from dataclasses import dataclass, field
from enum import Enum
from polisyos.foundry.methods.backends.chain_executor import ExecutorMode, FxRateProvider
from polisyos.foundry.methods.base import MethodSignature
from polisyos.foundry.methods.components.linker import LinkResult, SlotBinding, SlotLinker
from polisyos.foundry.methods.selection.registry import MethodRegistry
from types import MappingProxyType
from typing import Any
from uuid import UUID

__all__ = [
    "CompiledMethodChain",
    "CompositionDAG",
    "MethodComposer",
    "MethodNode",
    "SemanticValidationLevel",
]

class SemanticValidationLevel(Enum):
    OFF: str
    WARN: str
    STRICT: str

@dataclass(frozen=True, slots=True, order=True)
class NodeKey:
    method_fqn: str
    static_params_digest: str

@dataclass(frozen=True, slots=True)
class MethodNode:
    id: UUID
    method_fqn: str
    params: Mapping[str, Any]
    static_params: Mapping[str, Any]
    node_key: NodeKey | None = ...
    instance_index: int = ...
    commutes_with: frozenset[str] = ...
    _insertion_order: int = field(default=0, compare=False, hash=False)
    def __post_init__(self) -> None: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __repr__(self) -> str: ...

@dataclass(slots=True)
class CompositionDAG:
    nodes: dict[UUID, MethodNode] = field(default_factory=dict)
    successors: dict[UUID, set[UUID]] = field(default_factory=dict)
    predecessors: dict[UUID, set[UUID]] = field(default_factory=dict)
    edges: dict[tuple[UUID, UUID], LinkResult] = field(default_factory=dict)
    _insertion_counter: int = field(default=0, repr=False)
    def add_node(self, node: MethodNode) -> None: ...
    def add_edge(self, source_id: UUID, target_id: UUID, link_result: LinkResult) -> None: ...
    def _stable_key(self, node_id: UUID) -> tuple[NodeKey, int, int]: ...
    def _sort_ready(self, ready: Sequence[UUID]) -> list[UUID]: ...
    def topological_order(
        self, extra_predecessors: Mapping[UUID, set[UUID]] | None = None
    ) -> list[UUID]: ...
    def get_roots(self) -> list[UUID]: ...
    def get_leaves(self) -> list[UUID]: ...
    def get_edge(self, source_id: UUID, target_id: UUID) -> LinkResult | None: ...
    def compute_parallel_levels(
        self, extra_predecessors: Mapping[UUID, set[UUID]] | None = None
    ) -> list[list[UUID]]: ...
    def freeze(
        self, extra_predecessors: Mapping[UUID, set[UUID]] | None = None
    ) -> FrozenCompositionDAG: ...
    def __len__(self) -> int: ...
    def __contains__(self, node_id: UUID) -> bool: ...

@dataclass(frozen=True, slots=True)
class FrozenCompositionDAG:
    nodes: Mapping[UUID, MethodNode]
    successors: Mapping[UUID, frozenset[UUID]]
    predecessors: Mapping[UUID, frozenset[UUID]]
    edges: Mapping[tuple[UUID, UUID], LinkResult]
    def get_edge(self, source_id: UUID, target_id: UUID) -> LinkResult | None: ...
    def get_roots(self) -> list[UUID]: ...
    def get_leaves(self) -> list[UUID]: ...
    def _stable_key(self, node_id: UUID) -> tuple[NodeKey, int, int]: ...
    def _sort_ready(self, ready: Sequence[UUID]) -> list[UUID]: ...
    def compute_parallel_levels(self) -> list[list[UUID]]: ...
    def __len__(self) -> int: ...
    def __contains__(self, node_id: UUID) -> bool: ...

class MethodComposer:
    _registry: Incomplete
    _linker: Incomplete
    _dag: Incomplete
    _signatures: dict[UUID, MethodSignature]
    _insertion_counter: int
    _instance_counters: dict[NodeKey, int]
    def __init__(
        self, registry: MethodRegistry | None = None, linker: SlotLinker | None = None
    ) -> None: ...
    @property
    def dag(self) -> CompositionDAG: ...
    @classmethod
    def from_nodes(
        cls,
        nodes: Sequence[MethodNode],
        *,
        registry: MethodRegistry | None = None,
        linker: SlotLinker | None = None,
    ) -> MethodComposer: ...
    def add(self, method_name: str, **params: Any) -> MethodNode: ...
    def connect(
        self, source: MethodNode, target: MethodNode, slot_mapping: Mapping[str, str] | None = None
    ) -> LinkResult: ...
    def _requirement_edges(
        self, level: SemanticValidationLevel = ...
    ) -> tuple[dict[UUID, set[UUID]], list[str]]: ...
    def validate(self, level: SemanticValidationLevel = ...) -> list[str]: ...
    def build(
        self, *, validate_semantics: SemanticValidationLevel | bool = ...
    ) -> CompiledMethodChain: ...
    def _compute_composition_cache_keys(
        self, frozen_dag: FrozenCompositionDAG, req_predecessors: dict[UUID, set[UUID]]
    ) -> MappingProxyType[UUID, str]: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...

@dataclass(frozen=True, slots=True)
class CompiledMethodChain:
    dag: FrozenCompositionDAG
    signatures: Mapping[UUID, MethodSignature]
    execution_order: tuple[UUID, ...]
    bindings: tuple[SlotBinding, ...]
    warnings: tuple[str, ...]
    cache_keys: Mapping[UUID, str] = field(default_factory=Incomplete)
    def __len__(self) -> int: ...
    def methods_in_order(self) -> Iterator[tuple[UUID, MethodSignature]]: ...
    def get_node(self, node_id: UUID) -> MethodNode: ...
    def get_signature(self, node_id: UUID) -> MethodSignature: ...
    def get_bindings_for_target(self, target_id: UUID) -> list[SlotBinding]: ...
    @property
    def has_warnings(self) -> bool: ...
    @property
    def fqn_order(self) -> list[str]: ...
    def __repr__(self) -> str: ...
    def execute_heterogeneous(
        self,
        *,
        state: Any,
        params_per_node: Mapping[UUID, Mapping[str, Any]] | None = None,
        seed: int = 0,
        registry: MethodRegistry | None = None,
        executor_mode: ExecutorMode = "sequential",
        async_node_timeout_sec: float | None = None,
        fx_rate_provider: FxRateProvider | None = None,
    ) -> Any: ...
