"""Built-in source profiles for known public data APIs."""

from .models import SourceProfile

BUILTIN_PROFILES: list[SourceProfile] = [
    # ---- Production connectors ----
    SourceProfile(
        profile_id="worldbank_wdi",
        display_name="World Bank WDI",
        description="World Development Indicators via World Bank API v2",
        connector_family="worldbank",
        base_url="https://api.worldbank.org/v2",
        auth_policy="none",
        rate_limit_rps=10.0,
        tags=["international", "development", "gdp"],
        source_organization="The World Bank Group",
        source_url="https://data.worldbank.org",
        estimated_datasets=1600,
    ),
    SourceProfile(
        profile_id="wvs_wave7",
        display_name="World Values Survey Wave 7",
        description="World Values Survey observations with wave-based temporal matching",
        connector_family="wvs",
        base_url="https://api.worldvaluessurvey.org/v1",
        auth_policy="none",
        rate_limit_rps=5.0,
        tags=["international", "survey", "values", "trust"],
        source_organization="World Values Survey Association",
        source_url="https://www.worldvaluessurvey.org",
        estimated_datasets=2,
    ),
    SourceProfile(
        profile_id="eurostat_public",
        display_name="Eurostat",
        description="Eurostat statistical office data via REST API",
        connector_family="eurostat",
        base_url="https://ec.europa.eu/eurostat/api/dissemination/statistics/1.0/data",
        auth_policy="none",
        rate_limit_rps=5.0,
        tags=["europe", "eu", "statistics"],
        source_organization="European Commission",
        source_url="https://ec.europa.eu/eurostat",
        estimated_datasets=8000,
    ),
    SourceProfile(
        profile_id="ukons_public",
        display_name="UK ONS",
        description="UK Office for National Statistics",
        connector_family="ukons",
        base_url="https://api.ons.gov.uk",
        auth_policy="none",
        tags=["uk", "statistics", "national"],
        source_organization="Office for National Statistics",
        source_url="https://www.ons.gov.uk",
        estimated_datasets=500,
    ),
    SourceProfile(
        profile_id="who_gho",
        display_name="WHO GHO",
        description="WHO Global Health Observatory indicator API",
        connector_family="who",
        base_url="https://ghoapi.azureedge.net/api",
        auth_policy="none",
        rate_limit_rps=4.0,
        tags=["who", "health", "global", "indicators"],
        source_organization="World Health Organization",
        source_url="https://www.who.int/data/gho",
        estimated_datasets=5000,
    ),
    SourceProfile(
        profile_id="unpd_dataportal",
        display_name="UNPD Data Portal",
        description="United Nations Population Division data portal API",
        connector_family="unpd",
        base_url="https://population.un.org/dataportalapi/api/v1",
        auth_policy="none",
        rate_limit_rps=3.0,
        tags=["unpd", "population", "demography", "global"],
        source_organization="United Nations Population Division",
        source_url="https://population.un.org/dataportal/",
        estimated_datasets=86,
    ),
    SourceProfile(
        profile_id="unesco_uis_public",
        display_name="UNESCO UIS",
        description="UNESCO Institute for Statistics public indicator API",
        connector_family="unesco_uis",
        base_url="https://api.uis.unesco.org/api/public",
        auth_policy="none",
        rate_limit_rps=4.0,
        tags=["unesco", "education", "statistics", "global"],
        source_organization="UNESCO Institute for Statistics",
        source_url="https://api.uis.unesco.org",
        estimated_datasets=5000,
    ),
    # ---- SDMX profiles (reference connector available) ----
    SourceProfile(
        profile_id="ecb_sdmx",
        display_name="ECB Statistical Data Warehouse",
        description="European Central Bank via SDMX REST API",
        connector_family="sdmx",
        base_url="https://data-api.ecb.europa.eu/service",
        headers={
            "X-SDMX-Agency": "ECB",
            "X-SDMX-DataPath": "data",
            "X-SDMX-DataflowPath": "dataflow",
        },
        auth_policy="none",
        rate_limit_rps=5.0,
        tags=["ecb", "monetary", "finance", "europe"],
        source_organization="European Central Bank",
        source_url="https://data.ecb.europa.eu",
        estimated_datasets=600,
    ),
    SourceProfile(
        profile_id="oecd_sdmx",
        display_name="OECD Statistics",
        description="OECD statistical data via SDMX REST API",
        connector_family="sdmx",
        base_url="https://sdmx.oecd.org/public/rest",
        headers={
            "X-SDMX-Agency": "OECD",
            "X-SDMX-DataPath": "data",
            "X-SDMX-DataflowPath": "dataflow",
            "X-SDMX-IncludeAgencyInDataPath": "false",
        },
        auth_policy="none",
        rate_limit_rps=3.0,
        tags=["oecd", "international", "development"],
        source_organization="OECD",
        source_url="https://stats.oecd.org",
        estimated_datasets=1000,
    ),
    SourceProfile(
        profile_id="imf_sdmx",
        display_name="IMF Data",
        description="International Monetary Fund via SDMX REST API",
        connector_family="sdmx",
        base_url="https://sdmxcentral.imf.org/ws/public/sdmxapi/rest",
        headers={"X-SDMX-Agency": "IMF"},
        auth_policy="none",
        tags=["imf", "monetary", "finance", "international"],
        source_organization="International Monetary Fund",
        source_url="https://data.imf.org",
        estimated_datasets=400,
    ),
    SourceProfile(
        profile_id="bis_sdmx",
        display_name="BIS Statistics",
        description="Bank for International Settlements via SDMX",
        connector_family="sdmx",
        base_url="https://stats.bis.org/api/v2",
        headers={"X-SDMX-Agency": "BIS"},
        auth_policy="none",
        tags=["bis", "banking", "finance", "international"],
        source_organization="Bank for International Settlements",
        source_url="https://www.bis.org/statistics",
        estimated_datasets=200,
    ),
    # ---- Wave 2 SDMX profiles ----
    SourceProfile(
        profile_id="ilo_sdmx",
        display_name="ILO Statistics",
        description="International Labour Organization via SDMX REST API",
        connector_family="sdmx",
        base_url="https://sdmx.ilo.org/rest",
        headers={
            "X-SDMX-Agency": "ILO",
            "X-SDMX-IncludeAgencyInDataPath": "false",
        },
        auth_policy="none",
        rate_limit_rps=3.0,
        tags=["ilo", "labour", "employment", "international"],
        source_organization="International Labour Organization",
        source_url="https://ilostat.ilo.org",
        estimated_datasets=400,
    ),
    SourceProfile(
        profile_id="fao_sdmx",
        display_name="FAO Statistics",
        description="Food and Agriculture Organization via SDMX REST API",
        connector_family="sdmx",
        base_url="https://sdmx.fao.org/ws/rest",
        headers={"X-SDMX-Agency": "FAO"},
        auth_policy="none",
        rate_limit_rps=3.0,
        tags=["fao", "agriculture", "food", "international"],
        source_organization="Food and Agriculture Organization",
        source_url="https://www.fao.org/faostat",
        estimated_datasets=300,
    ),
    SourceProfile(
        profile_id="unsd_sdmx",
        display_name="UN Statistics Division",
        description="UN Statistics Division via SDMX REST API",
        connector_family="sdmx",
        base_url="https://data.un.org/ws/rest",
        headers={"X-SDMX-Agency": "UNSD"},
        auth_policy="none",
        rate_limit_rps=2.0,
        tags=["un", "global", "development", "international"],
        source_organization="United Nations Statistics Division",
        source_url="https://data.un.org",
        estimated_datasets=600,
    ),
    # ---- CKAN profiles ----
    SourceProfile(
        profile_id="data_gov_uk",
        display_name="data.gov.uk",
        description="UK Government open data portal (CKAN)",
        connector_family="ckan",
        base_url="https://data.gov.uk",
        auth_policy="none",
        tags=["uk", "government", "open_data"],
        source_organization="UK Government",
        source_url="https://data.gov.uk",
        estimated_datasets=50000,
    ),
    SourceProfile(
        profile_id="data_gov_us",
        display_name="data.gov (US)",
        description="US Federal open data portal (CKAN)",
        connector_family="ckan",
        base_url="https://catalog.data.gov",
        auth_policy="none",
        tags=["us", "government", "federal", "open_data"],
        source_organization="US Government",
        source_url="https://data.gov",
        estimated_datasets=300000,
    ),
    SourceProfile(
        profile_id="data_gov_ua",
        display_name="data.gov.ua",
        description="Ukraine Government open data portal (CKAN)",
        connector_family="ckan",
        base_url="https://data.gov.ua",
        auth_policy="none",
        tags=["ukraine", "government", "open_data"],
        source_organization="Government of Ukraine",
        source_url="https://data.gov.ua",
        estimated_datasets=50000,
    ),
    SourceProfile(
        profile_id="data_gov_ro",
        display_name="data.gov.ro",
        description="Romania Government open data portal (CKAN)",
        connector_family="ckan",
        base_url="https://data.gov.ro",
        auth_policy="none",
        tags=["romania", "government", "open_data"],
        source_organization="Government of Romania",
        source_url="https://data.gov.ro",
        estimated_datasets=5000,
    ),
    SourceProfile(
        profile_id="data_gov_md",
        display_name="dataset.gov.md",
        description="Moldova Government open data portal (CKAN)",
        connector_family="ckan",
        base_url="https://dataset.gov.md",
        auth_policy="none",
        tags=["moldova", "government", "open_data"],
        source_organization="Government of Moldova",
        source_url="https://dataset.gov.md",
        estimated_datasets=1300,
    ),
    SourceProfile(
        profile_id="eu_open_data",
        display_name="EU Open Data Portal",
        description="European Union open data portal (CKAN)",
        connector_family="ckan",
        base_url="https://data.europa.eu/api/hub/search",
        auth_policy="none",
        tags=["eu", "europe", "government", "open_data"],
        source_organization="European Union",
        source_url="https://data.europa.eu",
        estimated_datasets=1600000,
    ),
    # ---- Socrata profiles ----
    SourceProfile(
        profile_id="nyc_opendata",
        display_name="NYC Open Data",
        description="City of New York open data portal (Socrata)",
        connector_family="socrata",
        base_url="https://data.cityofnewyork.us",
        auth_policy="none",
        rate_limit_rps=5.0,
        tags=["us", "nyc", "municipal", "open_data"],
        source_organization="City of New York",
        source_url="https://opendata.cityofnewyork.us",
        estimated_datasets=2500,
    ),
    SourceProfile(
        profile_id="chicago_opendata",
        display_name="Chicago Data Portal",
        description="City of Chicago open data portal (Socrata)",
        connector_family="socrata",
        base_url="https://data.cityofchicago.org",
        auth_policy="none",
        rate_limit_rps=5.0,
        tags=["us", "chicago", "municipal", "open_data"],
        source_organization="City of Chicago",
        source_url="https://data.cityofchicago.org",
        estimated_datasets=1200,
    ),
    # ---- Opendatasoft profiles ----
    SourceProfile(
        profile_id="opendatasoft_public",
        display_name="Opendatasoft Public",
        description="Opendatasoft public data hub (30,000+ datasets)",
        connector_family="opendatasoft",
        base_url="https://public.opendatasoft.com",
        auth_policy="none",
        rate_limit_rps=5.0,
        tags=["international", "open_data", "aggregator"],
        source_organization="Opendatasoft",
        source_url="https://public.opendatasoft.com",
        estimated_datasets=30000,
    ),
    SourceProfile(
        profile_id="paris_opendata",
        display_name="Paris Open Data",
        description="City of Paris open data portal (Opendatasoft)",
        connector_family="opendatasoft",
        base_url="https://opendata.paris.fr",
        auth_policy="none",
        rate_limit_rps=5.0,
        tags=["france", "paris", "municipal", "open_data"],
        source_organization="City of Paris",
        source_url="https://opendata.paris.fr",
        estimated_datasets=300,
    ),
    # ---- SPARQL profiles ----
    SourceProfile(
        profile_id="wikidata_sparql",
        display_name="Wikidata SPARQL",
        description="Wikidata Query Service SPARQL endpoint",
        connector_family="sparql",
        base_url="https://query.wikidata.org",
        auth_policy="none",
        rate_limit_rps=5.0,
        tags=["wikidata", "linked_data", "knowledge_graph"],
        source_organization="Wikimedia Foundation",
        source_url="https://www.wikidata.org",
        estimated_datasets=100,
    ),
    SourceProfile(
        profile_id="dbpedia_sparql",
        display_name="DBpedia SPARQL",
        description="DBpedia SPARQL endpoint for structured Wikipedia data",
        connector_family="sparql",
        base_url="https://dbpedia.org",
        auth_policy="none",
        rate_limit_rps=2.0,
        tags=["dbpedia", "linked_data", "wikipedia"],
        source_organization="DBpedia Association",
        source_url="https://www.dbpedia.org",
        estimated_datasets=50,
    ),
    # ---- REST specialized profiles (Wave 3) ----
    SourceProfile(
        profile_id="data_gov_pl",
        display_name="dane.gov.pl",
        description="Poland Government open data JSON:API catalog",
        connector_family="rest",
        base_url="https://api.dane.gov.pl/1.4/datasets",
        headers={"Accept": "application/vnd.api+json"},
        auth_policy="none",
        rate_limit_rps=5.0,
        tags=["poland", "government", "open_data"],
        source_organization="Government of Poland",
        source_url="https://dane.gov.pl",
        estimated_datasets=21000,
    ),
    SourceProfile(
        profile_id="usgs_earthquake",
        display_name="USGS Earthquake Catalog",
        description="USGS earthquake event data via REST API",
        connector_family="rest",
        base_url="https://earthquake.usgs.gov/fdsnws/event/1/query",
        headers={
            "X-REST-DataPath": "features",
            "X-REST-Pagination": "page_number",
            "X-REST-PageParam": "offset",
            "X-REST-PageSize": "100",
            "X-REST-DateStart": "starttime",
            "X-REST-DateEnd": "endtime",
        },
        auth_policy="none",
        rate_limit_rps=5.0,
        tags=["usgs", "earthquake", "geophysics", "us"],
        source_organization="US Geological Survey",
        source_url="https://earthquake.usgs.gov",
        estimated_datasets=1,
    ),
    SourceProfile(
        profile_id="openaq_v2",
        display_name="OpenAQ Air Quality",
        description="Global air quality measurements via OpenAQ v2 REST API",
        connector_family="rest",
        base_url="https://api.openaq.org/v2/measurements",
        headers={
            "X-REST-DataPath": "results",
            "X-REST-Pagination": "page_number",
            "X-REST-PageParam": "page",
            "X-REST-PageSize": "100",
            "X-REST-DateStart": "date_from",
            "X-REST-DateEnd": "date_to",
        },
        auth_policy="none",
        rate_limit_rps=5.0,
        tags=["air_quality", "environment", "global"],
        source_organization="OpenAQ",
        source_url="https://openaq.org",
        estimated_datasets=100,
    ),
    SourceProfile(
        profile_id="open_meteo",
        display_name="Open-Meteo Weather",
        description="Open-Meteo weather forecast and historical data API",
        connector_family="rest",
        base_url="https://api.open-meteo.com/v1/forecast",
        headers={
            "X-REST-DataPath": "hourly",
        },
        auth_policy="none",
        rate_limit_rps=10.0,
        tags=["weather", "forecast", "climate", "global"],
        source_organization="Open-Meteo",
        source_url="https://open-meteo.com",
        estimated_datasets=50,
    ),
    SourceProfile(
        profile_id="eia_api",
        display_name="EIA Energy Data",
        description="US Energy Information Administration data via API v2",
        connector_family="rest",
        base_url="https://api.eia.gov/v2",
        headers={
            "X-REST-DataPath": "response.data",
            "X-REST-Pagination": "page_number",
            "X-REST-PageParam": "offset",
            "X-REST-PageSize": "100",
        },
        auth_policy="api_key",
        rate_limit_rps=5.0,
        tags=["energy", "us", "government"],
        source_organization="US Energy Information Administration",
        source_url="https://www.eia.gov",
        estimated_datasets=500,
    ),
    SourceProfile(
        profile_id="nvd_cve",
        display_name="NVD Vulnerability Database",
        description="NIST National Vulnerability Database CVE API",
        connector_family="rest",
        base_url="https://services.nvd.nist.gov/rest/json/cves/2.0",
        headers={
            "X-REST-DataPath": "vulnerabilities",
            "X-REST-Pagination": "page_number",
            "X-REST-PageParam": "startIndex",
            "X-REST-PageSize": "50",
        },
        auth_policy="none",
        rate_limit_rps=3.0,
        tags=["security", "vulnerability", "cve", "us"],
        source_organization="NIST",
        source_url="https://nvd.nist.gov",
        estimated_datasets=1,
    ),
]

__all__ = ["BUILTIN_PROFILES"]
