"""Curated source contracts that pin external provider schemas to internal connector expectations."""
from __future__ import annotations

from .eurostat_contracts import (
    EUROSTAT_CONTRACTS,
    EUROSTAT_GENERIC_CONTRACT,
    EUROSTAT_GENERIC_SCHEMA,
)
from .sdmx_contracts import SDMX_CONTRACTS, SDMX_GENERIC_CONTRACT, SDMX_GENERIC_SCHEMA
from .ukons_contracts import UKONS_CONTRACTS, UKONS_GENERIC_CONTRACT, UKONS_GENERIC_SCHEMA
from .world_bank_contracts import WDI_GENERIC_CONTRACT, WDI_GENERIC_SCHEMA, WORLD_BANK_CONTRACTS
from .wvs_contracts import WVS_CONTRACTS, WVS_GENERIC_CONTRACT, WVS_GENERIC_SCHEMA

ALL_SOURCE_CONTRACTS = (
    *WORLD_BANK_CONTRACTS,
    *WVS_CONTRACTS,
    *EUROSTAT_CONTRACTS,
    *UKONS_CONTRACTS,
    *SDMX_CONTRACTS,
)

__all__ = [
    "WDI_GENERIC_SCHEMA",
    "WDI_GENERIC_CONTRACT",
    "WORLD_BANK_CONTRACTS",
    "WVS_GENERIC_SCHEMA",
    "WVS_GENERIC_CONTRACT",
    "WVS_CONTRACTS",
    "EUROSTAT_GENERIC_SCHEMA",
    "EUROSTAT_GENERIC_CONTRACT",
    "EUROSTAT_CONTRACTS",
    "UKONS_GENERIC_SCHEMA",
    "UKONS_GENERIC_CONTRACT",
    "UKONS_CONTRACTS",
    "SDMX_GENERIC_SCHEMA",
    "SDMX_GENERIC_CONTRACT",
    "SDMX_CONTRACTS",
    "ALL_SOURCE_CONTRACTS",
]
