from __future__ import annotations

from .eurostat_contracts import EUROSTAT_CONTRACTS, EUROSTAT_GENERIC_CONTRACT, EUROSTAT_GENERIC_SCHEMA
from .ukons_contracts import UKONS_CONTRACTS, UKONS_GENERIC_CONTRACT, UKONS_GENERIC_SCHEMA
from .world_bank_contracts import WDI_GENERIC_CONTRACT, WDI_GENERIC_SCHEMA, WORLD_BANK_CONTRACTS

ALL_SOURCE_CONTRACTS = (
    *WORLD_BANK_CONTRACTS,
    *EUROSTAT_CONTRACTS,
    *UKONS_CONTRACTS,
)

__all__ = [
    "WDI_GENERIC_SCHEMA",
    "WDI_GENERIC_CONTRACT",
    "WORLD_BANK_CONTRACTS",
    "EUROSTAT_GENERIC_SCHEMA",
    "EUROSTAT_GENERIC_CONTRACT",
    "EUROSTAT_CONTRACTS",
    "UKONS_GENERIC_SCHEMA",
    "UKONS_GENERIC_CONTRACT",
    "UKONS_CONTRACTS",
    "ALL_SOURCE_CONTRACTS",
]

