import hashlib,json,pathlib,subprocess
D=pathlib.Path('/tmp/e02-F-continuation-20261007/economics/root-companion-review');repo='/workspace/e02-F-closeout-20261006';old='5609d09cbf519f01bde1ea81c6b3ee4a36a484a8';new='b5a421d83336e0b50ad9a6747f3f7d041d4c1b5a';P='policy-engine/docs/research/e02-cloud-test-plan/implementation-handoffs/F/'
def sha(b):return hashlib.sha256(b).hexdigest()
def dump(name,v):(D/name).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
def ref(path):
 b=(D/path).read_bytes();return {'path':path,'bytes':len(b),'sha256':sha(b)}
commands=json.loads((D/'commands.json').read_text());extra=[]
def git(name,args):
 q=subprocess.run(['git',*args],cwd=repo,capture_output=True);stem='final-'+name;(D/(stem+'.stdout')).write_bytes(q.stdout);(D/(stem+'.stderr')).write_bytes(q.stderr);extra.append({'name':name,'argv':['git',*args],'cwd':repo,'exit_code':q.returncode,'stdout':ref(stem+'.stdout'),'stderr':ref(stem+'.stderr')});assert q.returncode==0;return q.stdout
assert git('current-tree',['rev-parse',new+'^{tree}']).decode().strip()=='055871c409ce72e6a29619b235698aa45a6844d4'
current=json.loads((D/'current-b5a-binding.json').read_text())
for i,x in enumerate(current['six_owned_new_paths_plus_twelve_provider_paths']):
 a=git(f'current-provider-{i:02d}',['rev-parse',new+':'+x['path']]);b=git(f'old-provider-{i:02d}',['rev-parse',old+':'+x['path']]);assert a==b
checks=json.loads((D/'byte-audit.json').read_text());provenance=json.loads((D/'provenance.json').read_text())
receipts=[]
for name in ['api-installed-graph-reconciliation-20261007.json','tmle-persisted-consumers-20261007.json']:
 path=P+name;raw=git('receipt-'+name,['show',old+':'+path]);d=json.loads(raw)
 assert d['closure_ids']==[]
 candidate=d.get('candidate_source_sha',d.get('candidate_sha'));tree=d['candidate_tree_sha']
 assert git('candidate-tree-'+name,['rev-parse',candidate+'^{tree}']).decode().strip()==tree
 receipts.append({'git_ref':old,'path':path,'bytes':len(raw),'sha256':sha(raw),'candidate_source_sha':candidate,'candidate_tree_sha':tree,'closure_ids':[]})
commands.extend(extra);dump('commands.json',commands)
review={
 'schema':'policyos.e02.independent_root_companion_review.v1','reviewer':'F/economics; independent of API/FIT authors','verdict':'GO_BOUNDED','blocking_findings':[],
 'scope':{'read_only':True,'initial_root_source_sha':old,'initial_root_tree':'53176c14864e106c0b0deb87a6da9d5ba67d303c','current_composed_source_sha':new,'current_composed_tree':'055871c409ce72e6a29619b235698aa45a6844d4','api_carrier':'605dadeb76499c3f6eadd95e16a8df1bbb2cb89f','fit_carrier':'e04ddf884071b17ffb1d021c9a6b23f826d76774','numerical_tests_rerun':False,'product_doc_env_git_mutations':False,'graph647_independent_review':'Excluded: separately assigned API reviewer. This review proves the six assigned files and twelve named dependencies remain byte-identical atb5a; no Graph647 GO is inferred here.','root_current_three_document_edits':'Outside immutable source review; root is sole writer.'},
 'source_accuracy':{'complete_new_footprint':provenance['footprints'],'no_runtime_src_delta_on5609_vs8236':True,'all_six_owned_files_byte_equal_merged_root':True,'all_eighteen_assigned_files_byte_equal_b5a':True,'API_statement':'Test/doc/internal release-fragment verification only. Two installed owner cases exercise actual model_copy, NetworkX, CSV, ordinary to_kuzu dictionary emission, FileSystemCAS and isolated fresh typed readers; recorder does not instantiate live Kuzu. Param metadata/schema1.0/row multiplicity retained.','FIT_statement':'Test/doc/internal release-fragment verification only. One actual registered native MethodJob per producer run yields persisted TMLE SUCCESS/CI. The53-case suite challenges fresh consumers of that same result rather than claiming53 estimator fits or a common model-budget study. Relabeled copies retain actual persisted numerical values; no independent manufactured report or identification certificate.'},
 'history_accuracy':{'API_90c_ancestor605_root':True,'API_complete_reconciliation_commits':9,'API_complete_changed_paths':221,'API_classifications':provenance['competing_history']['221_path_classification'],'complete_non_evidence_contract_paths':7,'every_contract_path_five_ref_bindings_verified':35,'all_defining_graph_blobs':provenance['competing_history']['defining_graph_blobs'],'competing_to_canonical_graph_hunks':2,'whole_module_AST_equal':True,'ordinary_parent_history':'Actual root API/FIT/ECO two-parent merges preserve full90c and descendant implementation/handoff history. No flatten/reconstruction or whole3dde head PASS attribution. FIT f910 dependency merge also retains072 ancestry.','proofs':['provenance.json','complete-35-contract-blob-bindings.json','commands.json']},
 'candidate_institutional_and_value_planes':{
  'numerical_candidate':'CausalEffectReport SUCCESS/point/EIFCI and method_execution evidence remain numerical candidates. Converter hard-codes gate_eligibleFalse with causal_identification_admission_not_established; method execution receipt explicitly cannot establish method validity. Neither source relabeling nor gate flag supplies admitted identification.',
  'Confidence_consumer':'ConfidencePass.validate inserts the causal-purpose BLOCKER before any store/sibling loading; both ref addresses retain purpose even malformed/unresolved. Healthy simulation siblings and min_gate_ratio0 cannot remove that issue. No producer source label becomes institutional authority.',
  'native_value_consumer':'project_method_value_evidence returns method_output_contract_unresolved at unresolved TMLE report-slot contract before the later uncertainty gate check. Test/doc correctly state this upstream refusal and do not claim coverage of a downstream gate predicate or positive value projection.',
  'operational_profile':'Named inspected Runtime authority and appointment default resolvers return blocked/not_established, and verifier registry returnsNone. Their bytes matchG9a/072/candidates/currentroot. EvaluationExecutionContext and safety admission constitute another plane, not statistical identification or native value admission. No repository-wide supplier absence is inferred.',
  'missing_inputs_UNRUN':['accepted content-bound statistical issuer/verifier contract and producer-issued positive receipt','genuine operational current authority/appointment/verifier context in declared profile','native output-contract/value projection owner and exact estimand binding','B56 admitted common-study models/workloads/seeds/repeats/budget'],
  'adoption':'Both companion handoffs closure_ids[] and root/G acceptance pending. Prior B54 or other finding decisions are not promoted by these companions.'},
 'shared_dependency_consistency':{'nine_FIT_provider_paths_and_three_Runtime_paths':'All declared source hashes/blob IDs/bytes verified for every source role and against5609; all12 stay equal onb5a. API graph preparation uses maintained canonical8236 owner; source graph formatting reconciliation and fresh row-copy behavior do not provide identification/authority. API imports and FIT value/refusal/error roles do not contradict one another.','root_imported_code_scope':'5609 src directory has no delta from8236. b5a adds separate Graph647 governed changes reviewed elsewhere; new affected installedwave is pending and required before reporting b5a installed native success. No earlier native/199 result is transferred to current composed source by ancestry alone.'},
 'complete_evidence_review':{'API_complete_companion_files':120,'FIT_complete_companion_files':102,'stored_bytes':817385,'decoded_raw_bytes':4738274,'all_stored_and_lossless_decoded_bindings':True,'all_complete_outputs_read':True,'API_author_affected_native':'wheel2PASS andsdist2PASS at6f39 tested carrier using installed8236 owners; forced row-cache removal2FAIL ineach. Prior harness failures at3bfc/7f retained separately. IndependentCAU wheel2PASS and2FAIL removal preserved; no independent sdist claim.','FIT_author_and_independent':'Separate53PASS each with fullJUnit53 testcase census0FAIL/ERROR/SKIP.36 degraded simulation-load warnings recorded per native producer run; no warnings hidden and no54/106 composite-estimator claim. Actual canonical causal-role/collection-removal FAIL and independent role-drop FAIL, with same persisted SUCCESS/CI and upstream value refusal, are retained.','other_FAIL_ERROR':'Initial API static ancestry/typedArtifactID JSON observer harness failures; FIT initial release renderer type=other rejection; raw whitespace staged diff--check FAIL; initialdevelopment errors all remain explicit. Corrected source/fragment checks are source-specific; no global/P41 inherited PASS inferred.','CAS':'Both actual synthetic CAS archives fully read without extraction or mutation: author50 and independent36 regular-file bytes/SHA compared to entire respective member manifests. They contain synthetic observation/result/report/envelope/evidence/adversarial fixture inputs only.','proofs':['byte-audit.json','commands.json','bound-companion-blobs.stdin']},
 'limits':[
  'This is immutable source/claim/portable evidence review, no new numeric/native suite execution.',
  'API parameter-emission/CSV/NetworkX/CAS witnesses do not establish liveKuzu, external computed clients or all publicfacades.38 incomplete static export declarations remainUNKNOWN; known0 is not complete absence.',
  'Python3.14 default DoWhy/EconML marker exclusions remain exclusions rather than backend witnesses; this review neither supplies nor repeats those backends.',
  'One native observational synthetic TMLE fixture cannot establish identification on admitted real data, institutionally verified operational/value eligibility or B56 resource/common-study completeness.',
  'Root current closed/limited/held ledger and G adoption are separately owned decisions; both reviewed companion closure lists are empty.'
 ],
 'review_harness_errors':[
  {'outcome':'ERROR','cause':'Initial strict cleanliness assertion observed root-owned three common documentation edits while moving5609→b5a. Corrected review binds immutable Git source instead of requiring another author worktree unchanged.','product_attribution':False,'preserved':'initial-harness-error.json and audit-initial-clean-guard.py plus008-tracked-status.stdout'},
  {'outcome':'ERROR','cause':'Initial archive comparator assumed both file manifests use relative path; independent archive provides archive_member separately from original absolutepath. Corrected comparison uses declaredarchive_member and verifies every86 actual file bytes/SHA.','product_attribution':False,'preserved':'audit-initial-archive-profile.py and initial-archive-profile.stderr'},
  {'outcome':'ERROR','cause':'Initial interactive source lookup omitted maintained governance/methods/components package segments; corrected canonical paths fully read and retained. No original lookup stdout copy claimed beyond chat transcript.','product_attribution':False}
 ],
 'receipt_bindings':receipts,
 'complete_local_evidence':{'commands':ref('commands.json'),'provenance':ref('provenance.json'),'lossless_byte_audit':ref('byte-audit.json'),'current_binding':ref('current-b5a-binding.json'),'complete_blob_matrix':ref('complete-35-contract-blob-bindings.json'),'replayer':ref('audit.py'),'finalizer':ref('finish_review.py')}
}
dump('review.json',review)
# Transfer only the complete deciding final command outputs, proofs and preserved failing harness source/output.
selected={x[k]['path'] for x in commands for k in ['stdout','stderr']}
selected.update({'audit.py','finish_review.py','audit-summary.json','audit-run.stdout','audit-run.stderr','commands.json','provenance.json','byte-audit.json','bound-companion-blobs.stdin','current-b5a-binding.json','current-b5a-log.stdout','current-b5a-log.stderr','complete-35-contract-blob-bindings.json','review.json','initial-harness-error.json','audit-initial-clean-guard.py','008-tracked-status.stdout','008-tracked-status.stderr','audit-initial-archive-profile.py','initial-archive-profile.stdout','initial-archive-profile.stderr'})
# The first failed guard produced tracked status at command008; preserve exact existing path rather than invent.
for name in list(selected):
 if not (D/name).exists():
  if name.startswith('008-tracked-status'):selected.remove(name);selected.update(p.name for p in D.glob('*-tracked-status.'+name.rsplit('.',1)[1]) if not p.name.startswith('3'))
  else:raise FileNotFoundError(name)
records=[ref(x) for x in sorted(selected)]
dump('transfer-selection.json',{'schema':'policyos.e02.readonly_review_transfer_selection.v1','review_verdict':'GO_BOUNDED','root_source_sha':new,'files':records,'file_count':len(records),'total_bytes':sum(x['bytes'] for x in records),'no_sanitation':'Complete exact bytes, including binary Git batch stdout and historical harness failures. Stored Git companion blobs already have independent losslessdecoded audit inbyte-audit; no production inputs or credentials. No history/product writes.'})
print(json.dumps({'verdict':'GO_BOUNDED','review':ref('review.json'),'selection':ref('transfer-selection.json'),'files':len(records),'total_bytes':sum(x['bytes'] for x in records)}))
