"""Reconstruct the complete source-root census from immutable Git objects."""
import argparse,collections,hashlib,json,pathlib,re,subprocess
p=argparse.ArgumentParser();p.add_argument('--ref',required=True);p.add_argument('--output',required=True);a=p.parse_args();paths=subprocess.check_output(['git','ls-tree','-r','--name-only',a.ref],text=True).splitlines();roots=('policy-engine/src/','policy-engine/tests/','policy-engine/tools/','policy-engine/benchmarks/','policy-engine/scripts/','scripts/','src/','apps/','packages/');extensions={'.py','.js','.jsx','.ts','.tsx','.json','.yaml','.yml','.toml'};scope=[s for s in paths if s.startswith(roots) and pathlib.Path(s).suffix in extensions];pipe=subprocess.Popen(['git','cat-file','--batch'],stdin=subprocess.PIPE,stdout=subprocess.PIPE);rows=[]
for s in scope:
 pipe.stdin.write((a.ref+':'+s+'\n').encode());pipe.stdin.flush();header=pipe.stdout.readline().decode().split();size=int(header[2]);raw=pipe.stdout.read(size);assert pipe.stdout.read(1)==b'\n'
 try:lines=raw.decode().splitlines()
 except UnicodeError:continue
 hits=[{'line':i,'text':l} for i,l in enumerate(lines,1) if re.search(r'(?<!\w)DifferenceInDifferences\b|difference_in_differences|outcome_panel|treatment_indicator|["\x27]staggered["\x27]\s*:\s*(?:True|False|true|false)',l)]
 if hits:rows.append({'path':s,'bytes':len(raw),'sha256':hashlib.sha256(raw).hexdigest(),'hits':hits,'scope':'test/replay' if '/tests/' in s else 'maintained-source'})
pipe.stdin.close();assert pipe.wait()==0
out={'source_sha':subprocess.check_output(['git','rev-parse',a.ref],text=True).strip(),'source_tree':subprocess.check_output(['git','rev-parse',a.ref+'^{tree}'],text=True).strip(),'input_custody':'all source bytes read directly from immutable Git via cat-file batch; no mutable worktree bytes','explicit_roots':roots,'all_tracked_paths':len(paths),'source_or_test_config_denominator':len(scope),'extension_denominator':dict(collections.Counter(pathlib.Path(s).suffix for s in scope)),'denominator_paths_sha256':hashlib.sha256(('\n'.join(scope)+'\n').encode()).hexdigest(),'denominator_reconstruction':'git ls-tree -r --name-only REF, roots/extensions above; canonical tracked bytes retained in Git','rows':rows,'limitations':'Arbitrary external/dynamic callers and historical docs/receipt replayers outside named roots are not universal supported caller claims.'};pathlib.Path(a.output).write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({'source_sha':out['source_sha'],'source_tree':out['source_tree'],'denominator':len(scope),'hit_files':len(rows),'output':a.output}))
