import type { QuantityValue } from "@/shared/ui/quantity";

export const BUREAUCRATIC_GENRES = [
  "postanova_kmu",
  "zakonoproekt",
  "expert_vysnovok",
  "analitichna_zapyska",
] as const;

export type BureaucraticGenre = (typeof BUREAUCRATIC_GENRES)[number];

export type BureaucraticEpistemicKind =
  | "evidence_filled"
  | "model_generated"
  | "operator_filled"
  | "imported";

export type BureaucraticBlockKind =
  | "header"
  | "requisites"
  | "preamble"
  | "legal_basis"
  | "section"
  | "article"
  | "clause"
  | "subclause"
  | "paragraph"
  | "list"
  | "table"
  | "quantity"
  | "annex"
  | "signature"
  | "appendix";

export type BureaucraticTemplateRef = {
  id: string;
  version: string;
  genre: BureaucraticGenre;
  jurisdiction: string;
  locale: string;
  legal_review_status: "pending_external_review" | "approved" | "rejected";
};

export type BureaucraticAuthorship = {
  author: string;
  author_role: string;
  agent_version?: string | null;
  timestamp?: string | null;
  reviewed_by_human: boolean;
};

export type BureaucraticBlock = {
  id: string;
  kind: BureaucraticBlockKind;
  title?: string | null;
  text?: string | null;
  level: number;
  number?: string | null;
  items?: string[];
  quantity?: QuantityValue | null;
  epistemic_origin: BureaucraticEpistemicKind;
  authorship: BureaucraticAuthorship;
  provenance?: Array<{ kind: string; label: string; id?: string | null }>;
  raw_source_refs?: string[];
  children?: BureaucraticBlock[];
  metadata?: Record<string, unknown>;
};

export type BureaucraticEpistemicSummary = Record<
  BureaucraticEpistemicKind,
  number
>;

export type BureaucraticDocumentAST = {
  id: string;
  packet_id: string;
  genre: BureaucraticGenre;
  jurisdiction: string;
  template: BureaucraticTemplateRef;
  status: "draft" | "signed_external" | "archived";
  title: string;
  language: string;
  watermark: string;
  render_timestamp: string;
  packet_hash: string;
  temporal_scope?: Record<string, unknown> | null;
  trust_view: boolean;
  blocks: BureaucraticBlock[];
  annexes: BureaucraticBlock[];
  epistemic_summary: BureaucraticEpistemicSummary;
  metadata?: Record<string, unknown>;
};

export type BureaucraticDocumentValidation = {
  valid: boolean;
  watermarkPresent: boolean;
  missingBlockIds: string[];
  quantityBlocksWithoutLineage: string[];
};

export function flattenBureaucraticBlocks(
  document: Pick<BureaucraticDocumentAST, "annexes" | "blocks">,
): BureaucraticBlock[] {
  const flattened: BureaucraticBlock[] = [];
  function visit(block: BureaucraticBlock) {
    flattened.push(block);
    for (const child of block.children ?? []) {
      visit(child);
    }
  }
  for (const block of [...document.blocks, ...document.annexes]) {
    visit(block);
  }
  return flattened;
}

export function validateBureaucraticDocumentAST(
  document: BureaucraticDocumentAST,
): BureaucraticDocumentValidation {
  const blocks = flattenBureaucraticBlocks(document);
  const missingBlockIds = blocks
    .filter((block) => !block.id.trim())
    .map((block, index) => block.title ?? `block_${index}`);
  const quantityBlocksWithoutLineage = blocks
    .filter((block) => block.kind === "quantity")
    .filter((block) => !block.quantity?.lineage?.id)
    .map((block) => block.id);
  const watermarkPresent =
    document.watermark.includes("Generated by PolicyOS") &&
    document.status === "draft";
  return {
    valid:
      watermarkPresent &&
      missingBlockIds.length === 0 &&
      quantityBlocksWithoutLineage.length === 0,
    watermarkPresent,
    missingBlockIds,
    quantityBlocksWithoutLineage,
  };
}

export function genreLabel(genre: BureaucraticGenre): string {
  switch (genre) {
    case "postanova_kmu":
      return "Постанова КМУ";
    case "zakonoproekt":
      return "Законопроект";
    case "expert_vysnovok":
      return "Експертний висновок";
    case "analitichna_zapyska":
      return "Аналітична записка";
  }
}
