"""Keep N13b custody complete across generated and frozen-evidence families."""

from __future__ import annotations

import copy
import hashlib
import json
import tomllib
from pathlib import Path
from typing import Any

import pytest
from pydantic import ValidationError

from tools.quality.validation import layer3_gy_n13b_acquisition_contract as owner

REPO_ROOT = Path(__file__).resolve().parents[3]
SOURCE_FAMILY_ID = "policy-design-case-layer3-gy-n13b-frozen-acquisition-evidence"


def _registry_bytes(families: list[dict[str, Any]]) -> bytes:
    lines: list[str] = []
    for family in families:
        lines.append("[[family]]")
        for key, value in family.items():
            if isinstance(value, list):
                lines.extend(
                    [f"{key} = [", *(f"  {json.dumps(item)}," for item in value), "]"]
                )
            elif isinstance(value, dict):
                lines.extend(
                    f"{key}.{json.dumps(item)} = {json.dumps(digest)}"
                    for item, digest in value.items()
                )
            else:
                lines.append(f"{key} = {json.dumps(value)}")
    return ("\n".join(lines) + "\n").encode()


@pytest.fixture
def split_registry(tmp_path: Path) -> tuple[Path, list[dict[str, Any]], set[str]]:
    """Split the real complete input set while reading its existing bytes."""

    families = tomllib.loads((REPO_ROOT / owner.DEFAULT_GENERATED_ARTIFACTS).read_text())[
        "family"
    ]
    original = copy.deepcopy(next(row for row in families if row["id"] == owner.N13B_FAMILY_ID))
    existing_source = next((row for row in families if row["id"] == SOURCE_FAMILY_ID), None)
    assert existing_source is not None
    all_paths = set(original["outputs"])
    if existing_source is not None:
        all_paths.update(existing_source["outputs"])
    writer_paths = {
        owner.DEFAULT_N13B_CONTRACT.as_posix(),
        owner.DEFAULT_N13B_LIFECYCLE_MANIFEST.as_posix(),
        owner.DEFAULT_UNIVERSALITY_RECEIPT.as_posix(),
    }
    assert writer_paths.issubset(all_paths)
    original["outputs"] = sorted(writer_paths)
    source = {
        "id": SOURCE_FAMILY_ID,
        "lifecycle": "source_committed",
        "outputs": sorted(all_paths - writer_paths),
        "source_committed_rationale": "Frozen evidence; never regenerated by the contract writer.",
        "source_integrity_sha256": {
            path: (existing_source["source_integrity_sha256"][path])
            for path in sorted(all_paths - writer_paths)
        },
    }
    unrelated = {"id": "unrelated-owner", "lifecycle": "source_committed", "outputs": []}
    root = tmp_path / "policy-engine"
    (root / "architecture").mkdir(parents=True)
    for path in all_paths:
        target = root / path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.symlink_to(REPO_ROOT / path)
    rows = [original, source, unrelated]
    (root / owner.DEFAULT_GENERATED_ARTIFACTS).write_bytes(_registry_bytes(rows))
    return root, rows, all_paths


def test_split_manifest_preserves_complete_union_and_content_custody(
    split_registry: tuple[Path, list[dict[str, Any]], set[str]],
) -> None:
    root, _families, all_paths = split_registry
    update = owner.derive_n13b_generated_registry_update(root)
    manifest = owner.derive_lifecycle_manifest(
        root, required_cas_artifact_ids=update.required_cas_artifact_ids
    )

    assert {row.path for row in manifest.registrations} == all_paths
    assert manifest.owner_registration_derivation_missing_closed is True
    assert manifest.schema_version == "policyos.layer3.gy.n13b.lifecycle_manifest.v3"
    assert manifest.source_family_id == SOURCE_FAMILY_ID
    for row in manifest.registrations:
        if row.registration_status == "content_bound":
            payload = (root / row.path).read_bytes()
            assert row.byte_sha256 == f"sha256:{hashlib.sha256(payload).hexdigest()}"
            assert row.byte_size == len(payload)


def test_registry_update_changes_only_frozen_family_cas_membership(
    split_registry: tuple[Path, list[dict[str, Any]], set[str]],
) -> None:
    root, families, all_paths = split_registry
    stale = (owner.DEFAULT_N13B_CAS / "artifacts/sha256/ff/ff/stale.blob").as_posix()
    families[1]["outputs"].append(stale)
    families[1]["source_integrity_sha256"][stale] = "sha256:" + "f" * 64
    (root / owner.DEFAULT_GENERATED_ARTIFACTS).write_bytes(_registry_bytes(families))

    update = owner.derive_n13b_generated_registry_update(root)
    after = tomllib.loads(update.registry_bytes.decode())["family"]

    assert after[0] == families[0]
    assert after[2] == families[2]
    mutable = {"outputs", "source_integrity_sha256"}
    assert {key: value for key, value in after[1].items() if key not in mutable} == {
        key: value for key, value in families[1].items() if key not in mutable
    }
    assert set(after[0]["outputs"]) | set(after[1]["outputs"]) == all_paths
    assert tuple(path for path in after[1]["outputs"] if "/artifacts/sha256/" in path) == (
        update.required_cas_output_paths
    )
    assert update.obsolete_cas_output_paths == (stale,)
    assert after[1]["source_integrity_sha256"] == {
        path: digest
        for path, digest in families[1]["source_integrity_sha256"].items()
        if path != stale
    }


def test_source_updater_restores_full_verified_cas_membership_and_integrity(
    split_registry: tuple[Path, list[dict[str, Any]], set[str]],
) -> None:
    from tools.quality.validation.check_layer3_gy_generated_public_lifecycle_audit import (
        _validate_source_integrity,
    )

    root, families, _all_paths = split_registry
    required = set(owner.derive_n13b_generated_registry_update(root).required_cas_output_paths)
    original_source = copy.deepcopy(families[1])
    registered = {path for path in original_source["outputs"] if "/artifacts/sha256/" in path}
    assert registered == required
    families[1]["outputs"] = [path for path in families[1]["outputs"] if path not in required]
    families[1]["source_integrity_sha256"] = {
        path: digest
        for path, digest in families[1]["source_integrity_sha256"].items()
        if path not in required
    }
    (root / owner.DEFAULT_GENERATED_ARTIFACTS).write_bytes(_registry_bytes(families))

    update = owner.derive_n13b_generated_registry_update(root)
    after = tomllib.loads(update.registry_bytes.decode())["family"]
    issues: list[dict[str, Any]] = []
    _validate_source_integrity(root, after[1], after[1]["outputs"], issues)

    assert issues == []
    assert after[1] == original_source
    assert after[0] == families[0]
    assert after[2] == families[2]


@pytest.mark.parametrize("consumer", ["updater", "manifest"])
def test_frozen_manifest_byte_drift_cannot_be_restamped_or_admitted(
    split_registry: tuple[Path, list[dict[str, Any]], set[str]], consumer: str
) -> None:
    root, families, _all_paths = split_registry
    manifest_path = next(path for path in families[1]["outputs"] if path.endswith(".manifest.json"))
    target = root / manifest_path
    altered = target.read_bytes() + b"\n"
    target.unlink()
    target.write_bytes(altered)
    consume = (
        owner.derive_n13b_generated_registry_update
        if consumer == "updater"
        else owner.derive_lifecycle_manifest
    )

    with pytest.raises(owner.N13bContractError, match="n13b_source_integrity_drift"):
        consume(root)


@pytest.mark.parametrize("consumer", ["updater", "manifest"])
def test_frozen_non_cas_byte_drift_cannot_be_restamped_or_admitted(
    split_registry: tuple[Path, list[dict[str, Any]], set[str]], consumer: str
) -> None:
    root, _families, _all_paths = split_registry
    target = root / owner.DEFAULT_N13B_PROVISION
    altered = target.read_bytes() + b"\n"
    target.unlink()
    target.write_bytes(altered)
    consume = (
        owner.derive_n13b_generated_registry_update
        if consumer == "updater"
        else owner.derive_lifecycle_manifest
    )

    with pytest.raises(owner.N13bContractError, match="n13b_source_integrity_drift"):
        consume(root)


@pytest.mark.parametrize("duplicate_family", [0, 2])
def test_split_manifest_rejects_a_second_owner_for_a_frozen_input(
    split_registry: tuple[Path, list[dict[str, Any]], set[str]], duplicate_family: int
) -> None:
    root, families, _all_paths = split_registry
    families[duplicate_family]["outputs"].append(owner.DEFAULT_N13B_PROVISION.as_posix())
    (root / owner.DEFAULT_GENERATED_ARTIFACTS).write_bytes(_registry_bytes(families))

    with pytest.raises(owner.N13bContractError, match="n13b_lifecycle_output_multiple_owners"):
        owner.derive_lifecycle_manifest(root)


def test_split_manifest_requires_the_frozen_evidence_owner(
    split_registry: tuple[Path, list[dict[str, Any]], set[str]],
) -> None:
    root, families, _all_paths = split_registry
    (root / owner.DEFAULT_GENERATED_ARTIFACTS).write_bytes(
        _registry_bytes([row for row in families if row["id"] != SOURCE_FAMILY_ID])
    )

    with pytest.raises(owner.N13bContractError, match="n13b_source_family_unresolved"):
        owner.derive_lifecycle_manifest(root)


def test_split_manifest_rejects_frozen_evidence_relabelled_as_generated(
    split_registry: tuple[Path, list[dict[str, Any]], set[str]],
) -> None:
    root, families, _all_paths = split_registry
    families[1]["lifecycle"] = "generated_committed"
    (root / owner.DEFAULT_GENERATED_ARTIFACTS).write_bytes(_registry_bytes(families))

    with pytest.raises(owner.N13bContractError, match="n13b_source_family_lifecycle_invalid"):
        owner.derive_lifecycle_manifest(root)


def test_split_manifest_missing_cas_member_remains_red(
    split_registry: tuple[Path, list[dict[str, Any]], set[str]],
) -> None:
    root, families, _all_paths = split_registry
    update = owner.derive_n13b_generated_registry_update(root)
    families[1]["outputs"].remove(update.required_cas_output_paths[-1])
    (root / owner.DEFAULT_GENERATED_ARTIFACTS).write_bytes(_registry_bytes(families))

    with pytest.raises(owner.N13bContractError, match="n13b_generated_cas_output_denominator_drift"):
        owner.derive_lifecycle_manifest(root, required_cas_artifact_ids=update.required_cas_artifact_ids)


@pytest.mark.parametrize("receipt_kind", ["lifecycle", "contract"])
def test_previous_epoch_is_readable_but_cannot_enter_current_admission(
    tmp_path: Path, receipt_kind: str
) -> None:
    path = (
        owner.DEFAULT_N13B_LIFECYCLE_MANIFEST
        if receipt_kind == "lifecycle"
        else owner.DEFAULT_N13B_CONTRACT
    )
    payload = json.loads((REPO_ROOT / path).read_bytes())
    lifecycle = payload if receipt_kind == "lifecycle" else payload["lifecycle"]
    if lifecycle["schema_version"] != "policyos.layer3.gy.n13b.lifecycle_manifest.v2":
        current = owner.N13bLifecycleManifest.model_validate(lifecycle)
        historical = owner.N13bLifecycleManifestV2.model_construct(
            **{
                name: getattr(current, name)
                for name in owner.N13bLifecycleManifestV2.model_fields
                if name != "schema_version"
            },
        )
        historical = historical.model_copy(
            update={"manifest_sha256": owner.content_sha256(historical.identity_payload())}
        )
        if receipt_kind == "lifecycle":
            payload = historical.model_dump(mode="json")
        else:
            current_contract = owner.N13bAcquisitionExecutorContract.model_validate(payload)
            old_contract = owner.N13bAcquisitionExecutorContractV4.model_construct(
                **{
                    name: getattr(current_contract, name)
                    for name in owner.N13bAcquisitionExecutorContractV4.model_fields
                    if name not in {"schema_version", "lifecycle"}
                },
                lifecycle=historical,
            )
            old_contract = old_contract.model_copy(
                update={"contract_sha256": owner.content_sha256(old_contract.identity_payload())}
            )
            payload = old_contract.model_dump(mode="json")
    current_model = (
        owner.N13bLifecycleManifest
        if receipt_kind == "lifecycle"
        else owner.N13bAcquisitionExecutorContract
    )

    with pytest.raises(ValidationError):
        current_model.model_validate(payload)

    historical_path = tmp_path / f"{receipt_kind}.json"
    historical_path.write_text(json.dumps(payload))
    reader = (
        owner.read_n13b_lifecycle_manifest
        if receipt_kind == "lifecycle"
        else owner.read_n13b_acquisition_executor_contract
    )
    historical = reader(historical_path)
    assert historical.model_dump(mode="json") == payload
