import argparse,ast,hashlib,importlib,json,pathlib,subprocess,sys
p=argparse.ArgumentParser();p.add_argument('--role',choices=['dfk','can'],required=True);a=p.parse_args();repo=pathlib.Path('/workspace/orch02-c06-'+a.role);engine=repo/'policy-engine';sys.path[:0]=[str(engine/'src'),str(engine)]
frozen={'dfk':'cbbfffd367fe283813a8177575d26c0ede8d20c4','can':'4901e26841e2be0ae6ef393754abed5cafb1e2d4'}[a.role];base={'dfk':'a13f6c1acfe15a6750d71c6e86521f119d794def','can':'f00dd7661a8d3329fb1fa1b049decb0d1d2f277b'}[a.role];G='0321633c0e6d9a87bccfbbe889a4998934c52dd3';tools_name='tools.quality.validation.check_production_invocation';runtime_name='polisyos.runtime.quality.production_invocation';tool=importlib.import_module(tools_name);runtime=importlib.import_module(runtime_name);assert tool.main is runtime.main;origins=[]
for module in (tool,runtime):
 path=pathlib.Path(module.__file__).resolve();assert path.is_relative_to(engine);relative=str(path.relative_to(repo));b=path.read_bytes();states=[]
 for ref in (base,frozen,G):
  canonical=subprocess.check_output(['git','show',ref+':'+relative],cwd=repo);assert canonical==b;states.append({'commit':ref,'git_blob':subprocess.check_output(['git','rev-parse',ref+':'+relative],cwd=repo,text=True).strip()})
 tree=ast.parse(b);entries=[n for n in tree.body if isinstance(n,ast.If) and ast.dump(n.test,include_attributes=False)==ast.dump(ast.parse('__name__ == "__main__"',mode='eval').body,include_attributes=False)];assert len(entries)==1;entry=entries[0];assert len(entry.body)==1 and isinstance(entry.body[0],ast.Raise);call=entry.body[0].exc;assert isinstance(call,ast.Call) and isinstance(call.func,ast.Name) and call.func.id=='SystemExit' and len(call.args)==1;inner=call.args[0];assert isinstance(inner,ast.Call) and isinstance(inner.func,ast.Name) and inner.func.id=='main' and not inner.args and not inner.keywords
 origins.append({'module':module.__name__,'loaded_path':str(path),'canonical_path':relative,'bytes':len(b),'sha256':hashlib.sha256(b).hexdigest(),'base_candidate_G_source_identities':states,'main_entry':'raise SystemExit(main()) with no argument transformation'})
print(json.dumps({'role':a.role,'source_sha':frozen,'slice_base':base,'loaded_callable_identity':tool.main is runtime.main,'callable_module':tool.main.__module__,'origins':origins,'taxonomy':'Runtime quality module is actual checker implementation; tools quality validation module is the thin wrapper. The completed -m tools... run executed the required runtime main directly.','executed_flags':'Explicit --repo-root own policy-engine, --base exact slice base, --receipt unique saved output; wrapper changes no arguments.','equivalence_scope':'Same callable, immutable implementation and valid explicit arguments. Program label for --help/parser diagnostics can differ by module invocation; no help-text identity or external process/resource outcome equality inferred. Existing initial signal-9 remains ERROR.','native_or_heavy_graph_replay':'none; cheap source/import/callable binding only','runtime_invocation_established':False},indent=2))
