from __future__ import annotations


def test_bureaucratic_render_returns_draft_ast_with_watermark_and_quantities(
    runtime_api_env,
) -> None:
    client = runtime_api_env["client"]
    packet_id = runtime_api_env["decision_packet_artifact_id"]

    response = client.post(
        f"/api/v1/artifacts/{packet_id}/render",
        json={
            "genre": "postanova_kmu",
            "jurisdiction": "ua",
            "template_version": "ua.kmu.postanova.v1",
            "temporal_scope": {"valid_at": "2026-02-11T12:00:00Z"},
            "trust_view": True,
        },
    )

    assert response.status_code == 200
    document = response.json()["document"]
    assert document["packet_id"] == packet_id
    assert document["status"] == "draft"
    assert document["template"]["id"] == "ua.kmu.postanova.v1"
    assert document["template"]["legal_review_status"] == "pending_external_review"
    assert document["watermark"] == "Generated by PolicyOS / Draft / Not an official state document"
    assert document["packet_hash"]
    assert document["temporal_scope"]["valid_at"] == "2026-02-11T12:00:00Z"
    assert document["epistemic_summary"]["model_generated"] > 0
    assert document["epistemic_summary"]["imported"] > 0

    quantity_blocks = [block for block in document["blocks"] if block["kind"] == "quantity"]
    assert quantity_blocks
    metric = quantity_blocks[0]["quantity"]
    assert metric["quantity_class"] == "decision"
    assert metric["lineage"]["id"].startswith("artifact:")
    assert metric["lineage"]["status"] == "pending"
    assert metric["time"]["valid_at"] == "2026-02-11T12:00:00Z"
    assert any(block["id"] == "annex_raw_refs" for block in document["annexes"])


def test_bureaucratic_render_supports_all_first_class_genres(runtime_api_env) -> None:
    client = runtime_api_env["client"]
    packet_id = runtime_api_env["decision_packet_artifact_id"]
    genres = {
        "postanova_kmu": "ua.kmu.postanova.v1",
        "zakonoproekt": "ua.rada.zakonoproekt.v1",
        "expert_vysnovok": "ua.expert_vysnovok.v1",
        "analitichna_zapyska": "ua.analitichna_zapyska.v1",
    }

    for genre, template_id in genres.items():
        response = client.post(
            f"/api/v1/artifacts/{packet_id}/render",
            json={"genre": genre, "jurisdiction": "ua", "trust_view": False},
        )

        assert response.status_code == 200
        document = response.json()["document"]
        assert document["genre"] == genre
        assert document["template"]["id"] == template_id
        assert document["blocks"]


def test_bureaucratic_export_reuses_ast_and_includes_machine_watermark(runtime_api_env) -> None:
    client = runtime_api_env["client"]
    packet_id = runtime_api_env["decision_packet_artifact_id"]

    response = client.get(
        f"/api/v1/artifacts/{packet_id}/export",
        params={
            "format": "html",
            "genre": "expert_vysnovok",
            "trust_view": True,
            "valid_at": "2026-02-11T12:00:00Z",
            "tx_at": "2026-02-11T12:05:00Z",
        },
    )

    assert response.status_code == 200
    export = response.json()
    assert export["format"] == "html"
    assert export["content_type"] == "text/html; charset=utf-8"
    assert export["metadata"]["watermark"] == (
        "Generated by PolicyOS / Draft / Not an official state document"
    )
    assert 'name="polisyos:watermark"' in export["content"]
    assert 'data-block-id="quantity_policy_cost"' in export["content"]
    assert packet_id in export["content"]


def test_bureaucratic_export_pdf_and_docx_packets_are_deterministic_sources(
    runtime_api_env,
) -> None:
    client = runtime_api_env["client"]
    packet_id = runtime_api_env["decision_packet_artifact_id"]

    pdf = client.get(
        f"/api/v1/artifacts/{packet_id}/export",
        params={"format": "pdf", "genre": "postanova_kmu"},
    )
    docx = client.get(
        f"/api/v1/artifacts/{packet_id}/export",
        params={"format": "docx", "genre": "zakonoproekt"},
    )

    assert pdf.status_code == 200
    assert docx.status_code == 200
    assert pdf.json()["content"].startswith("%PDF-1.4")
    assert "Watermark:" in pdf.json()["content"]
    assert "DOCX source packet" in docx.json()["content"]
    assert docx.json()["metadata"]["parity_source"] == "bureaucratic_document_ast"
