"""Construct a source-bound fixture companion from actual complete evidence files."""
import hashlib,json,pathlib,shutil,subprocess,sys
root=pathlib.Path('/workspace/e02-F-graph-20261006');scratch=pathlib.Path(__file__).parent
sha='9824e04d630d42765ed44b9ff88702fcff885e08';base='b52c64c36504e17da9ae3f70f5551bfd1e01a5d5';tree='9aeed3f6a3ed62594062ab8cb10b24d719335753'
relative=pathlib.Path('policy-engine/docs/research/e02-cloud-test-plan/implementation-handoffs/F/causal-neighbor-fixtures-20261006');destination=root/relative;destination.mkdir(parents=True,exist_ok=True)
manifest=[];translation={}
def copy_file(source,name=None):
 source=pathlib.Path(source);name=name or source.name;target=destination/name;body=source.read_bytes();target.write_bytes(body);row={'path':str(relative/name),'bytes':len(body),'sha256':hashlib.sha256(body).hexdigest(),'encoding':'raw','scratch_original':str(source)};manifest.append(row);translation[str(source)]=row['path'];return row
for p in sorted(scratch.iterdir()):
 if p.is_file() and p.name not in {'historical-profile-primary.json','original-GRF01-card.md'}:copy_file(p)
review_dir=pathlib.Path('/tmp/e02-F-continuation-20261006/root-neighbor-review')
for name in ['review.json','stdout.txt','stderr.txt','junit.xml','independent_oracle.py','oracle.stdout.txt','oracle.stderr.txt']:copy_file(review_dir/name,'independent-root--'+name)
# Original card/primary bodies already exist unchanged in the fetched ancestor; bind rather than duplicate.
def git(*args):return subprocess.check_output(['git',*args],cwd=root)
def git_ref(source,path):
 body=git('show',source+':'+path);return {'artifact_git_ref':source,'path':path,'bytes':len(body),'sha256':hashlib.sha256(body).hexdigest()}
changed=git('diff','--name-only',base,sha).decode().splitlines();source_refs=[]
for path in changed:
 body=git('show',sha+':'+path);source_refs.append({'source_path':path,'source_sha':sha,'bytes':len(body),'sha256':hashlib.sha256(body).hexdigest()});assert (root/path).read_bytes()==body
assert not git('diff','--name-only',base,sha,'--','policy-engine/src','policy-engine/tools','policy-engine/workers','policy-engine/architecture/schemas')
checks=[]
def check_record(name,role,expected_negative=False):
 r=json.loads((scratch/(name+'.json')).read_bytes());refs=[]
 for x in r['output_refs']:refs.append({**x,'path':translation[x['path']]})
 item={'name':name,'command':r['command'],'target_sha':r['source_sha'],'source_tree':r['source_tree'],'environment':r['environment'],'input_closure':'Finite synthetic graphs and exact pytest selectors; immutable source_begin/source_end hashes in execution receipt. No admitted production inputs. This is not a complete P41 dependency denominator.','outcome':r['check'],'check':r['check'],'exit_code':r['exit_code'],'wall_s':r['wall_s'],'rss_kib':r['rss_kib'],'output':refs[0]['path'],'output_refs':refs,'execution_receipt':translation[str(scratch/(name+'.json'))],'role':role,'expected_negative':expected_negative};checks.append(item)
for name,role,negative in [('original-five','historical_source_fixture_characterization',False),('pre-edit-oracles','independent_pre_edit_analytic_and_native_oracles',False),('frozen-neighbors','current_deciding_native_consumers',False),('prepass-removal','marker_retaining_property_removal',True),('owned-fragment','scoped_canonical_compatibility_record',False),('frozen-quality','scoped_lint',False),('frozen-format','scoped_format',False)]:check_record(name,role,negative)
review=json.loads((review_dir/'review.json').read_bytes());assert review['check']=='PASS' and review['source_sha']==sha and review['actual_native_cases']==108
checks.extend([
 {'name':'independent-root-native','command':review['command'],'target_sha':sha,'source_tree':tree,'environment':{**review['environment'],'cwd':review['cwd'],'interpreter':review['command'][0]},'input_closure':'Exact three changed native test modules, 108 cases; full independent review and JUnit preserved. Finite supported graph profile only.','outcome':'PASS','check':'PASS','exit_code':0,'output':translation[str(review_dir/'stdout.txt')],'execution_receipt':translation[str(review_dir/'review.json')],'role':'independent_review','expected_negative':False},
 {'name':'independent-root-analytic-oracle','command':review['oracle_command'],'target_sha':sha,'source_tree':tree,'environment':{**review['environment'],'cwd':review['cwd'],'interpreter':review['oracle_command'][0]},'input_closure':'Independent Gaussian pairs beta=9/4,-2, observed-U collider/descendant controls, actual native SID/conditional-ID and actual unsupported CPDAG refusal.','outcome':'PASS','check':'PASS','exit_code':0,'output':translation[str(review_dir/'oracle.stdout.txt')],'execution_receipt':translation[str(review_dir/'review.json')],'role':'independent_analytic_and_native_control','expected_negative':False}
])
checks.extend([
 {'name':'interrupted-authorized-forward-merge','command':['git','merge','--no-edit','7185572917f7a3db5e93385a176cb611b35aff42'],'target_sha':'3ad29e43aaa16d2ce320d4b850f8b84f9abdd1e0','environment':{'cwd':str(root),'resource_failure':'overlay filesystem ENOSPC'},'input_closure':'Authorized exact forward merge; 947 actual partial files subsequently preserved and verified. No scientific test ran in partial state.','outcome':'ERROR','check':'ERROR','exit_code':128,'output':translation[str(scratch/'forward-718.stderr.txt')],'role':'historical_engineering_resource_error','expected_negative':False},
 {'name':'append-only-checkout-recovery','command':['git','diff','--exit-code',base,'7185572917f7a3db5e93385a176cb611b35aff42','--'],'target_sha':base,'environment':{'cwd':str(root),'mode':'already-target 947 files custody commit, ordinary no-ff merge, same-pair resume'},'input_closure':'Every actual partial file compared to its immutable root718 target; restored final tree exactly equals root718. Complete per-file binding and recovery/admission logs preserved. Actual full-tree git diff and both immutable tree hashes reconcile every accepted target path; custody/admission operations are additionally retained in recovery metadata and full logs.','outcome':'PASS','check':'PASS','exit_code':0,'output':translation[str(scratch/'recovery-tree-check.json')],'execution_receipt':translation[str(scratch/'recovery-final.json')],'role':'engineering_custody_reconciliation','expected_negative':False}
])
old='3ad29e43aaa16d2ce320d4b850f8b84f9abdd1e0'
d={
 'schema':'policyos.e02.implementation_handoff.v1','unit':'F','slice':'causal-neighbor-fixtures-20261006','role':'companion_consumer_fixture_migration','closure_ids':[],'related_finding_ids':['B216'],'bundle_ids':['GRF-01'],
 'slice_base_sha':base,'entry_source_sha':old,'accepted_shared_dependency_sha':'7185572917f7a3db5e93385a176cb611b35aff42','implementation_commits':[sha],'candidate_tree_sha':tree,'branch':'codex/e02-F-graph-20261006','pull_request':'https://github.com/DenisKopylov/polisyos/pull/62','changed_paths':changed,'source_bindings':source_refs,'baseline_cells':[],'checks':checks,
 'property':{'statement':'Finite supported consumers must execute the intended typed graph and disjoint query, and compiler tests must witness actual rewriting and transferred proofs rather than unavailable skips or non-raising calls.','runtime_path':['Typed CausalGraphModel','Native SID/conditional-ID and AMN separation','Actual rewrite_estimand with typed EstimandAST','compile_estimand consumed rewrite and ExecutorGraph proof steps'],'proxy_divergence':'The old tuple-edge constructor raised with an available model and was converted into SKIP. A compiler that merely returned an ExecutorGraph could pass the old non-raising test without executing Rule1; the marker-kept no-op rewriter now fails the real consumer test.','negative_controls':['Native two-node latent bow produces HEDGE with real certificate/proof','Observed-U collider remains distinct identified positive and reverses separation when U/descendant conditioned','Old AMN endpoint-conditioning request remains explicitFalse','Independent full-support Gaussian laws have identical observed covariance but distinct intervention means','Actual unsupported CPDAG refusal','Marker-retaining compiler prepass removal gives actual1FAIL'],'mechanism_owner':'Existing SID/conditional-ID, AMN and estimand compiler native consumers; only test fixtures/documentation changed.','producer_artifact_bridge_consumer':'Typed CausalGraphModel → maintained SID/conditional-ID and AMN; actual rewrite_estimand → rewritten EstimandAST → compile_estimand → ExecutorGraph proof steps. No new CAS/worker/authority path is introduced.','before':'Original five selectors at exact3ad produced3FAIL/2SKIP; bow fixtures actually contained observed-U bidirected colliders, AMN conditioned on an endpoint, and tuple-edge constructor errors were caught as unavailable.','after':'147 native neighbor cases PASS,0FAIL/SKIP/ERROR; two typed latent-bow controls return HEDGE_FOUND plus native certificate/proof, old observed-U collider remains identified, AMN uses disjoint conditioning and independent latent moralization, compiler performs true Rule1 and exact proof transfer/order.','independent_oracle':'Author hand latent moralization and full-support Gaussian pair beta1/2,3/2; reviewer independently uses beta9/4,-2 and actual native consumer controls. AMN Gaussian covariance computed from independent-source loading vectors.','removal':'Memory-only no-op rewrite preserves callable name/module/docstring and all graph/AST/provider source markers; the real compiler consumer test fails because Z remains in conditioning. Source restored in finally.','P40_bucket':'Verification-fixture semantic mismatch, not a numerical algorithm defect. Correct the fixture to its declared graph/domain and retain the old malformed fixture as characterization.','P41':'not_established; no disjoint full-input denominator is claimed.','production_source_delta':[]},
 'per_id':{'B216':{'check':'PASS','outcome':'limited','scope':'Finite supported native consumer fixture migration only; existing primary finding decisions are not superseded.','full_original_criterion_reassessment':'UNRUN','closure_proposed':False,'negative_control':'Marker-kept prepass removal gives actual1FAIL; independent collider/conditioned-descendant and CPDAG refusal controls retained.','next_owner':'Root/G original-criterion adjudication and integrated checkpoint; no new local production-data requirement for this finite graph property.'}},
 'predicate_basis':'independently_reconciled','predicate_bases':{'fixture_intent':'independently_reconciled','actual_consumer_walk':'recomputed','analytic_reference':'independently_reconciled','real_data_identification_authority':'not_established'},
 'capability_state_or_finding_state':'consumer fixture correction finished; no automatic finding closure, general ID completeness or real-data causal authority',
 'compatibility':{'change_class':'internal','impact':'compatible','public_exports_changed':False,'IR_schema_changed':False,'worker_profile_changed':False,'production_algorithms_changed':False,'generated_inventory_changed':False,'canonical_fragment_check':'PASS'},
 'historical_input_receipts':[
  {**git_ref(old,'policy-engine/docs/research/e02-cloud-test-plan/implementation-handoffs/F/static-admg-profile-20261006.json'),'role':'historical_prior_bounded_native_profile_not_new_closure'},
  {**git_ref(old,'policy-engine/docs/research/e02-cloud-test-plan/implementation-handoffs/F/static-admg-profile-20261006/profile-frozen-neighbors.stdout.txt'),'role':'historical_original133PASS3FAIL2SKIP_not_P41'},
  {**git_ref(old,'policy-engine/docs/plans/active/agent-packages/PolicyOS_E02_Combined_Agent_Package/bundles/GRF-01.md'),'role':'canonical_original_criterion'}],
 'evidence_transfer':{'mode':'Git via fetched topic/PR; chats are not inputs','manifest':manifest,'complete_outputs':True,'lossless':True,'original_output_bytes_preserved':True},
 'limitations_and_next_owner':['General ID/IDC/PAG/CPDAG/temporal completeness is not established by these finite graphs.','No real-data causal effect or positive authority admission is measured.','Historical sourceFAIL/SKIP, engineeringENOSPC ERROR and expected property-removalFAIL are separately retained, never converted into PASS.','No new full architecture/schema/docs/wheel/worker wave was run for this test-only delta. Existing primary receipts retain their source-specific scopes.','G remains publisher of integrated acceptance/formal original-criterion decisions; this companion proposes closure_ids=[].' ]
}
p=root/'policy-engine/docs/research/e02-cloud-test-plan/implementation-handoffs/F/causal-neighbor-fixtures-20261006.json';p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n')
# Hash every copied byte at construction; all copies are immutable deciding outputs/replayers.
for r in manifest:
 b=(root/r['path']).read_bytes();assert len(b)==r['bytes'] and hashlib.sha256(b).hexdigest()==r['sha256']
print(json.dumps({'path':str(p),'bytes':p.stat().st_size,'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'checks':len(checks),'companions':len(manifest),'companion_bytes':sum(r['bytes'] for r in manifest),'source_sha':sha,'source_tree':tree,'independent_review_bytes':(review_dir/'review.json').stat().st_size}))
