apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.server.serviceAccountName }}
  namespace: {{ .Values.namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.agent.serviceAccountName }}
  namespace: {{ .Values.namespace }}
