"""Read the completed default architecture gate; retain identities, not generated bytes."""
from pathlib import Path
import hashlib,json,re,tomllib
out=Path('/workspace/orch02-r2/c05/required-architecture-full-5ccbfa15')
repo=Path('/workspace/orch02-c05/policy-engine')
r=json.loads((out/'command.json').read_text())
assert r['state']=='COMPLETED'
assert r['source_binding_intact'] and r['tracked_python_inputs_intact']
assert r['source_before']['sha']=='5ccbfa15c5671623a4c1ff7a3145460c5ca5a857'
assert '--skip-generated-checks' not in r['argv']
text=(out/'stdout.txt').read_text();lines=text.splitlines()
workspace=Path(r['generated_freshness_workspace'])
def identity(p):
 b=p.read_bytes();return {'bytes':len(b),'sha256':hashlib.sha256(b).hexdigest()}
manifest=tomllib.loads((repo/'architecture/generated_artifacts.toml').read_text())
families=[f for f in manifest['family'] if f.get('default_freshness_check',False) or f['source_of_truth']=='schemas/runtime_api_v1.openapi.json']
assert len(families)==4
rows=[];all_outputs=[]
for f in families:
 name=f['id'];root=workspace/'outputs'/name
 unrun=[x for x in lines if x.startswith(f'- UNRUN {name} ')]
 findings=[x for x in lines if x.startswith(f'- {name} ')]
 outputs=[]
 for p in sorted(root.rglob('*')):
  if not p.is_file():continue
  rel=p.relative_to(root).as_posix();current=repo/rel
  row={'family':name,'path':rel,'generated':identity(p),'current':identity(current) if current.is_file() else None,'matches_current':current.is_file() and p.read_bytes()==current.read_bytes()}
  outputs.append(row);all_outputs.append(row)
 clean=[x for x in lines if x.startswith(f'Generated artifact freshness clean: {name} ')]
 status='UNRUN' if unrun else 'FAIL' if findings else 'PASS' if clean else 'UNESTABLISHED'
 rows.append({'family':name,'status':status,'unrun_rows':unrun,'finding_rows':findings,'clean_rows':clean,'declared_outputs':f['outputs'],'declared_output_probe_command':f['output_probe_command'],'output_count':len(outputs),'outputs':outputs})
deep=[x for x in lines if x.startswith('- New deep-import creep detected:')]
ownedpaths=['src/polisyos/data_forge/domains/catalog/batch/config.py','src/polisyos/data_forge/domains/catalog/batch/core_sources/loaders.py','src/polisyos/fabric/retrieval/service.py']
owned=[x for x in deep if any(f'({p})' in x for p in ownedpaths)]
issues=[x for x in lines if re.match(r'^- [A-Za-z]',x) and not x.startswith('- UNRUN ')]
inputs=json.loads((out/'inputs-before.json').read_text())
copy_mismatches=[]
for path,binding in inputs.items():
 rel=path.removeprefix('policy-engine/');p=workspace/'source'/rel
 if not p.is_file() or identity(p)!=binding:copy_mismatches.append(path)
config_paths=['architecture/generated_artifacts.toml','architecture/public_surface/contract.toml','architecture/public_surface/inventory.json','architecture/baselines/imports/deep_import.json','architecture/exceptions/guardrails.toml','architecture/guardrail_exceptions_registry.md','pyproject.toml','uv.lock','pnpm-lock.yaml','package.json','tools/devx/architecture/guardrails.py']
configs=[]
for path in config_paths:
 p=repo/path;q=workspace/'source'/path
 configs.append({'path':path,'current':identity(p),'copied_source':identity(q) if q.is_file() else None,'equal':q.is_file() and p.read_bytes()==q.read_bytes()})
x={'schema':'policyos.e02.c05.full-default-architecture-readback.v1','source_sha':r['source_before']['sha'],'source_tree':r['source_before']['tree'],'outcome':'PASS' if r['returncode']==0 else 'UNRUN' if r['returncode']==2 else 'FAIL' if r['returncode']==1 else 'ERROR','actual_returncode':r['returncode'],'wall_seconds':r['wall_seconds'],'max_rss_kib':r['max_rss_kib'],'command':'command.json','all_default_families_enabled':True,'stdout':identity(out/'stdout.txt'),'stderr':identity(out/'stderr.txt'),'stdout_line_count':len(lines),'source_clean_before_after':r['source_before']['status']==r['source_after']['status']=='','all_tracked_python_inputs_intact':r['tracked_python_inputs_intact'],'private_copied_python_input_count':len(inputs),'private_copied_python_mismatches':copy_mismatches,'total_issue_rows':len(issues),'baseline_drift_rows':[x for x in issues if x.startswith('- Deep-import baseline drift')],'deep_import_count':len(deep),'owned_deep_import_edges':owned,'other_deep_import_edges':len(deep)-len(owned),'all_other_issue_rows':[x for x in issues if x not in deep],'families':rows,'family_status_counts':{s:sum(y['status']==s for y in rows) for s in ['PASS','FAIL','UNRUN','UNESTABLISHED']},'output_file_denominator':len(all_outputs),'full_default_UNRUN_rows':[x for x in lines if x.startswith('- UNRUN ')],'family_isolation_escape_rows':[x for x in issues if 'outside its assigned scratch root' in x],'config_input_bindings':configs,'optional_or_standalone_Atlas_included':False,'P41':'not_established; no inherited-green attribution','private_snapshots_and_generated_bytes_not_published':True,'client_dashboard_qualification':'Successful generation compares each family to committed schema input; this is not a refreshed downstream chain from separately regenerated OpenAPI.'}
(out/'scoped-readback.json').write_text(json.dumps(x,indent=2)+'\n')
print(json.dumps({k:x[k] for k in ['outcome','actual_returncode','wall_seconds','max_rss_kib','total_issue_rows','deep_import_count','family_status_counts','output_file_denominator','private_copied_python_mismatches']}))
