"""Synthetic transport metadata control only; no product/science/source mutation."""
from pathlib import Path
import gzip,hashlib,json,subprocess,sys
base=Path(__file__).resolve().parent;probe=base/'utility-probe';probe.mkdir();source=probe/'inputs';source.mkdir();old=b'old\n';new=b'new\n';alpha=source/'alpha.txt';beta=source/'beta.txt';alpha.write_bytes(old);beta.write_bytes(old)
def ref(p):return {'bytes':p.stat().st_size,'sha256':hashlib.sha256(p.read_bytes()).hexdigest()}
prefix='policy-engine/docs/research/e02-cloud-test-plan/implementation-handoffs/F/continuation-closeout-20261007';target=prefix+'/companions/alpha.txt.gz';stage=probe/'prior-stage';archive=stage/target;archive.parent.mkdir(parents=True);archive.write_bytes(gzip.compress(old,mtime=0));raw={'bytes':len(old),'sha256':hashlib.sha256(old).hexdigest()}
seed={'draft':True,'source_window':{'scope':'Synthetic metadata alias/custody test; not domain or scientific evidence.'},'logical_files':[{'original_path':str(alpha),**raw,'disposition':'transport','target_path':target,'encoding':'gzip','role':'synthetic metadata'},{'original_path':str(beta),**raw,'disposition':'alias','canonical_original_path':str(alpha),'role':'synthetic metadata'}],'selection_inputs':[],'existing_declared_git_references':[],'pending_extensions':[],'policy':{'scope':'Synthetic metadata control only'}}
manifest={'files':[{'original_path':str(alpha),'path':target,'encoding':'gzip',**ref(archive),'decoded_bytes':raw['bytes'],'decoded_sha256':raw['sha256']}],'aliases':[{'original_path':str(beta),'stored_path':target}], 'existing_git_files':[]}
(probe/'seed.json').write_text(json.dumps(seed));(probe/'prior-manifest.json').write_text(json.dumps(manifest));alpha.write_bytes(new)
argv=[sys.executable,str(base/'refresh_selection.py'),'--seed-selection',str(probe/'seed.json'),'--prior-manifest',str(probe/'prior-manifest.json'),'--prior-staging-root',str(stage),'--repository','/workspace/e02-F-closeout-20261006','--final-source-sha','d8334672f44d24dd32113264f96ca3f7954dace4','--output',str(probe/'refreshed.json')]
r=subprocess.run(argv,capture_output=True);(probe/'refresh.stdout.json').write_bytes(r.stdout);(probe/'refresh.stderr.txt').write_bytes(r.stderr);assert r.returncode==0,r.stderr
result=json.loads((probe/'refreshed.json').read_bytes());assert result['counts']['changed_prior_inputs']==1;assert len(result['refresh']['retained_prior_custody'])==1
argv2=[sys.executable,str(base/'publish_transport_v2.py'),'--selection',str(probe/'refreshed.json'),'--repository','/workspace/e02-F-closeout-20261006','--materialize','--destination',str(probe/'staged-v2')]
r2=subprocess.run(argv2,capture_output=True);(probe/'publish.stdout.json').write_bytes(r2.stdout);(probe/'publish.stderr.txt').write_bytes(r2.stderr);assert r2.returncode==0,r2.stderr
actual=json.loads((probe/'staged-v2'/prefix/'artifact-transports.json').read_bytes());prior=next(row for row in actual['files'] if row.get('input_encoding')=='gzip');assert gzip.decompress((probe/'staged-v2'/prior['path']).read_bytes())==old;assert any(row['original_path']==str(beta) and row['decoded_sha256']==raw['sha256'] for row in actual['aliases']);assert alpha.read_bytes()==new and beta.read_bytes()==old and gzip.decompress(archive.read_bytes())==old
print(json.dumps({'scope':'Only own synthetic metadata aliases/custody, not scientific/domain fixtures','outcome':'PASS','changed_original_retains_complete_old_gzip_bytes':True,'unchanged_old_alias_rebinds_to_complete_prior_stream':True,'new_input_binds_new_bytes':True,'selection_transport_nonrecursive':actual['frozen_publisher_input'],'source_or_Git_writes':False,'commands':[argv,argv2],'raw_outputs':[{'path':str(probe/name),**ref(probe/name)} for name in ['refresh.stdout.json','refresh.stderr.txt','publish.stdout.json','publish.stderr.txt']]},indent=2))
