#!/usr/bin/env python3
"""
CLI scaffold generator for Policy OS connectors.

Generates a compliant, test-ready connector skeleton that passes
ConnectorTestHarness out of the box.
"""
from __future__ import annotations

import argparse
import re
import sys
import textwrap
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent.parent
SOURCE_DIR = REPO_ROOT / "src" / "polisyos" / "fabric" / "connectors" / "sources"
TEST_DIR = REPO_ROOT / "tests" / "fabric" / "connectors" / "sources"

VALID_TYPES = ("REST", "CSV", "SQL", "SDMX")


def to_snake_case(name: str) -> str:
    s1 = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", name)
    s2 = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1_\2", s1)
    return s2.lower().replace("-", "_").replace(" ", "_")


def to_class_name(name: str) -> str:
    clean = re.sub(r"[Cc]onnector$", "", name)
    parts = re.split(r"[_\-\s]+", clean)
    return "".join(part.capitalize() for part in parts if part) + "Connector"


def _source_template(class_name: str, snake_name: str, connector_type: str) -> str:
    capability_map = {
        "REST": (
            "ConnectorCapability.FULL_FETCH\n"
            "        | ConnectorCapability.DATE_RANGE_FILTER\n"
            "        | ConnectorCapability.RATE_LIMIT_AWARE"
        ),
        "CSV": (
            "ConnectorCapability.FULL_FETCH\n"
            "        | ConnectorCapability.SCHEMA_INTROSPECTION"
        ),
        "SQL": (
            "ConnectorCapability.FULL_FETCH\n"
            "        | ConnectorCapability.DATE_RANGE_FILTER\n"
            "        | ConnectorCapability.SCHEMA_INTROSPECTION"
        ),
        "SDMX": (
            "ConnectorCapability.FULL_FETCH\n"
            "        | ConnectorCapability.CATALOG_BROWSE\n"
            "        | ConnectorCapability.STREAMING\n"
            "        | ConnectorCapability.FRESHNESS_CHECK"
        ),
    }
    capabilities = capability_map.get(connector_type, capability_map["REST"])

    optional_stubs = {
        "REST": "",
        "CSV": textwrap.dedent('''
            async def get_dataset_schema(
                self, handle: ConnectionHandle, dataset_id: str
            ) -> "DataSchema":
                """Introspect the schema of a CSV dataset."""
                raise NotImplementedError("TODO: implement schema introspection")
        '''),
        "SQL": textwrap.dedent('''
            async def get_dataset_schema(
                self, handle: ConnectionHandle, dataset_id: str
            ) -> "DataSchema":
                """Introspect the schema via SQL INFORMATION_SCHEMA."""
                raise NotImplementedError("TODO: implement schema introspection")
        '''),
        "SDMX": textwrap.dedent('''
            async def list_datasets(
                self, handle: ConnectionHandle
            ) -> "AsyncIterator[DatasetDescriptor]":
                """Browse available SDMX dataflows."""
                raise NotImplementedError("TODO: implement catalog browsing")
                yield  # make this an async generator  # noqa: unreachable

            async def fetch_stream(
                self, handle: ConnectionHandle, request: FetchRequest
            ) -> "AsyncIterator[DataChunk]":
                """Stream SDMX observations."""
                raise NotImplementedError("TODO: implement streaming")
                yield  # noqa: unreachable

            async def check_freshness(
                self, handle: ConnectionHandle, dataset_id: str, cached_version: "DataVersion"
            ) -> "FreshnessStatus":
                """Check if cached data is stale."""
                raise NotImplementedError("TODO: implement freshness check")
        '''),
    }
    extra_stubs = optional_stubs.get(connector_type, "")

    return textwrap.dedent(f'''\
        # src/polisyos/fabric/connectors/sources/{snake_name}.py
        """
        {class_name} - a {connector_type}-based data connector.

        Generated by ``tools/connectors/scaffold.py``.
        Fill in the TODO sections before registering.

        Laws:
            - Law A: This module must NOT import from scientist.* or foundry.*.
            - Law D: fetch() must return a FetchResult with provenance.
            - Law E: evidence_ref must be populated (or delegated to the registry).
        """
        from __future__ import annotations

        from datetime import datetime, timezone
        from typing import ClassVar

        from polisyos.fabric.connectors.base import (
            BaseConnector,
            ConnectionConfig,
            ConnectionHandle,
            FetchRequest,
            FetchResult,
            HealthStatus,
        )
        from polisyos.fabric.connectors.types import ValidationResult
        from polisyos.ir.connectors import (
            ConnectorCapability,
            ConnectorMetadataSpec,
            DataVersion,
            QualityTier,
            TrustLevel,
            VersionStrategy,
        )


        class {class_name}(BaseConnector[list[dict]]):
            """
            Connector for <TODO: describe your data source>.

            Capabilities: {connector_type}-style access.
            """

            namespace: ClassVar[str] = "custom"
            short_id: ClassVar[str] = "{snake_name}"
            connector_id: ClassVar[str] = f"{{namespace}}.{{short_id}}"
            capabilities: ClassVar[ConnectorCapability] = (
                {capabilities}
            )
            metadata: ClassVar[ConnectorMetadataSpec] = ConnectorMetadataSpec(
                connector_id=short_id,
                version="0.1.0",
                namespace=namespace,
                source_name="<TODO: human-readable source name>",
                source_organization="<TODO: your organization>",
                trust_level=TrustLevel.MEDIUM,
                quality_tier=QualityTier.SILVER,
                capabilities=capabilities,
            )

            async def connect(self, config: ConnectionConfig) -> ConnectionHandle:
                """Establish connection and validate credentials."""
                return self._create_handle(config)

            async def disconnect(self, handle: ConnectionHandle) -> None:
                """Release resources."""
                pass

            async def health_check(self, handle: ConnectionHandle) -> HealthStatus:
                """Probe the upstream source."""
                return HealthStatus(healthy=True, message="OK")

            async def fetch(
                self,
                handle: ConnectionHandle,
                request: FetchRequest,
            ) -> FetchResult[list[dict]]:
                """
                Fetch data matching *request*.

                Returns a FetchResult with row_count, schema refs, and
                a DataVersion for caching / provenance.
                """
                raise NotImplementedError(
                    f"{{self.__class__.__name__}}.fetch() is not yet implemented. "
                    f"Requested dataset: {{request.dataset_id}}"
                )

            @classmethod
            def validate_config(cls, config: ConnectionConfig) -> ValidationResult:
                """Validate connection config at registration time."""
                return ValidationResult.success()
        {extra_stubs}
    ''')


def _test_template(class_name: str, snake_name: str) -> str:
    return textwrap.dedent(f'''\
        # tests/fabric/connectors/sources/test_{snake_name}.py
        """
        Compliance tests for {class_name}.

        Inherits the full ConnectorTestHarness suite (Phase 2.10),
        providing protocol compliance, lifecycle, fetch, and schema
        validation tests automatically.
        """
        from __future__ import annotations

        from typing import ClassVar

        import pytest

        from polisyos.fabric.connectors.base import (
            ConnectionConfig,
            FetchRequest,
        )
        from polisyos.fabric.connectors.contracts.schema import (
            DataSchema,
            FieldSpec,
            SchemaType,
            SchemaVersion,
        )
        from polisyos.fabric.connectors.testing import ConnectorTestHarness
        from polisyos.fabric.connectors.sources.{snake_name} import {class_name}


        _SAMPLE_SCHEMA = DataSchema(
            schema_id="custom.{snake_name}.dataset",
            version=SchemaVersion(0, 1, 0),
            fields=(
                FieldSpec(name="id", data_type=SchemaType.INT64, nullable=False),
                FieldSpec(name="value", data_type=SchemaType.FLOAT64, nullable=True),
            ),
            primary_key=("id",),
        )


        @pytest.mark.asyncio
        class Test{class_name}Compliance(ConnectorTestHarness):
            connector_class: ClassVar = {class_name}
            sample_config: ClassVar = ConnectionConfig(
                url="http://localhost:9999/{snake_name}",
            )
            sample_schema: ClassVar = _SAMPLE_SCHEMA
            sample_request: ClassVar = FetchRequest(
                dataset_id="custom.{snake_name}.dataset",
            )


        class Test{class_name}SourceSpecific:
            def test_placeholder(self) -> None:
                assert True
    ''')


def _create(args: argparse.Namespace) -> int:
    snake = to_snake_case(args.name)
    class_name = to_class_name(args.name)

    source_path = SOURCE_DIR / f"{snake}.py"
    test_path = TEST_DIR / f"test_{snake}.py"

    source_content = _source_template(class_name, snake, args.type.upper())
    test_content = _test_template(class_name, snake)

    if args.dry_run:
        print(f"\n{'=' * 70}")
        print("  DRY RUN - scaffold would create the following files:")
        print(f"{'=' * 70}\n")
        print(f"  {source_path}")
        print(f"  {test_path}")
        print(f"\n--- {source_path} ---\n")
        print(source_content)
        print(f"\n--- {test_path} ---\n")
        print(test_content)
        return 0

    source_path.parent.mkdir(parents=True, exist_ok=True)
    test_path.parent.mkdir(parents=True, exist_ok=True)

    if source_path.exists() and not args.force:
        print(f"Error: '{source_path}' already exists. Use --force to overwrite.", file=sys.stderr)
        return 2
    if test_path.exists() and not args.force:
        print(f"Error: '{test_path}' already exists. Use --force to overwrite.", file=sys.stderr)
        return 2

    source_path.write_text(source_content, encoding="utf-8")
    test_path.write_text(test_content, encoding="utf-8")

    print("\nConnector scaffold created successfully.\n")
    print(f"   Source : {source_path}")
    print(f"   Test   : {test_path}")
    print(f"   Class  : {class_name}")
    print(f"   ID     : custom.{snake}")
    print("\nNext steps:")
    print(f"   1. Fill in the TODO sections in {source_path.name}")
    print("   2. Run: python tools/lint/lint_connectors.py")
    print(f"   3. Run: pytest {test_path} -v")
    print("   4. Register in ConnectorRegistry (see docs/connectors/CONTRIBUTING.md)")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(
        prog="scaffold",
        description="Generate compliant Policy OS connector skeletons.",
    )
    subparsers = parser.add_subparsers(dest="command", help="Available commands.")

    create_parser = subparsers.add_parser(
        "create",
        help="Generate a new connector skeleton.",
    )
    create_parser.add_argument(
        "--name",
        required=True,
        help="Connector name in CamelCase (e.g. 'MySource', 'WorldBankGDP').",
    )
    create_parser.add_argument(
        "--type",
        required=True,
        choices=VALID_TYPES,
        help="Connector type - controls which capability stubs are generated.",
    )
    create_parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print generated files without writing them.",
    )
    create_parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing files.",
    )

    args = parser.parse_args()

    if args.command is None:
        parser.print_help()
        return 2

    if args.command == "create":
        return _create(args)

    return 2


if __name__ == "__main__":
    sys.exit(main())
