apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "polisyos-cell.fullname" . }}-security-note
  namespace: {{ include "polisyos-cell.namespaceName" . }}
  labels:
    {{- include "polisyos-cell.labels" . | nindent 4 }}
data:
  pss: "Namespace labels enforce Pod Security Standard: {{ .Values.podSecurityStandard.enforce }}"
