{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rbac.serviceAccountName }}
  namespace: {{ include "polisyos-cell.namespaceName" . }}
  labels:
    {{- include "polisyos-cell.labels" . | nindent 4 }}
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "polisyos-cell.fullname" . }}-role
  namespace: {{ include "polisyos-cell.namespaceName" . }}
  labels:
    {{- include "polisyos-cell.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets", "pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "polisyos-cell.fullname" . }}-binding
  namespace: {{ include "polisyos-cell.namespaceName" . }}
  labels:
    {{- include "polisyos-cell.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.rbac.serviceAccountName }}
    namespace: {{ include "polisyos-cell.namespaceName" . }}
roleRef:
  kind: Role
  name: {{ include "polisyos-cell.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
