import ast
from _typeshed import Incomplete
from collections.abc import Callable, Mapping
from dataclasses import dataclass, field
from enum import Enum
from polisyos.core.observability.determinism import DeterminismTier
from polisyos.ir.analytics.uncertainty import OutputContractCapability
from typing import Any, ClassVar, Protocol, TypeVar

def is_valid_semver(version: str) -> bool: ...
def parse_fqn(fqn: str) -> tuple[str, str, str]: ...

class FidelityLevel(Enum):
    LOW: Incomplete
    MEDIUM: Incomplete
    HIGH: Incomplete

class ComplexityClass(Enum):
    O_1: Incomplete
    O_LOG_N: Incomplete
    O_N: Incomplete
    O_N2: Incomplete
    O_N3: Incomplete
    O_EXP: Incomplete

class SlotType(Enum):
    SCALAR: Incomplete
    VECTOR: Incomplete
    MATRIX: Incomplete
    TENSOR: Incomplete

class ComputeBackend(str, Enum):
    JAX: str
    NUMPY: str
    SOLVER: str
    BAYESIAN: str

class MethodKind(str, Enum):
    PURE: str
    MECHANISM: str
    SIMULATION: str

class SideEffectProfile(str, Enum):
    NONE: str
    PATCH_EMISSION: str
    ARTIFACT_EMISSION: str
    TRAINING: str

@dataclass(frozen=True, slots=True)
class Unit:
    dimension: str
    symbol: str
    scale: float = ...
    def __post_init__(self) -> None: ...
    def is_compatible(self, other: Unit) -> bool: ...
    def stable_digest(self) -> str: ...
    def __hash__(self) -> int: ...

@dataclass(frozen=True)
class DimVar:
    name: str
    def __post_init__(self) -> None: ...
DimExpr = int | str | DimVar | None
Shape = tuple[DimExpr, ...]

@dataclass(frozen=True, slots=True)
class SlotSpec:
    name: str
    slot_type: SlotType
    unit: Unit
    contract_id: str | None = ...
    shape: Shape = ...
    description: str = ...
    bounds: tuple[float | int | None, float | int | None] = ...
    contract_capabilities: frozenset[OutputContractCapability] = ...
    contract_owner: str | None = ...
    def __post_init__(self) -> None: ...
    @classmethod
    def for_output_contract(cls, name: str, slot_type: SlotType, unit: Unit, *, output_contract: type[object], shape: Shape = (), description: str = '', bounds: tuple[float | int | None, float | int | None] = (None, None)) -> SlotSpec: ...
    def stable_digest(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...

@dataclass(frozen=True, slots=True)
class ParameterSpec:
    name: str
    default: Any
    is_static: bool = ...
    bounds: tuple[float | int | None, float | int | None] = ...
    description: str = ...
    def __post_init__(self) -> None: ...
    def stable_digest(self) -> str: ...
    def __hash__(self) -> int: ...

@dataclass(frozen=True, slots=True)
class MethodSignature:
    name: str
    namespace: str
    version: str
    input_slots: frozenset[SlotSpec]
    output_slots: frozenset[SlotSpec]
    parameters: tuple[ParameterSpec, ...]
    fidelity: FidelityLevel
    complexity: ComplexityClass
    backend: ComputeBackend = ...
    kind: MethodKind = ...
    family: str = ...
    variant: str = ...
    data_modalities: frozenset[str] = ...
    fidelity_tier: FidelityLevel | None = ...
    commutes_with: frozenset[str] = ...
    conflicts_with: frozenset[str] = ...
    requires: frozenset[str] = ...
    supports_jit: bool = ...
    supports_vmap: bool = ...
    supports_grad: bool = ...
    def __post_init__(self) -> None: ...
    @property
    def fqn(self) -> str: ...
    @property
    def execution_backend(self) -> ComputeBackend: ...
    @property
    def static_param_names(self) -> frozenset[str]: ...
    @property
    def dynamic_param_names(self) -> frozenset[str]: ...
    @property
    def input_slot_names(self) -> frozenset[str]: ...
    @property
    def output_slot_names(self) -> frozenset[str]: ...
    def get_input_slot(self, name: str) -> SlotSpec | None: ...
    def get_output_slot(self, name: str) -> SlotSpec | None: ...
    def abi_digest(self) -> str: ...
    def stable_digest(self) -> str: ...
    def __hash__(self) -> int: ...

@dataclass(frozen=True)
class MethodContracts:
    preconditions: tuple[str, ...] = ...
    postconditions: tuple[str, ...] = ...
    invariants: tuple[str, ...] = ...
    def __post_init__(self) -> None: ...

@dataclass(frozen=True, slots=True)
class MethodMetadata:
    description: str
    tags: frozenset[str] = ...
    citations: tuple[str, ...] = ...
    equations: Mapping[str, str] = field(default_factory=dict)
    assumptions: Mapping[str, str] = field(default_factory=dict)
    simulator_regime_schema: Mapping[str, Any] = field(default_factory=dict)
    summary_schema_ref: str | None = ...
    identifiable_target: Mapping[str, Any] = field(default_factory=dict)
    coverage_contract: Mapping[str, Any] = field(default_factory=dict)
    diagnostic_contract: Mapping[str, Any] = field(default_factory=dict)
    determinism_tier: DeterminismTier | None = ...
    declared_truthfulness_tier: str | None = ...
    truthfulness_scope: str | None = ...
    required_deps: tuple[str, ...] = ...
    optional_deps: tuple[str, ...] = ...
    fallback_policy: str = ...
    side_effect_profile: SideEffectProfile = ...
    contracts: MethodContracts | None = ...
    when_to_use: str = ...
    when_not_to_use: str = ...
    prerequisites: tuple[str, ...] = ...
    diagnostic_checks: tuple[str, ...] = ...
    typical_min_obs: int | None = ...
    output_interpretation: str = ...
    def __post_init__(self) -> None: ...
    def stable_digest(self) -> str: ...
    def __hash__(self) -> int: ...
StateT = TypeVar('StateT')
ParamsT = TypeVar('ParamsT', bound=Mapping[str, Any])

class FoundryMethod(Protocol[StateT, ParamsT]):
    signature: ClassVar[MethodSignature]
    metadata: ClassVar[MethodMetadata]
    @staticmethod
    def pure_step(state: StateT, params: ParamsT) -> StateT: ...
    @staticmethod
    def materialize_input(bound_inputs: Mapping[str, Any], fallback_state: Any) -> Any: ...
    @staticmethod
    def dematerialize_output(output: Any) -> Mapping[str, Any]: ...

def foundry_method(*, namespace: str, version: str = '1.0.0', tags: set[str] | None = None) -> Callable[[type], type]: ...

class _ContractExpressionValidator(ast.NodeVisitor):
    expression: Incomplete
    allow_result: Incomplete
    allowed_names: Incomplete
    def __init__(self, expression: str, *, allow_result: bool) -> None: ...
    def generic_visit(self, node: ast.AST) -> None: ...
    def visit_Expression(self, node: ast.Expression) -> None: ...
    def visit_BoolOp(self, node: ast.BoolOp) -> None: ...
    def visit_UnaryOp(self, node: ast.UnaryOp) -> None: ...
    def visit_BinOp(self, node: ast.BinOp) -> None: ...
    def visit_Compare(self, node: ast.Compare) -> None: ...
    def visit_Call(self, node: ast.Call) -> None: ...
    def visit_Attribute(self, node: ast.Attribute) -> None: ...
    def visit_Subscript(self, node: ast.Subscript) -> None: ...
    def visit_Slice(self, node: ast.Slice) -> None: ...
    def visit_Name(self, node: ast.Name) -> None: ...
    def visit_Constant(self, node: ast.Constant) -> None: ...
    def visit_List(self, node: ast.List) -> None: ...
    def visit_Tuple(self, node: ast.Tuple) -> None: ...

def check_protocol_compliance(cls) -> list[str]: ...

class FoundryMethodBase:
    def __init_subclass__(cls, skip_abi_check: bool = False, **kw: Any) -> None: ...
