"""
Type stubs for polisyos.foundry.methods.composer — Foundry Composer ABI.

Generated by polisyos-tools foundry generate-stubs. Do not edit manually.
Re-generate with: uv run polisyos-tools foundry generate-stubs
"""

from __future__ import annotations

from collections.abc import Iterator, Mapping
from dataclasses import dataclass
from typing import Any
from uuid import UUID

from polisyos.foundry.methods.backends.chain_executor import ExecutorMode, FxRateProvider
from polisyos.foundry.methods.base import MethodSignature
from polisyos.foundry.methods.linker import LinkResult, SlotBinding
from polisyos.foundry.methods.registry import MethodRegistry

__all__ = [
    "CompiledMethodChain",
    "CompositionDAG",
    "MethodComposer",
    "MethodNode",
]

# ---------------------------------------------------------------------------
# Node key
# ---------------------------------------------------------------------------

@dataclass(frozen=True, slots=True, order=True)
class NodeKey:
    method_fqn: str
    static_params_digest: str

# ---------------------------------------------------------------------------
# Method node
# ---------------------------------------------------------------------------

@dataclass(frozen=True, slots=True)
class MethodNode:
    id: UUID
    method_fqn: str
    params: Mapping[str, Any]
    static_params: Mapping[str, Any]
    node_key: NodeKey | None
    instance_index: int
    commutes_with: frozenset[str]
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __repr__(self) -> str: ...

# ---------------------------------------------------------------------------
# Composition DAG (mutable)
# ---------------------------------------------------------------------------

@dataclass(slots=True)
class CompositionDAG:
    nodes: dict[UUID, MethodNode]
    successors: dict[UUID, set[UUID]]
    predecessors: dict[UUID, set[UUID]]
    edges: dict[tuple[UUID, UUID], LinkResult]

    def add_node(self, node: MethodNode) -> None: ...
    def add_edge(self, source_id: UUID, target_id: UUID, link_result: LinkResult) -> None: ...
    def topological_order(
        self, extra_predecessors: Mapping[UUID, set[UUID]] | None = ...
    ) -> list[UUID]: ...
    def get_roots(self) -> list[UUID]: ...
    def get_leaves(self) -> list[UUID]: ...
    def get_edge(self, source_id: UUID, target_id: UUID) -> LinkResult | None: ...
    def compute_parallel_levels(
        self, extra_predecessors: Mapping[UUID, set[UUID]] | None = ...
    ) -> list[list[UUID]]: ...
    def freeze(self) -> FrozenCompositionDAG: ...
    def __len__(self) -> int: ...
    def __contains__(self, node_id: UUID) -> bool: ...

# ---------------------------------------------------------------------------
# Frozen (immutable) DAG snapshot
# ---------------------------------------------------------------------------

@dataclass(frozen=True, slots=True)
class FrozenCompositionDAG:
    nodes: Mapping[UUID, MethodNode]
    successors: Mapping[UUID, frozenset[UUID]]
    predecessors: Mapping[UUID, frozenset[UUID]]
    edges: Mapping[tuple[UUID, UUID], LinkResult]

    def get_edge(self, source_id: UUID, target_id: UUID) -> LinkResult | None: ...
    def get_roots(self) -> list[UUID]: ...
    def get_leaves(self) -> list[UUID]: ...
    def __len__(self) -> int: ...
    def __contains__(self, node_id: UUID) -> bool: ...

# ---------------------------------------------------------------------------
# Composer (builder)
# ---------------------------------------------------------------------------

class MethodComposer:
    def __init__(
        self,
        registry: MethodRegistry | None = ...,
        linker: object | None = ...,
    ) -> None: ...
    @property
    def dag(self) -> CompositionDAG: ...
    def add(self, method_name: str, **params: Any) -> MethodNode: ...
    def connect(
        self,
        source: MethodNode,
        target: MethodNode,
        slot_mapping: Mapping[str, str] | None = ...,
    ) -> LinkResult: ...
    def validate(self) -> list[str]: ...
    def build(self, *, validate_semantics: bool = ...) -> CompiledMethodChain: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...

# ---------------------------------------------------------------------------
# Compiled chain (immutable output of build())
# ---------------------------------------------------------------------------

@dataclass(frozen=True, slots=True)
class CompiledMethodChain:
    dag: FrozenCompositionDAG
    signatures: Mapping[UUID, MethodSignature]
    execution_order: tuple[UUID, ...]
    bindings: tuple[SlotBinding, ...]
    warnings: tuple[str, ...]

    def methods_in_order(self) -> Iterator[tuple[UUID, MethodSignature]]: ...
    def get_node(self, node_id: UUID) -> MethodNode: ...
    def get_signature(self, node_id: UUID) -> MethodSignature: ...
    def get_bindings_for_target(self, target_id: UUID) -> list[SlotBinding]: ...
    def execute_heterogeneous(
        self,
        *,
        state: Any,
        params_per_node: Mapping[UUID, Mapping[str, Any]] | None = ...,
        seed: int = ...,
        registry: MethodRegistry | None = ...,
        executor_mode: ExecutorMode = ...,
        async_node_timeout_sec: float | None = ...,
        fx_rate_provider: FxRateProvider | None = ...,
    ) -> Any: ...
    @property
    def has_warnings(self) -> bool: ...
    @property
    def fqn_order(self) -> list[str]: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
