"""
Type stubs for polisyos.foundry.methods.registry — Foundry Registry ABI.

Generated by polisyos-tools foundry generate-stubs. Do not edit manually.
Re-generate with: uv run polisyos-tools foundry generate-stubs
"""

from __future__ import annotations

from collections.abc import Callable, Generator, Iterator
from contextlib import contextmanager
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from polisyos.foundry.methods.base import (
    FoundryMethod,
    MethodMetadata,
    MethodSignature,
)
from polisyos.foundry.methods.lifecycle import LifecycleLog
from polisyos.foundry.methods.resolution import ResolutionPolicy, VersionConstraint

# ---------------------------------------------------------------------------
# Types
# ---------------------------------------------------------------------------

MethodFactory = Callable[[], type[FoundryMethod]]

# ---------------------------------------------------------------------------
# Audit log
# ---------------------------------------------------------------------------

@dataclass(slots=True)
class RegistryAuditEvent:
    event: str
    fqn: str
    timestamp: float
    caller: str
    details: dict[str, Any]

class RegistryAuditLog:
    def record(self, event: str, fqn: str, caller: str = ..., **details: object) -> None: ...
    def get_history(self, fqn: str | None = ...) -> list[RegistryAuditEvent]: ...
    def clear(self) -> None: ...
    def export_jsonl(self, path: Path) -> None: ...
    def __len__(self) -> int: ...

def get_registry_audit_log() -> RegistryAuditLog: ...

# ---------------------------------------------------------------------------
# Registry entry
# ---------------------------------------------------------------------------

@dataclass(slots=True)
class MethodEntry:
    signature: MethodSignature
    metadata: MethodMetadata
    factory: MethodFactory
    loaded: bool
    lifecycle_log: LifecycleLog
    @property
    def fqn(self) -> str: ...

@dataclass(slots=True)
class RegistrySnapshotEntry:
    signature: MethodSignature
    metadata: MethodMetadata
    loaded: bool
    import_module: str | None
    import_qualname: str | None
    @property
    def fqn(self) -> str: ...
    @property
    def persistable_import_target(self) -> tuple[str, str] | None: ...

# ---------------------------------------------------------------------------
# Snapshot
# ---------------------------------------------------------------------------

class RegistrySnapshot:
    @property
    def timestamp(self) -> float: ...
    def signatures(self) -> Iterator[MethodSignature]: ...
    def entries(self) -> Iterator[RegistrySnapshotEntry]: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[str]: ...

# ---------------------------------------------------------------------------
# Registry
# ---------------------------------------------------------------------------

class MethodRegistry:
    @classmethod
    def get_instance(cls) -> MethodRegistry: ...
    @classmethod
    def reset_instance(cls) -> None: ...

    # Configuration
    def set_default_policy(self, policy: ResolutionPolicy) -> None: ...
    def get_default_policy(self) -> ResolutionPolicy: ...

    # Registration
    def register(self, method_class: type[FoundryMethod], *, override: bool = ...) -> str: ...
    def register_lazy(
        self,
        signature: MethodSignature,
        metadata: MethodMetadata,
        factory: MethodFactory,
        *,
        override: bool = ...,
        import_target: tuple[str, str] | str | None = ...,
    ) -> str: ...
    def unregister(self, fqn: str) -> bool: ...

    # Retrieval
    def get(
        self,
        name: str,
        version: str | None = ...,
        *,
        policy: ResolutionPolicy | None = ...,
        constraint: VersionConstraint | None = ...,
    ) -> type[FoundryMethod]: ...
    def get_entry(self, fqn: str) -> MethodEntry | None: ...
    def get_signature(self, fqn: str) -> MethodSignature | None: ...

    # Queries
    def query(
        self,
        *,
        namespace: str | None = ...,
        tags: set[str] | None = ...,
        input_slots: set[str] | None = ...,
        output_slots: set[str] | None = ...,
        name_pattern: str | None = ...,
    ) -> Iterator[MethodSignature]: ...
    def find_by_output_slot(self, slot_name: str) -> Iterator[MethodSignature]: ...
    def find_by_input_slot(self, slot_name: str) -> Iterator[MethodSignature]: ...
    def find_connectable(self, source_fqn: str) -> Iterator[MethodSignature]: ...

    # Listing
    def list_all(self) -> list[MethodSignature]: ...
    def list_versions(self, base_name: str) -> list[str]: ...
    def list_namespaces(self) -> list[str]: ...
    def list_tags(self) -> list[str]: ...
    def snapshot(self) -> RegistrySnapshot: ...
    def stats(self) -> dict[str, Any]: ...

    # Container protocol
    def __len__(self) -> int: ...
    def __contains__(self, fqn: str) -> bool: ...
    def __iter__(self) -> Iterator[str]: ...
    def __repr__(self) -> str: ...

# ---------------------------------------------------------------------------
# Context helpers
# ---------------------------------------------------------------------------

@contextmanager
def registry_scope() -> Generator[MethodRegistry]: ...
def get_registry() -> MethodRegistry: ...
