"""Flattened facade for spatial methods catalog."""

from polisyos.foundry.methods.catalog.spatial import (
    AccessibilityData,
    AccessibilityIndexEstimator,
    GaussianProcessKrigingEstimator,
    GravityFlowData,
    GravityModelEstimator,
    GWREstimator,
    InverseDistanceWeightingEstimator,
    MAUPSensitivityProfileEstimator,
    MoranIEstimator,
    SpatialData,
    SpatialDurbinEstimator,
    SpatialMicrosimulationEstimator,
    SpatialResult,
    SpatialSARARPanelEstimator,
    SpatialSLXPanelEstimator,
    TwoStepFCAAccessibilityEstimator,
    ZoneBalanceDesignEstimator,
    ensure_spatial_methods_registered,
    register_spatial_methods,
)

__all__ = (
    "AccessibilityData",
    "AccessibilityIndexEstimator",
    "GWREstimator",
    "GaussianProcessKrigingEstimator",
    "GravityFlowData",
    "GravityModelEstimator",
    "InverseDistanceWeightingEstimator",
    "MAUPSensitivityProfileEstimator",
    "MoranIEstimator",
    "SpatialData",
    "SpatialDurbinEstimator",
    "SpatialMicrosimulationEstimator",
    "SpatialResult",
    "SpatialSARARPanelEstimator",
    "SpatialSLXPanelEstimator",
    "TwoStepFCAAccessibilityEstimator",
    "ZoneBalanceDesignEstimator",
    "ensure_spatial_methods_registered",
    "register_spatial_methods",
)
