"""One selected real curated-default consumer, neutral-I own installed profile."""
import hashlib,json,os,pathlib,sys
sys.dont_write_bytecode=True
import pytest
OUT=pathlib.Path(__file__).resolve().parent;PACKET=pathlib.Path('/tmp/e02-F-continuation-20261007/foundry/installed-default-resource-forward');config=json.loads((PACKET/'installed-config.json').read_text());kind=sys.argv[1];site=pathlib.Path(config['sites'][kind]).resolve();cwd=PACKET/(kind+'-consumer');assert pathlib.Path.cwd()==cwd and sys.flags.isolated==1 and not (cwd/'src').exists();assert not any(pathlib.Path(p).is_relative_to(pathlib.Path(config['source_root'])) for p in sys.path if p);manifest=json.loads((PACKET/'carrier-manifest.json').read_text());probe=next(r for r in manifest['files'] if r['path']=='test_installed_catalog_defaults.py');body=(cwd/probe['path']).read_bytes();assert len(body)==probe['bytes'] and hashlib.sha256(body).hexdigest()==probe['sha256'];os.environ.pop('PYTHONPATH',None);os.environ['E02_CATALOG_EXPECTED_JSON']=config['catalog_expected']
class Observer:
 def pytest_collection_finish(self,session):
  self.ids=[item.nodeid for item in session.items];assert len(self.ids)==1 and self.ids[0].endswith('test_real_six_owner_defaults_load_curated_content')
observer=Observer();argv=['-q','-s','-o','addopts=','--import-mode=importlib','-p','no:cacheprovider','--basetemp='+str(OUT/(kind+'-consumer-tmp')),str(cwd/'test_installed_catalog_defaults.py')+'::test_real_six_owner_defaults_load_curated_content'];status=pytest.main(argv,plugins=[observer]);origins={name:str(pathlib.Path(m.__file__).resolve()) for name,m in sys.modules.copy().items() if name.startswith(('polisyos','tools')) and getattr(m,'__file__',None)};violations={n:p for n,p in origins.items() if not pathlib.Path(p).is_relative_to(site)};assert not violations
result={'source_sha':config['source_sha'],'source_tree':config['source_tree'],'profile':kind,'executable':sys.executable,'isolated':sys.flags.isolated,'cwd':str(cwd),'sys_path':sys.path,'pytest_argv':argv,'pytest_exit':int(status),'collected_ids':observer.ids,'input_probe':probe,'origin_violations':violations,'product_origins':origins,'scope':'One realnative sixdefault-owner consumer:actual4packagedYAML plus seedpair/proxypenalties/WVS400/nativeDatasetBatchConfigmetrics14. NoMethodJob/worker/authority or79whole-suite reexecution.'};(OUT/(kind+'-consumer-proof.json')).write_text(json.dumps(result,indent=2)+'\n');print(json.dumps({'profile':kind,'pytest_exit':int(status),'owned_origins':len(origins),'origin_violations':len(violations)}));raise SystemExit(status)
