"""Render decision packets into machine-checkable bureaucratic document ASTs."""

from __future__ import annotations

import json
from datetime import UTC, datetime
from hashlib import sha256
from html import escape
from pathlib import Path
from typing import TYPE_CHECKING, Any, cast

from polisyos.core.canon import from_canonical_bytes
from polisyos.core.contracts.runtime import (
    ApiMeta,
    BureaucraticAuthorship,
    BureaucraticBlock,
    BureaucraticDocument,
    BureaucraticEpistemicKind,
    BureaucraticEpistemicSummary,
    BureaucraticExportFormat,
    BureaucraticExportResponse,
    BureaucraticGenre,
    BureaucraticRenderRequest,
    BureaucraticTemplateRef,
    LineageCompactSummaryItem,
    LineageRef,
    QuantityUncertainty,
    QuantityValue,
    TemporalRef,
    TemporalScope,
    UnitRef,
)

if TYPE_CHECKING:
    from polisyos.core.artifacts.ids import ArtifactID
    from polisyos.core.artifacts.manifest import ArtifactManifest
    from polisyos.core.artifacts.protocol import ArtifactStore


DRAFT_WATERMARK = "Generated by PolicyOS / Draft / Not an official state document"

_TEMPLATE_CATALOG: dict[BureaucraticGenre, tuple[str, str, str]] = {
    "postanova_kmu": (
        "ua.kmu.postanova.v1",
        "1.0.0",
        "Проект постанови Кабінету Міністрів України",
    ),
    "zakonoproekt": ("ua.rada.zakonoproekt.v1", "1.0.0", "Проект Закону України"),
    "expert_vysnovok": ("ua.expert_vysnovok.v1", "1.0.0", "Експертний висновок"),
    "analitichna_zapyska": ("ua.analitichna_zapyska.v1", "1.0.0", "Аналітична записка"),
}

_EXPORT_CONTENT_TYPES: dict[BureaucraticExportFormat, str] = {
    "html": "text/html; charset=utf-8",
    "pdf": "application/pdf",
    "docx": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
}


class BureaucraticRenderingService:
    """Map CAS decision packets to versioned bureaucratic document ASTs."""

    def __init__(self, *, store: ArtifactStore) -> None:
        self._store = store

    def render_document(
        self,
        packet_id: ArtifactID,
        request: BureaucraticRenderRequest,
    ) -> BureaucraticDocument:
        """Render one artifact payload into a canonical bureaucratic document AST."""
        manifest = self._store.get_manifest(packet_id)
        payload = _load_json_payload(self._store, packet_id)
        template = _template_for(
            genre=request.genre,
            jurisdiction=request.jurisdiction,
            requested_template=request.template_version,
        )
        title = _document_title(
            request.genre,
            payload=payload,
            fallback=_TEMPLATE_CATALOG[request.genre][2],
        )
        blocks = _build_main_blocks(
            packet_id=str(packet_id),
            manifest=manifest,
            payload=payload,
            genre=request.genre,
            temporal_scope=request.temporal_scope,
        )
        annexes = _build_annexes(
            packet_id=str(packet_id),
            manifest=manifest,
            payload=payload,
            temporal_scope=request.temporal_scope,
            trust_view=request.trust_view,
        )
        summary = _epistemic_summary([*blocks, *annexes])
        packet_hash = manifest.integrity.sha256
        document_id = f"doc_{request.genre}_{packet_hash[:16]}"
        return BureaucraticDocument(
            id=document_id,
            packet_id=str(packet_id),
            genre=request.genre,
            jurisdiction=request.jurisdiction,
            template=template,
            status="draft",
            title=title,
            watermark=DRAFT_WATERMARK,
            render_timestamp=datetime.now(UTC).replace(microsecond=0),
            packet_hash=packet_hash,
            temporal_scope=request.temporal_scope,
            trust_view=request.trust_view,
            blocks=blocks,
            annexes=annexes,
            epistemic_summary=summary,
            metadata={
                "source_artifact_kind": manifest.kind,
                "source_media_type": manifest.media_type,
                "template_id": template.id,
                "draft_disclaimer": DRAFT_WATERMARK,
                "legal_review_status": template.legal_review_status,
            },
        )

    def export_document(
        self,
        packet_id: ArtifactID,
        request: BureaucraticRenderRequest,
        *,
        export_format: BureaucraticExportFormat,
        meta: ApiMeta,
    ) -> BureaucraticExportResponse:
        """Build a deterministic export packet from the same canonical AST."""
        document = self.render_document(packet_id, request)
        html = render_document_html(document)
        content_type = _EXPORT_CONTENT_TYPES[export_format]
        filename = _export_filename(document, export_format)
        if export_format == "html":
            content = html
        elif export_format == "pdf":
            content = _pdf_print_packet(document, html)
        else:
            content = _docx_source_packet(document, html)
        return BureaucraticExportResponse(
            meta=meta,
            document_id=document.id,
            packet_id=str(packet_id),
            format=export_format,
            content_type=content_type,
            filename=filename,
            content=content,
            metadata={
                "watermark": document.watermark,
                "template_id": document.template.id,
                "template_version": document.template.version,
                "render_timestamp": document.render_timestamp.isoformat(),
                "packet_hash": document.packet_hash,
                "parity_source": "bureaucratic_document_ast",
            },
        )


def render_document_html(document: BureaucraticDocument) -> str:
    """Render semantic, accessible HTML from a bureaucratic document AST."""
    block_html = "\n".join(_block_to_html(block) for block in document.blocks)
    annex_html = "\n".join(_block_to_html(block) for block in document.annexes)
    summary = document.epistemic_summary
    metadata = {
        "document-id": document.id,
        "packet-id": document.packet_id,
        "packet-hash": document.packet_hash,
        "template-id": document.template.id,
        "template-version": document.template.version,
        "watermark": document.watermark,
    }
    meta_tags = "\n".join(
        f'<meta name="polisyos:{escape(key)}" content="{escape(str(value))}">'
        for key, value in metadata.items()
    )
    return f"""<!doctype html>
<html lang="{escape(document.language)}">
<head>
  <meta charset="utf-8">
  <title>{escape(document.title)}</title>
  {meta_tags}
</head>
<body data-document-id="{escape(document.id)}" data-template-id="{escape(document.template.id)}">
  <article aria-labelledby="document-title">
    <header>
      <p role="note">{escape(document.watermark)}</p>
      <p>{escape(document.template.id)} / {escape(document.template.version)}</p>
      <h1 id="document-title">{escape(document.title)}</h1>
    </header>
    {block_html}
    <section aria-labelledby="epistemic-map">
      <h2 id="epistemic-map">Epistemic appendix</h2>
      <dl>
        <dt>Evidence-filled</dt><dd>{summary.evidence_filled:.2f}</dd>
        <dt>Model-generated</dt><dd>{summary.model_generated:.2f}</dd>
        <dt>Operator-filled</dt><dd>{summary.operator_filled:.2f}</dd>
        <dt>Imported</dt><dd>{summary.imported:.2f}</dd>
      </dl>
    </section>
    {annex_html}
  </article>
</body>
</html>"""


def _load_json_payload(store: ArtifactStore, packet_id: ArtifactID) -> dict[str, Any]:
    payload = from_canonical_bytes(store.get_bytes(packet_id))
    if isinstance(payload, dict):
        return payload
    return {"payload": payload}


def _template_for(
    *,
    genre: BureaucraticGenre,
    jurisdiction: str,
    requested_template: str | None,
) -> BureaucraticTemplateRef:
    default_id, version, _title = _TEMPLATE_CATALOG[genre]
    template_id = requested_template or default_id
    return BureaucraticTemplateRef(
        id=template_id,
        version=version,
        genre=genre,
        jurisdiction=jurisdiction,
        locale="uk-UA" if jurisdiction == "ua" else "en",
        legal_review_status=_legal_review_status(template_id, version),
    )


def _legal_review_status(template_id: str, version: str) -> str:
    registry = _load_template_review_registry()
    entry = registry.get(template_id)
    if not isinstance(entry, dict):
        return "pending_external_review"
    if entry.get("reviewed_template_version") != version:
        return "pending_external_review"
    if entry.get("status") == "approved":
        approvals = [
            entry.get("watermark_disclaimer_approved"),
            entry.get("numbering_approved"),
            entry.get("signature_seal_placeholders_approved"),
        ]
        if all(approvals):
            return "approved"
    return "pending_external_review"


def _load_template_review_registry() -> dict[str, Any]:
    root = Path(__file__).resolve().parents[5]
    registry_path = root / "docs/brand/bureaucratic-template-review.json"
    try:
        payload = json.loads(registry_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}
    templates = payload.get("templates") if isinstance(payload, dict) else None
    return templates if isinstance(templates, dict) else {}


def _document_title(
    genre: BureaucraticGenre,
    *,
    payload: dict[str, Any],
    fallback: str,
) -> str:
    run_id = _as_str(payload.get("run_id"))
    if genre == "postanova_kmu":
        return f"{fallback} щодо рішення {run_id or 'PolicyOS'}"
    if genre == "zakonoproekt":
        return f"{fallback} про реалізацію рішення {run_id or 'PolicyOS'}"
    if genre == "expert_vysnovok":
        return f"{fallback} щодо доказовості рішення {run_id or 'PolicyOS'}"
    return f"{fallback}: {run_id or 'PolicyOS decision packet'}"


def _build_main_blocks(
    *,
    packet_id: str,
    manifest: ArtifactManifest,
    payload: dict[str, Any],
    genre: BureaucraticGenre,
    temporal_scope: TemporalScope | None,
) -> list[BureaucraticBlock]:
    run_id = _as_str(payload.get("run_id")) or "unknown-run"
    governance = _as_dict(payload.get("governance"))
    diagnostics = _as_dict(payload.get("diagnostics_summary"))
    blocks: list[BureaucraticBlock] = [
        BureaucraticBlock(
            id="header",
            kind="header",
            title=_TEMPLATE_CATALOG[genre][2],
            text=f"Decision packet {packet_id} rendered for run {run_id}.",
            epistemic_origin="imported",
            provenance=_artifact_provenance(packet_id, manifest),
            raw_source_refs=[packet_id],
            metadata={"run_id": run_id},
        ),
        BureaucraticBlock(
            id="requisites",
            kind="requisites",
            title="Реквізити",
            items=[
                "Статус: проект, не є офіційним державним документом",
                f"Пакет рішення: {packet_id}",
                f"Хеш пакета: {manifest.integrity.sha256}",
                f"Дата формування: {datetime.now(UTC).replace(microsecond=0).isoformat()}",
            ],
            epistemic_origin="imported",
            provenance=_artifact_provenance(packet_id, manifest),
            raw_source_refs=[packet_id],
        ),
        BureaucraticBlock(
            id="preamble",
            kind="preamble",
            title="Преамбула",
            text=_preamble_text(genre, run_id=run_id),
            epistemic_origin="model_generated",
            provenance=[
                LineageCompactSummaryItem(kind="agent", label="PolicyOS bureaucratic renderer"),
                LineageCompactSummaryItem(kind="artifact", label=packet_id),
            ],
            raw_source_refs=[packet_id],
        ),
        BureaucraticBlock(
            id="legal_basis",
            kind="legal_basis",
            title="Правові підстави та межі використання",
            items=_legal_basis_items(payload),
            epistemic_origin="imported",
            provenance=_source_refs(payload),
            raw_source_refs=_raw_refs(payload),
        ),
        BureaucraticBlock(
            id="operative",
            kind="section",
            title="Оперативна частина",
            text=_operative_text(genre, governance=governance, diagnostics=diagnostics),
            epistemic_origin="operator_filled",
            provenance=[
                LineageCompactSummaryItem(kind="result", label="governance verdict"),
                LineageCompactSummaryItem(kind="result", label="decision packet diagnostics"),
            ],
            raw_source_refs=[packet_id],
        ),
    ]
    blocks.extend(
        _metric_blocks(
            payload=payload,
            packet_id=packet_id,
            packet_hash=manifest.integrity.sha256,
            temporal_scope=temporal_scope,
        )
    )
    blocks.extend(_authored_blocks(payload, packet_id=packet_id))
    blocks.append(
        BureaucraticBlock(
            id="signature_placeholders",
            kind="signature",
            title="Підпис",
            text="Підпис, печатка та офіційне затвердження не виконуються у PolicyOS.",
            epistemic_origin="operator_filled",
            authorship=BureaucraticAuthorship(author="PolicyOS", author_role="system"),
            provenance=[LineageCompactSummaryItem(kind="agent", label="PolicyOS")],
            metadata={"signature_status": "external_required"},
        )
    )
    return blocks


def _build_annexes(
    *,
    packet_id: str,
    manifest: ArtifactManifest,
    payload: dict[str, Any],
    temporal_scope: TemporalScope | None,
    trust_view: bool,
) -> list[BureaucraticBlock]:
    annexes = [
        BureaucraticBlock(
            id="annex_epistemic_appendix",
            kind="annex",
            title="Додаток 1. Епістемічна карта",
            text=(
                "Кожен блок документа має походження: evidence-filled, "
                "model-generated, operator-filled або imported."
            ),
            epistemic_origin="model_generated",
            provenance=[
                LineageCompactSummaryItem(kind="method", label="PolicyOS epistemic map"),
            ],
            metadata={"trust_view": trust_view},
        ),
        BureaucraticBlock(
            id="annex_provenance",
            kind="annex",
            title="Додаток 2. Provenance та відтворюваність",
            items=[
                f"Source artifact: {packet_id}",
                f"Packet hash: {manifest.integrity.sha256}",
                f"Valid at: {_scope_valid_at(temporal_scope)}",
                f"Known at: {_scope_tx_at(temporal_scope)}",
            ],
            epistemic_origin="imported",
            provenance=_artifact_provenance(packet_id, manifest),
            raw_source_refs=[packet_id],
            metadata={"trust_view": trust_view},
        ),
    ]
    if trust_view:
        annexes.append(
            BureaucraticBlock(
                id="annex_raw_refs",
                kind="annex",
                title="Додаток 3. Raw source refs",
                items=_raw_refs(payload) or [packet_id],
                epistemic_origin="imported",
                provenance=_source_refs(payload) or _artifact_provenance(packet_id, manifest),
                raw_source_refs=_raw_refs(payload) or [packet_id],
            )
        )
    return annexes


def _metric_blocks(
    *,
    payload: dict[str, Any],
    packet_id: str,
    packet_hash: str,
    temporal_scope: TemporalScope | None,
) -> list[BureaucraticBlock]:
    simulation = _as_dict(payload.get("simulation_results"))
    comparisons = _as_list(payload.get("metric_validation_comparison_rows"))
    blocks: list[BureaucraticBlock] = []
    for key, value in simulation.items():
        point = _as_float(value)
        if point is None:
            continue
        blocks.append(
            BureaucraticBlock(
                id=f"quantity_{_slug(key)}",
                kind="quantity",
                title=_label(key),
                text=f"Decision-bearing metric {_label(key)}.",
                quantity=_quantity(
                    metric_id=key,
                    label=_label(key),
                    point=point,
                    packet_id=packet_id,
                    packet_hash=packet_hash,
                    temporal_scope=temporal_scope,
                    comparison=_comparison_for_metric(comparisons, key),
                ),
                epistemic_origin="model_generated",
                provenance=[
                    LineageCompactSummaryItem(kind="result", label=f"simulation_results.{key}"),
                    LineageCompactSummaryItem(kind="artifact", label=packet_id),
                ],
                raw_source_refs=[packet_id],
            )
        )
    return blocks


def _authored_blocks(payload: dict[str, Any], *, packet_id: str) -> list[BureaucraticBlock]:
    blocks: list[BureaucraticBlock] = []
    for collection_name in ("blocks", "narrative_blocks", "evidence_summary_blocks"):
        for index, item in enumerate(_as_list(payload.get(collection_name))):
            item_dict = _as_dict(item)
            content = _as_str(item_dict.get("content"))
            if not content:
                continue
            source_refs = [
                _as_str(source.get("ref"))
                for source in _as_list(item_dict.get("sources"))
                if isinstance(source, dict)
            ]
            source_refs = [ref for ref in source_refs if ref]
            blocks.append(
                BureaucraticBlock(
                    id=f"{collection_name}_{index + 1}",
                    kind="paragraph",
                    text=content,
                    epistemic_origin=_authored_epistemic_origin(item_dict),
                    authorship=BureaucraticAuthorship(
                        author=_as_str(item_dict.get("author")) or "PolicyOS",
                        author_role=_as_str(item_dict.get("author")) or "system",
                        agent_version=_as_str(item_dict.get("author_agent_version")),
                        timestamp=_parse_datetime(item_dict.get("timestamp")),
                        reviewed_by_human=bool(item_dict.get("reviewed_by_human")),
                    ),
                    provenance=[
                        LineageCompactSummaryItem(kind="source", label=ref)
                        for ref in source_refs
                    ]
                    or [LineageCompactSummaryItem(kind="artifact", label=packet_id)],
                    raw_source_refs=source_refs or [packet_id],
                )
            )
    return blocks


def _quantity(
    *,
    metric_id: str,
    label: str,
    point: float,
    packet_id: str,
    packet_hash: str,
    temporal_scope: TemporalScope | None,
    comparison: dict[str, Any] | None,
) -> QuantityValue:
    ci_95 = None
    if comparison is not None:
        low = _as_float(comparison.get("ci_low"))
        high = _as_float(comparison.get("ci_high"))
        ci_95 = (low, high) if low is not None and high is not None else None
    return QuantityValue(
        point=point,
        unit=_unit_for_metric(metric_id),
        metric_id=metric_id,
        label=label,
        lineage=LineageRef(
            id=f"artifact:{packet_hash[:16]}:metric:{metric_id}",
            hash=f"sha256:{packet_hash}",
            status="pending",
            freshness="current",
            summary={
                "source": packet_id,
                "method": "bureaucratic_rendering.metric_projection",
                "agent": "PolicyOS",
            },
            compact_summary=[
                LineageCompactSummaryItem(kind="artifact", label=packet_id),
                LineageCompactSummaryItem(kind="result", label=metric_id),
            ],
        ),
        uncertainty=QuantityUncertainty(
            ci_95=ci_95,
            method=_as_str(comparison.get("resampling_method")) if comparison else None,
            identifiability="estimated" if ci_95 is not None else "unknown",
            disputed=False,
        )
        if comparison is not None
        else None,
        time=_temporal_ref(temporal_scope),
        quantity_class="decision",
    )


def _temporal_ref(scope: TemporalScope | None) -> TemporalRef | None:
    if scope is None:
        return None
    return TemporalRef(
        valid_at=scope.valid_at,
        tx_at=scope.tx_at,
        snapshot_id=scope.snapshot_id,
        branch=scope.branch,
        scenario_id=scope.scenario_id,
    )


def _comparison_for_metric(rows: list[Any], metric_id: str) -> dict[str, Any] | None:
    for row in rows:
        row_dict = _as_dict(row)
        if _as_str(row_dict.get("metric_id")) == metric_id:
            return row_dict
    return None


def _epistemic_summary(blocks: list[BureaucraticBlock]) -> BureaucraticEpistemicSummary:
    counts: dict[BureaucraticEpistemicKind, int] = {
        "evidence_filled": 0,
        "model_generated": 0,
        "operator_filled": 0,
        "imported": 0,
    }

    def visit(block: BureaucraticBlock) -> None:
        counts[block.epistemic_origin] += 1
        for child in block.children:
            visit(child)

    for block in blocks:
        visit(block)
    total = sum(counts.values()) or 1
    return BureaucraticEpistemicSummary(
        evidence_filled=round(counts["evidence_filled"] / total, 4),
        model_generated=round(counts["model_generated"] / total, 4),
        operator_filled=round(counts["operator_filled"] / total, 4),
        imported=round(counts["imported"] / total, 4),
    )


def _block_to_html(block: BureaucraticBlock) -> str:
    title = f"<h{block.level + 1}>{escape(block.title)}</h{block.level + 1}>" if block.title else ""
    number = f'<span class="number">{escape(block.number)}</span> ' if block.number else ""
    text = f"<p>{number}{escape(block.text)}</p>" if block.text else ""
    quantity = ""
    if block.quantity is not None:
        unit = block.quantity.unit.display or block.quantity.unit.code
        value = "-" if block.quantity.point is None else str(block.quantity.point)
        quantity = (
            f'<p data-quantity-metric="{escape(block.quantity.metric_id or "")}" '
            f'data-lineage-id="{escape(block.quantity.lineage.id)}">'
            f"{escape(value)} {escape(unit)}</p>"
        )
    items = ""
    if block.items:
        items = "<ul>" + "".join(f"<li>{escape(item)}</li>" for item in block.items) + "</ul>"
    children = "\n".join(_block_to_html(child) for child in block.children)
    raw_refs = " ".join(block.raw_source_refs)
    return (
        f'<section data-block-id="{escape(block.id)}" '
        f'data-epistemic-origin="{escape(block.epistemic_origin)}" '
        f'data-raw-source-refs="{escape(raw_refs)}">'
        f"{title}{text}{quantity}{items}{children}</section>"
    )


def _pdf_print_packet(document: BureaucraticDocument, html: str) -> str:
    digest = sha256(html.encode("utf-8")).hexdigest()
    return (
        "%PDF-1.4\n"
        f"% PolicyOS deterministic print-source packet for {document.id}\n"
        f"% Watermark: {document.watermark}\n"
        f"% HTML-SHA256: {digest}\n"
        "% Generate final PDF through the browser print pipeline "
        "to preserve accessible HTML parity.\n"
    )


def _docx_source_packet(document: BureaucraticDocument, html: str) -> str:
    digest = sha256(html.encode("utf-8")).hexdigest()
    return (
        f"PolicyOS DOCX source packet\nDocument: {document.id}\n"
        f"Watermark: {document.watermark}\nHTML-SHA256: {digest}\n"
        "The frontend DOCX exporter consumes the same BureaucraticDocumentAST.\n"
    )


def _export_filename(
    document: BureaucraticDocument,
    export_format: BureaucraticExportFormat,
) -> str:
    return f"{document.genre}-{document.packet_hash[:12]}.{export_format}"


def _artifact_provenance(
    packet_id: str,
    manifest: ArtifactManifest,
) -> list[LineageCompactSummaryItem]:
    producer = manifest.producer.component if manifest.producer is not None else None
    return [
        LineageCompactSummaryItem(kind="artifact", label=packet_id),
        LineageCompactSummaryItem(kind="source", label=manifest.kind),
        LineageCompactSummaryItem(kind="agent", label=str(producer or "unknown producer")),
    ]


def _source_refs(payload: dict[str, Any]) -> list[LineageCompactSummaryItem]:
    refs = _raw_refs(payload)
    return [LineageCompactSummaryItem(kind="source", label=ref) for ref in refs[:8]]


def _raw_refs(payload: dict[str, Any]) -> list[str]:
    refs: list[str] = []
    for container_name in ("inputs", "artifacts"):
        container = _as_dict(payload.get(container_name))
        for value in container.values():
            ref = _ref_string(value)
            if ref and ref not in refs:
                refs.append(ref)
    feedback = _as_dict(payload.get("feedback_loop"))
    for value in feedback.values():
        ref = _ref_string(value)
        if ref and ref not in refs:
            refs.append(ref)
    return refs


def _legal_basis_items(payload: dict[str, Any]) -> list[str]:
    refs = _raw_refs(payload)
    items = [
        "Документ є проектом, сформованим для аналізу, обговорення та зовнішнього погодження.",
        "Офіційне підписання та затвердження відбуваються поза PolicyOS.",
    ]
    if refs:
        items.append(f"Використані джерела/артефакти: {', '.join(refs[:5])}.")
    diagnostics = _as_dict(payload.get("diagnostics_summary"))
    warnings = _as_list(diagnostics.get("contract_warnings"))
    if warnings:
        items.append(f"Контрактні попередження: {', '.join(str(item) for item in warnings[:5])}.")
    return items


def _preamble_text(genre: BureaucraticGenre, *, run_id: str) -> str:
    if genre == "postanova_kmu":
        return f"Кабінет Міністрів України постановляє розглянути матеріали PolicyOS run {run_id}."
    if genre == "zakonoproekt":
        return f"Цей проект Закону підготовлено на підставі decision packet run {run_id}."
    if genre == "expert_vysnovok":
        return f"Висновок описує доказову базу, припущення та ризики рішення run {run_id}."
    return f"Записка узагальнює policy question, докази та ризики рішення run {run_id}."


def _operative_text(
    genre: BureaucraticGenre,
    *,
    governance: dict[str, Any],
    diagnostics: dict[str, Any],
) -> str:
    verdict = _as_str(governance.get("verdict")) or "unknown"
    legal_executed = diagnostics.get("legal_executed")
    if genre == "postanova_kmu":
        return (
            "Схвалити подальший розгляд матеріалів за умови усунення відкритих "
            f"governance issues. Поточний verdict: {verdict}; legal executed: {legal_executed}."
        )
    if genre == "zakonoproekt":
        return (
            "Визначити предмет регулювання, очікуваний вплив та обмеження "
            f"на підставі packet verdict {verdict}."
        )
    if genre == "expert_vysnovok":
        return f"Експертний висновок фіксує рівень готовності рішення: {verdict}."
    return f"Аналітична записка подає recommendation context; поточний verdict: {verdict}."


def _authored_epistemic_origin(item: dict[str, Any]) -> BureaucraticEpistemicKind:
    author = _as_str(item.get("author"))
    if author == "citation":
        return "evidence_filled"
    if author == "human":
        return "operator_filled"
    return "model_generated"


def _unit_for_metric(metric_id: str) -> UnitRef:
    lowered = metric_id.lower()
    if "cost" in lowered or "budget" in lowered:
        return UnitRef(code="USD", system="ucum", display="USD")
    if "share" in lowered or "rate" in lowered or "ratio" in lowered:
        return UnitRef(code="1", system="ucum", display="ratio")
    return UnitRef(code="1", system="ucum", display="value")


def _scope_valid_at(temporal_scope: TemporalScope | None) -> str:
    if temporal_scope is None or temporal_scope.valid_at is None:
        return "current"
    return temporal_scope.valid_at.isoformat()


def _scope_tx_at(temporal_scope: TemporalScope | None) -> str:
    if temporal_scope is None or temporal_scope.tx_at is None:
        return "latest"
    return temporal_scope.tx_at.isoformat()


def _ref_string(value: object) -> str | None:
    if isinstance(value, str) and value.strip():
        return value.strip()
    if isinstance(value, dict):
        artifact_id = value.get("artifact_id")
        if isinstance(artifact_id, str) and artifact_id.strip():
            return artifact_id.strip()
    return None


def _as_dict(value: object) -> dict[str, Any]:
    return cast("dict[str, Any]", value) if isinstance(value, dict) else {}


def _as_list(value: object) -> list[Any]:
    return cast("list[Any]", value) if isinstance(value, list) else []


def _as_str(value: object) -> str | None:
    if isinstance(value, str) and value.strip():
        return value.strip()
    return None


def _as_float(value: object) -> float | None:
    if isinstance(value, bool):
        return None
    if isinstance(value, (int, float)):
        return float(value)
    if isinstance(value, str):
        try:
            return float(value)
        except ValueError:
            return None
    return None


def _parse_datetime(value: object) -> datetime | None:
    if not isinstance(value, str):
        return None
    try:
        return datetime.fromisoformat(value.replace("Z", "+00:00"))
    except ValueError:
        return None


def _label(value: str) -> str:
    return value.replace("_", " ").replace(".", " ").title()


def _slug(value: str) -> str:
    return "".join(ch if ch.isalnum() else "_" for ch in value.lower()).strip("_") or "value"
