import { describe, expect, it } from "vitest";

import {
  flattenBureaucraticBlocks,
  validateBureaucraticDocumentAST,
  type BureaucraticDocumentAST,
} from "./bureaucratic-document-ast";

describe("BureaucraticDocumentAST", () => {
  it("validates watermark and quantity lineage", () => {
    const document = fixtureDocument();

    expect(flattenBureaucraticBlocks(document).map((block) => block.id)).toEqual(
      ["header", "quantity", "annex"],
    );
    expect(validateBureaucraticDocumentAST(document)).toMatchObject({
      valid: true,
      watermarkPresent: true,
      missingBlockIds: [],
      quantityBlocksWithoutLineage: [],
    });
  });
});

function fixtureDocument(): BureaucraticDocumentAST {
  return {
    annexes: [
      {
        authorship: {
          author: "PolicyOS",
          author_role: "system",
          reviewed_by_human: false,
        },
        epistemic_origin: "imported",
        id: "annex",
        kind: "annex",
        level: 1,
        title: "Annex",
      },
    ],
    blocks: [
      {
        authorship: {
          author: "PolicyOS",
          author_role: "system",
          reviewed_by_human: false,
        },
        epistemic_origin: "imported",
        id: "header",
        kind: "header",
        level: 1,
        title: "Header",
      },
      {
        authorship: {
          author: "PolicyOS",
          author_role: "system",
          reviewed_by_human: false,
        },
        epistemic_origin: "model_generated",
        id: "quantity",
        kind: "quantity",
        level: 1,
        quantity: {
          lineage: {
            freshness: "current",
            id: "lin_1",
            status: "verified",
          },
          point: 10,
          quantity_class: "decision",
          unit: { code: "1", system: "ucum" },
        },
      },
    ],
    epistemic_summary: {
      evidence_filled: 0,
      imported: 0.5,
      model_generated: 0.5,
      operator_filled: 0,
    },
    genre: "postanova_kmu",
    id: "doc_1",
    jurisdiction: "ua",
    language: "uk",
    packet_hash: "hash",
    packet_id: "sha256:abc",
    render_timestamp: "2026-02-11T12:00:00Z",
    status: "draft",
    template: {
      genre: "postanova_kmu",
      id: "ua.kmu.postanova.v1",
      jurisdiction: "ua",
      legal_review_status: "pending_external_review",
      locale: "uk-UA",
      version: "1.0.0",
    },
    title: "Document",
    trust_view: false,
    watermark: "Generated by PolicyOS / Draft / Not an official state document",
  };
}
