"""Freeze one full gzip report plus small deciding/replay companions; no product writes."""
import datetime,gzip,hashlib,json,pathlib,platform,subprocess
O=pathlib.Path(__file__).resolve().parent
REPO='/workspace/e02-F-graph-20261006'
BLOB='175c1ed4db37589e8adaf14af6700ad639edb2c8'
def ref(name,role):
 p=O/name;b=p.read_bytes();return {'path':str(p),'name':name,'bytes':len(b),'sha256':hashlib.sha256(b).hexdigest(),'role':role}
probe=subprocess.run(['git','cat-file','-t',BLOB],cwd=REPO,capture_output=True)
(O/'historical-blob-local-git.stdout.txt').write_bytes(probe.stdout);(O/'historical-blob-local-git.stderr.txt').write_bytes(probe.stderr)
probe_meta={'schema':'policyos.e02.historical-blob-availability-probe.v1','observed_utc':datetime.datetime.now(datetime.UTC).isoformat(),'git_blob':BLOB,'check':'UNRUN','classification':'unavailable_historical_non_deciding','local_git_probe':{'command':['git','cat-file','-t',BLOB],'cwd':REPO,'exit_code':probe.returncode,'stdout':ref('historical-blob-local-git.stdout.txt','complete local Git probe stdout'),'stderr':ref('historical-blob-local-git.stderr.txt','complete local Git probe stderr')},'github_read_only_probe':{'command':['gh','api','repos/DenisKopylov/polisyos/git/blobs/'+BLOB],'exit_code':1,'http_status':404,'stdout':ref('historical-blob-gh-response.json','complete original GitHub blob probe stdout'),'stderr':ref('historical-blob-gh-stderr.txt','complete original GitHub blob probe stderr'),'capture_metadata_limit':'Original cwd/timing were not captured; no values inferred. This is the one completed read-only GitHub probe, not a second request.'},'scope':'Original record explicitly excludes current finding-status/behavior evidence. No unavailable source is treated as PASS and no ledger is modified.'}
assert probe.returncode!=0
assert json.loads((O/'historical-blob-gh-response.json').read_text())['status']=='404'
(O/'historical-blob-probe.json').write_text(json.dumps(probe_meta,indent=2)+'\n')
report_path=O/'F-published-protocol-audit.json';d=json.loads(report_path.read_text());inventory=json.loads((O/'canonical-receipt-inventory.json').read_text())
assert d['check']=='UNRUN' and d['current_deciding_reference_check']=='PASS' and d['all_reference_custody_check']=='UNRUN' and d['historical_non_deciding_reference_check']=='UNRUN'
assert not d['current_deciding_issues'] and len(d['historical_unavailable_non_deciding_records'])==4
assert d['denominator']['all_canonical_handoffs']==15 and d['denominator']['published_topics']==12 and d['denominator']['all_canonical_check_records']==267
assert d['mapping35_bundles17']['actual_finding_count']==35 and d['mapping35_bundles17']['actual_bundle_count']==17
assert inventory['check']=='PASS' and inventory['canonical_unique_path_count']==15 and inventory['topic_head_denominator']==12
scripts=['audit.py','audit_companions.py','audit_incremental.py','audit_all.py','consolidate.py','canonical_inventory.py','replay_final_protocol_audit.py','apply-scoped-historical-custody.py','finalize_transfer.py']
d['canonical_receipt_inventory']={'result':inventory,'source':ref('canonical-receipt-inventory.json','complete actual registered/introduced canonical receipt denominator')}
d['audit_execution_environment']={'python':platform.python_version(),'git':subprocess.check_output(['git','--version'],text=True).strip(),'audit_product_checkout':REPO,'mode':'Read-only exact Git inputs plus unique scratch outputs; no scientific tests or product/ledger writes in this protocol audit.','replayer_source_bindings':[ref(x,'complete audit/checker/replay source') for x in scripts]}
d['historical_custody_disposition']['probe_outputs']=['historical-blob-probe.json','historical-blob-gh-response.json','historical-blob-gh-stderr.txt','historical-blob-local-git.stdout.txt','historical-blob-local-git.stderr.txt']
d['historical_custody_disposition']['probe_binding']=ref('historical-blob-probe.json','complete historical blob probe execution and original full-output bindings')
d['parent_per_id_check_semantics']='Missing parent aggregate check fields remain null. Explicit criterion outcomes/check references retain their authored meanings. No aggregate PASS is invented; canonical267 check outcome/output/environment records are validated separately.'
report_path.write_text(json.dumps(d,indent=2)+'\n');raw=report_path.read_bytes();stored=gzip.compress(raw,compresslevel=9,mtime=0);gz=O/'F-published-protocol-audit.json.gz';gz.write_bytes(stored)
assert gzip.decompress(stored)==raw
text_path=O/'F-published-protocol-audit.txt';summary=text_path.read_text()
if 'Historical non-deciding reference check: UNRUN' not in summary:summary+='Historical non-deciding reference check: UNRUN; exact175c blob/4occurrences remain recorded; current deciding references PASS.\n'
text_path.write_text(summary)
selection_names=[('F-published-protocol-audit.txt','complete concise deciding summary'),('canonical-receipt-inventory.json','complete15-receipt/12-topic register binding'),('remote-heads.json','actual read-only remote snapshot'),('historical-blob-probe.json','complete local/GitHub historical source availability probe'),('historical-blob-gh-response.json','complete original read-only GitHub HTTP404 output'),('historical-blob-gh-stderr.txt','complete original GitHub stderr'),('historical-blob-local-git.stdout.txt','complete local absent-blob probe stdout'),('historical-blob-local-git.stderr.txt','complete local absent-blob probe stderr')]
selection_names += [(x,'complete audit/checker/replay source') for x in scripts]
selection_names += [(x,'complete supplementary fully walked large source JSON reference denominator') for x in ['large-source-json-hash-ref-denominator.json','large-source-source-path-alias-check.json']]
for phase,role in [('final-full','complete original final15 orchestration output; parser locator gaps were subsequently corrected, not product failures'),('final-reference-forms','complete locator/card/block/source_path correction output; remaining175c unavailable source subsequently classified explicitly'),('final-scoped-reference-check','complete final API/FRY currentPASS/historicalUNRUN check output'),('final-consolidation','complete final15/267 deciding consolidation output'),('final-canonical-inventory','complete canonical15/12 inventory output')]:
 for stream in ['stdout','stderr']:selection_names.append((phase+'.'+stream+'.txt',role+'; '+stream))
selected=[ref(x,role) for x,role in selection_names]
selection={'schema':'policyos.e02.audit-transfer-selection.v1','unit':'F','reviewer':'F/graph_scm','observed_utc':datetime.datetime.now(datetime.UTC).isoformat(),'check':'UNRUN','current_deciding_reference_check':'PASS','all_reference_custody_check':'UNRUN','historical_non_deciding_reference_check':'UNRUN','scope':'Read-only final published protocol audit: current15canonical/12topics/267checks/35IDs/17bundles checked. One unavailable explicitly historical blob with4occurrences retained UNRUN; it is not closure evidence. No ledger/authority/integration decisions made.','complete_report':{**ref(gz.name,'one complete lossless full audit report; uncompressed duplicate excluded from transfer'),'encoding':'gzip','decompressed_bytes':len(raw),'decompressed_sha256':hashlib.sha256(raw).hexdigest()},'companions':selected,'companion_count':len(selected),'denominator':d['denominator'],'topic_component_inputs':[{'component':r['component'],'role':role,'head':r['head'],'primary':r['primary'],'candidate_sha':r['candidate_sha'],'candidate_tree_sha':r['candidate_tree_sha']} for group,role in [('primary_components','primary'),('companion_components','companion'),('ancillary_components','ancillary_historical_native')] for r in d[group]],'replay':{'command':'python3 replay_final_protocol_audit.py --repo <fetched-checkout> --out <new-empty-scratch-dir> --snapshot F-published-protocol-audit.json.gz','scope':'Navigation repo/output arguments only; fixed exact15 receipt refs. Existing measured gzip decode identities are reused solely after fresh compressed Git bytes and declared raw identity reconciliation. Full uncached decoding is available by omitting --snapshot.','numeric_tests':'Not rerun; original actual source-bound scientific receipts retain PASS/FAIL/ERROR/SKIP/UNRUN.'},'transfer_rule':'Commit only the gzip report and selected small companions, one copy of each. Original uncompressed full report and per-component caches are intentionally excluded. Raw full-body hashes and complete source-bind records are retained inside the lossless report; those original deciding output bodies remain at exact published Git refs.','oversize_exception_reason':'Complete full deciding protocol/source/raw-byte denominator is required. One compressed full report preserves all records instead of a truncated tail, sample, or duplicate raw view.'}
sel=O/'F-published-protocol-transfer-selection.json';sel.write_text(json.dumps(selection,indent=2)+'\n')
print(json.dumps({'selection':ref(sel.name,'final transfer selection'),'report_gzip':selection['complete_report'],'current_deciding_reference_check':'PASS','historical_non_deciding_reference_check':'UNRUN','companions':len(selected),'denominator':d['denominator']},indent=2))
