import type { Meta, StoryObj } from "@storybook/react-vite";

import type { BureaucraticDocumentAST } from "./ast/bureaucratic-document-ast";
import { PostanovaKMURenderer } from "./renderers/PostanovaKMURenderer";

const meta = {
  title: "Artifacts/Bureaucratic Rendering",
  component: PostanovaKMURenderer,
} satisfies Meta<typeof PostanovaKMURenderer>;

export default meta;

type Story = StoryObj<typeof meta>;

export const DraftPostanova: Story = {
  args: {
    document: {
      annexes: [],
      blocks: [
        {
          authorship: {
            author: "PolicyOS",
            author_role: "system",
            reviewed_by_human: false,
          },
          epistemic_origin: "imported",
          id: "header",
          kind: "header",
          level: 1,
          title: "Реквізити",
          text: "Decision packet rendered as a draft.",
        },
      ],
      epistemic_summary: {
        evidence_filled: 0,
        imported: 1,
        model_generated: 0,
        operator_filled: 0,
      },
      genre: "postanova_kmu",
      id: "doc_story",
      jurisdiction: "ua",
      language: "uk",
      packet_hash: "storyhash",
      packet_id: "sha256:story",
      render_timestamp: "2026-02-11T12:00:00Z",
      status: "draft",
      template: {
        genre: "postanova_kmu",
        id: "ua.kmu.postanova.v1",
        jurisdiction: "ua",
        legal_review_status: "pending_external_review",
        locale: "uk-UA",
        version: "1.0.0",
      },
      title: "Проект постанови Кабінету Міністрів України",
      trust_view: false,
      watermark: "Generated by PolicyOS / Draft / Not an official state document",
    } satisfies BureaucraticDocumentAST,
  },
};
