import { render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { epochNonreceipt } from "@/shared/ui/temporal/TimeSemanticsLabel";

import type { BureaucraticDocumentAST } from "./ast/bureaucratic-document-ast";

const { useBureaucraticRenderMock } = vi.hoisted(() => ({
  useBureaucraticRenderMock: vi.fn(),
}));

vi.mock("@/api/hooks/useBureaucraticRender", () => ({
  useBureaucraticRender: (...args: unknown[]) =>
    useBureaucraticRenderMock(...args),
}));

vi.mock("@/shared/ui/temporal/TemporalRuntimeBridge", () => ({
  useMaybeTemporalCursor: () => ({
    effectiveScope: {
      validAt: "2026-02-11T12:00:00Z",
      txAt: "2026-02-11T12:05:00Z",
    },
  }),
}));

vi.mock("@/shared/ui/quantity", () => ({
  Quantity: ({ value }: { value: { point: number | null } }) => (
    <span data-testid="quantity">{value.point}</span>
  ),
}));

import { BureaucraticArtifactView } from "./BureaucraticArtifactView";

describe("BureaucraticArtifactView", () => {
  beforeEach(() => {
    useBureaucraticRenderMock.mockReset();
    useBureaucraticRenderMock.mockReturnValue({
      data: { document: fixtureDocument("postanova_kmu") },
      isError: false,
      isLoading: false,
    });
  });

  it("renders genre picker, watermark, quantity and AST/export validation", () => {
    render(<BureaucraticArtifactView artifactId="sha256:abc" />);

    expect(
      screen.getByText("Native bureaucratic rendering"),
    ).toBeInTheDocument();
    expect(
      screen.getByText(
        "Generated by PolicyOS / Draft / Not an official state document",
      ),
    ).toBeInTheDocument();
    expect(screen.getByTestId("quantity")).toHaveTextContent("100");
    expect(screen.getByText(/AST valid/)).toBeInTheDocument();
    expect(useBureaucraticRenderMock).toHaveBeenCalledWith("sha256:abc", {
      genre: "postanova_kmu",
      jurisdiction: "ua",
      temporalScope: {
        txAt: "2026-02-11T12:05:00Z",
        validAt: "2026-02-11T12:00:00Z",
      },
      trustView: false,
    });
  });

  it("preserves packet content while switching genre and trust view", async () => {
    const user = userEvent.setup();
    render(<BureaucraticArtifactView artifactId="sha256:abc" />);

    await user.click(screen.getByRole("radio", { name: /Законопроект/ }));
    const trustView = screen.getByLabelText("Trust View");
    expect(trustView).toHaveClass("atlas-checkbox");
    await user.click(trustView);

    expect(useBureaucraticRenderMock).toHaveBeenLastCalledWith("sha256:abc", {
      genre: "zakonoproekt",
      jurisdiction: "ua",
      temporalScope: {
        txAt: "2026-02-11T12:05:00Z",
        validAt: "2026-02-11T12:00:00Z",
      },
      trustView: true,
    });
  });
});

function fixtureDocument(genre: BureaucraticDocumentAST["genre"]) {
  return {
    annexes: [
      {
        authorship: {
          author: "PolicyOS",
          author_role: "system",
          reviewed_by_human: false,
        },
        epistemic_origin: "imported",
        id: "annex_provenance",
        items: ["Source artifact: sha256:abc"],
        kind: "annex",
        level: 1,
        title: "Provenance",
      },
    ],
    blocks: [
      {
        authorship: {
          author: "PolicyOS",
          author_role: "system",
          reviewed_by_human: false,
        },
        epistemic_origin: "imported",
        id: "header",
        kind: "header",
        level: 1,
        title: "Header",
      },
      {
        authorship: {
          author: "PolicyOS",
          author_role: "system",
          reviewed_by_human: false,
        },
        epistemic_origin: "model_generated",
        id: "quantity_policy_cost",
        kind: "quantity",
        level: 1,
        quantity: {
          label: "Policy Cost",
          lineage: {
            freshness: "current",
            id: "artifact:abc:metric:policy_cost",
            status: "pending",
          },
          metric_id: "policy_cost",
          point: 100,
          quantity_class: "decision",
          unit: { code: "USD", display: "USD", system: "ucum" },
        },
        title: "Policy Cost",
      },
    ],
    epistemic_summary: {
      evidence_filled: 0,
      imported: 0.5,
      model_generated: 0.5,
      operator_filled: 0,
    },
    genre,
    id: `doc_${genre}`,
    jurisdiction: "ua",
    language: "uk",
    packet_hash: "abcdef123456",
    packet_id: "sha256:abc",
    render_timestamp: "2026-02-11T12:00:00Z",
    temporal_semantics: epochNonreceipt(),
    status: "draft",
    template: {
      genre,
      id: "ua.kmu.postanova.v1",
      jurisdiction: "ua",
      legal_review_status: "pending_external_review",
      locale: "uk-UA",
      version: "1.0.0",
    },
    title: "Test document",
    trust_view: false,
    watermark: "Generated by PolicyOS / Draft / Not an official state document",
  } satisfies BureaucraticDocumentAST;
}
