apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak
  namespace: {{ .Values.namespace }}
spec:
  serviceName: keycloak
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: {{ .Values.image }}
          args:
            - start-dev
            - --http-port={{ .Values.service.port }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          env:
            - name: KEYCLOAK_ADMIN
              value: {{ .Values.admin.username | quote }}
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: {{ .Values.admin.password | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
