"""Calibration harness and stationarity-regime models for DDM-15.7."""

from polisyos.ddm.calibration.audit import (
    CalibrationInvalidationStatus,
    build_calibration_audit,
    check_calibration_validity,
)
from polisyos.ddm.calibration.calibrate import (
    CalibrationExpiration,
    CalibrationReport,
    DetectionDelayTests,
    EmpiricalStationaryHoldout,
    FpTarget,
    Period,
    StationarityRegime,
    SyntheticDelayResult,
    average_run_length,
    binomial_wilson_interval,
    bootstrap_stationary_streams,
    calibrate_detector,
    first_alarm_index,
    first_alarm_index_with_thresholds,
    max_statistic_quantile,
    moving_block_bootstrap,
    stratified_bootstrap_stationary_streams,
    synthetic_delay_test,
    time_varying_thresholds,
)
from polisyos.ddm.calibration.multiple_testing import (
    MultipleTestingPlan,
    OnlineFDRController,
    OnlineFDRDecision,
    allocate_conservative_budget,
)

__all__ = [
    "CalibrationExpiration",
    "CalibrationInvalidationStatus",
    "CalibrationReport",
    "DetectionDelayTests",
    "EmpiricalStationaryHoldout",
    "FpTarget",
    "MultipleTestingPlan",
    "OnlineFDRController",
    "OnlineFDRDecision",
    "Period",
    "StationarityRegime",
    "SyntheticDelayResult",
    "allocate_conservative_budget",
    "average_run_length",
    "binomial_wilson_interval",
    "bootstrap_stationary_streams",
    "build_calibration_audit",
    "calibrate_detector",
    "check_calibration_validity",
    "first_alarm_index",
    "first_alarm_index_with_thresholds",
    "max_statistic_quantile",
    "moving_block_bootstrap",
    "stratified_bootstrap_stationary_streams",
    "synthetic_delay_test",
    "time_varying_thresholds",
]
