"""Public fabric world package API."""
from __future__ import annotations

from polisyos.fabric.world.store import (
    SEGMENTS_INDEX_NAME,
    WorldFactError,
    WorldIDError,
    WorldSegmentError,
    WorldStoreError,
    WorldValidationError,
    append_world_segment_index,
    emit_attr_fact,
    emit_claim_facts,
    emit_doc_fragment_facts,
    emit_doc_meta_facts,
    emit_edge_fact,
    emit_world_event_facts,
    emit_world_node_facts,
    event_world_provenance_v1,
    load_world_fact_manifests,
    persist_claim,
    persist_conflict_set,
    persist_doc_fragment,
    persist_doc_meta,
    persist_fact_segment_manifest,
    persist_quality_report,
    persist_trust_assessment,
    persist_world_event,
    stable_world_provenance_v1,
    validate_claim_id,
    validate_conflict_set_id,
    validate_doc_fragment_ids,
    validate_doc_meta_ids,
    validate_fact_is_world_abi,
    validate_quality_report_id,
    validate_trust_assessment_id,
    validate_world_event_id,
    validate_world_facts,
    write_world_fact_segment,
)

try:
    from polisyos.fabric.world.materialize import (
        MergeStrategy,
        WorldArtifactReadError,
        WorldKuzuCopyError,
        WorldKuzuImportError,
        WorldKuzuNotAvailable,
        WorldMaterializationError,
        WorldMaterializeSegmentStats,
        WorldMaterializeStats,
        WorldMergeConflict,
        WorldSchemaError,
        WorldSegmentHashMismatch,
        apply_world_segment,
        ensure_world_kuzu_schema,
        ensure_world_materialized,
        ensure_world_schema,
        materialize_world_duckdb_from_fact_log,
        materialize_world_kuzu_from_duckdb,
    )
    _MATERIALIZE_AVAILABLE = True
except ModuleNotFoundError:  # pragma: no cover - optional dependency path
    _MATERIALIZE_AVAILABLE = False

__all__ = [
    "SEGMENTS_INDEX_NAME",
    "WorldFactError",
    "WorldIDError",
    "WorldSegmentError",
    "WorldStoreError",
    "WorldValidationError",
    "append_world_segment_index",
    "emit_attr_fact",
    "emit_claim_facts",
    "emit_doc_fragment_facts",
    "emit_doc_meta_facts",
    "emit_edge_fact",
    "emit_world_event_facts",
    "emit_world_node_facts",
    "event_world_provenance_v1",
    "load_world_fact_manifests",
    "persist_claim",
    "persist_conflict_set",
    "persist_doc_fragment",
    "persist_doc_meta",
    "persist_quality_report",
    "persist_trust_assessment",
    "persist_fact_segment_manifest",
    "persist_world_event",
    "stable_world_provenance_v1",
    "validate_claim_id",
    "validate_conflict_set_id",
    "validate_doc_fragment_ids",
    "validate_doc_meta_ids",
    "validate_fact_is_world_abi",
    "validate_quality_report_id",
    "validate_trust_assessment_id",
    "validate_world_event_id",
    "validate_world_facts",
    "write_world_fact_segment",
]

if _MATERIALIZE_AVAILABLE:
    __all__.extend(
        [
            "MergeStrategy",
            "WorldArtifactReadError",
            "WorldKuzuCopyError",
            "WorldKuzuImportError",
            "WorldKuzuNotAvailable",
            "WorldMaterializationError",
            "WorldMaterializeSegmentStats",
            "WorldMaterializeStats",
            "WorldMergeConflict",
            "WorldSchemaError",
            "WorldSegmentHashMismatch",
            "apply_world_segment",
            "ensure_world_materialized",
            "ensure_world_kuzu_schema",
            "ensure_world_schema",
            "materialize_world_duckdb_from_fact_log",
            "materialize_world_kuzu_from_duckdb",
        ]
    )
