import type { BureaucraticGenre } from "../../ast/bureaucratic-document-ast";

export const BUREAUCRATIC_WATERMARK =
  "Generated by PolicyOS / Draft / Not an official state document";

export const BUREAUCRATIC_GENRE_TITLES: Record<BureaucraticGenre, string> = {
  postanova_kmu: "Постанова КМУ",
  zakonoproekt: "Законопроект",
  expert_vysnovok: "Експертний висновок",
  analitichna_zapyska: "Аналітична записка",
};

export const BUREAUCRATIC_TEMPLATE_HELP: Record<BureaucraticGenre, string> = {
  postanova_kmu: "ua.kmu.postanova.v1",
  zakonoproekt: "ua.rada.zakonoproekt.v1",
  expert_vysnovok: "ua.expert_vysnovok.v1",
  analitichna_zapyska: "ua.analitichna_zapyska.v1",
};

export const EPISTEMIC_COLORS = {
  evidence_filled: "border-emerald-400/40 bg-emerald-500/10",
  model_generated: "border-sky-400/40 bg-sky-500/10",
  operator_filled: "border-amber-400/40 bg-amber-500/10",
  imported: "border-zinc-400/40 bg-zinc-500/10",
} as const;
