import { Children, isValidElement, type ReactNode } from "react";
import type { DecisionPacketAuthoredBlock } from "@polisyos/runtime-api-client";

import { GLYPH_ANCHORS } from "@/shared/brand/glyph-vocabulary";

export type AuthoredTextAuthor = NonNullable<
  DecisionPacketAuthoredBlock["author"]
>;

export const AUTHORSHIP_HIGHLIGHT_MODES = [
  "off",
  "subtle",
  "prominent",
] as const;

export type AuthorshipHighlightMode =
  (typeof AUTHORSHIP_HIGHLIGHT_MODES)[number];

export type AuthorshipSource = NonNullable<
  DecisionPacketAuthoredBlock["sources"]
>[number] & {
  ref: string;
};

export type AuthoredNarrativeBlock = {
  id?: DecisionPacketAuthoredBlock["id"];
  content: DecisionPacketAuthoredBlock["content"];
  author?: DecisionPacketAuthoredBlock["author"];
  author_agent_version?: DecisionPacketAuthoredBlock["author_agent_version"];
  sources?: AuthorshipSource[] | null;
  timestamp?: DecisionPacketAuthoredBlock["timestamp"];
  confidence?: DecisionPacketAuthoredBlock["confidence"];
  reviewed_by_human?: DecisionPacketAuthoredBlock["reviewed_by_human"];
};

export type NormalizedAuthoredNarrativeBlock = {
  id: string;
  content: string;
  author: AuthoredTextAuthor | null;
  authorAgentVersion?: string;
  sourceRef?: string;
  sources: AuthorshipSource[];
  timestamp?: string;
  confidence?: number;
  reviewedByHuman: boolean;
};

export type AuthorRegistryEntry = {
  badgeLabel: string;
  borderVar: `--${string}`;
  glyph?: string;
  isModelCandidate: boolean;
  toneClassName: string;
  announcement: (sourceRef?: string) => string;
};

const CITATION_LABEL = "Citation";
const HUMAN_LABEL = "Operator";
const DRAFTER_LABEL = "Drafter";
const FORMALIZER_LABEL = "Formalizer";
const CRITIC_LABEL = "Critic";
const QUOTED_TEXT_PREFIX = "Quoted text from";
const AI_GENERATED_PREFIX = "AI-generated by";
const AI_REVIEW_PREFIX = "AI review by";

const AUTHOR_REGISTRY = {
  citation: {
    badgeLabel: CITATION_LABEL,
    borderVar: "--gold",
    isModelCandidate: false,
    toneClassName: "text-[var(--gold)]",
    announcement: (sourceRef) =>
      sourceRef
        ? `${QUOTED_TEXT_PREFIX} ${sourceRef}`
        : `${QUOTED_TEXT_PREFIX} cited source`,
  },
  human: {
    badgeLabel: HUMAN_LABEL,
    borderVar: "--line",
    isModelCandidate: false,
    toneClassName: "text-[var(--ink)]",
    announcement: () => HUMAN_LABEL,
  },
  drafter: {
    badgeLabel: DRAFTER_LABEL,
    borderVar: "--teal",
    glyph: GLYPH_ANCHORS.intervention,
    isModelCandidate: true,
    toneClassName: "text-[var(--teal)]",
    announcement: () => `${AI_GENERATED_PREFIX} ${DRAFTER_LABEL}`,
  },
  formalizer: {
    badgeLabel: FORMALIZER_LABEL,
    borderVar: "--slate",
    glyph: GLYPH_ANCHORS.identifiability,
    isModelCandidate: true,
    toneClassName: "text-[var(--slate)]",
    announcement: () => `${AI_GENERATED_PREFIX} ${FORMALIZER_LABEL}`,
  },
  critic: {
    badgeLabel: CRITIC_LABEL,
    borderVar: "--ember",
    glyph: GLYPH_ANCHORS.counterfactual,
    isModelCandidate: true,
    toneClassName: "text-[var(--ember)]",
    announcement: () => `${AI_REVIEW_PREFIX} ${CRITIC_LABEL}`,
  },
} satisfies Record<AuthoredTextAuthor, AuthorRegistryEntry>;

const UNRECOGNIZED_AUTHOR: AuthorRegistryEntry = {
  announcement: () => "Unrecognized authorship",
  badgeLabel: "Unrecognized author",
  borderVar: "--line",
  isModelCandidate: true,
  toneClassName: "text-[var(--muted)]",
};

export function getAuthorPresentation(
  author: AuthoredTextAuthor | null | undefined,
): AuthorRegistryEntry {
  return isAuthoredTextAuthor(author)
    ? AUTHOR_REGISTRY[author]
    : UNRECOGNIZED_AUTHOR;
}

export function isAuthoredTextAuthor(
  value: unknown,
): value is AuthoredTextAuthor {
  return typeof value === "string" && Object.hasOwn(AUTHOR_REGISTRY, value);
}

export function normalizeAuthorshipHighlightMode(
  value: unknown,
): AuthorshipHighlightMode {
  return typeof value === "string" &&
    (AUTHORSHIP_HIGHLIGHT_MODES as readonly string[]).includes(value)
    ? (value as AuthorshipHighlightMode)
    : "subtle";
}

export function normalizeAuthoredTextAuthor(
  value: unknown,
): AuthoredTextAuthor | null {
  return isAuthoredTextAuthor(value) ? value : null;
}

export function normalizeAuthoredNarrativeBlock(
  block: AuthoredNarrativeBlock,
): NormalizedAuthoredNarrativeBlock {
  const sources = block.sources ?? [];
  const sourceRef = sources[0]?.ref;
  const author = normalizeAuthoredTextAuthor(block.author);

  return {
    id:
      block.id?.trim() ||
      `legacy-${author ?? "unrecognized"}-${block.content.slice(0, 24)}`,
    content: block.content,
    author,
    authorAgentVersion: block.author_agent_version ?? undefined,
    confidence:
      typeof block.confidence === "number" ? block.confidence : undefined,
    reviewedByHuman: Boolean(block.reviewed_by_human),
    sourceRef,
    sources,
    timestamp: block.timestamp ?? undefined,
  };
}

export function excerptText(text: string, maxLength = 132) {
  const compact = text.replace(/\s+/gu, " ").trim();
  if (compact.length <= maxLength) {
    return compact;
  }
  return `${compact.slice(0, maxLength - 1).trimEnd()}…`;
}

export function extractTextFromNode(node: ReactNode): string {
  if (typeof node === "string" || typeof node === "number") {
    return String(node);
  }

  if (Array.isArray(node)) {
    return node.map((item) => extractTextFromNode(item)).join(" ");
  }

  if (!node) {
    return "";
  }

  if (isValidElement<{ children?: ReactNode }>(node)) {
    return extractTextFromNode(node.props.children ?? null);
  }

  return Children.toArray(node)
    .map((item) => extractTextFromNode(item))
    .join(" ");
}
