import { screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { afterEach } from "vitest";

import { renderWithProviders } from "@/test/render";

import { AuthoredText } from "./AuthoredText";
import {
  AuthorshipProvider,
  AuthorshipTimeline,
  useAuthorship,
} from "./AuthorshipProvider";

const CITATION_SOURCE = "Evidence bundle EB-17";
const CITATION_HREF = "/evidence?focus=artifact&artifactId=eb_17&runId=run-42";

afterEach(() => {
  window.history.replaceState(null, "", "/");
});

describe("AuthoredText", () => {
  it("renders unverified model prose as candidate and never as human reviewed", () => {
    window.history.replaceState(null, "", "/?trust=expanded");

    renderWithProviders(
      <AuthorshipProvider highlightMode="prominent">
        <AuthoredText
          author="drafter"
          data-testid="unverified-model-prose"
          reviewedByHuman
        >
          A model-authored recommendation awaiting governed verification.
        </AuthoredText>
      </AuthorshipProvider>,
    );

    expect(screen.getByTestId("unverified-model-prose")).toHaveAttribute(
      "data-authority-posture",
      "candidate",
    );
    expect(screen.getByTestId("unverified-model-prose")).toHaveClass(
      "border-dashed",
    );
    expect(screen.queryByText("Human reviewed")).not.toBeInTheDocument();
    expect(screen.queryByText("Verified")).not.toBeInTheDocument();
  });

  it("keeps model candidate clothing when authorship highlighting is off", () => {
    renderWithProviders(
      <AuthorshipProvider highlightMode="off">
        <AuthoredText author="critic" data-testid="quiet-model-prose">
          A model critique remains a candidate in low-noise reading mode.
        </AuthoredText>
      </AuthorshipProvider>,
    );

    expect(screen.getByTestId("quiet-model-prose")).toHaveStyle({
      borderLeftWidth: "1px",
    });
    expect(screen.getByTestId("quiet-model-prose")).toHaveClass(
      "border-dashed",
    );
  });

  it.each([
    {
      author: "citation" as const,
      expectedAnnouncement: `Quoted text from ${CITATION_SOURCE}. `,
      glyph: null,
      props: {
        sourceHref: CITATION_HREF,
        sourceRef: CITATION_SOURCE,
      },
      text: "Section 12 requires the baseline threshold to be published.",
    },
    {
      author: "human" as const,
      expectedAnnouncement: "Operator. ",
      glyph: null,
      props: {},
      text: "Operator confirmed the implementation window.",
    },
    {
      author: "drafter" as const,
      expectedAnnouncement: "AI-generated by Drafter. ",
      glyph: "⊙",
      props: {},
      text: "Drafter synthesized the decision summary for review.",
    },
    {
      author: "formalizer" as const,
      expectedAnnouncement: "AI-generated by Formalizer. ",
      glyph: "≔",
      props: {},
      text: "Formalizer normalized the policy language into a ratifiable draft.",
    },
    {
      author: "critic" as const,
      expectedAnnouncement: "AI review by Critic. ",
      glyph: "⋌",
      props: {},
      text: "Critic highlighted the unresolved uncertainty envelope.",
    },
  ])(
    "announces the $author register for assistive technologies",
    ({ author, expectedAnnouncement, glyph, props, text }) => {
      renderWithProviders(
        <AuthorshipProvider highlightMode="subtle">
          <AuthoredText author={author} {...props}>
            {text}
          </AuthoredText>
        </AuthorshipProvider>,
      );

      expect(
        screen.getByText((_, element) => {
          return (
            element?.classList.contains("sr-only") === true &&
            element.textContent === expectedAnnouncement
          );
        }),
      ).toBeInTheDocument();
      expect(screen.getByText(text)).toBeInTheDocument();
      expect(Boolean(glyph && screen.queryByText(glyph))).toBe(Boolean(glyph));
    },
  );

  it("renders citation badges as evidence links and exposes the prominent timeline", () => {
    renderWithProviders(
      <AuthorshipProvider highlightMode="prominent">
        <div className="gap-4 xl:grid xl:grid-cols-[minmax(0,1fr)_20rem]">
          <div className="space-y-4">
            <AuthoredText author="drafter" timestamp="2026-04-22T10:30:00Z">
              Drafter summarized the policy trade-off in one paragraph.
            </AuthoredText>
            <AuthoredText
              author="citation"
              sourceHref={CITATION_HREF}
              sourceRef={CITATION_SOURCE}
              timestamp="2026-04-22T10:32:00Z"
            >
              Section 12 requires the baseline threshold to be published.
            </AuthoredText>
          </div>
          <AuthorshipTimeline />
        </div>
      </AuthorshipProvider>,
    );

    expect(screen.getByTestId("authorship-timeline")).toBeInTheDocument();
    const citationLinks = screen.getAllByRole("link", {
      name: `Citation · ${CITATION_SOURCE}`,
    });
    expect(citationLinks).toHaveLength(2);
    expect(citationLinks[0]).toHaveAttribute("href", CITATION_HREF);
    expect(screen.getByText("Trace operator and AI prose")).toBeInTheDocument();
  });

  it("switches between off, subtle, and prominent highlight modes", async () => {
    const user = userEvent.setup();

    renderWithProviders(
      <AuthorshipProvider defaultHighlightMode="off">
        <AuthorshipModeHarness />
      </AuthorshipProvider>,
    );

    expect(screen.getByTestId("authorship-mode-value")).toHaveTextContent(
      "off",
    );
    expect(screen.queryByText("⊙")).not.toBeInTheDocument();
    expect(screen.queryByTestId("authorship-timeline")).not.toBeInTheDocument();

    await user.click(screen.getByRole("button", { name: "subtle" }));
    expect(screen.getByTestId("authorship-mode-value")).toHaveTextContent(
      "subtle",
    );
    expect(screen.getByText("⊙")).toBeInTheDocument();
    expect(screen.queryByTestId("authorship-timeline")).not.toBeInTheDocument();

    await user.click(screen.getByRole("button", { name: "prominent" }));
    expect(screen.getByTestId("authorship-mode-value")).toHaveTextContent(
      "prominent",
    );
    expect(screen.getByTestId("authorship-timeline")).toBeInTheDocument();
  });
});

function AuthorshipModeHarness() {
  const { highlightMode, setHighlightMode } = useAuthorship();

  return (
    <div className="gap-4 xl:grid xl:grid-cols-[minmax(0,1fr)_20rem]">
      <div className="space-y-4">
        <div className="flex gap-2">
          <button type="button" onClick={() => setHighlightMode("off")}>
            off
          </button>
          <button type="button" onClick={() => setHighlightMode("subtle")}>
            subtle
          </button>
          <button type="button" onClick={() => setHighlightMode("prominent")}>
            prominent
          </button>
        </div>
        <p data-testid="authorship-mode-value">{highlightMode}</p>
        <AuthoredText author="drafter" timestamp="2026-04-22T11:00:00Z">
          Drafter produced the current packet summary.
        </AuthoredText>
      </div>
      <AuthorshipTimeline />
    </div>
  );
}
