import { Children, isValidElement, type ReactNode } from "react";

import { GLYPH_ANCHORS } from "@/shared/brand/glyph-vocabulary";

export const AUTHORED_TEXT_AUTHORS = [
  "citation",
  "human",
  "drafter",
  "formalizer",
  "critic",
] as const;

export type AuthoredTextAuthor = (typeof AUTHORED_TEXT_AUTHORS)[number];

export const AUTHORSHIP_HIGHLIGHT_MODES = [
  "off",
  "subtle",
  "prominent",
] as const;

export type AuthorshipHighlightMode =
  (typeof AUTHORSHIP_HIGHLIGHT_MODES)[number];

export type AuthorshipSource = {
  kind?: string;
  ref: string;
};

export type AuthoredNarrativeBlock = {
  id?: string;
  content: string;
  author?: AuthoredTextAuthor | null;
  author_agent_version?: string | null;
  sources?: AuthorshipSource[] | null;
  timestamp?: string | null;
  confidence?: number | null;
  reviewed_by_human?: boolean | null;
};

export type NormalizedAuthoredNarrativeBlock = {
  id: string;
  content: string;
  author: AuthoredTextAuthor;
  authorAgentVersion?: string;
  sourceRef?: string;
  sources: AuthorshipSource[];
  timestamp?: string;
  confidence?: number;
  reviewedByHuman: boolean;
};

export type AuthorRegistryEntry = {
  badgeLabel: string;
  borderVar: `--${string}`;
  glyph?: string;
  toneClassName: string;
  announcement: (sourceRef?: string) => string;
};

const CITATION_LABEL = "Citation";
const HUMAN_LABEL = "Operator";
const DRAFTER_LABEL = "Drafter";
const FORMALIZER_LABEL = "Formalizer";
const CRITIC_LABEL = "Critic";
const QUOTED_TEXT_PREFIX = "Quoted text from";
const AI_GENERATED_PREFIX = "AI-generated by";
const AI_REVIEW_PREFIX = "AI review by";

export const AUTHOR_REGISTRY: Record<AuthoredTextAuthor, AuthorRegistryEntry> =
  {
    citation: {
      badgeLabel: CITATION_LABEL,
      borderVar: "--gold",
      toneClassName: "text-[var(--gold)]",
      announcement: (sourceRef) =>
        sourceRef
          ? `${QUOTED_TEXT_PREFIX} ${sourceRef}`
          : `${QUOTED_TEXT_PREFIX} cited source`,
    },
    human: {
      badgeLabel: HUMAN_LABEL,
      borderVar: "--line",
      toneClassName: "text-[var(--ink)]",
      announcement: () => HUMAN_LABEL,
    },
    drafter: {
      badgeLabel: DRAFTER_LABEL,
      borderVar: "--teal",
      glyph: GLYPH_ANCHORS.intervention,
      toneClassName: "text-[var(--teal)]",
      announcement: () => `${AI_GENERATED_PREFIX} ${DRAFTER_LABEL}`,
    },
    formalizer: {
      badgeLabel: FORMALIZER_LABEL,
      borderVar: "--slate",
      glyph: GLYPH_ANCHORS.identifiability,
      toneClassName: "text-[var(--slate)]",
      announcement: () => `${AI_GENERATED_PREFIX} ${FORMALIZER_LABEL}`,
    },
    critic: {
      badgeLabel: CRITIC_LABEL,
      borderVar: "--ember",
      glyph: GLYPH_ANCHORS.counterfactual,
      toneClassName: "text-[var(--ember)]",
      announcement: () => `${AI_REVIEW_PREFIX} ${CRITIC_LABEL}`,
    },
  };

export function isAuthoredTextAuthor(
  value: unknown,
): value is AuthoredTextAuthor {
  return (
    typeof value === "string" &&
    (AUTHORED_TEXT_AUTHORS as readonly string[]).includes(value)
  );
}

export function normalizeAuthorshipHighlightMode(
  value: unknown,
): AuthorshipHighlightMode {
  return typeof value === "string" &&
    (AUTHORSHIP_HIGHLIGHT_MODES as readonly string[]).includes(value)
    ? (value as AuthorshipHighlightMode)
    : "subtle";
}

export function normalizeAuthoredTextAuthor(
  value: unknown,
  fallback: AuthoredTextAuthor = "human",
): AuthoredTextAuthor {
  return isAuthoredTextAuthor(value) ? value : fallback;
}

export function normalizeAuthoredNarrativeBlock(
  block: AuthoredNarrativeBlock,
  fallbackAuthor: AuthoredTextAuthor = "human",
): NormalizedAuthoredNarrativeBlock {
  const sources = block.sources ?? [];
  const sourceRef = sources[0]?.ref;

  return {
    id:
      block.id?.trim() ||
      `legacy-${normalizeAuthoredTextAuthor(block.author, fallbackAuthor)}-${block.content.slice(0, 24)}`,
    content: block.content,
    author: normalizeAuthoredTextAuthor(block.author, fallbackAuthor),
    authorAgentVersion: block.author_agent_version ?? undefined,
    confidence:
      typeof block.confidence === "number" ? block.confidence : undefined,
    reviewedByHuman: Boolean(block.reviewed_by_human),
    sourceRef,
    sources,
    timestamp: block.timestamp ?? undefined,
  };
}

export function excerptText(text: string, maxLength = 132) {
  const compact = text.replace(/\s+/gu, " ").trim();
  if (compact.length <= maxLength) {
    return compact;
  }
  return `${compact.slice(0, maxLength - 1).trimEnd()}…`;
}

export function extractTextFromNode(node: ReactNode): string {
  if (typeof node === "string" || typeof node === "number") {
    return String(node);
  }

  if (Array.isArray(node)) {
    return node.map((item) => extractTextFromNode(item)).join(" ");
  }

  if (!node) {
    return "";
  }

  if (isValidElement<{ children?: ReactNode }>(node)) {
    return extractTextFromNode(node.props.children ?? null);
  }

  return Children.toArray(node)
    .map((item) => extractTextFromNode(item))
    .join(" ");
}
