import { expectNoA11yViolations } from "@/test/a11y";

import { AuthoredText } from "./AuthoredText";
import { AuthorshipProvider, AuthorshipTimeline } from "./AuthorshipProvider";

describe("AuthorshipProvider accessibility", () => {
  it("has no WCAG AA violations in prominent mode", async () => {
    await expectNoA11yViolations(
      <AuthorshipProvider defaultHighlightMode="prominent">
        <AuthoredText author="drafter" authorAgentVersion="drafter@1.4.2">
          This narrative block was generated by the drafting agent.
        </AuthoredText>
        <AuthorshipTimeline />
      </AuthorshipProvider>,
    );
  });
});
