"""Read complete actual native/negative XML+rawbytes; no estimator/native rerun."""
import collections,hashlib,json,pathlib,re,xml.etree.ElementTree as ET
OUT=pathlib.Path(__file__).resolve().parent;ORIGINAL=pathlib.Path('/tmp/e02-F-continuation-20261007/api/installed-resource-final-519');P=pathlib.Path('/tmp/e02-F-continuation-20261007/foundry/installed-default-resource-forward');OLD=pathlib.Path('/tmp/e02-F-continuation-20261007/foundry/installed-continuation-final');SHA='519e4822f608cbe4e7ac1ee7b01f6c29cb84bc82';TREE='750d28da94f372848fe6b2db5f88db95b94cb57d'
def read(n):return json.loads((P/n).read_text())
def ref(p):p=pathlib.Path(p);b=p.read_bytes();return {'path':str(p),'bytes':len(b),'sha256':hashlib.sha256(b).hexdigest()}
def outcome(c):return 'FAIL' if c.find('failure') is not None else 'ERROR' if c.find('error') is not None else 'SKIP' if c.find('skipped') is not None else 'PASS'
def key(c):return (c.attrib['classname'].split('tests.',1)[-1],c.attrib['name'])
profiles={};census=read('native-census.json');post=read('post-native-custody.json');assert post['outcome']=='PASS' and post['source_sha']==SHA
for kind in ['wheel','sdist']:
 run=read(kind+'-native-v2.json');proof=read(kind+'-installed-proof.json');xml=ET.parse(P/(kind+'-junit.xml'));cases=xml.findall('.//testcase');assert len(cases)==91 and collections.Counter(outcome(c) for c in cases)=={'PASS':91};assert proof['source_sha']==SHA and proof['source_tree']==TREE and proof['isolated']==1 and proof['pytest_exit']==0 and not proof['origin_violations'];assert len(proof['collected_ids'])==91
 site=pathlib.Path(read('installed-config.json')['sites'][kind]).resolve();assert all(pathlib.Path(v).resolve().is_relative_to(site) for v in proof['product_origins'].values());assert run['exit_code']==0 and run['environment']['PYTHONPATH']=='absent'
 for k in ['stdout','stderr','resources']:assert ref(run[k]['path'])==run[k]
 raw=(P/(kind+'-native-v2.stdout.txt')).read_text();err=(P/(kind+'-native-v2.stderr.txt')).read_text();assert not err;assert re.search(r'91 passed, 1 warning in [0-9.]+s',raw)
 warnings={'PytestUnknownMarkWarning':raw.count('PytestUnknownMarkWarning:'),'actual_flag_all_severities_format':len(re.findall(r'\[(?:INFO|WARNING|ERROR)\] [^\n]*?: (?:nan_detected|inf_detected|unexpected_key|missing_key|empty_array|shape_mismatch|distribution_shift)',raw+'\n'+err)),'LightGBM_literal':raw.count('LightGBM')+err.count('LightGBM'),'Prometheus_bootstrap_literal':raw.count('Prometheus metrics exporter disabled')+err.count('Prometheus metrics exporter disabled'),'load_simulation_result_degraded_literal':raw.count('Degraded path component=governance.confidence_pass')+err.count('Degraded path component=governance.confidence_pass')};assert warnings=={'PytestUnknownMarkWarning':1,'actual_flag_all_severities_format':0,'LightGBM_literal':0,'Prometheus_bootstrap_literal':0,'load_simulation_result_degraded_literal':0}
 graph=[c for c in cases if c.attrib['classname'].startswith('tests.')];assert len(graph)==79;old={key(c):outcome(c) for c in ET.parse(OLD/(kind+'-junit.xml')).iter('testcase')};assert all(key(c) in old for c in graph);base_counts=collections.Counter(old[key(c)] for c in graph);assert base_counts=={'PASS':47,'FAIL':32};modules=collections.Counter(c.attrib['classname'].split('.')[-1] for c in cases);assert modules=={'test_graph_intake_current_content':38,'test_reconcile_causal_graph_node':9,'test_reconcile_causal_graph':8,'test_graph_reconciliation':24,'test_installed_catalog_defaults':12}
 assert census['profiles'][kind]['actual_cases']==91 and census['profiles'][kind]['outcomes']=={'PASS':91} and census['profiles'][kind]['origin_count']==len(proof['product_origins'])==990
 own= json.loads((ORIGINAL/(kind+'-consumer-proof.json')).read_text());assert own['isolated']==1 and own['pytest_exit']==0 and len(own['collected_ids'])==1 and not own['origin_violations'];assert all(pathlib.Path(p).resolve().is_relative_to(site) for p in own['product_origins'].values())
 profiles[kind]={'outcomes':{'PASS':91,'FAIL':0,'ERROR':0,'SKIP':0},'native_modules':dict(modules),'origin_count':990,'origin_violations':0,'parent_isolated':1,'literal_warning_membership':warnings,'fullraw_outputs':[ref(P/(kind+'-native-v2.stdout.txt')),ref(P/(kind+'-native-v2.stderr.txt')),ref(P/(kind+'-junit.xml')),ref(P/(kind+'-installed-proof.json'))],'actualGraph79_b5_membership_counts':dict(base_counts),'currentGraph79':{'PASS':79},'b5_XML_ref':ref(OLD/(kind+'-junit.xml')),'fresh_reader_scope':'Actual Graph fixture fresh() reopens FileSystemCAS in sameprocess; no newGraphchild-I claim. Bothparent profiles-I; historicalAPI/FIT fresh-I readers remain different unchanged-source receipts.','own_selected_one_consumer':{'outcome':'PASS','owned_origins':len(own['product_origins']),'origin_violations':0,'proof':ref(ORIGINAL/(kind+'-consumer-proof.json'))}}
negatives=[]
for row in read('negative-controls.json')['profiles']:
 assert row['source_sha']==SHA and row['source_tree']==TREE and row['exit_code']==1 and row['outcome']=='FAIL';assert ref(row['stdout']['path'])==row['stdout'] and ref(row['stderr']['path'])==row['stderr'];raw=pathlib.Path(row['stdout']['path']).read_text();assert re.search(r'1 failed in [0-9.]+s',raw) and '1 error' not in raw and '1 skipped' not in raw
 if row['label']=='law-removal':assert 'FileNotFoundError' in raw and 'load_seed_alignments(seed)' in raw and '"public_identity_annotations_and_markers_preserved": true' in raw and '"restored_memory_body": true' in raw
 elif row['label']=='projection-missing':assert 'FileNotFoundError' in raw and 'raw = path.read_bytes()' in raw
 elif row['label']=='projection-changed':assert 'AssertionError' in raw and '1355 == 1309' in raw and 'retained-schema byte-substitution negative' in raw
 else:raise AssertionError(row['label'])
 negatives.append({'profile':row['kind'],'kind':row['label'],'actual_outcome':'FAIL','actual_failed_cases':1,'harness_error':False,'full_output':row['stdout'],'complete_command_record':row})
assert len(negatives)==6;assert post['current_installed']['complete_site_checks']==2*3464 and post['old_b5_installed_unchanged']['complete_site_checks']==2*3459 and post['actual_sdist_decoded_regular_members_unchanged']==12981
result={'source_sha':SHA,'source_tree':TREE,'outcome':'PASS','scope':'Complete read-only actual91nativeoutput+XML/origin/6negative review; exactlyoneadditionalcheapnative6ownerconsumer/profile. No duplicate79/TMLE/backend/science replay.','profiles':profiles,'expected_negative_actual_FAIL_count':len(negatives),'negative_review':negatives,'complete_postcustody':ref(P/'post-native-custody.json'),'custody_postscope':'Authorold/new before/after completebytes capturedpriorrootauthorizedOLDgeneratedarchive retirement; no claimretiredoldarchivecurrentavailability. Newcurrentbytes independentlyverifiedagain.','global_gate_limits':['38staticpublicparserUNKNOWN/canonical38FAIL notrerunorpromotedhere;source/bindingssameatresource81.','Productionoperational/statistical/valueRuntimeauthority andB56 competing-studybudget UNRUN.','Currentprofiles omitunchangedTMLE/API/ECOheavywave;oldb5API2/FIT53/ECO28 andprior8236scientificreceipts remaindifferent source/profile witnesses.','No compiledDoWhy/EconML invocation positivefromthis Graph79+resource12 run. App3.14 unchanged;worker3.12 merelyconfigured unchanged.']};(OUT/'native-output-review.json').write_text(json.dumps(result,indent=2)+'\n');print(json.dumps({'source_sha':SHA,'outcome':'PASS','profiles':{k:{x:v[x] for x in ['outcomes','native_modules','origin_count','literal_warning_membership','actualGraph79_b5_membership_counts']} for k,v in profiles.items()},'expected_negative_actual_FAIL':6,'own_consumer_each':'1PASSneutral-I'},indent=2))
