/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Health */
        get: operations["runtime_api_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run Details */
        get: operations["get_run_details"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run Timeline */
        get: operations["get_run_timeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run Nodes */
        get: operations["get_run_nodes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/lineage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run Lineage */
        get: operations["get_run_lineage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run Agents */
        get: operations["get_run_agents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/workflow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run Workflow */
        get: operations["get_run_workflow"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/debug/runs/{run_id}/nodes/{alias}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Node Debug */
        get: operations["get_node_debug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/debug/runs/{run_id}/governance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Governance Debug */
        get: operations["get_governance_debug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/debug/runs/{run_id}/errors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run Errors */
        get: operations["get_run_errors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artifacts/{artifact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Artifact Manifest */
        get: operations["get_artifact_manifest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artifacts/{artifact_id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Artifact Content */
        get: operations["get_artifact_content"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artifacts/{artifact_id}/lineage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Artifact Lineage */
        get: operations["get_artifact_lineage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artifacts/{artifact_id}/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Artifact Schema */
        get: operations["get_artifact_schema"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/control/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Launch a workflow run */
        post: operations["launch_run"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/control/runs/nl": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Launch a natural-language run via agent circuit */
        post: operations["launch_nl_run"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/control/data/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger data collection from connectors */
        post: operations["ingest_data"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/control/data/connectors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List available data connectors */
        get: operations["list_connectors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/control/data/cache": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get data cache status */
        get: operations["get_cache_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentPipelineAttempt */
        AgentPipelineAttempt: {
            /** Attempt */
            attempt: number;
            /**
             * Status
             * @default unknown
             */
            status: string;
            /** Verdict */
            verdict?: string | null;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Duration Ms */
            duration_ms?: number | null;
            /** Steps */
            steps?: components["schemas"]["AgentPipelineStep"][];
            /** Notes */
            notes?: string[];
        };
        /** AgentPipelineResponse */
        AgentPipelineResponse: {
            meta: components["schemas"]["ApiMeta"];
            pipeline: components["schemas"]["AgentPipelineView"];
        };
        /** AgentPipelineStep */
        AgentPipelineStep: {
            /**
             * Attempt
             * @default 1
             */
            attempt: number;
            /** Agent */
            agent: string;
            /** Action */
            action: string;
            /**
             * Status
             * @default info
             * @enum {string}
             */
            status: "ok" | "warn" | "fail" | "info";
            /** Timestamp */
            timestamp?: string | null;
            /** Summary */
            summary?: string | null;
            /** Details */
            details?: {
                [key: string]: unknown;
            };
            /** Prompt */
            prompt?: string | null;
            /** Response */
            response?: string | null;
            /** Model */
            model?: string | null;
            /** Latency Ms */
            latency_ms?: number | null;
            /** Token Usage */
            token_usage?: {
                [key: string]: number;
            };
        };
        /** AgentPipelineView */
        AgentPipelineView: {
            /** Run Id */
            run_id: string;
            /**
             * Source Kind
             * @constant
             */
            source_kind: "core_run";
            /**
             * Total Attempts
             * @default 0
             */
            total_attempts: number;
            /** Latest Verdict */
            latest_verdict?: string | null;
            /** Attempts */
            attempts?: components["schemas"]["AgentPipelineAttempt"][];
            decision_packet_ref?: components["schemas"]["ArtifactRef"] | null;
            reflexion_terminal_ref?: components["schemas"]["ArtifactRef"] | null;
            /** Source */
            source?: string | null;
            /** Notes */
            notes?: string[];
        };
        /** ApiMeta */
        ApiMeta: {
            /** Request Id */
            request_id: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at?: string;
            /** Source Kinds */
            source_kinds?: "core_run"[];
        };
        /** ArtifactContentPreview */
        ArtifactContentPreview: {
            /** Artifact Id */
            artifact_id: string;
            /** Kind */
            kind: string;
            /** Media Type */
            media_type: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "json" | "text" | "binary";
            /** Size Bytes */
            size_bytes: number;
            /** Max Bytes */
            max_bytes: number;
            /**
             * Truncated
             * @default false
             */
            truncated: boolean;
            /** Preview */
            preview?: unknown;
        };
        /** ArtifactContentResponse */
        ArtifactContentResponse: {
            meta: components["schemas"]["ApiMeta"];
            artifact: components["schemas"]["ArtifactContentPreview"];
        };
        /**
         * ArtifactID
         * @description Format: sha256:<64hex>
         */
        ArtifactID: string;
        /** ArtifactLineageEdge */
        ArtifactLineageEdge: {
            /** Parent Artifact Id */
            parent_artifact_id: string;
            /** Child Artifact Id */
            child_artifact_id: string;
            /** Role */
            role: string;
        };
        /** ArtifactLineageNode */
        ArtifactLineageNode: {
            /** Artifact Id */
            artifact_id: string;
            /** Role */
            role?: string | null;
            /** Kind */
            kind?: string | null;
            /** Status */
            status: string;
            /**
             * Byte Size
             * @default 0
             */
            byte_size: number;
            /**
             * Depth
             * @default 0
             */
            depth: number;
        };
        /** ArtifactLineageResponse */
        ArtifactLineageResponse: {
            meta: components["schemas"]["ApiMeta"];
            lineage: components["schemas"]["ArtifactLineageView"];
        };
        /** ArtifactLineageView */
        ArtifactLineageView: {
            /** Root Artifact Ids */
            root_artifact_ids?: string[];
            /**
             * Total Nodes
             * @default 0
             */
            total_nodes: number;
            /**
             * Total Edges
             * @default 0
             */
            total_edges: number;
            /**
             * Total Size Bytes
             * @default 0
             */
            total_size_bytes: number;
            /**
             * Is Complete
             * @default false
             */
            is_complete: boolean;
            /** Missing Artifact Ids */
            missing_artifact_ids?: string[];
            /** Corrupted Artifact Ids */
            corrupted_artifact_ids?: string[];
            /** Nodes */
            nodes?: components["schemas"]["ArtifactLineageNode"][];
            /** Edges */
            edges?: components["schemas"]["ArtifactLineageEdge"][];
        };
        /** ArtifactManifestResponse */
        ArtifactManifestResponse: {
            meta: components["schemas"]["ApiMeta"];
            artifact: components["schemas"]["ArtifactManifestView"];
        };
        /** ArtifactManifestView */
        ArtifactManifestView: {
            /** Artifact Id */
            artifact_id: string;
            /** Kind */
            kind: string;
            /** Media Type */
            media_type: string;
            /** Byte Size */
            byte_size: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Schema Name */
            schema_name?: string | null;
            /** Schema Version */
            schema_version?: string | null;
            /** Producer Component */
            producer_component?: string | null;
            /** Producer Version */
            producer_version?: string | null;
            /** Inputs */
            inputs?: components["schemas"]["InputRef"][];
            /** Integrity Sha256 */
            integrity_sha256: string;
        };
        /** ArtifactRef */
        ArtifactRef: {
            artifact_id: components["schemas"]["ArtifactID"];
            /** Kind */
            kind: string;
            /** Media Type */
            media_type: string;
        };
        /** ArtifactSchemaResponse */
        ArtifactSchemaResponse: {
            meta: components["schemas"]["ApiMeta"];
            schema: components["schemas"]["ArtifactSchemaView"];
        };
        /** ArtifactSchemaView */
        ArtifactSchemaView: {
            /** Artifact Id */
            artifact_id: string;
            /** Kind */
            kind: string;
            /** Media Type */
            media_type: string;
            /** Schema Name */
            schema_name?: string | null;
            /** Schema Version */
            schema_version?: string | null;
            /** Top Level Keys */
            top_level_keys?: string[];
        };
        /** CacheEntryInfo */
        CacheEntryInfo: {
            /** Cache Key */
            cache_key: string;
            /** Connector Id */
            connector_id: string;
            /** Dataset Id */
            dataset_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Expires At */
            expires_at?: string | null;
            /**
             * Size Bytes
             * @default 0
             */
            size_bytes: number;
            /**
             * Is Valid
             * @default true
             */
            is_valid: boolean;
        };
        /** CacheStatusResponse */
        CacheStatusResponse: {
            meta: components["schemas"]["ApiMeta"];
            /**
             * Total Entries
             * @default 0
             */
            total_entries: number;
            /**
             * Total Size Bytes
             * @default 0
             */
            total_size_bytes: number;
            /** Entries */
            entries?: components["schemas"]["CacheEntryInfo"][];
        };
        /** ConnectorInfo */
        ConnectorInfo: {
            /** Connector Id */
            connector_id: string;
            /** Namespace */
            namespace: string;
            /** Version */
            version: string;
            /** Known Datasets */
            known_datasets?: string[];
            /**
             * Loaded
             * @default false
             */
            loaded: boolean;
            /** Last Health Check */
            last_health_check?: string | null;
        };
        /** ConnectorsListResponse */
        ConnectorsListResponse: {
            meta: components["schemas"]["ApiMeta"];
            /** Connectors */
            connectors?: components["schemas"]["ConnectorInfo"][];
        };
        /** CursorPage */
        CursorPage: {
            /**
             * Limit
             * @default 50
             */
            limit: number;
            /** Cursor */
            cursor?: string | null;
            /** Next Cursor */
            next_cursor?: string | null;
            /**
             * Count
             * @default 0
             */
            count: number;
            /** Total */
            total?: number | null;
        };
        /**
         * DataSourceBinding
         * @description Exactly one of these fields must be provided.
         */
        DataSourceBinding: {
            /** Data Snapshot Ref */
            data_snapshot_ref?: string | null;
            /** Input Bindings Ref */
            input_bindings_ref?: string | null;
            /** Data View Request Ref */
            data_view_request_ref?: string | null;
        };
        /** DatasetFetchSpecRequest */
        DatasetFetchSpecRequest: {
            /** Connector Id */
            connector_id: string;
            /** Dataset Id */
            dataset_id: string;
            /** Filters */
            filters?: {
                [key: string]: string[];
            };
            /** Date Start */
            date_start?: string | null;
            /** Date End */
            date_end?: string | null;
        };
        /** GovernanceDebugResponse */
        GovernanceDebugResponse: {
            meta: components["schemas"]["ApiMeta"];
            debug: components["schemas"]["GovernanceDebugView"];
        };
        /** GovernanceDebugView */
        GovernanceDebugView: {
            /** Run Id */
            run_id: string;
            /**
             * Source Kind
             * @constant
             */
            source_kind: "core_run";
            /** Verdict */
            verdict?: string | null;
            /** Issues */
            issues?: {
                [key: string]: unknown;
            }[];
            /** Notes */
            notes?: string[];
            report_ref?: components["schemas"]["ArtifactRef"] | null;
            /** Validation Trace */
            validation_trace?: {
                [key: string]: unknown;
            } | null;
            /**
             * Fallback From Decision Packet
             * @default false
             */
            fallback_from_decision_packet: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IngestRequest
         * @description POST /api/v1/control/data/ingest — trigger data collection.
         */
        IngestRequest: {
            /** Datasets */
            datasets: components["schemas"]["DatasetFetchSpecRequest"][];
            /**
             * Source
             * @default dashboard
             */
            source: string;
            /**
             * License Name
             * @default open
             */
            license_name: string;
            /**
             * Cache Policy
             * @default default
             */
            cache_policy: string;
        };
        /** IngestResponse */
        IngestResponse: {
            meta: components["schemas"]["ApiMeta"];
            /**
             * Status
             * @enum {string}
             */
            status: "completed" | "partial" | "failed";
            /** Evidence Bundle Ref */
            evidence_bundle_ref?: string | null;
            /**
             * Datasets Fetched
             * @default 0
             */
            datasets_fetched: number;
            /** Message */
            message: string;
        };
        /** InputRef */
        InputRef: {
            artifact_id: components["schemas"]["ArtifactID"];
            /** Role */
            role: string;
        };
        /**
         * NaturalLanguageRunRequest
         * @description POST /api/v1/control/runs/nl — NL request triggering agent circuit.
         */
        NaturalLanguageRunRequest: {
            /** Request */
            request: string;
            /** Context */
            context?: {
                [key: string]: unknown;
            };
            /** Domain Hint */
            domain_hint?: string | null;
            data_source?: components["schemas"]["DataSourceBinding"] | null;
            /**
             * Max Iterations
             * @default 3
             */
            max_iterations: number;
            /** Llm Model */
            llm_model?: string | null;
            /**
             * Checkpoint Policy
             * @default strict
             * @enum {string}
             */
            checkpoint_policy: "strict" | "lenient" | "disabled";
        };
        /** NodeDebugResponse */
        NodeDebugResponse: {
            meta: components["schemas"]["ApiMeta"];
            debug: components["schemas"]["NodeDebugView"];
        };
        /** NodeDebugView */
        NodeDebugView: {
            /** Run Id */
            run_id: string;
            /**
             * Source Kind
             * @constant
             */
            source_kind: "core_run";
            /** Alias */
            alias: string;
            record: components["schemas"]["RunNodeRecord"];
            /** Timeline Events */
            timeline_events?: components["schemas"]["RunTimelineEvent"][];
            /**
             * Cache Hits
             * @default 0
             */
            cache_hits: number;
            /**
             * Cache Stores
             * @default 0
             */
            cache_stores: number;
            /**
             * Cache Bypasses
             * @default 0
             */
            cache_bypasses: number;
            /** Notes */
            notes?: string[];
        };
        /** RunDetails */
        RunDetails: {
            /** Run Id */
            run_id: string;
            /**
             * Source Kind
             * @constant
             */
            source_kind: "core_run";
            /** Status */
            status: string;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Duration Ms */
            duration_ms?: number | null;
            /** Tenant Id */
            tenant_id?: string | null;
            /** Cell Id */
            cell_id?: string | null;
            /**
             * Has Trace
             * @default false
             */
            has_trace: boolean;
            manifest_ref?: components["schemas"]["ArtifactRef"] | null;
            trace_ref?: components["schemas"]["ArtifactRef"] | null;
            /** Root Artifacts */
            root_artifacts?: components["schemas"]["ArtifactRef"][];
            /**
             * Has Workflow Report
             * @default false
             */
            has_workflow_report: boolean;
            workflow_report_ref?: components["schemas"]["ArtifactRef"] | null;
            /** Warnings */
            warnings?: string[];
        };
        /** RunDetailsResponse */
        RunDetailsResponse: {
            meta: components["schemas"]["ApiMeta"];
            run: components["schemas"]["RunDetails"];
        };
        /** RunErrorView */
        RunErrorView: {
            /**
             * Source
             * @enum {string}
             */
            source: "manifest" | "workflow_report" | "trace" | "runtime";
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Node Alias */
            node_alias?: string | null;
            /** Timestamp */
            timestamp?: string | null;
            /** Details */
            details?: {
                [key: string]: unknown;
            };
        };
        /** RunErrorsResponse */
        RunErrorsResponse: {
            meta: components["schemas"]["ApiMeta"];
            /** Run Id */
            run_id: string;
            /** Errors */
            errors?: components["schemas"]["RunErrorView"][];
        };
        /** RunLaunchResponse */
        RunLaunchResponse: {
            meta: components["schemas"]["ApiMeta"];
            /**
             * Status
             * @enum {string}
             */
            status: "accepted" | "rejected";
            /** Run Id */
            run_id: string;
            /** Message */
            message: string;
        };
        /** RunLineageResponse */
        RunLineageResponse: {
            meta: components["schemas"]["ApiMeta"];
            /** Run Id */
            run_id: string;
            lineage: components["schemas"]["ArtifactLineageView"];
        };
        /** RunNodeRecord */
        RunNodeRecord: {
            /** Alias */
            alias: string;
            /** Node Id */
            node_id?: string | null;
            /**
             * Status
             * @default unknown
             * @enum {string}
             */
            status: "ok" | "skip" | "fail" | "unknown";
            /**
             * Duration Ms
             * @default 0
             */
            duration_ms: number;
            /** Error Code */
            error_code?: string | null;
            /** Error Message */
            error_message?: string | null;
            /** Error Details */
            error_details?: {
                [key: string]: unknown;
            };
            /** Skip Reason */
            skip_reason?: string | null;
            /** Artifact Ids */
            artifact_ids?: string[];
            /** Input Artifact Ids */
            input_artifact_ids?: string[];
            /** Output Artifact Ids */
            output_artifact_ids?: string[];
        };
        /** RunNodesResponse */
        RunNodesResponse: {
            meta: components["schemas"]["ApiMeta"];
            /** Run Id */
            run_id: string;
            /**
             * Source Kind
             * @constant
             */
            source_kind: "core_run";
            /** Nodes */
            nodes?: components["schemas"]["RunNodeRecord"][];
        };
        /** RunSummary */
        RunSummary: {
            /** Run Id */
            run_id: string;
            /**
             * Source Kind
             * @constant
             */
            source_kind: "core_run";
            /** Status */
            status: string;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Duration Ms */
            duration_ms?: number | null;
            /** Tenant Id */
            tenant_id?: string | null;
            /** Cell Id */
            cell_id?: string | null;
            /**
             * Has Trace
             * @default false
             */
            has_trace: boolean;
            /**
             * Root Artifact Count
             * @default 0
             */
            root_artifact_count: number;
            /**
             * Has Workflow Report
             * @default false
             */
            has_workflow_report: boolean;
            /** Warnings */
            warnings?: string[];
        };
        /** RunTimelineEvent */
        RunTimelineEvent: {
            /** Index */
            index: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Phase */
            phase: string;
            /** Event */
            event: string;
            /** Span Id */
            span_id?: string | null;
            /** Parent Span Id */
            parent_span_id?: string | null;
            /** Input Artifact Ids */
            input_artifact_ids?: string[];
            /** Output Artifact Ids */
            output_artifact_ids?: string[];
            /** Metrics */
            metrics?: {
                [key: string]: number;
            };
            /**
             * Warning Count
             * @default 0
             */
            warning_count: number;
            /**
             * Error Count
             * @default 0
             */
            error_count: number;
        };
        /** RunTimelineResponse */
        RunTimelineResponse: {
            meta: components["schemas"]["ApiMeta"];
            timeline: components["schemas"]["RunTimelineView"];
        };
        /** RunTimelineSummary */
        RunTimelineSummary: {
            /** Run Id */
            run_id: string;
            /**
             * Total Events
             * @default 0
             */
            total_events: number;
            /** Duration Ms */
            duration_ms?: number | null;
            /** Node Status Counts */
            node_status_counts?: {
                [key: string]: number;
            };
            /** Phase Counts */
            phase_counts?: {
                [key: string]: number;
            };
            /**
             * Cache Hits
             * @default 0
             */
            cache_hits: number;
            /**
             * Cache Stores
             * @default 0
             */
            cache_stores: number;
            /**
             * Cache Bypasses
             * @default 0
             */
            cache_bypasses: number;
        };
        /** RunTimelineView */
        RunTimelineView: {
            /** Run Id */
            run_id: string;
            /**
             * Source Kind
             * @constant
             */
            source_kind: "core_run";
            summary: components["schemas"]["RunTimelineSummary"];
            /** Events */
            events?: components["schemas"]["RunTimelineEvent"][];
            /** Notes */
            notes?: string[];
        };
        /** RunWorkflowEdgeView */
        RunWorkflowEdgeView: {
            /** From Alias */
            from_alias: string;
            /** To Alias */
            to_alias: string;
        };
        /** RunWorkflowNodeView */
        RunWorkflowNodeView: {
            /** Alias */
            alias: string;
            /** Node Id */
            node_id?: string | null;
            /** Depends On */
            depends_on?: string[];
            /**
             * Depth
             * @default 0
             */
            depth: number;
            /**
             * Status
             * @default unknown
             * @enum {string}
             */
            status: "ok" | "skip" | "fail" | "unknown";
            /**
             * Duration Ms
             * @default 0
             */
            duration_ms: number;
            /** Error Code */
            error_code?: string | null;
            /** Error Message */
            error_message?: string | null;
            /** Artifact Ids */
            artifact_ids?: string[];
            /** Input Artifact Ids */
            input_artifact_ids?: string[];
            /** Output Artifact Ids */
            output_artifact_ids?: string[];
            /**
             * Heat
             * @default 0
             */
            heat: number;
        };
        /** RunWorkflowResponse */
        RunWorkflowResponse: {
            meta: components["schemas"]["ApiMeta"];
            workflow: components["schemas"]["RunWorkflowView"];
        };
        /** RunWorkflowSummary */
        RunWorkflowSummary: {
            /** Workflow Id */
            workflow_id?: string | null;
            /** Error Policy */
            error_policy?: string | null;
            /** Status */
            status?: string | null;
            /**
             * Node Count
             * @default 0
             */
            node_count: number;
            /**
             * Edge Count
             * @default 0
             */
            edge_count: number;
            /**
             * Ok Count
             * @default 0
             */
            ok_count: number;
            /**
             * Skip Count
             * @default 0
             */
            skip_count: number;
            /**
             * Fail Count
             * @default 0
             */
            fail_count: number;
            /**
             * Max Depth
             * @default 0
             */
            max_depth: number;
            /** Critical Path Duration Ms */
            critical_path_duration_ms?: number | null;
        };
        /** RunWorkflowView */
        RunWorkflowView: {
            /** Run Id */
            run_id: string;
            /**
             * Source Kind
             * @constant
             */
            source_kind: "core_run";
            summary: components["schemas"]["RunWorkflowSummary"];
            /** Nodes */
            nodes?: components["schemas"]["RunWorkflowNodeView"][];
            /** Edges */
            edges?: components["schemas"]["RunWorkflowEdgeView"][];
            workflow_spec_ref?: components["schemas"]["ArtifactRef"] | null;
            workflow_report_ref?: components["schemas"]["ArtifactRef"] | null;
            /** Notes */
            notes?: string[];
        };
        /** RunsListResponse */
        RunsListResponse: {
            meta: components["schemas"]["ApiMeta"];
            page: components["schemas"]["CursorPage"];
            /** Runs */
            runs?: components["schemas"]["RunSummary"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WorkflowRunRequest
         * @description POST /api/v1/control/runs — launch a workflow run.
         */
        WorkflowRunRequest: {
            /**
             * Mode
             * @default workflow
             * @enum {string}
             */
            mode: "workflow" | "agent_circuit";
            data_source: components["schemas"]["DataSourceBinding"];
            /** Trinity Bundle Ref */
            trinity_bundle_ref?: string | null;
            /** Policy Spec Ref */
            policy_spec_ref?: string | null;
            /** Model Spec Ref */
            model_spec_ref?: string | null;
            /** Research Intent Ref */
            research_intent_ref?: string | null;
            /** Knowledge Bundle Ref */
            knowledge_bundle_ref?: string | null;
            /** Norm Pack Ref */
            norm_pack_ref?: string | null;
            /** Calibration Report Ref */
            calibration_report_ref?: string | null;
            /**
             * Checkpoint Policy
             * @default strict
             * @enum {string}
             */
            checkpoint_policy: "strict" | "lenient" | "disabled";
            /** Params */
            params?: {
                [key: string]: unknown;
            };
        };
        /** RuntimeApiProblem */
        RuntimeApiProblem: {
            /**
             * Type
             * @default about:blank
             */
            type: string;
            /** Title */
            title: string;
            /**
             * Status
             * @default 500
             */
            status: number;
            /** Detail */
            detail: string;
            /** Code */
            code: string;
            /**
             * Instance
             * @default null
             */
            instance: string | null;
            /**
             * Request Id
             * @default null
             */
            request_id: string | null;
            /**
             * Error
             * @default null
             */
            error: string | null;
            /**
             * Status Code
             * @default 500
             */
            status_code: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Malformed request payload or parameters. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Authentication is required for this route. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Authenticated principal cannot access this resource. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Requested resource does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Request validation failed. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Unexpected runtime API failure. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
        };
    };
    ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Malformed request payload or parameters. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Authentication is required for this route. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Authenticated principal cannot access this resource. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Requested resource does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Request validation failed. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Unexpected runtime API failure. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
        };
    };
    runtime_api_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Malformed request payload or parameters. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Authentication is required for this route. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Authenticated principal cannot access this resource. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Requested resource does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Request validation failed. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Unexpected runtime API failure. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
        };
    };
    list_runs: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
                status?: string | null;
                from_ts?: string | null;
                to_ts?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunsListResponse"];
                };
            };
            /** @description Malformed request payload or parameters. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Authentication is required for this route. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Authenticated principal cannot access this resource. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Requested resource does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Unexpected runtime API failure. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
        };
    };
    get_run_details: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetailsResponse"];
                };
            };
            /** @description Malformed request payload or parameters. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Authentication is required for this route. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Authenticated principal cannot access this resource. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Requested resource does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Unexpected runtime API failure. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
        };
    };
    get_run_timeline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunTimelineResponse"];
                };
            };
            /** @description Malformed request payload or parameters. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Authentication is required for this route. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Authenticated principal cannot access this resource. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Requested resource does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Unexpected runtime API failure. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
        };
    };
    get_run_nodes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunNodesResponse"];
                };
            };
            /** @description Malformed request payload or parameters. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Authentication is required for this route. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Authenticated principal cannot access this resource. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Requested resource does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Unexpected runtime API failure. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
        };
    };
    get_run_lineage: {
        parameters: {
            query?: {
                root_artifact_id?: string[] | null;
                max_depth?: number | null;
                max_nodes?: number | null;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunLineageResponse"];
                };
            };
            /** @description Malformed request payload or parameters. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Authentication is required for this route. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Authenticated principal cannot access this resource. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Requested resource does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Unexpected runtime API failure. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
        };
    };
    get_run_agents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentPipelineResponse"];
                };
            };
            /** @description Malformed request payload or parameters. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Authentication is required for this route. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Authenticated principal cannot access this resource. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Requested resource does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Unexpected runtime API failure. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
        };
    };
    get_run_workflow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunWorkflowResponse"];
                };
            };
            /** @description Malformed request payload or parameters. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Authentication is required for this route. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Authenticated principal cannot access this resource. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Requested resource does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Unexpected runtime API failure. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
        };
    };
    get_node_debug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                alias: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeDebugResponse"];
                };
            };
            /** @description Malformed request payload or parameters. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Authentication is required for this route. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Authenticated principal cannot access this resource. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Requested resource does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Unexpected runtime API failure. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
        };
    };
    get_governance_debug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GovernanceDebugResponse"];
                };
            };
            /** @description Malformed request payload or parameters. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Authentication is required for this route. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Authenticated principal cannot access this resource. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Requested resource does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Unexpected runtime API failure. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
        };
    };
    get_run_errors: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunErrorsResponse"];
                };
            };
            /** @description Malformed request payload or parameters. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Authentication is required for this route. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Authenticated principal cannot access this resource. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Requested resource does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Unexpected runtime API failure. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
        };
    };
    get_artifact_manifest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactManifestResponse"];
                };
            };
            /** @description Malformed request payload or parameters. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Authentication is required for this route. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Authenticated principal cannot access this resource. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Requested resource does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Unexpected runtime API failure. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
        };
    };
    get_artifact_content: {
        parameters: {
            query?: {
                max_bytes?: number | null;
            };
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactContentResponse"];
                };
            };
            /** @description Malformed request payload or parameters. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Authentication is required for this route. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Authenticated principal cannot access this resource. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Requested resource does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Unexpected runtime API failure. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
        };
    };
    get_artifact_lineage: {
        parameters: {
            query?: {
                max_depth?: number | null;
                max_nodes?: number | null;
            };
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactLineageResponse"];
                };
            };
            /** @description Malformed request payload or parameters. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Authentication is required for this route. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Authenticated principal cannot access this resource. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Requested resource does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Unexpected runtime API failure. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
        };
    };
    get_artifact_schema: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactSchemaResponse"];
                };
            };
            /** @description Malformed request payload or parameters. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Authentication is required for this route. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Authenticated principal cannot access this resource. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Requested resource does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Unexpected runtime API failure. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
        };
    };
    launch_run: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunLaunchResponse"];
                };
            };
            /** @description Malformed request payload or parameters. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Authentication is required for this route. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Authenticated principal cannot access this resource. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Requested resource does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Unexpected runtime API failure. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
        };
    };
    launch_nl_run: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NaturalLanguageRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunLaunchResponse"];
                };
            };
            /** @description Malformed request payload or parameters. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Authentication is required for this route. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Authenticated principal cannot access this resource. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Requested resource does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Unexpected runtime API failure. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
        };
    };
    ingest_data: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResponse"];
                };
            };
            /** @description Malformed request payload or parameters. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Authentication is required for this route. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Authenticated principal cannot access this resource. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Requested resource does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Unexpected runtime API failure. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
        };
    };
    list_connectors: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectorsListResponse"];
                };
            };
            /** @description Malformed request payload or parameters. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Authentication is required for this route. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Authenticated principal cannot access this resource. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Requested resource does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Request validation failed. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Unexpected runtime API failure. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
        };
    };
    get_cache_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CacheStatusResponse"];
                };
            };
            /** @description Malformed request payload or parameters. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Authentication is required for this route. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Authenticated principal cannot access this resource. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Requested resource does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Request validation failed. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
            /** @description Unexpected runtime API failure. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["RuntimeApiProblem"];
                };
            };
        };
    };
}
