import hashlib,json,re,subprocess
from pathlib import Path
out=Path(__file__).parent;author=Path('/workspace/e02-F-20261006-receipts/installed-latest');repo=Path('/workspace/polisyos')
source='5cd190d24d133f618fcc66ecc01f70c8a1b4f1f6';tree='c75afd88c27037708844f48d7789fbcbe84a4797'
def binding(path):
 p=Path(path);raw=p.read_bytes();return {'path':str(p),'bytes':len(raw),'sha256':hashlib.sha256(raw).hexdigest()}
def git_binding(path):
 raw=subprocess.check_output(['git','show',source+':'+path],cwd=repo)
 return {'source_sha':source,'source_tree':tree,'path':path,'bytes':len(raw),'sha256':hashlib.sha256(raw).hexdigest(),'git_blob':subprocess.check_output(['git','rev-parse',source+':'+path],cwd=repo,text=True).strip()}
summary=json.loads((out/'replay-summary.json').read_text());cache=json.loads((out/'cache-abi-pair.json').read_text());proof=json.loads((out/'full-source-archive-installed-bindings.json').read_text())
assert proof['product_byte_denominator']==2917 and proof['actual_python_denominator']==3146 and proof['byte_violations']==0
checks=[{'name':'complete Git/archive/owned-installed byte and path denominator','outcome':'PASS','output':str(out/'full-source-archive-installed-bindings.json'),'output_ref':binding(out/'full-source-archive-installed-bindings.json'),'command':['python3',str(out/'replay_and_bind.py')],'denominator':{'product_resources':2917,'all_actual_python':3146,'profiles':2,'byte_violations':0},'property':'Every declared product/resource and every actual wheel Python file matches immutable Git source, sdist member and both owned installed sites; exact installed Python name sets exclude omissions/extras.'}]
for r in summary['native_checks']:
 text=Path(r['output']).read_text();m=re.search(r'^(\d+) passed in ([0-9.]+)s$',text,re.M);assert m and int(m[1])==13
 origins=json.loads(text.splitlines()[-1]);assert origins['product_origin_count']==776 and origins['source_origin_violations']==0
 checks.append({**r,'name':r['profile']+' readonly independent original public/private algorithm, monkeypatch, pickle, canonical layout and CAS consumers','output_ref':binding(r['output']),'stderr_ref':binding(r['stderr']),'passed':13,'failed':0,'skipped':0,'errors':0,'warnings':0,'pytest_s':float(m[2]),'owned_product_origins':776,'origin_violations':0,'property':'Exact immutable API carrier executes native identification and patch/removal discriminators, persistence and canonical IR layout identity. No reflection/import-only scientific inference.'})
for r in cache:
 text=Path(r['output']).read_text();m=re.search(r'^(\d+) passed in ([0-9.]+)s$',text,re.M);assert m and int(m[1])==5
 origins=json.loads(text.splitlines()[-1]);assert origins['product_origin_count']==773 and origins['source_origin_violations']==0
 checks.append({**r,'name':r['profile']+' readonly installed root/methods canonical helper/factory identity plus independent B220 consumer controls','passed':5,'failed':0,'skipped':0,'errors':0,'warnings':0,'pytest_s':float(m[2]),'owned_product_origins':773,'origin_violations':0,'property':'Four root-Foundry/methods canonical functions and pure report factory preserve pickle identity. Independently exercises detached plain dict rows, model truth/ancestors, real fresh CAS and complete CSV quoting, actual to_kuzu parameter-call ABI with a recording consumer, once-per-version serialization/copy reset and real adjacency/component weakref cleanup.'})
author_checks=[]
for kind in ['wheel','sdist']:
 for suite,count,warnings in [('native',3,15),('b220',19,1)]:
  receipt=json.loads((author/(kind+'-'+suite+'.json')).read_text());assert receipt['exit_code']==0 and receipt['source_before']['head']==receipt['source_after']['head']==source
  output=receipt['outputs']['stdout'];assert binding(output['path'])==output
  text=Path(output['path']).read_text();assert re.search(r'\b'+str(count)+r' passed, '+str(warnings)+r' warnings in ',text)
  author_checks.append({'name':kind+' '+suite,'audit_role':'Complete author execution/raw output inspected, not rerun by this independent reviewer','outcome':'PASS','command':receipt['argv'],'output':output['path'],'output_ref':output,'execution_ref':binding(author/(kind+'-'+suite+'.json')),'passed':count,'warnings':warnings,'skip':0,'errors':0,'source_sha':source})
paths=['policy-engine/hatch.toml','policy-engine/src/polisyos/foundry/methods/catalog/causal/gcm_fit.py','policy-engine/src/polisyos/foundry/methods/catalog/causal/gcm_query.py','policy-engine/src/polisyos/ir/analytics/causal_graph.py','policy-engine/src/polisyos/foundry/methods/catalog/causal/_dowhy_worker.py','policy-engine/src/polisyos/foundry/methods/catalog/causal/dowhy_identify_estimate.py','policy-engine/src/polisyos/foundry/__init__.py','policy-engine/src/polisyos/foundry/methods/api.py','policy-engine/tests/unit/foundry/methods/catalog/causal/test_installed_facade_contract.py','policy-engine/tests/unit/foundry/methods/catalog/causal/test_installed_worker_profile.py','policy-engine/tests/unit/ir/test_causal_graph_cache_rows.py','policy-engine/tests/unit/foundry/methods/catalog/causal/test_performance_primitives.py']
profile_sources=[b for b in proof['product_bindings'] if b['source_path'].startswith('policy-engine/workers/dowhy-014/')];assert len(profile_sources)==6
companions=[binding(p) for p in sorted(out.iterdir()) if p.is_file() and p.name not in ['review.json','transfer-selection.json']]
scan_patterns={'github_token':r'\b(?:gh[pousr]_[A-Za-z0-9]{20,}|github_pat_[A-Za-z0-9_]{20,})\b','aws_access_key':r'\b(?:AKIA|ASIA)[A-Z0-9]{16}\b','private_key':r'-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----','signed_query':r'[?&](?:X-Amz-Signature|X-Goog-Signature|sig|signature|access_token|api_key)=[A-Za-z0-9%_+/-]{12,}'}
scan={k:[] for k in scan_patterns}
for b in companions:
 text=Path(b['path']).read_text(errors='replace')
 for name,pat in scan_patterns.items():
  if re.search(pat,text):scan[name].append(Path(b['path']).name)
assert not any(scan.values()),scan
status=subprocess.check_output(['git','status','--porcelain'],cwd='/workspace/e02-F-installed-worker-20261006',text=True)
review={'schema':'policyos.e02.independent-review.v1','unit':'F','slice':'installed-latest-dependencies-20261006','reviewer':'fit_tmle','implementation_sha':source,'implementation_tree':tree,'decision':'GO','decision_scope':'Bounded current-source installed package identity, canonical public/private consumer ABI and B220 cache/reader mechanism; no production admission or general causal validity claim.','closure_ids':[],'related_finding_ids':['B212','B213','B219','B220','B221','B223','LA-007','LA-019','LA-020'],'checks':checks,'author_checks_inspected':author_checks,'source_bindings':[git_binding(p) for p in paths],'canonical_profile_assets':profile_sources,'author_manifest_bindings':{p:binding(author/p) for p in ['archive-source-bindings.json','installed-source-bindings.json','wheel-setup-manifest.json','sdist-setup-manifest.json','candidate-source.json','compatibility_launch.py','environment.json','environment.stdout','final_launch.py']},'all_actual_python_denominator':3146,'product_byte_denominator':2917,'own_native_total':36,'own_skip_error_fail':0,'own_profile_mutations':0,'assets_read_back_unchanged':True,'observed_worktree_status':status,'monitor_residual':{'outcome':'limited','evidence':'Both complete author3-case outputs retain15 warnings including raw runner [ERROR] causal_effect_report missing_key and undeclared raw producer keys. The true dematerialize_method_output declared-slot consumer assertion passes; monitor diagnostic is retained and is not an invented full ABI closure.','output_refs':[binding(author/(k+'-native.stdout')) for k in ['wheel','sdist']]},'limits':['No live Kuzu backend: to_kuzu ABI is invoked with a recording consumer; real CSV and FileSystemCAS operations execute.','No in-process DoWhy/EconML baseline3.14 backend claim. Genuine configured canonical DoWhy3.12 worker and native GCM numerical/fresh-reader cases are author3-case executions inspected in full; reviewer runs independent readonly36 cases.','Third-party dependencies are reused from a readonly shared directory through literal .pth; product origins are owned installs, not source checkout. This is not independent dependency-resolution certification.','No four-family activation-to-state mapping, full arbitrary plugin/dynamic-filename retirement lifecycle, real-data causal estimand or production authority/input admission. Existing per-ID limited states remain.','No repository-wide architecture/invocation/P41 inherited-failure attribution from this narrow review. Historical oldab56 greens and pre-fix cache failure are retained separately.'],'credential_signedquery_scan':{'patterns':scan_patterns,'hits':scan,'sanitation':'none; complete deciding bytes retained'},'complete_companions':companions}
(out/'review.json').write_text(json.dumps(review,ensure_ascii=False,indent=2)+'\n')
files=[binding(out/'review.json'),*companions]
(out/'transfer-selection.json').write_text(json.dumps({'schema':'policyos.e02.transfer-selection.v1','source_sha':source,'source_tree':tree,'decision':'GO_bounded','files':files,'file_count':len(files),'total_bytes':sum(b['bytes'] for b in files),'sanitation':'none; no credential/signedquery pattern hits; complete moderate logs/proofs/replayers required'},indent=2)+'\n')
print(json.dumps({'review':binding(out/'review.json'),'transfer':binding(out/'transfer-selection.json'),'files':len(files),'bytes':sum(b['bytes'] for b in files),'decision':'GO','own_pass':36},indent=2))
