"""CausalRunSnapshot — reproducibility snapshot for a causal engine run.

Ties a ``run_id`` to a complete fingerprint of the inputs used: the causal
graph, the estimand, every dataset, all method invocations, and the runtime
environment.  Supports CAS persistence and lookup by run_id.

Design
------
- Frozen Pydantic model (``extra="forbid"``).
- ``stable_hash()`` — deterministic BLAKE2b-128 of all fingerprints; used as CAS key.
- ``persist_snapshot()`` / ``lookup_snapshot()`` — append-only JSONL index in
  ``<cas_root>/index/causal_run_snapshots.jsonl`` maps run_id → artifact_id.
"""

from __future__ import annotations

import hashlib
import json
import logging
import sys
from datetime import UTC, datetime
from functools import cached_property
from pathlib import Path
from typing import Any

import pandas as pd
from pydantic import BaseModel, ConfigDict, Field, ValidationError

from polisyos.ir.analytics.estimand import EstimandAST
from polisyos.ir.analytics.evidence_bundle import EvidenceFingerprintError, _fingerprint
from polisyos.ir.data.versioning import version_dataset

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Sub-models
# ---------------------------------------------------------------------------


class MethodInvocationRecord(BaseModel):
    """Record of a single method invocation during estimation."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    method_fqn: str
    """Fully-qualified method name (namespace.name)."""

    method_version: str | None = None
    """SemVer string, e.g. '1.0.0'."""

    backend: str = ""
    """Compute backend (e.g. 'numpy', 'sklearn', 'jax')."""

    params_hash: str = ""
    """Truncated SHA-256 of the params dict used."""

    determinism_tier: str = ""
    """DeterminismTier.value at invocation time."""

    library_versions: dict[str, str] = Field(default_factory=dict)
    """Snapshot of key library versions at invocation (e.g. {'numpy': '1.26.0'})."""

    is_nuisance: bool = False


# ---------------------------------------------------------------------------
# Main model
# ---------------------------------------------------------------------------


class CausalRunSnapshot(BaseModel):
    """Complete reproducibility snapshot for one causal engine run.

    All fingerprints are 16-char hex prefixes of SHA-256, consistent with
    the convention in ``ir/data/versioning.py``.
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    schema_version: str = "1.0"

    run_id: str
    """Unique identifier generated by CausalEngine.run()."""

    # Graph
    graph_fingerprint: str = ""
    """Fingerprint of the CausalGraphModel (nodes + edges serialised)."""

    graph_schema_version: str = ""
    """schema_version field from CausalGraphModel."""

    n_nodes: int = 0
    """Number of nodes in the causal graph at run time."""

    n_edges: int = 0
    """Number of edges in the causal graph at run time."""

    # Estimand
    estimand_fingerprint: str = ""
    """Fingerprint of the serialised EstimandAST."""

    estimand_shape: str = ""
    """EstimandShape.value chosen by the compiler."""

    query_str: str = ""
    """Human-readable query string."""

    # Data
    dataset_fingerprints: dict[str, str] = Field(default_factory=dict)
    """Map from dataset_ref → content_hash (from DatasetVersion)."""

    dataset_n_obs: dict[str, int] = Field(default_factory=dict)
    """Map from dataset_ref → number of observations."""

    # Methods
    method_invocations: tuple[MethodInvocationRecord, ...] = ()
    """One record per MethodDagNode executed."""

    # Plan linkage (optional — set when run via scientist)
    plan_hash: str | None = None
    method_catalog_hash: str | None = None

    # Environment
    algorithm_version: str = ""
    """Version of the identification algorithm (e.g. 'id_v1')."""

    python_version: str = ""
    """Python version string at run time."""

    created_at: str = ""
    """ISO 8601 UTC timestamp."""
    warnings: tuple[str, ...] = ()
    """Structured degradation signals captured while building the snapshot."""

    @cached_property
    def _stable_hash_value(self) -> str:
        payload = {
            "graph_fingerprint": self.graph_fingerprint,
            "estimand_fingerprint": self.estimand_fingerprint,
            "dataset_fingerprints": dict(sorted(self.dataset_fingerprints.items())),
            "method_invocations": [
                {
                    "fqn": r.method_fqn,
                    "version": r.method_version,
                    "params_hash": r.params_hash,
                }
                for r in sorted(self.method_invocations, key=lambda r: r.method_fqn)
            ],
            "algorithm_version": self.algorithm_version,
        }
        content = json.dumps(payload, separators=(",", ":"), sort_keys=True).encode("utf-8")
        return hashlib.blake2b(content, digest_size=16).hexdigest()

    def stable_hash(self) -> str:
        """Return a deterministic 32-char BLAKE2b hex hash of snapshot fingerprints.

        The hash covers only the content fingerprints (not timestamps or run_id),
        so two identical runs produce the same hash.
        """
        return self._stable_hash_value

    @classmethod
    def build(
        cls,
        *,
        run_id: str,
        graph: Any | None = None,
        estimand_ast_dict: dict[str, Any] | None = None,
        estimand_shape: str = "",
        query_str: str = "",
        estimation_steps: Any = (),  # tuple[EstimationStep, ...]
        data_dict: dict[str, Any] | None = None,
        algorithm_version: str = "",
        compilation_steps: Any = (),  # tuple[CompilationStep, ...]
    ) -> CausalRunSnapshot:
        """Factory: build from CausalEngine.run() artefacts."""
        warnings: dict[str, None] = {}

        def _add_warning(message: str, *, exc: Exception | None = None) -> None:
            warnings.setdefault(message, None)
            if exc is not None:
                logger.warning("Causal run snapshot warning %s: %s", message, exc)
            else:
                logger.warning("Causal run snapshot warning %s", message)

        # Graph fingerprint
        graph_fp = ""
        graph_schema_ver = ""
        n_nodes = 0
        n_edges = 0
        if graph is not None:
            try:
                g_dict = graph.model_dump(mode="json")
                graph_fp = _fingerprint(g_dict)
                graph_schema_ver = str(g_dict.get("schema_version", ""))
                n_nodes = len(g_dict.get("nodes", []))
                n_edges = len(g_dict.get("edges", []))
            except (AttributeError, TypeError, ValueError, EvidenceFingerprintError) as exc:
                _add_warning("graph_fingerprint_unavailable", exc=exc)

        # Estimand fingerprint
        estimand_fp = ""
        if estimand_ast_dict:
            try:
                estimand_fp = EstimandAST.model_validate(estimand_ast_dict).content_hash(
                    prefix=True
                )
            except (ValidationError, ValueError) as exc:
                _add_warning("estimand_normalization_failed", exc=exc)
                try:
                    estimand_fp = _fingerprint(estimand_ast_dict)
                except EvidenceFingerprintError as fingerprint_exc:
                    _add_warning("estimand_fingerprint_unavailable", exc=fingerprint_exc)

        # Estimand shape from compilation steps
        if not estimand_shape and compilation_steps:
            estimand_shape = (
                getattr(compilation_steps[0], "estimand_shape", "") if compilation_steps else ""
            )

        # Dataset fingerprints (cheap: just use dict keys + n_obs from DataProvenance)
        ds_fps: dict[str, str] = {}
        ds_nobs: dict[str, int] = {}
        if data_dict:
            for ref, df in data_dict.items():
                if isinstance(df, pd.DataFrame):
                    try:
                        ver = version_dataset(df, ref)
                        ds_fps[ref] = ver.content_hash
                        ds_nobs[ref] = ver.n_obs
                    except (TypeError, ValueError, OSError) as exc:
                        _add_warning(f"dataset_versioning_failed:{ref}", exc=exc)
                        try:
                            ds_fps[ref] = _fingerprint(
                                {"dataset_ref": ref, "python_type": type(df).__qualname__}
                            )
                        except EvidenceFingerprintError as fingerprint_exc:
                            _add_warning(
                                f"dataset_fingerprint_unavailable:{ref}",
                                exc=fingerprint_exc,
                            )
                            ds_fps[ref] = ""
                else:
                    try:
                        ds_fps[ref] = _fingerprint(
                            {"dataset_ref": ref, "python_type": type(df).__qualname__}
                        )
                    except EvidenceFingerprintError as exc:
                        _add_warning(f"dataset_fingerprint_unavailable:{ref}", exc=exc)
                        ds_fps[ref] = ""

        # Method invocations from EstimationStep
        invocations: list[MethodInvocationRecord] = []
        for step in estimation_steps:
            invocations.append(
                MethodInvocationRecord(
                    method_fqn=getattr(step, "method_fqn", ""),
                    method_version=getattr(step, "method_version", None),
                    backend=getattr(step, "backend", ""),
                    params_hash=getattr(step, "params_hash", ""),
                    determinism_tier=getattr(step, "determinism_tier", ""),
                    is_nuisance=getattr(step, "is_nuisance", False),
                )
            )

        return cls(
            run_id=run_id,
            graph_fingerprint=graph_fp,
            graph_schema_version=graph_schema_ver,
            n_nodes=n_nodes,
            n_edges=n_edges,
            estimand_fingerprint=estimand_fp,
            estimand_shape=estimand_shape,
            query_str=query_str,
            dataset_fingerprints=ds_fps,
            dataset_n_obs=ds_nobs,
            method_invocations=tuple(invocations),
            algorithm_version=algorithm_version,
            python_version=f"{sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}",
            created_at=datetime.now(UTC).isoformat(),
            warnings=tuple(warnings),
        )


# ---------------------------------------------------------------------------
# CAS persistence (optional — only used when a CAS is provided)
# ---------------------------------------------------------------------------


def persist_snapshot(snapshot: CausalRunSnapshot, cas_root: str | Path) -> str:
    """Persist snapshot to a CAS-like directory and return artifact_id.

    Writes JSON to ``<cas_root>/snapshots/<stable_hash>.json`` and appends a
    line to the index at ``<cas_root>/index/causal_run_snapshots.jsonl``.

    Returns
    -------
    str
        The stable_hash used as the artifact identifier.
    """
    root = Path(cas_root)
    artifact_id = snapshot.stable_hash()

    snap_dir = root / "snapshots"
    snap_dir.mkdir(parents=True, exist_ok=True)
    snap_path = snap_dir / f"{artifact_id}.json"
    if not snap_path.exists():
        snap_path.write_text(snapshot.model_dump_json(indent=2))

    index_dir = root / "index"
    index_dir.mkdir(parents=True, exist_ok=True)
    index_path = index_dir / "causal_run_snapshots.jsonl"
    entry = json.dumps({"run_id": snapshot.run_id, "artifact_id": artifact_id})
    with index_path.open("a") as fh:
        fh.write(entry + "\n")

    return artifact_id


def lookup_snapshot(
    run_id: str,
    cas_root: str | Path,
) -> CausalRunSnapshot | None:
    """Look up a CausalRunSnapshot by run_id from the CAS index.

    Scans ``<cas_root>/index/causal_run_snapshots.jsonl`` for the first entry
    matching *run_id*, then loads the snapshot JSON.

    Returns None if not found or if the file is corrupted.
    """
    root = Path(cas_root)
    index_path = root / "index" / "causal_run_snapshots.jsonl"
    if not index_path.exists():
        return None

    artifact_id: str | None = None
    try:
        for line in index_path.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line:
                continue
            entry = json.loads(line)
            if entry.get("run_id") == run_id:
                artifact_id = entry.get("artifact_id")
    except (OSError, TypeError, ValueError, json.JSONDecodeError) as exc:
        logger.warning("Failed to read causal run snapshot index '%s': %s", index_path, exc)
        return None

    if artifact_id is None:
        return None

    snap_path = root / "snapshots" / f"{artifact_id}.json"
    if not snap_path.exists():
        return None
    try:
        return CausalRunSnapshot.model_validate_json(snap_path.read_text(encoding="utf-8"))
    except (OSError, ValidationError, ValueError) as exc:
        logger.warning("Failed to load causal run snapshot '%s': %s", snap_path, exc)
        return None


__all__ = [
    "CausalRunSnapshot",
    "MethodInvocationRecord",
    "lookup_snapshot",
    "persist_snapshot",
]
