from .compiler import CompileReportRef, LinkReportRef
from .fabric import (
    DataViewRequestRef,
    EvidenceBundle,
    EvidenceBundleRef,
    FabricResult,
    FabricResultRef,
    QueryPlan,
    QueryPlanRef,
    UncertaintyBounds,
    UncertaintyBoundsRef,
    WarningsBundle,
    WarningsRef,
)
from .foundry import (
    CalibrationReportRef,
    ExecConfig,
    ExecConfigRef,
    ExecPlan,
    ExecPlanRef,
    EnvironmentManifestRef,
    LoweredIR,
    LoweredIRRef,
    Metrics,
    MetricsRef,
    PolicySurfaceIRRef,
    ProgramGraph,
    ProgramGraphRef,
    StateDelta,
    StateDeltaRef,
    StateSnapshot,
    StateSnapshotRef,
    TraceSliceRef,
    TreasurySeed,
    TreasurySeedRef,
)
try:
    # Legal contracts may pull in optional heavy dependencies.
    from .legal import NormPack, NormRef, NormRule, RuleType, RuleBackend

    _LEGAL_EXPORTS = ["NormPack", "NormRef", "NormRule", "RuleType", "RuleBackend"]
except ModuleNotFoundError:  # pragma: no cover
    _LEGAL_EXPORTS = []
from .scientist import CritiqueRef, DecisionCardRef, FailureCardRef, PolicyIRRef, TimelineRef
from .trinity import (
    ModelSpecRef,
    PolicySpecRef,
    ProblemFrameRef,
    TrinityBundle,
    TrinityManifest,
)

__all__ = [
    "DataViewRequestRef",
    "EvidenceBundle",
    "EvidenceBundleRef",
    "UncertaintyBounds",
    "UncertaintyBoundsRef",
    "ExecConfig",
    "ExecConfigRef",
    "ExecPlan",
    "ExecPlanRef",
    "EnvironmentManifestRef",
    "FabricResult",
    "FabricResultRef",
    "CalibrationReportRef",
    "LoweredIR",
    "LoweredIRRef",
    "Metrics",
    "MetricsRef",
    "PolicySurfaceIRRef",
    "ProgramGraph",
    "ProgramGraphRef",
    "QueryPlan",
    "QueryPlanRef",
    "StateDelta",
    "StateDeltaRef",
    "StateSnapshot",
    "StateSnapshotRef",
    "TraceSliceRef",
    "TreasurySeed",
    "TreasurySeedRef",
    "WarningsBundle",
    "WarningsRef",
    "LinkReportRef",
    "CompileReportRef",
    "FailureCardRef",
    "PolicyIRRef",
    "CritiqueRef",
    "TimelineRef",
    "DecisionCardRef",
    "ProblemFrameRef",
    "PolicySpecRef",
    "ModelSpecRef",
    "TrinityBundle",
    "TrinityManifest",
] + _LEGAL_EXPORTS
