"""Public builtins state keys module API."""

from __future__ import annotations

# Canonical input keys (ExperimentState.inputs)
INPUT_TRINITY_BUNDLE_REF = "trinity_bundle_ref"
INPUT_POLICY_SPEC_REF = "policy_spec_ref"
INPUT_MODEL_SPEC_REF = "model_spec_ref"
INPUT_REGISTRY_BUNDLE_REF = "registry_bundle_ref"
INPUT_DATA_SNAPSHOT_REF = "data_snapshot_ref"
INPUT_STATE_SNAPSHOT_REF = "state_snapshot_ref"
INPUT_INPUT_BINDINGS_REF = "input_bindings_ref"
INPUT_UKRAINE_FOUNDRY_METHOD_BUNDLE_REF = "ukraine_foundry_method_input_bundle_ref"
INPUT_UKRAINE_SELECTED_METHOD_CONTRACT_REF = "ukraine_selected_foundry_method_contract_ref"
INPUT_DATA_VIEW_REQUEST_REF = "data_view_request_ref"
INPUT_KNOWLEDGE_BUNDLE_REF = "knowledge_bundle_ref"
INPUT_RESEARCH_INTENT_REF = "research_intent_ref"
INPUT_NORM_PACK_REF = "norm_pack_ref"
INPUT_CALIBRATION_REPORT_REF = "calibration_report_ref"
INPUT_PARAMETER_OVERRIDE_BUNDLE_REF = "parameter_override_bundle_ref"
INPUT_EXECUTION_PLAN_REF = "execution_plan_ref"
INPUT_GRAPH_PRIOR_BUNDLE_REF = "graph_prior_bundle_ref"
INPUT_PRIOR_KNOWLEDGE_BUNDLE_REF = "prior_knowledge_bundle_ref"
INPUT_PROMOTION_EVIDENCE_BUNDLE_REF = "promotion_evidence_bundle_ref"

# Canonical artifact keys (ExperimentState.artifacts_index)
ARTIFACT_EXEC_PLAN_REF = "exec_plan_ref"
ARTIFACT_PROGRAM_GRAPH_REF = "program_graph_ref"
ARTIFACT_LOWERED_IR_REF = "lowered_ir_ref"
ARTIFACT_SIMULATION_RESULT_REF = "simulation_result_ref"
ARTIFACT_METRICS_REF = "metrics_ref"
ARTIFACT_METRIC_OBSERVATION_BUNDLE_REF = "metric_observation_bundle_ref"
ARTIFACT_METRIC_VALIDATION_REPORT_REF = "metric_validation_report_ref"
ARTIFACT_VALIDATION_REPORT_REF = "validation_report_ref"
ARTIFACT_FAIRNESS_AUDIT_REPORT_REF = "fairness_audit_report_ref"
ARTIFACT_SHIFT_DIAGNOSTIC_REPORT_REF = "shift_diagnostic_report_ref"
ARTIFACT_SENSITIVITY_ANALYSIS_BUNDLE_REF = "sensitivity_analysis_bundle_ref"
ARTIFACT_EXPLANATION_BUNDLE_REF = "explanation_bundle_ref"
ARTIFACT_JUDGE_VERDICT_REF = "judge_verdict_ref"
ARTIFACT_DRIFT_READINESS_REF = "drift_readiness_ref"
ARTIFACT_STATE_DELTA_REF = "state_delta_ref"
ARTIFACT_STATE_SNAPSHOT_REF = "state_snapshot_ref"
ARTIFACT_INPUT_BINDING_REPORT_REF = "input_binding_report_ref"
ARTIFACT_CONSTRAINT_REPORT_REF = "constraint_report_ref"
ARTIFACT_ENVIRONMENT_MANIFEST_REF = "environment_manifest_ref"
ARTIFACT_TEE_ATTESTATION_REF = "tee_attestation_ref"
ARTIFACT_SBOM_REF = "sbom_ref"
ARTIFACT_SLOT_LAYOUT_REF = "slot_layout_ref"
ARTIFACT_TREASURY_PLAN_REF = "treasury_plan_ref"
ARTIFACT_DECISION_PACKET_REF = "decision_packet_ref"
ARTIFACT_CLAIMS_REF = "claims_ref"
ARTIFACT_CLAIM_LEDGER_V2_REF = "claim_ledger_v2_ref"
ARTIFACT_RESEARCH_DAG_REF = "research_dag_ref"
ARTIFACT_VOI_RUN_REPORT_REF = "voi_run_report_ref"
ARTIFACT_CONTINUOUS_GOVERNANCE_REPORT_REF = "continuous_governance_report_ref"
ARTIFACT_REISSUE_PACKET_REF = "reissue_packet_ref"
ARTIFACT_WITHDRAWAL_RECORD_REF = "withdrawal_record_ref"
ARTIFACT_HUMAN_REVIEW_PACKET_REF = "human_review_packet_ref"
ARTIFACT_HUMAN_REVIEW_DECISION_REF = "human_review_decision_ref"
ARTIFACT_WEB_EVIDENCE_BUNDLE_REF = "web_evidence_bundle_ref"
ARTIFACT_DECISION_CARD_REF = "decision_card_ref"
ARTIFACT_PROPAGATION_REPORT_REF = "propagation_report_ref"
ARTIFACT_CAUSAL_REPORT_REF = "causal_report_ref"
ARTIFACT_CAUSAL_ENVELOPE_REF = "causal_envelope_ref"
ARTIFACT_CAUSAL_METHOD_RESULT_REF = "causal_method_result_ref"
ARTIFACT_CAUSAL_METHOD_EVIDENCE_REF = "causal_method_evidence_ref"
ARTIFACT_CAUSAL_VALIDITY_BUNDLE_REF = "causal_validity_bundle_ref"
ARTIFACT_STRUCTURAL_CAUSAL_MODEL_SPEC_REF = "structural_causal_model_spec_ref"
ARTIFACT_CAUSAL_QUERY_RESULT_REF = "causal_query_result_ref"
ARTIFACT_CAUSAL_QUERY_ENVELOPE_REF = "causal_query_envelope_ref"
ARTIFACT_CAUSAL_QUERY_METHOD_RESULT_REF = "causal_query_method_result_ref"
ARTIFACT_CAUSAL_QUERY_METHOD_EVIDENCE_REF = "causal_query_method_evidence_ref"
ARTIFACT_CAUSAL_ENSEMBLE_REF = "causal_ensemble_ref"
ARTIFACT_CAUSAL_ENSEMBLE_ENVELOPE_REF = "causal_ensemble_envelope_ref"
ARTIFACT_CAUSAL_EVIDENCE_BUNDLE_REF = "causal_evidence_bundle_ref"
ARTIFACT_PROOF_BUNDLE_REF = "proof_bundle_ref"
ARTIFACT_PROOF_WITNESS_INDEX_REF = "proof_witness_index_ref"
ARTIFACT_PROOF_COMPOSABILITY_CERTIFICATE_REF = "proof_composability_certificate_ref"
ARTIFACT_SIMULATION_CALIBRATION_RECEIPT_REF = "simulation_calibration_receipt_ref"
ARTIFACT_SIMULATION_PROOF_BRIDGE_REF = "simulation_proof_bridge_ref"
ARTIFACT_HTE_RESULT_REF = "hte_result_ref"
ARTIFACT_POLICY_RECOMMENDATION_REF = "policy_recommendation_ref"
ARTIFACT_BACKTEST_REPORT_REF = "backtest_report_ref"
ARTIFACT_DISTRIBUTIONAL_REPORT_REF = "distributional_report_ref"
ARTIFACT_DISTRIBUTIONAL_EFFECT_BUNDLE_REF = "distributional_effect_bundle_ref"
ARTIFACT_WELFARE_BUNDLE_REF = "welfare_bundle_ref"
ARTIFACT_OPTIMIZATION_AMBIGUITY_CERTIFICATE_REF = "optimization_ambiguity_certificate_ref"
ARTIFACT_FISCAL_FEEDBACK_LINK_REF = "fiscal_feedback_link_ref"
ARTIFACT_STRATEGIC_SCM_REF = "strategic_scm_ref"
ARTIFACT_STRATEGIC_RESPONSE_BUNDLE_REF = "strategic_response_bundle_ref"
ARTIFACT_ECONOMETRIC_RESULT_REF = "econometric_result_ref"
ARTIFACT_ECONOMETRIC_EVIDENCE_REF = "econometric_evidence_ref"
ARTIFACT_ECONOMETRIC_ENVELOPE_REF = "econometric_envelope_ref"
ARTIFACT_NORM_IMPACT_REPORT_REF = "norm_impact_report_ref"
ARTIFACT_SENSITIVITY_RESULT_REF = "sensitivity_result_ref"
ARTIFACT_TRANSPORTABILITY_RESULT_REF = "transportability_result_ref"
ARTIFACT_CAUSAL_READINESS_BUNDLE_REF = "causal_readiness_bundle_ref"
ARTIFACT_CAUSAL_EXECUTION_BUNDLE_REF = "causal_execution_bundle_ref"
ARTIFACT_BOUNDS_BUNDLE_REF = "bounds_bundle_ref"
ARTIFACT_DYNAMIC_TREATMENT_REGIME_REF = "dynamic_treatment_regime_ref"
ARTIFACT_EFFECT_TRAJECTORY_BUNDLE_REF = "effect_trajectory_bundle_ref"
ARTIFACT_NORMATIVE_ARBITRATION_RESULT_REF = "normative_arbitration_result_ref"
ARTIFACT_LITERATURE_PRIOR_REF = "literature_prior_ref"
ARTIFACT_LITERATURE_PRIOR_GRAPH_REF = "literature_prior_graph_ref"
ARTIFACT_RECONCILED_CAUSAL_GRAPH_REF = "reconciled_causal_graph_ref"
ARTIFACT_ALIGNMENT_REPORT_REF = "alignment_report_ref"
ARTIFACT_INTERFACE_MAPPING_REF = "interface_mapping_ref"
ARTIFACT_COMPOSITION_CERTIFICATE_REF = "composition_certificate_ref"
ARTIFACT_COMPOSITION_FAILURE_CARD_BUNDLE_REF = "composition_failure_card_bundle_ref"
ARTIFACT_CONTEXT_ADAPTIVE_PARAMETER_BUNDLE_REF = "context_adaptive_parameter_bundle_ref"
ARTIFACT_CROSS_GRAPH_EVIDENCE_PROFILE_REF = "cross_graph_evidence_profile_ref"
ARTIFACT_ABM_ALIGNMENT_REPORT_REF = "abm_alignment_report_ref"
ARTIFACT_FINITE_STATE_ABSTRACTION_MAP_REF = "finite_state_abstraction_map_ref"
ARTIFACT_ABSTRACTION_CERTIFICATE_REF = "abstraction_certificate_ref"
ARTIFACT_STRESS_TEST_REPORT_REF = "stress_test_report_ref"
ARTIFACT_CALIBRATION_VALIDATION_BUNDLE_REF = "calibration_validation_bundle_ref"
ARTIFACT_EXECUTION_PLAN_REF = "execution_plan_ref"
ARTIFACT_METHOD_CATALOG_SNAPSHOT_REF = "method_catalog_snapshot_ref"
ARTIFACT_CAUSAL_CAPABILITY_CONTRACT_REF = "causal_capability_contract_ref"
ARTIFACT_PREFLIGHT_REPORT_REF = "preflight_report_ref"
ARTIFACT_EVALUATOR_REPORT_REF = "evaluator_report_ref"
ARTIFACT_ITERATION_STATE_REF = "iteration_state_ref"
ARTIFACT_REPRODUCIBILITY_MANIFEST_REF = "reproducibility_manifest_ref"
ARTIFACT_POLICY_REQUEST_FRAME_REF = "policy_request_frame_ref"
ARTIFACT_LEGAL_CANDIDATE_PACK_REF = "legal_candidate_pack_ref"
ARTIFACT_LEGAL_SOURCE_PACK_REF = "legal_source_pack_ref"
ARTIFACT_SOURCE_VERIFICATION_REPORT_REF = "source_verification_report_ref"
ARTIFACT_POLICY_OPTION_SET_REF = "policy_option_set_ref"
ARTIFACT_VERIFIED_POLICY_REPORT_REF = "verified_policy_report_ref"
ARTIFACT_POLICY_FRONTIER_REPORT_REF = "policy_frontier_report_ref"
ARTIFACT_CHAMPION_POLICY_DOSSIER_REF = "champion_policy_dossier_ref"
ARTIFACT_POLICY_BRIEF_REF = "policy_brief_ref"
ARTIFACT_CONSTRAINT_SATISFACTION_REPORT_REF = "constraint_satisfaction_report_ref"
ARTIFACT_SUBGROUP_IMPACT_REPORT_REF = "subgroup_impact_report_ref"
ARTIFACT_POLICY_UNCERTAINTY_REPORT_REF = "policy_uncertainty_report_ref"
ARTIFACT_POLICY_TRANSPORTABILITY_REPORT_REF = "policy_transportability_report_ref"
ARTIFACT_GOVERNANCE_GATE_PACKET_REF = "governance_gate_packet_ref"
ARTIFACT_IMPLEMENTATION_PLAN_REF = "implementation_plan_ref"
ARTIFACT_REJECTED_ALTERNATIVES_SUMMARY_REF = "rejected_alternatives_summary_ref"
ARTIFACT_REPLAYABLE_AUDIT_BUNDLE_REF = "replayable_audit_bundle_ref"
ARTIFACT_POLICY_OUTPUT_BUNDLE_REF = "policy_output_bundle_ref"
ARTIFACT_DECISION_READINESS_CONTRACT_REF = "decision_readiness_contract_ref"
ARTIFACT_PROMOTION_EVIDENCE_BUNDLE_REF = "promotion_evidence_bundle_ref"
ARTIFACT_PLATFORM_META_EVALUATION_REPORT_REF = "platform_meta_evaluation_report_ref"
ARTIFACT_DISCOVERY_ARTIFACT_BUNDLE_REF = "discovery_artifact_bundle_ref"

# Legacy bridge (optional)
ARTIFACT_SIMULATION_SUMMARY_REF = "simulation_summary_ref"

# Canonical report keys (ExperimentState.reports_index)
REPORT_LINK_REPORT_REF = "link_report_ref"
REPORT_COMPILE_REPORT_REF = "compile_report_ref"
REPORT_LEGAL_REPORT_REF = "legal_report_ref"
REPORT_CHANGE_PROPOSAL_REF = "change_proposal_ref"
REPORT_GOVERNANCE_REPORT_REF = "governance_report_ref"


__all__ = [
    "ARTIFACT_ABM_ALIGNMENT_REPORT_REF",
    "ARTIFACT_ABSTRACTION_CERTIFICATE_REF",
    "ARTIFACT_ALIGNMENT_REPORT_REF",
    "ARTIFACT_BACKTEST_REPORT_REF",
    "ARTIFACT_BOUNDS_BUNDLE_REF",
    "ARTIFACT_CALIBRATION_VALIDATION_BUNDLE_REF",
    "ARTIFACT_CAUSAL_CAPABILITY_CONTRACT_REF",
    "ARTIFACT_CAUSAL_ENSEMBLE_ENVELOPE_REF",
    "ARTIFACT_CAUSAL_ENSEMBLE_REF",
    "ARTIFACT_CAUSAL_ENVELOPE_REF",
    "ARTIFACT_CAUSAL_EVIDENCE_BUNDLE_REF",
    "ARTIFACT_CAUSAL_EXECUTION_BUNDLE_REF",
    "ARTIFACT_CAUSAL_METHOD_EVIDENCE_REF",
    "ARTIFACT_CAUSAL_METHOD_RESULT_REF",
    "ARTIFACT_CAUSAL_QUERY_ENVELOPE_REF",
    "ARTIFACT_CAUSAL_QUERY_METHOD_EVIDENCE_REF",
    "ARTIFACT_CAUSAL_QUERY_METHOD_RESULT_REF",
    "ARTIFACT_CAUSAL_QUERY_RESULT_REF",
    "ARTIFACT_CAUSAL_READINESS_BUNDLE_REF",
    "ARTIFACT_CAUSAL_REPORT_REF",
    "ARTIFACT_CAUSAL_VALIDITY_BUNDLE_REF",
    "ARTIFACT_CHAMPION_POLICY_DOSSIER_REF",
    "ARTIFACT_CLAIM_LEDGER_V2_REF",
    "ARTIFACT_CLAIMS_REF",
    "ARTIFACT_COMPOSITION_CERTIFICATE_REF",
    "ARTIFACT_COMPOSITION_FAILURE_CARD_BUNDLE_REF",
    "ARTIFACT_CONSTRAINT_REPORT_REF",
    "ARTIFACT_CONSTRAINT_SATISFACTION_REPORT_REF",
    "ARTIFACT_CONTINUOUS_GOVERNANCE_REPORT_REF",
    "ARTIFACT_CONTEXT_ADAPTIVE_PARAMETER_BUNDLE_REF",
    "ARTIFACT_CROSS_GRAPH_EVIDENCE_PROFILE_REF",
    "ARTIFACT_DECISION_CARD_REF",
    "ARTIFACT_DECISION_PACKET_REF",
    "ARTIFACT_DECISION_READINESS_CONTRACT_REF",
    "ARTIFACT_DISCOVERY_ARTIFACT_BUNDLE_REF",
    "ARTIFACT_DRIFT_READINESS_REF",
    "ARTIFACT_DISTRIBUTIONAL_EFFECT_BUNDLE_REF",
    "ARTIFACT_DISTRIBUTIONAL_REPORT_REF",
    "ARTIFACT_DYNAMIC_TREATMENT_REGIME_REF",
    "ARTIFACT_ECONOMETRIC_ENVELOPE_REF",
    "ARTIFACT_ECONOMETRIC_EVIDENCE_REF",
    "ARTIFACT_ECONOMETRIC_RESULT_REF",
    "ARTIFACT_EFFECT_TRAJECTORY_BUNDLE_REF",
    "ARTIFACT_ENVIRONMENT_MANIFEST_REF",
    "ARTIFACT_EVALUATOR_REPORT_REF",
    "ARTIFACT_EXPLANATION_BUNDLE_REF",
    "ARTIFACT_EXECUTION_PLAN_REF",
    "ARTIFACT_EXEC_PLAN_REF",
    "ARTIFACT_FAIRNESS_AUDIT_REPORT_REF",
    "ARTIFACT_FINITE_STATE_ABSTRACTION_MAP_REF",
    "ARTIFACT_FISCAL_FEEDBACK_LINK_REF",
    "ARTIFACT_GOVERNANCE_GATE_PACKET_REF",
    "ARTIFACT_HTE_RESULT_REF",
    "ARTIFACT_HUMAN_REVIEW_DECISION_REF",
    "ARTIFACT_HUMAN_REVIEW_PACKET_REF",
    "ARTIFACT_IMPLEMENTATION_PLAN_REF",
    "ARTIFACT_INPUT_BINDING_REPORT_REF",
    "ARTIFACT_INTERFACE_MAPPING_REF",
    "ARTIFACT_ITERATION_STATE_REF",
    "ARTIFACT_JUDGE_VERDICT_REF",
    "ARTIFACT_LEGAL_CANDIDATE_PACK_REF",
    "ARTIFACT_LEGAL_SOURCE_PACK_REF",
    "ARTIFACT_LITERATURE_PRIOR_GRAPH_REF",
    "ARTIFACT_LITERATURE_PRIOR_REF",
    "ARTIFACT_LOWERED_IR_REF",
    "ARTIFACT_METHOD_CATALOG_SNAPSHOT_REF",
    "ARTIFACT_METRICS_REF",
    "ARTIFACT_METRIC_OBSERVATION_BUNDLE_REF",
    "ARTIFACT_METRIC_VALIDATION_REPORT_REF",
    "ARTIFACT_NORMATIVE_ARBITRATION_RESULT_REF",
    "ARTIFACT_NORM_IMPACT_REPORT_REF",
    "ARTIFACT_OPTIMIZATION_AMBIGUITY_CERTIFICATE_REF",
    "ARTIFACT_PLATFORM_META_EVALUATION_REPORT_REF",
    "ARTIFACT_POLICY_BRIEF_REF",
    "ARTIFACT_POLICY_FRONTIER_REPORT_REF",
    "ARTIFACT_POLICY_OPTION_SET_REF",
    "ARTIFACT_POLICY_OUTPUT_BUNDLE_REF",
    "ARTIFACT_POLICY_RECOMMENDATION_REF",
    "ARTIFACT_POLICY_REQUEST_FRAME_REF",
    "ARTIFACT_POLICY_TRANSPORTABILITY_REPORT_REF",
    "ARTIFACT_POLICY_UNCERTAINTY_REPORT_REF",
    "ARTIFACT_PREFLIGHT_REPORT_REF",
    "ARTIFACT_PROGRAM_GRAPH_REF",
    "ARTIFACT_PROOF_BUNDLE_REF",
    "ARTIFACT_PROOF_COMPOSABILITY_CERTIFICATE_REF",
    "ARTIFACT_PROOF_WITNESS_INDEX_REF",
    "ARTIFACT_PROMOTION_EVIDENCE_BUNDLE_REF",
    "ARTIFACT_PROPAGATION_REPORT_REF",
    "ARTIFACT_RECONCILED_CAUSAL_GRAPH_REF",
    "ARTIFACT_REJECTED_ALTERNATIVES_SUMMARY_REF",
    "ARTIFACT_RESEARCH_DAG_REF",
    "ARTIFACT_REISSUE_PACKET_REF",
    "ARTIFACT_REPLAYABLE_AUDIT_BUNDLE_REF",
    "ARTIFACT_REPRODUCIBILITY_MANIFEST_REF",
    "ARTIFACT_SBOM_REF",
    "ARTIFACT_SENSITIVITY_ANALYSIS_BUNDLE_REF",
    "ARTIFACT_SENSITIVITY_RESULT_REF",
    "ARTIFACT_SHIFT_DIAGNOSTIC_REPORT_REF",
    "ARTIFACT_SIMULATION_CALIBRATION_RECEIPT_REF",
    "ARTIFACT_SIMULATION_PROOF_BRIDGE_REF",
    "ARTIFACT_SIMULATION_RESULT_REF",
    "ARTIFACT_SIMULATION_SUMMARY_REF",
    "ARTIFACT_SLOT_LAYOUT_REF",
    "ARTIFACT_SOURCE_VERIFICATION_REPORT_REF",
    "ARTIFACT_STATE_DELTA_REF",
    "ARTIFACT_STATE_SNAPSHOT_REF",
    "ARTIFACT_STRATEGIC_RESPONSE_BUNDLE_REF",
    "ARTIFACT_STRATEGIC_SCM_REF",
    "ARTIFACT_STRESS_TEST_REPORT_REF",
    "ARTIFACT_STRUCTURAL_CAUSAL_MODEL_SPEC_REF",
    "ARTIFACT_SUBGROUP_IMPACT_REPORT_REF",
    "ARTIFACT_TEE_ATTESTATION_REF",
    "ARTIFACT_TRANSPORTABILITY_RESULT_REF",
    "ARTIFACT_TREASURY_PLAN_REF",
    "ARTIFACT_VERIFIED_POLICY_REPORT_REF",
    "ARTIFACT_VALIDATION_REPORT_REF",
    "ARTIFACT_VOI_RUN_REPORT_REF",
    "ARTIFACT_WELFARE_BUNDLE_REF",
    "ARTIFACT_WITHDRAWAL_RECORD_REF",
    "INPUT_CALIBRATION_REPORT_REF",
    "INPUT_DATA_SNAPSHOT_REF",
    "INPUT_DATA_VIEW_REQUEST_REF",
    "INPUT_EXECUTION_PLAN_REF",
    "INPUT_GRAPH_PRIOR_BUNDLE_REF",
    "INPUT_INPUT_BINDINGS_REF",
    "INPUT_KNOWLEDGE_BUNDLE_REF",
    "INPUT_MODEL_SPEC_REF",
    "INPUT_NORM_PACK_REF",
    "INPUT_PARAMETER_OVERRIDE_BUNDLE_REF",
    "INPUT_POLICY_SPEC_REF",
    "INPUT_PRIOR_KNOWLEDGE_BUNDLE_REF",
    "INPUT_PROMOTION_EVIDENCE_BUNDLE_REF",
    "INPUT_REGISTRY_BUNDLE_REF",
    "INPUT_RESEARCH_INTENT_REF",
    "INPUT_STATE_SNAPSHOT_REF",
    "INPUT_TRINITY_BUNDLE_REF",
    "INPUT_UKRAINE_FOUNDRY_METHOD_BUNDLE_REF",
    "INPUT_UKRAINE_SELECTED_METHOD_CONTRACT_REF",
    "REPORT_CHANGE_PROPOSAL_REF",
    "REPORT_COMPILE_REPORT_REF",
    "REPORT_GOVERNANCE_REPORT_REF",
    "REPORT_LEGAL_REPORT_REF",
    "REPORT_LINK_REPORT_REF",
]
