import { render, screen } from "@testing-library/react";

const { useBureaucraticRenderMock } = vi.hoisted(() => ({
  useBureaucraticRenderMock: vi.fn(),
}));

vi.mock("@/api/hooks/useBureaucraticRender", () => ({
  useBureaucraticRender: (...args: unknown[]) =>
    useBureaucraticRenderMock(...args),
}));

vi.mock("@/app/providers/useTemporalCursor", () => ({
  useMaybeTemporalCursor: () => null,
}));

vi.mock("@/shared/ui/quantity", () => ({
  Quantity: ({ value }: { value: { point: number | null } }) => (
    <span>{value.point}</span>
  ),
}));

import { BureaucraticArtifactView } from "./BureaucraticArtifactView";

describe("BureaucraticArtifactView accessibility", () => {
  it("exposes genre choices, document label and draft note semantically", () => {
    useBureaucraticRenderMock.mockReturnValue({
      data: { document: documentFixture },
      isError: false,
      isLoading: false,
    });

    render(<BureaucraticArtifactView artifactId="sha256:abc" />);

    expect(
      screen.getByRole("radiogroup", { name: /Render as/ }),
    ).toBeInTheDocument();
    expect(screen.getAllByRole("radio")).toHaveLength(4);
    expect(
      screen.getByRole("article", { name: /Постанова КМУ/ }),
    ).toBeInTheDocument();
    expect(
      screen.getByRole("note", {
        name: /Generated by PolicyOS \/ Draft/,
      }),
    ).toBeInTheDocument();
    expect(
      screen.getByRole("heading", { name: /Epistemic legend/ }),
    ).toBeInTheDocument();
  });
});

const documentFixture = {
  annexes: [],
  blocks: [
    {
      authorship: {
        author: "PolicyOS",
        author_role: "system",
        reviewed_by_human: false,
      },
      epistemic_origin: "imported",
      id: "header",
      kind: "header",
      level: 1,
      title: "Header",
    },
  ],
  epistemic_summary: {
    evidence_filled: 0,
    imported: 1,
    model_generated: 0,
    operator_filled: 0,
  },
  genre: "postanova_kmu",
  id: "doc_1",
  jurisdiction: "ua",
  language: "uk",
  packet_hash: "abcdef",
  packet_id: "sha256:abc",
  render_timestamp: "2026-02-11T12:00:00Z",
  status: "draft",
  template: {
    genre: "postanova_kmu",
    id: "ua.kmu.postanova.v1",
    jurisdiction: "ua",
    legal_review_status: "pending_external_review",
    locale: "uk-UA",
    version: "1.0.0",
  },
  title: "Постанова КМУ",
  trust_view: false,
  watermark: "Generated by PolicyOS / Draft / Not an official state document",
};
