#!/usr/bin/env python3
"""Generate and verify split mypy, Ruff, and MkDocs configuration."""

from __future__ import annotations

import argparse
import difflib
import json
import os
import re
import sys
import tomllib
from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from tools.lib.fs import atomic_write_text
from tools.lib.imports import repo_root_from

REPO_ROOT = repo_root_from(__file__)
DEFAULT_MANIFEST = "architecture/tooling/tool_config_split.toml"
GENERATED_NOTICE = (
    "Generated by `uv run polisyos-tools workspace tool-configs`.\n"
    "Edit the source fragments declared in architecture/tooling/tool_config_split.toml.\n"
)


@dataclass(frozen=True)
class RenderedFile:
    path: Path
    content: str
    repo_root: Path = REPO_ROOT

    @property
    def relative_path(self) -> str:
        return self.path.relative_to(self.repo_root).as_posix()


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Generate or verify split mypy, Ruff, and MkDocs configuration."
    )
    parser.add_argument(
        "--manifest",
        default=DEFAULT_MANIFEST,
        help="Tool-config split manifest, relative to the repository root.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Do not write files; fail if generated files or dead override state drift.",
    )
    parser.add_argument(
        "--json-output",
        type=Path,
        help="Optional JSON report path.",
    )
    return parser


def load_manifest(repo_root: Path = REPO_ROOT, manifest: str = DEFAULT_MANIFEST) -> dict[str, Any]:
    path = repo_root / manifest
    return tomllib.loads(path.read_text(encoding="utf-8"))


def render_files(
    repo_root: Path = REPO_ROOT, manifest: str = DEFAULT_MANIFEST
) -> tuple[RenderedFile, ...]:
    data = load_manifest(repo_root, manifest)
    return (
        *_render_mypy(repo_root, data),
        *_render_ruff(repo_root, data),
        *_render_mkdocs(repo_root, data),
    )


def _render_mypy(repo_root: Path, data: dict[str, Any]) -> tuple[RenderedFile, ...]:
    config = data["mypy"]
    base = _read_fragment(repo_root, config["base_config"])
    fragments = [_read_fragment(repo_root, path) for path in config["override_fragments"]]

    root_content = _comment_notice("mypy.ini") + _ensure_trailing_newline(base)
    generated_content = _comment_notice(config["generated_config"]) + _join_blocks(
        [base, *fragments]
    )
    return (
        RenderedFile(repo_root / config["root_config"], root_content, repo_root),
        RenderedFile(repo_root / config["generated_config"], generated_content, repo_root),
    )


def _render_ruff(repo_root: Path, data: dict[str, Any]) -> tuple[RenderedFile, ...]:
    config = data["ruff"]
    base = _read_fragment(repo_root, config["base_config"])
    generated_config = config["generated_config"]
    fragments = [
        _read_ruff_per_file_ignore_fragment(repo_root, path, generated_config)
        for path in config["per_file_ignore_fragments"]
    ]
    product_root_settings = config["product_root_settings"]
    root_content = _comment_notice("ruff.toml") + _join_blocks(
        [
            f"extend = {json.dumps(generated_config)}\n",
            _format_ruff_settings(product_root_settings),
        ]
    )
    generated_content = _comment_notice(generated_config) + _join_blocks(
        [base, "[lint.per-file-ignores]\n", *fragments]
    )
    workspace_root_config = config["workspace_root_generated_config"]
    workspace_root_prefix = config["workspace_root_prefix"]
    workspace_root_fragments = [
        _read_ruff_per_file_ignore_fragment(
            repo_root,
            path,
            workspace_root_config,
            pattern_prefix=workspace_root_prefix,
        )
        for path in config["per_file_ignore_fragments"]
    ]
    workspace_root_settings = _render_workspace_root_settings(
        product_root_settings,
        path_settings=config["workspace_root_path_settings"],
        pattern_settings=config["workspace_root_pattern_settings"],
        prefix=workspace_root_prefix,
    )
    workspace_config_path = repo_root / workspace_root_config
    base_config_path = repo_root / config["base_config"]
    workspace_extend = Path(
        os.path.relpath(base_config_path, workspace_config_path.parent)
    ).as_posix()
    workspace_root_content = _comment_notice(workspace_root_config) + _join_blocks(
        [
            f"extend = {json.dumps(workspace_extend)}\n",
            workspace_root_settings,
            "[lint.per-file-ignores]\n",
            *workspace_root_fragments,
        ]
    )
    return (
        RenderedFile(repo_root / config["root_config"], root_content, repo_root),
        RenderedFile(repo_root / generated_config, generated_content, repo_root),
        RenderedFile(repo_root / workspace_root_config, workspace_root_content, repo_root),
    )


def _render_workspace_root_settings(
    product_root_settings: dict[str, Any],
    *,
    path_settings: Sequence[str],
    pattern_settings: Sequence[str],
    prefix: str,
) -> str:
    """Render caller-root overrides for all declared path and glob settings."""

    lines: list[str] = []
    for name in path_settings:
        if name not in product_root_settings:
            raise ValueError(
                f"workspace-root path setting {name!r} is absent from product-root settings"
            )
        value = _prefix_ruff_setting(product_root_settings[name], prefix, kind="path")
        lines.append(f"{name} = {_format_ruff_value(value)}")
    for name in pattern_settings:
        if name not in product_root_settings:
            continue
        value = _prefix_ruff_setting(product_root_settings[name], prefix, kind="pattern")
        lines.append(f"{name} = {_format_ruff_value(value)}")
    return "\n".join(lines) + ("\n" if lines else "")


def _format_ruff_settings(settings: dict[str, Any]) -> str:
    return (
        "\n".join(f"{name} = {_format_ruff_value(value)}" for name, value in settings.items())
        + "\n"
    )


def _prefix_ruff_setting(value: str | list[str], prefix: str, *, kind: str) -> str | list[str]:
    if isinstance(value, str):
        return _prefix_ruff_root_value(value, prefix, kind=kind)
    if isinstance(value, list) and all(isinstance(item, str) for item in value):
        return [_prefix_ruff_root_value(item, prefix, kind=kind) for item in value]
    raise ValueError(f"unsupported Ruff {kind} setting value: {value!r}")


def _prefix_ruff_root_value(value: str, prefix: str, *, kind: str) -> str:
    if not prefix or prefix == "." or value.startswith("/"):
        return value
    if kind == "pattern":
        negated = value.startswith("!")
        subject = value[1:] if negated else value
        if subject.startswith("/"):
            return value
        subject = subject.removeprefix("./")
        rendered = f"{prefix}/{subject}"
        return f"!{rendered}" if negated else rendered
    subject = value.removeprefix("./")
    if subject == ".":
        return prefix
    return f"{prefix}/{subject}"


def _format_ruff_value(value: str | list[str]) -> str:
    if isinstance(value, str):
        return json.dumps(value)
    if isinstance(value, list) and all(isinstance(item, str) for item in value):
        return "[" + ", ".join(json.dumps(item) for item in value) + "]"
    raise ValueError(f"unsupported Ruff setting value: {value!r}")


def _render_mkdocs(repo_root: Path, data: dict[str, Any]) -> tuple[RenderedFile, ...]:
    config = data["mkdocs"]
    blocks = [
        _read_fragment(repo_root, config["base_config"]),
        _read_fragment(repo_root, config["exclude_docs_fragment"]),
        _read_fragment(repo_root, config["not_in_nav_fragment"]),
        "nav:\n",
        *(_read_fragment(repo_root, path) for path in config["nav_fragments"]),
    ]
    root_content = _comment_notice("mkdocs.yml") + f"INHERIT: {config['generated_config']}\n"
    generated_content = _comment_notice(config["generated_config"], comment="#") + _join_blocks(
        blocks
    )
    return (
        RenderedFile(repo_root / config["root_config"], root_content, repo_root),
        RenderedFile(repo_root / config["generated_config"], generated_content, repo_root),
    )


def _comment_notice(target: str, *, comment: str = "#") -> str:
    lines = [f"{comment} {line}" for line in GENERATED_NOTICE.strip().splitlines()]
    lines.append(f"{comment} Target: {target}")
    return "\n".join(lines) + "\n\n"


def _read_fragment(repo_root: Path, relative_path: str) -> str:
    return (repo_root / relative_path).read_text(encoding="utf-8")


_RUFF_PER_FILE_IGNORE_KEY_RE = re.compile(
    r'^(?P<indent>\s*)"(?P<pattern>[^"]+)"(?P<suffix>\s*=.*)$'
)


def _read_ruff_per_file_ignore_fragment(
    repo_root: Path,
    relative_path: str,
    generated_config: str,
    *,
    pattern_prefix: str | None = None,
) -> str:
    fragment = _read_fragment(repo_root, relative_path)
    generated_dir = (repo_root / generated_config).parent
    rendered_lines = []
    for line in fragment.splitlines():
        match = _RUFF_PER_FILE_IGNORE_KEY_RE.match(line)
        if match is None:
            rendered_lines.append(line)
            continue
        pattern = match.group("pattern")
        if pattern_prefix is None:
            rendered_pattern = _ruff_pattern_for_generated_config(pattern, repo_root, generated_dir)
        else:
            rendered_pattern = _ruff_pattern_for_prefix(pattern, pattern_prefix)
        rendered_lines.append(f'{match.group("indent")}"{rendered_pattern}"{match.group("suffix")}')
    return "\n".join(rendered_lines) + ("\n" if fragment.endswith("\n") else "")


def _ruff_pattern_for_generated_config(pattern: str, repo_root: Path, generated_dir: Path) -> str:
    """Render repo-root-relative Ruff patterns relative to the generated config."""

    prefix = os.path.relpath(repo_root, generated_dir).replace(os.sep, "/")
    return _ruff_pattern_for_prefix(pattern, prefix)


def _ruff_pattern_for_prefix(pattern: str, prefix: str) -> str:
    """Render a repo-root-relative Ruff pattern below a caller's project root."""

    negated = pattern.startswith("!")
    subject = pattern[1:] if negated else pattern
    if subject.startswith(("/", "./", "../")):
        return pattern
    rendered = f"{prefix}/{subject}" if prefix not in {"", "."} else subject
    return f"!{rendered}" if negated else rendered


def _ensure_trailing_newline(content: str) -> str:
    return content if content.endswith("\n") else f"{content}\n"


def _join_blocks(blocks: Sequence[str]) -> str:
    rendered: list[str] = []
    for block in blocks:
        text = _ensure_trailing_newline(block).rstrip()
        if not text:
            continue
        rendered.append(text)
    return "\n\n".join(rendered) + "\n"


def check_drift(rendered: Sequence[RenderedFile]) -> list[dict[str, str]]:
    findings: list[dict[str, str]] = []
    for item in rendered:
        current = item.path.read_text(encoding="utf-8") if item.path.exists() else ""
        if current == item.content:
            continue
        diff = "\n".join(
            difflib.unified_diff(
                current.splitlines(),
                item.content.splitlines(),
                fromfile=f"current/{item.relative_path}",
                tofile=f"generated/{item.relative_path}",
                lineterm="",
            )
        )
        findings.append(
            {
                "path": item.relative_path,
                "message": "generated config is stale",
                "diff": diff,
            }
        )
    return findings


def write_rendered(rendered: Sequence[RenderedFile]) -> None:
    for item in rendered:
        atomic_write_text(item.path, item.content)


def override_report_findings(repo_root: Path = REPO_ROOT) -> list[dict[str, Any]]:
    from tools.ops_runners.reports import dead_overrides

    report = dead_overrides.build_report(repo_root)
    return list(report["findings"])


def _write_json(path: Path, payload: dict[str, Any]) -> None:
    target = path if path.is_absolute() else REPO_ROOT / path
    atomic_write_text(target, json.dumps(payload, indent=2, sort_keys=True) + "\n")


def main(argv: Sequence[str] | None = None) -> int:
    args = _build_parser().parse_args(argv)
    rendered = render_files(REPO_ROOT, args.manifest)
    drift = check_drift(rendered)
    override_findings = override_report_findings(REPO_ROOT)

    payload = {
        "status": "failed" if drift or override_findings else "passed",
        "generated_files": [item.relative_path for item in rendered],
        "drift_findings": drift,
        "override_findings": override_findings,
    }
    if args.json_output is not None:
        _write_json(args.json_output, payload)

    if args.check:
        if drift:
            print("Tool config split check failed: generated files are stale.", file=sys.stderr)
            for finding in drift:
                print(f"\n==> {finding['path']}", file=sys.stderr)
                print(finding["diff"], file=sys.stderr)
        if override_findings:
            print("Tool config split check failed: override report has findings.", file=sys.stderr)
            for finding in override_findings:
                print(
                    f"- {finding['check']} {finding['tool']} {finding['subject']}: "
                    f"{finding['detail']}",
                    file=sys.stderr,
                )
        return 1 if drift or override_findings else 0

    write_rendered(rendered)
    if override_findings:
        print("Generated configs, but override report still has findings:", file=sys.stderr)
        for finding in override_findings:
            print(
                f"- {finding['check']} {finding['tool']} {finding['subject']}: {finding['detail']}",
                file=sys.stderr,
            )
        return 1
    print("Generated split mypy, Ruff, and MkDocs configuration.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
