from pathlib import Path
import json,hashlib,gzip,subprocess,tarfile,io,datetime,xml.etree.ElementTree as ET
R=Path('/workspace/orch02-native-c06');pairs={'dfk':('794471915834b56353701648a7907dade74bc108','9b291d004cb9350aa7df54d87c427b0b4f54796f','cbbfffd367fe283813a8177575d26c0ede8d20c4'),'can':('cd884528829160c25c58acbd648c021089711477','cee713ae4915d2bc5b2826577ebc9b1ea7abd1c5','4901e26841e2be0ae6ef393754abed5cafb1e2d4')};roles=[]
def hash_bytes(b):return hashlib.sha256(b).hexdigest()
def ref(p):b=p.read_bytes();return {'path':str(p),'bytes':len(b),'sha256':hash_bytes(b)}
def stream_hash(p,compressed=False):
 h=hashlib.sha256();size=0
 with (gzip.open(p,'rb') if compressed else p.open('rb')) as f:
  for b in iter(lambda:f.read(1048576),b''):h.update(b);size+=len(b)
 return size,h.hexdigest()
def git(repo,*args):return subprocess.check_output(['git','-C',str(repo),*args])
for role,(doc,tree,source) in pairs.items():
 repo=Path('/workspace/orch02-c06-'+role);prefix=Path('policy-engine/docs/research/e02-cloud-test-plan/implementation-handoffs/C/orch02-c06-'+role+'-recovery-20261008');assert git(repo,'rev-parse',doc+'^{tree}').decode().strip()==tree;assert git(repo,'rev-parse','HEAD').decode().strip()==doc;assert not git(repo,'status','--porcelain','-z');subprocess.run(['git','-C',str(repo),'merge-base','--is-ancestor',source,doc],check=True)
 diff=[p.decode() for p in git(repo,'diff','--name-only','-z',source,doc).split(b'\0') if p];assert all(p.startswith(str(prefix)+'/') for p in diff),diff
 snap=R/'publication-documents'/(role+'-'+doc+'-compact-denominator');snap.mkdir(parents=True,exist_ok=False)
 with tarfile.open(fileobj=io.BytesIO(git(repo,'archive',doc,'--',str(prefix)))) as t:t.extractall(snap,filter='data')
 leaf=snap/prefix;handoff=json.loads((leaf/'handoff.json').read_text());manifest=json.loads((leaf/(role+'-final-manifest.json')).read_text());audit=json.loads((leaf/'native-publication-audit.json').read_text());lossless={x['raw_published_relative_path']:x for x in json.loads((leaf/'lossless-byte-artifact-map.json').read_text())};exceptions={x['raw_mutant_reference']:x for x in audit['raw_source_snapshot_exceptions']}
 assert handoff['source_acceptance']=='not_admitted_by_G';assert handoff['formal_G_closure']=='not_adjudicated';assert handoff['closure_ids']==[];assert handoff['candidate_sha']==source;assert handoff['candidate_tree_sha']==git(repo,'rev-parse',source+'^{tree}').decode().strip();assert handoff['source_manifest']==manifest['source']['complete_changed_paths']
 for x in handoff['source_manifest']:
  b=git(repo,'show',doc+':'+x['path']);assert hash_bytes(b)==x['sha256'];assert git(repo,'rev-parse',doc+':'+x['path']).decode().strip()==x['blob']
 inventory=json.loads((leaf/'companion-inventory.json').read_text());checked=[]
 for x in inventory['files']:
  p=snap/x['path'];assert p.stat().st_size==x['bytes'];assert ref(p)['sha256']==x['sha256'];checked.append(x)
 declared={x['path'] for x in inventory['files']}|set(inventory['additional_paths']);actual={str(p.relative_to(snap)) for p in leaf.rglob('*') if p.is_file()};assert declared==actual,(declared-actual,actual-declared);assert actual==set(diff)
 assert ref(leaf/(role+'-final-manifest.json'))['sha256']==audit['original_manifest_sha256']==ref(R/(role+'-final-manifest.json'))['sha256']
 native_rows=[]
 for x in manifest['publishable_moderate_complete_artifacts']:
  original=Path(x['path']);relative=original.relative_to(R/'handoff-evidence'/role);local_relative='native-evidence/'+str(relative);p=leaf/local_relative
  if str(original) in exceptions:
   ex=exceptions[str(original)];delta=leaf/ex['delta_publication_path'];assert ref(delta)['sha256']==ex['delta_sha256'];data=gzip.decompress(delta.read_bytes()) if ex['delta_encoding']=='gzip' else delta.read_bytes();assert hash_bytes(data)==ex['decoded_delta_sha256'];lines=data.splitlines(keepends=True);assert lines[0].startswith(b'--- ') and lines[1].startswith(b'+++ ')
   lines[0]=('--- a/'+ex['canonical_source']+'\n').encode();lines[1]=('+++ b/'+ex['canonical_source']+'\n').encode();work=R/'publication-final-reconstruction'/(role+'-'+doc+'-compact-denominator')/Path(ex['canonical_source']).stem/Path(ex['raw_mutant_reference']).stem;target=work/ex['canonical_source'];target.parent.mkdir(parents=True,exist_ok=True);target.write_bytes(git(repo,'show',ex['canonical_source_commit']+':'+ex['canonical_source']));patch=work/'native-header-normalized.diff';patch.write_bytes(b''.join(lines));subprocess.run(['git','-C',str(work),'apply',str(patch)],capture_output=True,check=True);assert ref(target)['sha256']==x['sha256']==ex['raw_mutant_sha256'];assert target.stat().st_size==x['bytes']==ex['raw_mutant_bytes'];native_rows.append({'original':str(relative),'method':'canonical Git blob plus original delta; only filename headers normalized','decoded_sha256':x['sha256']})
  elif local_relative in lossless:
   z=lossless[local_relative];zipfile=leaf/z['lossless_published_path'];assert ref(zipfile)['sha256']==z['gzip_sha256'];n,h=stream_hash(zipfile,True);assert (n,h)==(x['bytes'],x['sha256'])==(z['raw_bytes'],z['raw_sha256']);native_rows.append({'original':str(relative),'method':'complete lossless gzip text/EOF encoding','decoded_sha256':h})
  else:
   assert p.stat().st_size==x['bytes'];assert ref(p)['sha256']==x['sha256'];native_rows.append({'original':str(relative),'method':'exact bytes','decoded_sha256':x['sha256']})
 gziprows=[]
 for x in manifest['publishable_lossless_complete_artifacts']:
  p=leaf/'native-evidence'/Path(x['complete_lossless_gzip']['path']).relative_to(R/'handoff-evidence'/role);assert ref(p)['sha256']==x['complete_lossless_gzip']['sha256'];n,h=stream_hash(p,True);assert (n,h)==(x['decoded_exact']['bytes'],x['decoded_exact']['sha256']);gziprows.append({'path':str(p.relative_to(leaf)),'decoded_bytes':n,'decoded_sha256':h})
 gate_summary=json.loads((leaf/'required-gates-summary.json').read_text());assert any(x['gate']=='full architecture default generated families' and x['outcome']=='FAIL' for x in gate_summary['checks'])
 if role=='dfk':
  skip=[x for x in gate_summary['checks'] if x['gate'].startswith('scoped lint_imports')][0];assert skip['outcome']=='SKIP_no_changed_src_gate_inputs';assert 'IMPORT_SCOPE_SKIPPED_ZERO_DENOMINATOR' in handoff['checks'][2]['outcome'];assert 'unstaged' in handoff['property']['statement'];assert 'exit2' in handoff['property']['statement'] or 'exit 2' in handoff['property']['statement']
  raw_import=json.loads((leaf/'required-gates/imports/stdout.txt').read_text());assert raw_import['status']=='skipped';assert raw_import['data']['changed_file_count']==0
 inv=[]
 for name in ['invocation-initial','invocation-retry']:
  d=leaf/'required-gates'/name
  if not d.exists():continue
  command=json.loads((d/'command.json').read_text());stdout=json.loads((d/'stdout.txt').read_text());assert stdout['runtime_invocation_established'] is False;assert stdout['coverage']=='partial';mapping=json.loads((d/'lossless.json').read_text());published=leaf/Path(mapping['compressed']['path']).relative_to(repo/prefix);assert ref(published)['sha256']==mapping['compressed']['sha256'];n,h=stream_hash(published,True);assert (n,h)==(mapping['decoded_exact']['bytes'],mapping['decoded_exact']['sha256']);assert stream_hash(Path(mapping['decoded_exact']['path']))==(n,h)
  inv.append({'run':name,'returncode':command['returncode'],'wall_seconds':command['wall_seconds'],'max_rss_kib':command['max_rss_kib'],'complete_deciding_stdout':ref(d/'stdout.txt'),'receipt_decoded_bytes':n,'receipt_decoded_sha256':h,'runtime_invocation_established':False})
 if role=='can':
  assert [x['returncode'] for x in inv]==[-9,0];assert inv[0]['receipt_decoded_sha256']==inv[1]['receipt_decoded_sha256'];cmd1=json.loads((leaf/'required-gates/invocation-initial/command.json').read_text())['argv'];cmd2=json.loads((leaf/'required-gates/invocation-retry/command.json').read_text())['argv'];assert cmd1[:-1]==cmd2[:-1]
  recon=json.loads((leaf/'required-gates/invocation-input-reconciliation.json').read_text());assert recon['runs'][0]['denominator_sha256']==recon['runs'][1]['denominator_sha256'];raw=Path('/workspace/orch02-recovery/c06-required-can-invocation-retry/receipt.json');
  with raw.open('rb') as f:f.seek(-8192,2);tail=f.read().decode()
  denom,_=json.JSONDecoder().raw_decode(tail.rsplit('"denominator": ',1)[1]);assert hash_bytes(json.dumps(denom,sort_keys=True,separators=(',',':')).encode())==recon['runs'][0]['denominator_sha256'];assert 'identifiability' in '\n'.join(handoff['limitations_and_next_owner'])
 else:assert [x['returncode'] for x in inv]==[0]
 for d in (leaf/'required-gates').rglob('command.json'):
  c=json.loads(d.read_text())
  for f,x in c.get('outputs',c.get('complete_outputs',{})).items():
   p=d.parent/f
   if p.is_file():assert ref(p)['sha256']==x['sha256'];assert p.stat().st_size==x['bytes']
 roles.append({'role':role.upper(),'documentation_commit':doc,'documentation_tree':tree,'source_commit':source,'source_tree':handoff['candidate_tree_sha'],'source_acceptance':'not_admitted_by_G','formal_G_closure':'not_adjudicated','all_original_source_export_native_inputs_unchanged':True,'complete_docs_only_diff_denominator':len(diff),'complete_documentation_byte_footprint':checked,'unhashed_self_and_primary_paths':inventory['additional_paths'],'handoff_ref':ref(leaf/'handoff.json'),'gate_summary_ref':ref(leaf/'required-gates-summary.json'),'all_native_publishable_complete_bytes_validated':native_rows,'complete_lossless_deciding_roundtrips':gziprows,'invocation_history':inv,'archive_and_RECORD_closure':'Full member/RECORD proof published losslessly and hash-identical to independently reviewed final native packet; no installed source overlay proof transferred to G','mandatory_architecture_status':'FAIL, retained with narrow correction; P41 inherited status not_established','technical_verdict':'GO for bounded already-reviewed technical properties and accurate publication packet; not source admission, overall release green or formal closure'})
result={'reviewer':'/root/native_c06 independent direct helper; no children','review_type':'read-only exact frozen documentation/evidence publication review; no native replays','created_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'source_acceptance':'not_admitted_by_G','formal_G_closure':'not_adjudicated','material_unresolved_publication_findings':[],'resolved_review_findings':['DFK import gate was incorrectly labelled PASS despite skipped zero input denominator; corrected doc-only with explicit SKIP and original raw outputs unchanged','DFK staged deleted rename versus unstaged tracked missing source now explicit, preserving real Y=R fail-closed evidence'],'scope_and_limits':['Complete selected frozen documentation trees and every inventory/native mapped byte checked; self-index/primary files included in complete path denominator without recursive self-hash claim','Normal topic publication and independent root remote-head/tree/blob readback still required; this review does not assert remote availability','Global architecture FAIL remains; narrow affected-family observer cannot establish full green or P41 inherited red','CAN initial signal -9 cause not established; same-input serial retry child0 establishes partial static check only, no runtime reachability proof','CAN loaded f00 identifiability versus G032 remains composition delta; Core bypass/options and historical profile-less deploy compatibility remain C02/G decisions','DFK finite local census/package prefix observations do not establish external/historical/computed/ignored/binary retirement or alias sunset','LA023 is a bounded read-only contract-choice packet; no new training source, run or formal closure'], 'prior_native_review':ref(R/'independent-final-review.json'),'selected_family_measurement_review':ref(R/'family-correction-independent-review.json'),'retained_gate_source_complete_byte_audit':ref(R/'retained-gate-source-complete-byte-audit.json.gz'),'roles':roles}
p=R/'independent-publication-review.json';p.write_text(json.dumps(result,indent=2)+'\n');md=R/'independent-publication-review.md';md.write_text('Read-only independent publication review: bounded technical GO for the exact DFK and CAN documentation commits below. `source_acceptance: not_admitted_by_G`; `formal_G_closure: not_adjudicated`; no overall release green.\n\n'+''.join('- '+x['role']+' docs `'+x['documentation_commit']+'` tree `'+x['documentation_tree']+'`; native source `'+x['source_commit']+'` unchanged. Complete docs footprint '+str(x['complete_docs_only_diff_denominator'])+' paths and all mapped native/required deciding bytes independently verified.\n' for x in roles)+'\nArchitecture remains FAIL; P41 inheritance is not established. DFK import check has zero selected inputs and is explicitly SKIP. The CAN initial signal -9 and same-input successful retry remain separate; the retry proves only partial static direct-call reachability. Every lossless output roundtrip and four minimal mutation reconstructions retain exact tested bytes.\n\nCAN requires selected G composition checks for the loaded identifiability delta and C02/G decisions for raw Core bypass/options and profile-less history. DFK finite census and package member observations do not establish external or historical retirement. LA023 remains a read-only contract-choice proposal. Root must independently fetch and verify normal topic publication.\n\nFull byte/ref/oracle evidence is recorded in `independent-publication-review.json`.\n');print(json.dumps({'json':ref(p),'markdown':ref(md),'roles':[(x['role'],x['complete_docs_only_diff_denominator']) for x in roles]}))
